### ISSUE TITLE
Suggestions for template hierarchy page in themes handbook

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#1]
A few suggestions on https://developer.wordpress.org/themes/basics/template-hierarchy/ (from a person who's learning WP and reading WP docs for the first time).

1) Fix the link on "query string", which currently points to a (non-anchored) "This page was moved to" page.

2) Update the explanation regarding the query string and how it relates to finding the right template.
As currently I read:

> "WordPress uses the query string to decide which template [..] should be used to display the page. [..] It comes after the initial question mark and may contain a number of parameters separated by ampersands."
Many (if not most?) WP websites use URLs without question marks or ampersands. So, this explanation is puzzling.

3) A note about child templates would be nice, as currently, that hierarchy description (and the examples) is considering only a stand-alone themes.

**Comment by joyously** [comment]
1. that link is to the Glossary, but it is to the old glossary (codex).
2. I suggest removing "It comes after the initial question mark and may contain a number of parameters separated by ampersands."
3. The hierarchy itself doesn't care whether the template is met with a child file or a parent file. That doesn't belong on this page, which is about how WP maps a requested URL to a template file.

**Comment by JanisE** [comment]
(1) Right, the link points to the old glossary which does not exist any more.

(3) If the hierarchy itself doesn't care about whether there is a parent theme or not, then this could be mentioned on that page. It would certainly help a programmer to understand what that page has set out explain:
> This article explains how WordPress determines which template file(s) to use on individual pages. If you want to customize an existing WordPress theme it will help you decide which template file needs to be edited.

So, if I want to adjust the design of my webpage, I would need to know which specific file is used, which includes the knowledge whether it is a file of the child or parent theme. I suppose, this is trivial in the case when both themes contain the same set of files – the child files will be used. But it is not obvious what happens if, for example, I open a category "Unicorns" and the child theme has only "category.php", but the parent theme has also "category-unicorns.php" template.

**Comment by atachibana** [comment]
@joyously
Thank you. I'll fix the document according to your advice.

@JanisE 
Certainly this page is missing the description about Child Themes. 
How about adding some sentences at the end of Overview section? For example,

## Overview
...

When you are using a [child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/), any file you add to your child theme will overwrite the same file in the parent theme. For example, both themes contain the same template `category.php`, then child theme's template is used.
If a child theme contains the specific template such as `category-unicorns.php` and the parent theme contains lower prioritized template such as `category.php`, then child theme's `category-unicorns.php` is used.
Contrary, if a child them contains general template only such as `category.php` and the parent theme contains the specific one such as `category-unicorns.php`, then parent's template `category-unicorns.php` is used.

**Comment by JanisE** [comment]
That would be a perfect note about child themes, thanks!

**Comment by theMikeD** [comment]
"...any file you add to your child theme will **over-ride** the same file in the parent theme."

**Comment by joyously** [comment]
"if a child them contains" should be "if a child theme contains"
But I think this is a bad idea to add to this page, given that the template logic is changing because of full site editing.

**Comment by theMikeD** [comment]
We had a discussion on slack about how old stuff must remain and can't be purged, and I think this falls under that decision doesn't it?

**Comment by joyously** [comment]
> This would seem to be a good place to add a link to the template heirarchy too.

Do you mean the image, because this issue is about the template hierarchy page.

> I think this falls under that decision doesn't it?

No one is suggesting to purge old stuff. The suggestion is to add information that doesn't really belong on this page, and that information will conflict with any new docs that talk about how the template hierarchy is affected by templates created in the editor.

**Comment by JanisE** [comment]
If duplicating information is the problem, just a hyperlink can also be added to where this information is written, instead of copying the text.

**Comment by atachibana** [comment]
Hi all,
First, I modified the page with your whole suggestions include typo (@theMikeD and @joyously, thank you for careful reading). These updated information must be helpful to existing theme developer. I hope I don't exceed my authority...
https://developer.wordpress.org/themes/basics/template-hierarchy/

@joyously 
FSE! Can we still use this Theme Handbook with minor changes for FSE? I imagined we have to create brand new Theme handbook and will leave this one as 'Classic' Theme Handbook...

@kafleg 
Any comments?

**Comment by joyously** [comment]
> Can we still use this Theme Handbook with minor changes for FSE?

I don't know. I have deliberately not followed the evolving mess of the block world and the new custom post type named "template". @carolinan was leading the handbook changes, I think.

**Comment by carolinan** [comment]
@atachibana I have not heard any suggestions about having two separate handbooks, but if you think this would be a better solution, please bring it up with the [team representatives](https://make.wordpress.org/themes/handbook/about/members/). _It might be easier to have two separate handbooks than trying to combine them._

FSE is experimental and until it is no longer experimental, the documentation for FSE is in the block editor handbook.

**Comment by kafleg** [comment]
@atachibana I will look into this and reply here. Sorry, I missed this notification.

**Comment by kafleg** [comment]
I prefer to go with a separate handbook for FSE. But I am not sure how users will find it easy on the same or in different.

**Comment by atachibana** [comment]
@carolinan, @kafleg and all, Thank you.

For the time being, at least while FSE is experimental, the Gutenberg Handbook and minor changes to Developer Handbook will be fine. In fact, [theme.json page](https://developer.wordpress.org/themes/advanced-topics/theme-json/) exists in the Theme Handbook.
I close this issue but would like to follow this topic.

**Comment by carolinan** [comment]
theme.json is not limited to full site editing, it also works with "classic" themes.

**Comment by atachibana** [comment]
@carolinan
Ah, Sorry, I mixed the FSE and block relating features in my context.
