### ISSUE TITLE
Add a REST API client library for PHP

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#10]
On https://developer.wordpress.org/rest-api/using-the-rest-api/client-libraries/ , there are client library recommendations for JavaScript, Ruby, C#.

I would suggest adding a recommendation for PHP as well, seeing as how Wordpress is run by PHP itself.

This could be a good enough candidate: https://github.com/varsitynewsnetwork/wordpress-rest-api-client (last updated 10 months ago).
This one probably not so: https://github.com/WP-API/client-php (last update 7 years ago).

BTW, the recommended Ruby one is unmaintained too, tested up to WP 4.7.2, last updated 4 years ago.

**Comment by zzap** [comment]
Same as the other REST API issue, #9, this one should be reported in [REST API repo](https://github.com/WP-API/docs/issues). Thanks
