### ISSUE TITLE
[Theme Handbook Overhaul] Global Settings and Styles > Settings

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1003]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Settings" under Chapter 3: Global Settings and Styles

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1CTpWrwr_Vjqtc3f4oHRjtzEY8SR5PXHleUsooaGulUA/edit?usp=sharing

**Comment by justintadlock** [comment]
This one was relatively short because it is just an intro page to `theme.json` > `settings`. Mostly, it's just a links page to each of the individual settings docs: https://docs.google.com/document/d/1CTpWrwr_Vjqtc3f4oHRjtzEY8SR5PXHleUsooaGulUA/edit?usp=sharing

It may need to be updated as each of the sub-pages are drafted.

**Comment by justintadlock** [comment]
This has now been ported to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=148907&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/global-settings-and-styles/settings/
