### ISSUE TITLE
Change the theme name in child theme page

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#103]
Information on the child theme page is quite old. Better to change the theme name to the current latest WordPress core theme.
https://developer.wordpress.org/themes/advanced-topics/child-themes/

Twenty Fifteen => Twenty Twenty-Two

**Comment by Kenshino** [comment]
Feel free to edit it but there isn't really a need or benefit to this.

It's fine as long as we understand there's no need to update documents for such reasons. It's a catch-up we won't ever finish

**Comment by kafleg** [comment]
Thanks for adding your view. :)

**Comment by carolinan** [comment]
Agree, as long as the content including any code examples are still valid, the theme name doesn't need to be updated.
