### ISSUE TITLE
[DevHub] Including CSS & JavaScript | Theme Handbook

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#1037]
## Issue Description
Revise content for updated fifth `$args` parameter of `wp_enqueue_script()` and `wp_register_script()` from WP 6.3.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/basics/including-css-javascript/

## Section of Page with the issue
* amend "Scripts" section
* add "Delayed Script Loading" section between "Scripts" section and "Comment Reply Script" section

## Why is this a problem?
They've become outdated since the release of WP 6.3

## Suggested Fix
See each of the comments below for detail.

**Comment by stevenlinx** [comment]
### Scripts section

original text:
**$in_footer** is a boolean parameter (true/false) that allows you to place your scripts in the footer of your HTML document rather then in the header, so that it does not delay the loading of the DOM tree.

replacement text:
**$args** an array of arguments that define footer printing (via an in_footer key) and script loading strategies (via a strategy key) such as defer or async. This replaces/overloads the $in_footer parameter as of WordPress version 6.3.

**Comment by stevenlinx** [comment]
### new section: Delayed Script Loading
(add between "Scripts" section and "Comment Reply Script" section)

WordPress provides support for specifying a script loading strategy via the `wp_register_script()` and `wp_enqueue_script()` functions, by way of the `strategy` key within the new `$args` array parameter introduced in WordPress 6.3.

Supported strategies are as follows:

- **defer**
    - Added by specifying an array key value pair of `'strategy' => 'defer'` to the $args parameter.
    - Scripts marked for deferred execution — via the defer script attribute — are only executed once the DOM tree has fully loaded (but before the `DOMContentLoaded` and window load events). Deferred scripts are executed in the same order they were printed/added in the DOM, unlike asynchronous scripts.
- **async**
    - Added by specifying an array key value pair of **'strategy' => 'async'** to the `$args` parameter.
    - Scripts marked for asynchronous execution — via the `async` script attribute — are executed as soon as they are loaded by the browser. Asynchronous scripts do not have a guaranteed execution order, as script B (although added to the DOM after script A) may execute first given that it may complete loading prior to script A. Such scripts may execute either before the DOM has been fully constructed or after the `DOMContentLoaded` event.

Following is an example of specifying a loading strategy during script registration:

```
wp_register_script( 
    'foo', 
    '/path/to/foo.js', 
    array(), 
    '1.0.0', 
    array( 
        'strategy'  => 'defer',
    )
);
```

The same approach applies when using `wp_enqueue_script()`.

When specifying a delayed script loading strategy, consideration of the script’s dependency tree (its dependencies and/or dependents) is taken into account when deciding on an “eligible strategy” so as not to result in application of a strategy that is valid for one script but detrimental to others in the tree by causing an unintended out of order of execution. As a result of such logic, the intended loading strategy that you pass via the `$args` parameter may not be the final (chosen) strategy, but it will never be detrimental to (or stricter than) the intended strategy.

**Comment by stevenlinx** [comment]
@simondowdles

I've updated the Handbook page for this Issue.

**Comment by 10upsimon** [comment]
@stevenlinx I've noticed that the code example block under the [Scripts](https://developer.wordpress.org/themes/basics/including-css-javascript/#scripts) heading needs updating.

It currently reads as follows:

```
wp_enqueue_script( $handle, $src, $deps, $ver, $in_footer);
```

Which references the older `$in_footer` arg. I also note the missing space before closing parenthesis. It should be updated to read as follows (making use of the new `$args` param):

```
wp_enqueue_script( $handle, $src, $deps, $ver, $args );
```

**Comment by stevenlinx** [comment]
I've revised the content with the correct param.
