### ISSUE TITLE
[DevHub] Server Side PHP and Enqueuing | Plugin Handbook

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#1040]
## Issue Description
Revise content for updated fifth `$args` parameter of `wp_enqueue_script()` and `wp_register_script()` from WP 6.3.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/javascript/enqueuing/

## Section of Page with the issue
* amend "Enqueue" section
* add new “Delayed Script Loading” section following the existing "Register vs. Enqueue" section.

## Why is this a problem?
They've become outdated since the release of WP 6.3

## Suggested Fix
See each of the comments below for detail.

**Comment by stevenlinx** [comment]
### "Enqueue" section

Update introductory paragraph preceding code block

The enqueue function accepts five parameters as follows:

- **$handle** is the name for the script.
- **$src** defines where the script is located. For portability, use `plugins_url()` to build the proper URL. If you are enqueuing the script for something besides a plugin, use some related function to create a proper URL – never hardcode it
- **$deps** is an array that can handle any script that your new script depends on, such as jQuery. Since we are using jQuery to send an AJAX request, you will at least need to list `'jquery'` in the array.
- **$ver** lets you list a version number.
- **$args** an array of arguments that define footer printing (via an `in_footer` key) and script loading strategies (via a `strategy` key) such as `defer` or `async`. This replaces/overloads the `$in_footer` parameter as of WordPress version 6.3.

Update first code block:

replace last parameter with:

```
    array(
          'in_footer' => true,
     )
```

Update second code block:

replace last parameter with:

```
           array(
                'in_footer' => true,
           )
```

**Comment by stevenlinx** [comment]
### new section: Delayed Script Loading
(add after existing "Register vs. Enqueue" section)

WordPress provides support for specifying a script loading strategy via the `wp_register_script()` and `wp_enqueue_script()` functions, by way of the `strategy` key within the new `$args` array parameter introduced in WordPress 6.3.

Supported strategies are as follows:

- **defer**
    - Added by specifying an array key value pair of `'strategy' => 'defer'` to the $args parameter.
    - Scripts marked for deferred execution — via the defer script attribute — are only executed once the DOM tree has fully loaded (but before the `DOMContentLoaded` and window load events). Deferred scripts are executed in the same order they were printed/added in the DOM, unlike asynchronous scripts.
- **async**
    - Added by specifying an array key value pair of `'strategy' => 'async'` to the `$args` parameter.
    - Scripts marked for asynchronous execution — via the `async` script attribute — are executed as soon as they are loaded by the browser. Asynchronous scripts do not have a guaranteed execution order, as script B (although added to the DOM after script A) may execute first given that it may complete loading prior to script A. Such scripts may execute either before the DOM has been fully constructed or after the `DOMContentLoaded` event.

Following is an example of specifying a loading strategy for an additional script enqueue within our plugin:

````
wp_register_script( 
    'ajax-script-two',
	plugins_url( '/js/myscript.js', __FILE__ ),
	array( ajax-script ),
	'1.0.,0',
	array(
          'strategy' => 'defer',
     )
);
````

The same approach applies when using `wp_enqueue_script()`. In the example above, we indicate that we intend to load the `'ajax-script-two'` script in a deferred manner.

When specifying a delayed script loading strategy, consideration of the script’s dependency tree (its dependencies and/or dependents) is taken into account when deciding on an “eligible strategy” so as not to result in application of a strategy that is valid for one script but detrimental to others in the tree by causing an unintended out of order of execution. As a result of such logic, the intended loading strategy that you pass via the `$args` parameter may not be the final (chosen) strategy, but it will never be detrimental to (or stricter than) the intended strategy.

**Comment by stevenlinx** [comment]
@simondowdles

I've revised the Handbook page for this Issue.

**Comment by 10upsimon** [comment]
This looks good @stevenlinx, thank you. Not a blocker, but one observation is that the updated/adde code block under the [Delayed Script Loading](https://developer.wordpress.org/plugins/javascript/enqueuing/#delayed-script-loading) header is not formatted the same as the others, i.e probably does not have the PHP language selected for syntax highlighting.

**Comment by stevenlinx** [comment]
I've revised the syntax from none to PHP.
