### ISSUE TITLE
[DevHub] wp_register_script() | Code Reference

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#1041]
## Issue Description
Revise content for updated fifth `$args` parameter of `wp_register_script()` from WP 6.3.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/wp_register_script/

## Section of Page with the issue
* amend "Usage" section under More Info section
* add “Delayed Script Loading” Section under More Info section

## Why is this a problem?
They've become outdated since the release of WP 6.3.

## Suggested Fix
See each of the comments below for detail.

**Comment by stevenlinx** [comment]
### Usage section

Add an additional bullet point:

- "As of WordPress 6.3, the new $args parameter - that replaces/overloads the prior $in_footer parameter - can be used to specify a script loading strategy. See the sections to follow for more information."

**Comment by stevenlinx** [comment]
### new section: Delayed Script Loading

WordPress provides support for specifying a script loading strategy via the <tt>wp_register_script()</tt> and <tt>wp_enqueue_script()</tt> functions, by way of the `strategy` key within the new `$args` array parameter introduced in WordPress 6.3.

Supported strategies are as follows:

- **defer**
    - Added by specifying an array key value pair of `'strategy' => 'defer'` to the $args parameter.
    - Scripts marked for deferred execution — via the defer script attribute — are only executed once the DOM tree has fully loaded (but before the `DOMContentLoaded` and window load events). Deferred scripts are executed in the same order they were printed/added in the DOM, unlike asynchronous scripts.
- **async**
    - Added by specifying an array key value pair of `'strategy' => 'async'` to the `$args` parameter.
    - Scripts marked for asynchronous execution — via the `async` script attribute — are executed as soon as they are loaded by the browser. Asynchronous scripts do not have a guaranteed execution order, as script B (although added to the DOM after script A) may execute first given that it may complete loading prior to script A. Such scripts may execute either before the DOM has been fully constructed or after the `DOMContentLoaded` event.

Following is an example of specifying a loading strategy during script registration:

````
wp_register_script( 
    'foo', 
    '/path/to/foo.js', 
    array(), 
    '1.0.0', 
    array( 
        'strategy'  => 'defer',
    )
);
````

The same approach applies when using <tt>wp_enqueue_script()</tt>.

When applying a loading strategy via either the <tt>wp_register_script()</tt> and <tt>wp_enqueue_script()</tt> functions, the scripts dependency tree is taken into consideration and the most eligible loading strategy is applied. 

While the intended (delayed) strategy passed by the code author may not be the final one, it will never be a stricter one, thus maintaining the integrity of the dependency tree.

**Comment by stevenlinx** [comment]
@simondowdles

I've revised the Handbook page for this Issue.

**Comment by 10upsimon** [comment]
@stevenlinx this page is looking good, thank you.
