### ISSUE TITLE
[DevHub] wp_enqueue_script() | Code Reference

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#1043]
## Issue Description
Revise content for updated fifth `$args` parameter of `wp_enqueue_script()` from WP 6.3.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/wp_enqueue_script/

## Section of Page with the issue
* amend "Usage" section under More Info section

## Why is this a problem?
They've become outdated since the release of WP 6.3.

## Suggested Fix
See each of the comments below for detail.

**Comment by stevenlinx** [comment]
### "Usage" section

Additions of the following paragraphs:

"As of WordPress 6.3, the new `$args` parameter - that replaces/overloads the prior `$in_footer` parameter - can be used to specify a script loading strategy. See below for more information."

"Following is an example of specifying a loading strategy during script enqueuing:"

````
wp_enqueue_script( 
    'foo', 
    '/path/to/foo.js', 
    array(), 
    '1.0.0', 
    array( 
        'strategy'  => 'defer',
    )
);
````

"The same approach applies when using <tt>wp_register_script()</tt>."

"When applying a loading strategy via either the <tt>wp_register_script()</tt> and <tt>wp_enqueue_script()</tt> functions, the scripts dependency tree is taken into consideration and the most eligible loading strategy is applied."

"While the intended (delayed) strategy passed by the code author may not be the final one, it will never be a stricter one, thus maintaining the integrity of the dependency tree. "

**Comment by stevenlinx** [comment]
@simondowdles

1.)
For this page, I added the section

"Supported strategies are as follows:

- **defer** ...
- **async** ..."

which I think should be included that wasn't in the Google Doc.

The rationale being the function shares the same `$args` operation as `wp_register_script()` and as the first paragraph indicated "...can be used to specify a script loading strategy."

2.)
I've revised the page.

**Comment by 10upsimon** [comment]
Thanks for adding that extra info @stevenlinx, this page looks good to me.
