### ISSUE TITLE
#6479 Encourage people to change default tagline

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1069]
https://core.trac.wordpress.org/ticket/6479

**Comment by zzap** [comment]
Hey @dougaxe1, thanks for your interest in this issue! 🍪🍪🍪<br>If you have any questions, do not hesitate to ask them in our <a href='https://wordpress.slack.com/archives/C02RP4WU5'>#docs</a> Slack channel.<br>Enjoy and happy contributing ❤️<br><br>P.S. This is bot comment.

**Comment by dougaxe1** [comment]
HelpHub page to be updated noting the new blank default:
- https://wordpress.org/documentation/article/settings-general-screen/#tagline

**Comment by dougaxe1** [comment]
/review

HelpHub page updated: https://wordpress.org/documentation/article/settings-general-screen/ (and Changelog added)

**Comment by estelaris** [comment]
This article has been updated
