### ISSUE TITLE
Typo on https://wordpress.org/documentation/article/template-part-block

### ISSUE THREAD

**Issue by mdrovdahl** [WordPress/Documentation-Issue-Tracker#1090]
## Issue Description

In https://wordpress.org/documentation/article/template-part-block/#managing-template-parts-and-patterns

> At the bottom of the patters screen, there is an option to manage template parts.

Should read (without the bold):

> At the bottom of the **patterns** screen, there is an option to manage template parts.

## URL of the Page with the Issue

In https://wordpress.org/documentation/article/template-part-block/

## Section of Page with the issue

In https://wordpress.org/documentation/article/template-part-block/#managing-template-parts-and-patterns

## Why is this a problem?

Patters means to make a repeated light [tapping] sound. I'm 100% certain the author meant to use the word patterns instead =)

## Suggested Fix

add an "n"

**Comment by flexseth** [comment]
Apologies, assigned this to myself but I'm not sure how to edit this part of the documentation.
