### ISSUE TITLE
Migrate "Supported Versions" page from Codex to HelpHub

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#1094]
## What is the new page you are requesting?

Supported Versions page.

Codex page:
https://codex.wordpress.org/Supported_Versions

HelpHub page:
https://wordpress.org/documentation/article/supported-versions/

The following paragraph (edited) should also be migrated:
"Some folks in [WordPress Slack](https://make.wordpress.org/chat/) might be familiar with unreleased versions, but it'll be hit-or-miss, and no guarantee of support is provided."

## How will this new page help you?
All relevant Codex pages shall be migrated to HelpHub/DevHub.

Part of the content on this Codex page is dependent on new WP versions, and as long as it still exists, someone will need to update this page (or `{{Template:CurrentVersion}}`) whenever a new WP version is released. Hence, these type of pages shall have higher priority for the migration project.

**Comment by zzap** [comment]
Versions info is all over the place and should be cleared up. 

Codex:
- https://codex.wordpress.org/Supported_Versions
- https://codex.wordpress.org/WordPress_Versions
- https://wordpress.org/documentation/wordpress-version/version-0-70/
- each version...

HelpHub:
- Article: https://wordpress.org/documentation/article/supported-versions/
- Article: https://wordpress.org/documentation/article/wordpress-versions/ - each version links to the Codex one
- CPT archive: https://wordpress.org/documentation/wordpress-versions/
- CPT single: https://wordpress.org/documentation/wordpress-version/version-6-3-1/
- each version..

Download:
- https://wordpress.org/download/releases/

**Comment by zzap** [comment]
I'm going to open a new issue for tracking all tasks in this migration.

**Comment by stevenlinx** [comment]
Done and redirected.
