### ISSUE TITLE
Update and modernize the design and styles for handbooks

### ISSUE THREAD

**Issue by mkaz** [WordPress/Documentation-Issue-Tracker#11]
The overall design needs updating and modernizing to work better in a multi-device, responsive world. The fonts and typography are quite small and difficult to read. The middle columns are narrow, the sidebars are cramped and the overall look and feel of the documentation sites look dated.

This cuts across the entire Make network of sites, and [the News site has a design refresh in the works](https://wordpress.org/news/2021/06/a-new-design-is-coming-to-wordpress-news/). Ideally we can poach styles from those updates and improve the documentation sites.

**Comment by zzap** [comment]
I believe there's an overal wp.org design update happening right now so I'm going to close this one.
