### ISSUE TITLE
Title on Advanced Administration handbook is "Handbook Handbook"

### ISSUE THREAD

**Issue by Kenshino** [WordPress/Documentation-Issue-Tracker#1101]
We gotta fix this title :P

<img width="456" alt="image" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/4746365/1803e408-ffa0-4cd8-8ae4-c0b0bf5ff345">

**Comment by zzap** [comment]
What URL is that? We have two instances of Advanced administration handbook.

**Comment by zzap** [comment]
Fixed. It was the settings in dashboard.
![General-Settings-‹-WordPress-Developer-Resources-—-WordPress](https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/3c9d3abc-9ad3-4937-9bf1-9c0f7cde1545)
