### ISSUE TITLE
Redirect HelpHub articles to Advanced Administration handbook

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1102]
- [x] [WordPress Advanced Administration Handbook](https://developer.wordpress.org/advanced-administration/)
   - [x] [Before You Install](https://developer.wordpress.org/advanced-administration/before-install/)
      - [x] [Creating Database for WordPress](https://developer.wordpress.org/advanced-administration/before-install/creating-database/)
      - [x] [How to install WordPress](https://developer.wordpress.org/advanced-administration/before-install/howto-install/)
      - [x] [Running a Development Copy of WordPress](https://developer.wordpress.org/advanced-administration/before-install/development/)
      - [x] [Installing WordPress in your language](https://developer.wordpress.org/advanced-administration/before-install/in-your-language/)
      - [x] [Installing Multiple WordPress Instances](https://developer.wordpress.org/advanced-administration/before-install/multiple-instances/)
      - [x] [Install WordPress at popular providers](https://developer.wordpress.org/advanced-administration/before-install/popular-providers/)
   - [x] [Server configuration](https://developer.wordpress.org/advanced-administration/server/)
      - [x] [Changing File Permissions](https://developer.wordpress.org/advanced-administration/server/file-permissions/)
      - [x] [Finding Server Info](https://developer.wordpress.org/advanced-administration/server/server-info/)
      - [x] [Giving WordPress Its Own Directory](https://developer.wordpress.org/advanced-administration/server/wordpress-in-directory/)
      - [x] [Configuring Wildcard Subdomains](https://developer.wordpress.org/advanced-administration/server/subdomains-wildcard/)
      - [x] [Emptying a Database Table](https://developer.wordpress.org/advanced-administration/server/empty-database/)
      - [x] [Web servers](https://developer.wordpress.org/advanced-administration/server/web-server/)
      - [x] [nginx](https://developer.wordpress.org/advanced-administration/server/web-server/nginx/)
      - [x] [Control Panels](https://developer.wordpress.org/advanced-administration/server/control-panel/)
   - [x] [WordPress configuration](https://developer.wordpress.org/advanced-administration/wordpress/)
      - [x] [wp-config.php](https://developer.wordpress.org/advanced-administration/wordpress/wp-config/)
      - [x] [Site Architecture](https://developer.wordpress.org/advanced-administration/wordpress/site-architecture/)
      - [x] [Cookies](https://developer.wordpress.org/advanced-administration/wordpress/cookies/)
      - [x] [Update Services](https://developer.wordpress.org/advanced-administration/wordpress/update-services/)
      - [x] [Editing Files](https://developer.wordpress.org/advanced-administration/wordpress/edit-files/)
      - [x] [CSS](https://developer.wordpress.org/advanced-administration/wordpress/css/)
      - [x] [Feeds](https://developer.wordpress.org/advanced-administration/wordpress/feeds/)
      - [x] [Multilingual WordPress](https://developer.wordpress.org/advanced-administration/wordpress/multilingual/)
      - [x] [oEmbed](https://developer.wordpress.org/advanced-administration/wordpress/oembed/)
      - [x] [Loopbacks](https://developer.wordpress.org/advanced-administration/wordpress/loopback/)
      - [x] [Common errors](https://developer.wordpress.org/advanced-administration/wordpress/common-errors/)
   - [x] [Upgrading / Migration](https://developer.wordpress.org/advanced-administration/upgrade/)
      - [x] [FTP Clients](https://developer.wordpress.org/advanced-administration/upgrade/ftp/)
         - [x] [Using FileZilla](https://developer.wordpress.org/advanced-administration/upgrade/ftp/filezilla/)
      - [x] [phpMyAdmin](https://developer.wordpress.org/advanced-administration/upgrade/phpmyadmin/)
      - [x] [Upgrading](https://developer.wordpress.org/advanced-administration/upgrade/upgrading/)
      - [x] [Migration](https://developer.wordpress.org/advanced-administration/upgrade/migrating/)
   - [x] [WordPress Multisite / Network](https://developer.wordpress.org/advanced-administration/multisite/)
      - [x] [Before You Create A Network](https://developer.wordpress.org/advanced-administration/multisite/prepare-network/)
      - [x] [Create A Network](https://developer.wordpress.org/advanced-administration/multisite/create-network/)
      - [x] [WordPress Multisite Domain Mapping](https://developer.wordpress.org/advanced-administration/multisite/domain-mapping/)
      - [x] [Multisite Network Administration](https://developer.wordpress.org/advanced-administration/multisite/administration/)
      - [x] [Network Admin](https://developer.wordpress.org/advanced-administration/multisite/admin/)
      - [x] [Migrate WordPress sites into WordPress Multisite](https://developer.wordpress.org/advanced-administration/multisite/sites-multisite/)
   - [x] [Plugins](https://developer.wordpress.org/advanced-administration/plugins/)
      - [x] [Must Use Plugins](https://developer.wordpress.org/advanced-administration/plugins/mu-plugins/)
   - [x] [Themes](https://developer.wordpress.org/advanced-administration/themes/)
   - [x] [Security](https://developer.wordpress.org/advanced-administration/security/)
      - [x] [Your password](https://developer.wordpress.org/advanced-administration/security/logging-in/)
      - [x] [Multi-Factor Authentication](https://developer.wordpress.org/advanced-administration/security/mfa/)
      - [x] [Backups](https://developer.wordpress.org/advanced-administration/security/backup/)
         - [x] [Database Backup](https://developer.wordpress.org/advanced-administration/security/backup/database/)
         - [x] [Files Backup](https://developer.wordpress.org/advanced-administration/security/backup/files/)
      - [x] [HTTPS](https://developer.wordpress.org/advanced-administration/security/https/)
      - [x] [Brute Force Attacks](https://developer.wordpress.org/advanced-administration/security/brute-force/)
      - [x] [Hardening WordPress](https://developer.wordpress.org/advanced-administration/security/hardening/)
   - [x] [Performance / Optimization](https://developer.wordpress.org/advanced-administration/performance/)
      - [x] [Cache](https://developer.wordpress.org/advanced-administration/performance/cache/)
      - [x] [Optimization](https://developer.wordpress.org/advanced-administration/performance/optimization/)
   - [x] [Debugging WordPress](https://developer.wordpress.org/advanced-administration/debug/)
      - [x] [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/)
      - [x] [Debugging a WordPress Network](https://developer.wordpress.org/advanced-administration/debug/debug-network/)
      - [x] [Using Your Browser to Diagnose JavaScript Errors](https://developer.wordpress.org/advanced-administration/debug/debug-javascript/)
      - [x] [Test Driving WordPress](https://developer.wordpress.org/advanced-administration/debug/test-driving/)
   - [x] [Resources](https://developer.wordpress.org/advanced-administration/resources/)

**Comment by javiercasares** [comment]
When 
- https://github.com/WordPress/wporg-documentation-2022/pull/77
- https://github.com/WordPress/wporg-documentation-2022/pull/60
- https://github.com/WordPress/wporg-documentation-2022/issues/59
are closed, this ticked should be closed too.

**Comment by ryelle** [comment]
These redirects from Documentation were just deployed. Let me know if anything seems off 🙂

**Comment by javiercasares** [comment]
Checked and everything is redirecting! Thanks a lot @ryelle 
cc// @zzap @estelaris

**Comment by sabernhardt** [comment]
As reported on [Core Trac 60736](https://core.trac.wordpress.org/ticket/60736), the [Feeds page from DevHub](https://wordpress.org/documentation/article/wordpress-feeds/) is missing without a redirect.

The [new Advanced Administration handbook page](https://developer.wordpress.org/advanced-administration/wordpress/feeds/) removed some sections (https://github.com/WordPress/Advanced-administration-handbook/issues/93), but it likely is still appropriate to redirect to that URL.
