### ISSUE TITLE
[Theme Handbook Overhaul] Global Settings and Styles > Styles

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1117]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Styles" under Chapter 3: Global Settings and Styles

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/11SuTqMXWx_vm9BMDDg_L_ZDnmZyv60tDiZKwitIAWF0/edit?usp=sharing

**Comment by justintadlock** [comment]
After mapping the outline for this doc, I came to the conclusion that this is best split into four separate documents (this includes the intro and three sub-docs):

- Styles (introduces `theme.json`'s `styles` structure)
	- Applying Styles (how to apply styles to root, elements, blocks)
	- Using Presets (how to reference presets from settings presets)
	- Supported Styles (reference to every available style)

This was one of the questions I'd pondered when we made the outline. I wasn't sure what it'd look like until we really got into it. But after outlining all of this, I realized that this would be a massively long doc if it wasn't split up.

**Comment by justintadlock** [comment]
This intro doc is now drafted and can be reviewed: https://docs.google.com/document/d/11SuTqMXWx_vm9BMDDg_L_ZDnmZyv60tDiZKwitIAWF0/edit?usp=sharing

**Comment by justintadlock** [comment]
This has now been ported to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=148909&action=edit

**Comment by kafleg** [comment]
Looks good.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/global-settings-and-styles/styles/
