### ISSUE TITLE
[Theme Handbook Overhaul] Global Settings and Styles > Styles > Applying Styles

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1118]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Applying Styles" under Chapter 3: Global Settings and Styles > Styles.

This ticket was split from #1117.

The content of this page is already drafted and ready for review: https://docs.google.com/document/d/1wgkFt7htULaA3WgHCUKjR_OUkDYGQX4DlTBz4_mpOlg/edit?usp=sharing

**Comment by justintadlock** [comment]
This is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149109&action=edit

**Comment by kafleg** [comment]
Looks good to me. Checking and reading documentation is giving me lots of ideas as well.

**Comment by carolinan** [comment]
Hi, 
can we also add `core/button: fill` under "The currently available blocks and their core WordPress style variations are:"

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/global-settings-and-styles/styles/applying-styles/
