### ISSUE TITLE
Typos in section 4. Installing VVV

### ISSUE THREAD

**Issue by jamesgoldswain** [WordPress/Documentation-Issue-Tracker#112]
## Issue Description
The section with the note on running the _vagrant up_ command has spelling mistakes which would improve the manner in which it reads.

## URL of the Page with the Issue
https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/installing-vvv/#4-start-up-vvv

## Section of Page with the issue
4-start-up-vvv

## Why is this a problem?
Typo - should be, reads incorrectly

"If you are on Windows this **_must be a ran_** with elevated administrator **_priviledges_**."

## Suggested Fix
"If you are on Windows this **_must be run_** with elevated administrator **_privileges_**."

**Comment by zzap** [comment]
Thank you for reporting this, @jamesgoldswain. It is fixed now.
