### ISSUE TITLE
[Theme Handbook Overhaul] Global Settings and Styles > Introduction to theme.json

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1122]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Introduction to theme.json" under Chapter 3: Global Settings and Styles.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1cbAzl6QjkotMnHPqY6SnmDBqcG3ZLxe7UU7dWyqv_kM/edit?usp=sharing

**Comment by justintadlock** [comment]
This has now been ported to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=148903&action=edit

**Comment by kafleg** [comment]
Thank you :)

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/global-settings-and-styles/introduction-to-theme-json/

Do not close yet. See note above.

**Comment by justintadlock** [comment]
Page updated with new links.
