### ISSUE TITLE
[Theme Handbook Overhaul] Global Settings and Styles > Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1124]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Patterns" under Chapter 3: Global Settings and Styles.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1SoZraC5XnR289tQq4bapb4XSkvFtiYdEPX3FPv-jTQ8/edit?usp=sharing

_Note that this was a missing `theme.json` section from the original outline._

**Comment by justintadlock** [comment]
This doc is now drafted and ready for review.

**Comment by kafleg** [comment]
Looks good to me. 

can you write a sentence on how the patterns are categorised in the themes patterns section? 
![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/13062231/2c8eaf6a-b72b-4da1-a841-02ca76f17291)

**Comment by justintadlock** [comment]
> can you write a sentence on how the patterns are categorised in the themes patterns section?

Good idea! I'll add that in.

**Comment by justintadlock** [comment]
This has now been ported to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=148915&action=edit

**Comment by kafleg** [comment]
Minor edit, looks fine.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/global-settings-and-styles/patterns/
