### ISSUE TITLE
[Theme Handbook Overhaul] Templates > Introduction to templates

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1126]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Introduction to templates" under Chapter 4: Templates.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1vxZaQpk_81l82GpCv08vcvbGvlCpLVTdqwRwi6o7LtY/edit?usp=sharing

**Comment by kafleg** [comment]
Looks good to me. The words are very easy to understand. Thank you so much.

**Comment by justintadlock** [comment]
The draft for this is now in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149221&action=edit

**Comment by justintadlock** [comment]
The page is now published here: https://developer.wordpress.org/themes/templates/introduction-to-templates/
