### ISSUE TITLE
[Theme Handbook Overhaul] Templates > Template Parts

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1130]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Template Parts" under Chapter 4: Templates.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1k2AMYrlto4s0VyZP5HMtAW-hNwHD9Mm_2WO-kGKKrTQ/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft for this doc is finished and ready for review.

**Comment by kafleg** [comment]
Looks good to me.

**Comment by carolinan** [comment]
Looks good.
- Unless I missed it, I was surprised that the wp_template_part post type was not mentioned.
- I am glad that it mentions that nested folders are not supported since this is currently broken: https://github.com/WordPress/gutenberg/issues/54279

**Comment by justintadlock** [comment]
Thanks for the feedback.

> Unless I missed it, I was surprised that the wp_template_part post type was not mentioned.

I added a note on the first mention of user-created parts being saved.

> I am glad that it mentions that nested folders are not supported since this is currently broken: https://github.com/WordPress/gutenberg/issues/54279

Thanks for this link. I added it where the missing support was mentioned in the post in case someone wanted to dig deeper.

**Comment by justintadlock** [comment]
The draft for this doc is now in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149235&action=edit

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/templates/template-parts/
