### ISSUE TITLE
Add Creating Tables with Plugins Page to DevHub

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Documentation-Issue-Tracker#1133]
## What is the new page you are requesting?

I am opening this issue knowing full well that I still need to [finish up the Action and Filter Reference migration](https://github.com/WordPress/Documentation-Issue-Tracker/issues/370), but I'm hoping some other contributor has time to work on this.

The Codex has a page on [Creating Tables with Plugins](https://codex.wordpress.org/Creating_Tables_with_Plugins), which would be ideal to move to the developer hub. I think it would make sense to add this to the [Plugin Handbook](https://developer.wordpress.org/plugins/), as a new chapter after [Post Types](https://developer.wordpress.org/plugins/post-types/)

## How will this new page help you?

This is one of the few pages (the Action and Filter Reference being the other) that hasn't been migrated to the new developer docs hub, and moving it over will allow us to improve it for future developers.

**Comment by digitalchild** [comment]
I'd be interested to assist with this.

**Comment by jonathanbossenger** [comment]
@digitalchild how about we go about doing this

1. I'll add the page from the Codex to the Plugin handbook as is
2. When you are finished with the suggested updates, you share that here, and we can review it together.

Once we're in agreement on the updates, I can work on getting the new page in the handbook updated, but at least in the meantime a version of it exists in DevHub.

**Comment by jonathanbossenger** [comment]
@theMikeD I'd like to check in with you, to see if you agree to add the [Creating Tables with Plugins](https://codex.wordpress.org/Creating_Tables_with_Plugins) would make sense to add to the [Plugin Handbook](https://developer.wordpress.org/plugins/), as a new chapter after [Post Types](https://developer.wordpress.org/plugins/post-types/)?

If you agree, I can start porting that data over.

**Comment by jonathanbossenger** [comment]
I have started with a draft, and I'll be reviewing it and updating any links over the next week or so

https://developer.wordpress.org/wp-admin/post.php?post=152387&action=edit

@dd32 I know you're working on a sheet of old Codex pages, so wanted to share this update with you as well.

**Comment by jonathanbossenger** [comment]
I have updated the links and published this page.
