### ISSUE TITLE
[Theme Handbook Overhaul] Features > Chapter Landing Page

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1134]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating the landing page content for Chapter 5: Features.

The content for the new page is drafted in a Google Doc: https://docs.google.com/document/d/1Hn4Ph9G-z4Sv1_H2w7nHKdL9cyY6q9URCwFh42t57Ic/edit?usp=sharing

This draft is already written and can be reviewed.

**Comment by justintadlock** [comment]
This doc is now moved to the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149260&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
This doc is now published here: https://developer.wordpress.org/themes/features/
