### ISSUE TITLE
[Theme Handbook Overhaul] Features > Block Stylesheets

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1135]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Block Stylesheets" under Chapter 5: Features.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1ssbRkL09_yQe9JNqLFwG1iTHgz8SJuI4_d3hek0o038/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc is now drafted and ready for review.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149276&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
This doc is now published here: https://developer.wordpress.org/themes/features/block-stylesheets/
