### ISSUE TITLE
[HelpHub] First Steps with WordPress (Classic Editor) - screenshots and alt text

### ISSUE THREAD

**Issue by josevarghese** [WordPress/Documentation-Issue-Tracker#1137]
## Issue Description
Update the screenshots with the new interface of the Plugin page

## URL of the Page with the Issue
(https://wordpress.org/documentation/article/first-steps-with-wordpress-classic/#using-wordpress-plugins)

## Section of Page with the issue
Using WordPress Plugins

## Why is this a problem?
Outdated image

## Suggested Fix
See below

**Comment by josevarghese** [comment]
Can you please assign to me

**Comment by josevarghese** [comment]
Change the image under the heading "Using WordPress Plugins" to the one below, as the current screenshot is missing the option to enable auto-update.

![plugins-page](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/ef96c990-fd08-4b18-afc9-adfe2f5120e5)
Alt tag for the image: Plugin screen

Also, right now the alt title and paragraph are not divided by a line break. So kindly add a line break after the "Plugin Screen", so that the paragraph can be read correctly.

**Comment by Leonardus-Nugraha** [comment]
Updated the plugin screen image on the article & added alt text.

**Comment by josevarghese** [comment]
Thank you @Leonardus-Nugraha :)
