### ISSUE TITLE
[Theme Handbook Overhaul] Features > Block Style Variations

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1138]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Block Style Variations" under Chapter 5: Features.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1JjQ1XS32SWos17WlxwGxT3rTggKWr8d5sjhP5W_Ht0I/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc has now been drafted and can be reviewed.

**Comment by kafleg** [comment]
In-depth writing. I've added a comment in the image. Rest of the content is fine to me.

**Comment by carolinan** [comment]
I added a comment about the 'fill' button style.

**Comment by kafleg** [comment]
LGTM
