### ISSUE TITLE
Remove mentions of plugins in user docs

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#114]
## Issue Description
We are recommending multilinual plugins.

## URL of the Page with the Issue
https://wordpress.org/support/article/multilingual-wordpress/

## Why is this a problem?
1. we are documenting only WordPress, not themes or plugins
2. we can't recommend theme or plugin because we're not responsible for it's proper functionality, support or documentation
3. this is prone to favorising products and we definitely want to avoid that
4. even if we disregard all from the above, which we shouldn't, we are making more work for us to keep recommendations up to date

## Suggested Fix
Remove all plugins mentions and modify text to still include various posibilities (functionalities). Add link to search results in Plugins repository, e.g. https://wordpress.org/plugins/search/multilingual/

Fixes #44

**Comment by theMikeD** [comment]
The only issue here is that the search results return only free solutions, which means WPMl is not shown. How do we address this? Or do we?

**Comment by zzap** [comment]
We note that there are paid options outside of WordPress repository and searching `WordPress multilingual plugin` in Google should provide enough results for moving forward.

**Comment by krafit** [comment]
Pull request crated ✅ 
https://github.com/WordPress/Advanced-administration-handbook/pull/284

**Comment by Leonardus-Nugraha** [comment]
Closing this issue as this was solved
