### ISSUE TITLE
[Theme Handbook Overhaul] Features > Block Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1141]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Block Patterns" under Chapter 5: Features.

The content for the new page will be drafted in a Google Doc:https://docs.google.com/document/d/1Zir3QD5ednCkdbNmsuTvvaVAIHgieAiOIN-N8v0IKXg/edit?usp=sharing

**Comment by justintadlock** [comment]
This draft is now complete and can be reviewed.

## Notes

Honestly, I think a single document cannot truly cover everything that's possible with patterns. As it stands, this initial draft is 3,600+ words. That's about the equivalent of a 14 or 15-page printed paper, so it's pretty big. I really don't like going that big with one doc because you tend to lose the reader, and it becomes harder to find what you're looking for, even with a Table of Contents.

While I think I hit most of the major points, there's still so much more to cover. In the **long term**, I believe we'll benefit from splitting this into multiple sub-pages that goes into even more details.

For the **short term** as we get this handbook overhaul moving forward, I think we can stick with a single doc.

**Comment by justintadlock** [comment]
The draft for this in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149262&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
This doc is now published here: https://developer.wordpress.org/themes/features/block-patterns/
