### ISSUE TITLE
[Theme Handbook Overhaul] Features > Block Variations

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1142]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Block Variations" under Chapter 5: Features.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1pVNG_r7P_ZvJW0efvOxP50LWVhacCL5WA0i0LqGymjg/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc is now drafted and ready for review.

**Comment by justintadlock** [comment]
This draft is now in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149280&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
This doc is now published here: https://developer.wordpress.org/themes/features/block-variations/
