### ISSUE TITLE
Block Hooks

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1144]
Marked as needing a standalone dev note on the Gutenberg  repo. Two tickets were combined in Oct 2023 to be one dev note on Block Hooks area.

For info, the full list and discussion on these tickets https://github.com/WordPress/gutenberg/issues/54998

**Comment by abhansnuk** [comment]
Updating this ticket to be a combined dev note for 'Block Hooks' as this has changed in the Gutenberg tracker. 

Experiment: Auto-inserting blocks on the frontend and in the editor (via REST API) #51449

https://github.com/WordPress/gutenberg/pull/54293
https://github.com/WordPress/gutenberg/pull/51449

@gzielo and @ndiego working on the dev note (TBC).

**Comment by bph** [comment]
Hi @ndiego Ideally, we need it by Monday... but do check in if there are blockers...

**Comment by bph** [comment]
Draft in Progress https://make.wordpress.org/core/wp-admin/post.php?post=108745&action=edit

**Comment by abhansnuk** [comment]
Excellent dev note @ndiego and really like your explanation and dividing this into two clear points, plus explaining why this causes some limitations.

I have done the second review for time, and
- changed the reference to "let's us" to 'explore below" to avoid the reference to 'we' and 'us' in dev notes
- added Developer Blog to the link to the article (good link by the way) to raise awareness that this exists
- added an excerpt 
- added tags
- added props line. Other collaborators or reviewers to be added to this

I wondered as this is going to be a very useful feature for eCommerce, whether there was a tag that has been used before on dev notes for flagging up notes particularly useful for eCommerce. @bph you might already know.

Thanks Nick for writing this dev note.  Perhaps it is one that will give rise to some case study posts on the Dev Blog.

**Comment by ndiego** [comment]
Thanks @abhansnuk! I'll add a few additional props when you are out. The code blocks still need a final review tomorrow by @gziolo.

**Comment by bph** [comment]
I reviewed the post: 

- changed title to **Introduction to Block Hooks for dynamic blocks** 
- typo fixed:  Blook Hooks to Block Hooks
- added an excerpt 
- changed `title "Plugins"` to titled **Plugins**  (Style guide: when referring to UI items, they need to be bolded)
- added review props

**Comment by gziolo** [comment]
The example included could get some tiny changes:

```php
function example_block_hooks( $hooked_blocks, $position, $anchor_block, $context ) {

	// Template/Template Part hooks.
	if ( $context instanceof WP_Block_Template ) {
		
		// Hook the "Like" button block before the Post Title in the Single template.
		if ( 
			'core/post-title' === $anchor_block &&
			'before' === $position &&
			'single' === $context->slug
		) {
			$hooked_blocks[] = 'ockham/like-button';
		}

		// Hook the Login/Logout link block after the Navigation block if the context of the template part is a header.
		if ( 
			'core/group' === $anchor_block &&
			'last_child' === $position &&
			'header' === $context->area
		) {
			$hooked_blocks[] = 'core/loginout';
		}
	}

	// Pattern hooks.
	if ( is_array( $context ) && isset( $context['slug'] ) ) {
		
		// Hook into the Post Meta pattern in the Twenty Twenty-Four theme.
		if ( 
			'core/post-terms' === $anchor_block && 
			'after' === $position && 
			'twentytwentyfour/post-meta' === $context['slug']
		) {
			$hooked_blocks[] = 'ockham/like-button';
		}
	}

	return $hooked_blocks;
}
```

The list of proposed changes:
- Stylistic: code comments end with full stop :sweat_smile:
- Stylistic: there were two spaces before “after the Navigation block`.
- It’s going to be better to check if an instance of $context is WP_Block_Template. This way, we ensure that all fields used later are defined.
- With patterns, we don’t have the luxury of well-defined API, so we must operate cautiously. The only mandatory fields for registered patterns are `title` and `content`, so that’s why we always need to use `isset` or similar constructs to ensure the value is defined. In general, we should account for future changes where a different array could get passed as `$context`.

**Comment by bph** [comment]
I added updated the code examples. Thank you, @gziolo

**Comment by bph** [comment]
Published: [Introducing Block Hooks for dynamic blocks](https://make.wordpress.org/core/2023/10/15/__trashed-3/)

**Comment by ndiego** [comment]
Thanks everyone. I see this has been published. Team effort 💪

**Comment by abhansnuk** [comment]
Published link https://make.wordpress.org/core/2023/10/15/introducing-block-hooks-for-dynamic-blocks/  
Was added to Field Guide.
