### ISSUE TITLE
Miscellaneous Editor Changes Dev Note for 6.4

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1146]
This needs to combine both Miscellaneous Dev Notes in general and those under Gutenberg. 
Headings and sections need to be added to this Dev Note in the CMS to make it clearer for the reader.

For info, the Gutenberg tracking issue https://github.com/WordPress/gutenberg/issues/54998

**Comment by abhansnuk** [comment]
These are the PRs identified in the Gutenberg repo which need to be on the Miscellaneous Dev Note post for 6.4.

https://github.com/WordPress/gutenberg/pull/54310 @ellatrix

 https://github.com/WordPress/gutenberg/pull/54242 @scruffian

 https://github.com/WordPress/gutenberg/pull/54167 @matiasbenedetto

 https://github.com/WordPress/gutenberg/pull/54161 @matiasbenedetto

**Comment by abhansnuk** [comment]
Post set up in Make/Core CMS. 
Public preview link: https://make.wordpress.org/core/?p=108646&preview=1&_ppp=93ab1c13e2

Before publication to check no previous javascript is still showing in error in code view.
Check 'top' links are correct, they may need updating.

**Comment by bph** [comment]
I should be ready for review now.

**Comment by abhansnuk** [comment]
Reviewing

**Comment by abhansnuk** [comment]
Reviewing 
 miscellaneous editor note:
- First par: “For component updates see to UI components, please see also “ change to “… updates, check the UI components, please also refer to…”
- Background image section, capitalize ‘H’ in GitHub
- Rich text section, delete brackets around the ticket number to be consistent with other references. Same for New Public section. In that one too, add ‘above’ before ‘dev note’ in props line
- brackets around the ticket number also on the last two dev notes 
- 
if time, change refer to WP 6.4 to WordPress 6.4

Thanks so much @bph and all contributors to this useful dev note.

**Comment by abhansnuk** [comment]
@bph could you please check there is a short excerpt, and do please publish when all ready. Thanks for your help coordinating

**Comment by bph** [comment]
Published: [Miscellaneous Editor changes in WordPress 6.4](https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/)

**Comment by abhansnuk** [comment]
@codente the issues with the content links has been resolved by @bph . 
Thanks both.
