### ISSUE TITLE
[DevNote] Add new registerInserterMediaCategory API to make media categories extensible

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1147]
Dev Note for #51542 - standalone.

**Comment by abhansnuk** [comment]
@ntsekouras is working on this in Make/Core CMS. Link shared to preview in ticket has expired. New link needed to draft.

**Comment by ntsekouras** [comment]
Here's the new link: https://make.wordpress.org/core/?p=108427&preview=1&_ppp=aa6e13eab3

**Comment by abhansnuk** [comment]
Thanks @ntsekouras for all the work on this style guide. It will be interesting to developers.

For time, I have started on second reviews and have the following comments.

**First paragraph:** Suggest the paragraph below to replace the first one to help people searching and give context, and to avoid ending on 'from'. 

"From WordPress 6.4, extenders can register their own inserter media categories and provide users with more options from which to choose."

**Third paragraph:** From an accessibility perspective, there have been previous conversations about whether to capitalize **'id'** if not used in code in a post, to assist screen readers and those using translation tools. I can't find a noted decision on this in the documentation style book. 

**Fourth paragraph:** could you please use words to help the reader follow where they are being sent when describing the link as we avoid 'here' as a descriptor as it is difficult for accessibility.

**Fifth paragraph:** 'The example...': there is an extra full stop before the colon. 

Added a props holding line.

Added an excerpt.

Added 6.4 dev notes tag.

Thanks Nik.

**Comment by abhansnuk** [comment]
@ntsekouras the Marcomms team for the release are collating an email to plugin authors. This dev note may be a good one to highlight for inclusion.

**Comment by ntsekouras** [comment]
I made the small updates per the above suggestions. Feel free though to edit whatever you see fit, if they are about some rewording or in general not something technical. If it's something about code or implementation details, I can help of course with whatever needed. Thanks!

**Comment by bph** [comment]
Published: [New `registerInserterMediaCategory` API](https://make.wordpress.org/core/2023/10/16/new-registerinsertermediacategory-api/)
