### ISSUE TITLE
Admin: clarify the "Add New" links for better accessibility

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Documentation-Issue-Tracker#1149]
https://core.trac.wordpress.org/ticket/47125

Focus: ui, accessibility, administration
Keyword: needs-dev-note
Ticket owner: joedolson
Core committer: joedolson

**Comment by abhansnuk** [comment]
Defect(bug) fixed. 
Joe Dolson owner of the ticket.

**Comment by shabnam611** [comment]
Follow up on dev note: @abhansnuk asked owner and reported of the ticket on core trac
Add PR and owner information

**Comment by nalininsbs** [comment]
[Follow-up in 6.4 release-leads](https://wordpress.slack.com/archives/C055Y7FKS7N/p1697472129738369) 

Note: no maintainers for the Admin component.

**Comment by nalininsbs** [comment]
Text: Miscellaneous Dev Note provided by Pascal in latest comment on
 [Trac Ticket #47125](https://core.trac.wordpress.org/ticket/47125).
Action: Jamie asked to add to post.
Marcomms
: not needed for separate pull out for plugin email.

**Comment by abhansnuk** [comment]
@bph i think Jamie did this yesterday. Would you be able to check please. Thanks

**Comment by bph** [comment]
That has been added to https://make.wordpress.org/core/?p=96096&preview=1&_ppp=266a1c5caa
