### ISSUE TITLE
HTML API: Add support for BUTTON element

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1151]
Ticket: https://core.trac.wordpress.org/ticket/58961
Owner: Bernhard Reiter
Labeled 'needs dev note'

This needs go go under HTML API -  option not coming up under 'component' so have created new component label for it.

**Comment by codente** [comment]
Checking on whether a dev note is needed: https://core.trac.wordpress.org/ticket/58961#comment:8

**Comment by codente** [comment]
Per comment, no dev note needed https://core.trac.wordpress.org/ticket/58961#comment:9

But does alert to a new issue that needs one.

**Comment by nalininsbs** [comment]
No dev note needed, added to list at end of Field Guide.

Complete. Label can be changed @zzap, thank you.
