### ISSUE TITLE
Better Login Error&Message Displaying

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1155]
Trac ticket: https://core.trac.wordpress.org/ticket/30685

Owner: sabernhardt

Labeled as 'needs dev note'
Note Joe Dolson's comment on https://core.trac.wordpress.org/ticket/30685#comment:57

**Comment by abhansnuk** [comment]
Response from maintainer Rajin Sharwar that this will be ready on October 15, 2023.
[Slack message](https://wordpress.slack.com/archives/C02RQBWTW/p1697244134228179?thread_ts=1697087149.192159&cid=C02RQBWTW).

**Comment by Rajinsharwar** [comment]
Hi @abhansnuk, here is a draft for the dev note. Requesting peer review and proofreading.
https://make.wordpress.org/core/?p=108803

**Comment by nalininsbs** [comment]
@codente and @nalinisbs we will put this under 'Users' in the Field Guide as it is a sub component of this. It can then list Login and Registration.

**Comment by codente** [comment]
Hi @Rajinsharwar thank you and nice work on this dev note:

I do have a couple suggestions

1. I think a word is missing here

_WordPress 6.4 brings a number of key improvements to the HTML markup of the wp-login.php page to its structure_

at the end there, to _make_ its structure

Or a similar word to make as right now that is not making sense to me. 

2.  In the second paragraph, I think you could remove the period before And here "And <div>" and just join it together without a separate sentence.

3. In the 3rd paragraph, I think you could remove this And

"And, in the case of multiple error messages"

4. Same paragraph, last sentence I'd rewrite it a little differently.

_In the case of multiple errors, bullets have been removed in favor of a small margin between error messages._

5. In the Some other changes section, do we need to do inline code when you mention the br tags and include the opening and closing tag so it looks like this `<br>`?

6. I think you could remove the So from the last line.

**Comment by Rajinsharwar** [comment]
I @codente, just edited the doc with your suggestions. Let me know it it looks good now.

**Comment by codente** [comment]
@Rajinsharwar I think the word make got added in the wrong place.  It should be before the word its and not after.

"WordPress 6.4 brings a number of key improvements to the HTML markup of the wp-login.php page to _make its structure_"

Otherwise, the changes look good from here :)

**Comment by abhansnuk** [comment]
@Rajinsharwar can you please add an excerpt to the dev note. I will add tags once the other the tech edit and changes are done. 

Did any of the other maintainers do a tech peer review please? If so, do you have their WP.org IDs please? Thanks for working on this dev note.

**Comment by Rajinsharwar** [comment]
Ah lol, done @codente. :)

**Comment by Rajinsharwar** [comment]
Hi @abhansnuk, I added an excerpt. For now, none other than @codente did the review. I am not really sure of your WP.org ID @codente 😅

**Comment by abhansnuk** [comment]
Hello @Rajinsharwar Thanks for the update. 

Could you reduce the size of the excerpt please as it is too long to be effective in search and embeds.

Could you make the images of before and after 6.4 the same height please assuming this is possible with the content wanting to be visible? If not, can they both start at the same top level? 

I will share it for further feedback in core once you have finished the current editing you are doing, and do the second docs review too.

Thanks.

**Comment by Rajinsharwar** [comment]
Hi @abhansnuk, just re-updated the doc. Can you take a look now?

**Comment by abhansnuk** [comment]
Shared in core for another core review in the next few hours.

**Comment by abhansnuk** [comment]
@Rajinsharwar are you able to deal with these please? 

Thanks @sabernhardt for the review.

**Comment by sabernhardt** [comment]
The sentence about multiple error messages mentions the styling, but it says nothing about the new list markup. Maybe just add that each message is a list item:
> In the case of multiple errors, each message is a list item, and bullets have been removed in favor of a small margin between error messages.

Minor formatting recommendations:
- The `wp-login.php` filename would be [wrapped in inline code](https://make.wordpress.org/docs/style-guide/formatting/filenames/#referring-to-filenames) instead of italicizing it.
- The quoted text for each link (“Log in“, “Register” and “Lost your password?”) should not need italicizing either because the quotation marks already set the text apart.

**Comment by Rajinsharwar** [comment]
Hi @sabernhardt @abhansnuk, just updated the doc. Can you take a look now?

**Comment by sabernhardt** [comment]
1. The heading levels within the post content need to be raised by one. Right now, it skips from level one (the title) to level three. The two section headings should be H2.
2. The second image caption text does not have a period.
3. We probably should add another sentence to say plainly: "CSS selectors such as `p.message` will not apply styles to the informational messages." It could fit after mentioning "classes on the div (`<div>`) instead of the paragraph (`<p>`).").

**Comment by Rajinsharwar** [comment]
Just made the changes again @sabernhardt.

**Comment by codente** [comment]
@Rajinsharwar @sabernhardt 

With this change:

CSS selectors such as p.message will not apply styles to the **informational** messages.

Stephen mentioned informational specifically but in the post it says notice messages.  Does that distinction matter or is it fine as is?  

Stephen's comment makes me think it only applies to certain (informational) notices while the way it is worded now seems like it may apply to all notices?

**Comment by sabernhardt** [comment]
I see it's already updated to "notice": "will not apply styles to the notice messages." **Consistency** should be better than saying "informational" there. 

Technically, both errors and informational messages have the `notice` class. Then the `notice-info` and `notice-error` classes differentiate those two types.

**Comment by sabernhardt** [comment]
And it's published 😄
https://make.wordpress.org/core/2023/10/17/html-markup-improvements-to-the-login-and-registration-page/

**Comment by nalininsbs** [comment]
Is there anything on this for updating the Field Guide?

**Comment by nalininsbs** [comment]
Noting discussion in release docs area - add to other developer updates in the Field Guide.

**Comment by nalininsbs** [comment]
@zzap can you change the label to complete please. We are unable to change this. Thank you.
