### ISSUE TITLE
Delay loading comment-reply script with async loading strategy

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Documentation-Issue-Tracker#1159]
Trac Ticket https://core.trac.wordpress.org/ticket/58870

Comments component
Focuses: javascript, performance

**Comment by nalininsbs** [comment]
Follow-up with ticket reporter and owner @westonruter on comment. 
Checking if there will be a link from any text in the Field Guide to a dev note on this change. Note 'needs dev note' has not been labelled. 
Checking for any draft wording for Field Guide.
Link to tracking shared.

**Comment by abhansnuk** [comment]
Link to the [comment on Trac](https://core.trac.wordpress.org/ticket/58870#comment:9)

**Comment by westonruter** [comment]
I haven't written the Dev Note yet, but it  is top of my list for Monday (October 16). cf. https://github.com/WordPress/performance/issues/840#issuecomment-1763712836

**Comment by westonruter** [comment]
Ready for review: https://docs.google.com/document/d/1mOzcwLbCaQNbWOMGFj4H4MJPtIMz7Fs90uBwOQZbDS8/edit?usp=sharing

**Comment by westonruter** [comment]
@abhansnuk Thank you. I've applied your feedback and I've added an excerpt to the top.

> On another note, given that the script loading strategies result in breaking a prior method for adding `async` or `defer` to scripts using the `clean_url` filter, which will affect plugins, could this be in the email to plugins that is being collated by Marcomms?

I'm not sure this is necessary. The back-compat breakage is largely graceful.

**Comment by westonruter** [comment]
Here is the public preview link: https://make.wordpress.org/core/?p=108934&preview=1&_ppp=f8ab32089f

**Comment by westonruter** [comment]
Performance review is complete. I can publish now if you like.

**Comment by abhansnuk** [comment]
Both reviews are done. Just checking tags.

**Comment by nalininsbs** [comment]
Published:
[Script loading changes in 6.4](https://make.wordpress.org/core/2023/10/17/script-loading-changes-in-wordpress-6-4/)
