### ISSUE TITLE
[DevNote] Tests: update for PHPUnit Polyfills 1.1.0

### ISSUE THREAD

**Issue by shabnam611** [WordPress/Documentation-Issue-Tracker#1162]
Trac ticket: https://core.trac.wordpress.org/ticket/59150 

Keyword: needs-dev-note
Ticket owner: Sergey Biryukov
Core committer: jrf

**Comment by codente** [comment]
Comment from jrf says they don't believe this needs a separate dev note but should be included in the email to plugin developers

https://core.trac.wordpress.org/ticket/59150#comment:9

**Comment by nalininsbs** [comment]
Reply from @ jrf 
"...There is no draft dev-note and to be honest, I'm not sure this needs a separate dev-note. In my opinion, it should be mentioned in the "Miscellaneous developer facing changes" dev-note and that should probably be enough."


Q. From reading the ticket, I understand this could have implications for plugins/ Themes running integration tests with WordPress, and in some cases a manual update will be necessary. Is this something that Marcomms need to include in the email to plugin developers which is currently being drafted?

Reply: I think it would be a good change to mention in the mail to plugin devs, but it shouldn't need more than just a simple mention "PHPUnit Polyfills 1.1.0 is required for running integration tests with WP 6.4".
I mean if people don't know the Polyfills, it isn't relevant for them as they won't have tests which they run in the context of WP and if they do know the Polyfills, the above suggested mention will be enough for them to know what to do.

**Comment by nalininsbs** [comment]
Thank you @jrfnl for your speedy reply and assistance . The text suggested for the plugins email has also been added to Miscellaneous Dev Notes for WordPress 6.4 on the P2. Marcomms have been alerted to your reply too for the plugins email.

**Comment by nalininsbs** [comment]
@jrfnl the link to the Miscellaneous dev note incorporating this change. Thank you. https://make.wordpress.org/core/?p=96096&preview=1&_ppp=266a1c5caa
