### ISSUE TITLE
Font Face: Server-side @font-face styles generator and printer

### ISSUE THREAD

**Issue by shabnam611** [WordPress/Documentation-Issue-Tracker#1164]
Trac ticket: https://core.trac.wordpress.org/ticket/59165

Keyword: needs-dev-note
Ticket owner: hellofromTonya
Core committer: hellofromTonya

**Comment by codente** [comment]
Requested dev note here and asked if it should be included in email to plugin devs
https://core.trac.wordpress.org/ticket/59165#comment:33

**Comment by nalininsbs** [comment]
Oct 16, [Link to Slack confirmation of dev note writer ](https://wordpress.slack.com/archives/C02RQBWTW/p1697475320819889?thread_ts=1697444235.029219&cid=C02RQBWTW)- Tonya

**Comment by nalininsbs** [comment]
Same as for other ticket in General. Dev note with @hellofromtonya. @abhansnuk to check if leave reference as coming in the FG or leave off completely.

**Comment by hellofromtonya** [comment]
I'm leaning towards not publishing a dev note for this until 6.5, when the Font Library ships. 

This dev note is not a blocker to publishing the Field Guide.

Thanks :)

**Comment by hellofromtonya** [comment]
Update: I removed the `needs-dev-note` [keyword for its ticket](https://core.trac.wordpress.org/ticket/59165#comment:35). Thus this tracking issue can be closed.

**Comment by nalininsbs** [comment]
Reference and ticket from Field Guide removed. Note for 6.5

**Comment by abhansnuk** [comment]
The details have been copied to the tracker for 6.5 and are located at this issue https://github.com/WordPress/Documentation-Issue-Tracker/issues/1386 for when you're ready @hellofromtonya .

Closing this ticket. Thanks Tonya, @nalininsbs and @shabnam611 .
