### ISSUE TITLE
Twenty Twenty-Two support page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#117]
Similar to previous default themes, we need a TT2 support page: https://wordpress.org/support/article/twenty-twenty-one/ Thank you to [folks who flagged this in slack](https://wordpress.slack.com/archives/C02RP4VMP/p1642633404049200)! I managed to miss this one.

I've kicked off a draft here: https://docs.google.com/document/d/1NnInppt4lGVHCjgdVvrF18AgoPVKWteUvJkmvrEENiU/edit#

Since this is a block theme, the options are fairly endless for customization so taking the approach of talking about those features/referencing other support articles instead of going through every detail. This includes for areas like block patterns -- unlike TT1, let's not list all 64 block patterns out. 

Working on this with Kjell and Jeff.

**Comment by annezazu** [comment]
https://wordpress.org/support/article/twenty-twenty-two/

Closing for now. Will loop back later once 5.9 is out and the TT2 is in the directory to include links to 5.9 and the support forums for the theme.

**Comment by annezazu** [comment]
Updated :)

**Comment by zzap** [comment]
Thank you @annezazu :heart:
