### ISSUE TITLE
Force split queries in WP_Query in object caching is enabled

### ISSUE THREAD

**Issue by shabnam611** [WordPress/Documentation-Issue-Tracker#1176]
Trac ticket: https://core.trac.wordpress.org/ticket/57296

Keyword: needs-dev-note
Ticket owner: spacedmonkey
Core committer: spacedmonkey

**Comment by abhansnuk** [comment]
Note: this has been checked if it still needs a dev note. Confirmed.

Draft on [google doc]([url](https://docs.google.com/document/d/1dtrWzGHlzpcfaQG4wSHYtHkkzAbUScQiXeL968UKBTc/edit?usp=sharing)) from Jonny

**Comment by nalininsbs** [comment]
As certain fields are not available to the docs release group, an additional note providing an overview of performance tickets in the run up to the Field Guide deadline, can be found on this docs sheet: [Google sheet](https://docs.google.com/spreadsheets/d/133JpBHy1ATh3m8aUxRUcurpSFyvb6XHYT2ayXrK6740/edit?pli=1#gid=0) to better understand status on the performance labelled tickets. Note performance team is wrangling those tickets for identification, first draft and performance first review.
