### ISSUE TITLE
Editor Components updates in WordPress 6.4

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1179]

**Comment by abhansnuk** [comment]
For info to assist the cohort.
- A first review is being done by @bph and others over in Gutenberg.

- I've done a second review, and added comments on the Gutenberg GitHub issue where Editor dev notes are being wrangled.  

Also raised two questions for all dev notes. You can see the questions on the [Gutenberg GitHub ticket](https://github.com/WordPress/gutenberg/issues/54998#issuecomment-1762062447).

**Comment by bph** [comment]
Thanks for the review notes @abhansnuk I made the necessary changes and published the dev note. If there is further nitpicking to be done we can do it later this week. 🧐
https://make.wordpress.org/core/2023/10/16/editor-components-updates-in-wordpress-6-4/
