### ISSUE TITLE
Eliminate manual construction of script tags in WP_Scripts and of inline scripts on frontend/login screen

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1187]
Trac ticket: https://core.trac.wordpress.org/ticket/58664

Reported and owned by: westonruter

**Comment by codente** [comment]
Requested dev note:
https://core.trac.wordpress.org/ticket/58664#comment:36

**Comment by westonruter** [comment]
Yes, here is the public preview: https://make.wordpress.org/core/?p=108934&preview=1&_ppp=f8ab32089f

**Comment by westonruter** [comment]
The same dev note is also for https://github.com/WordPress/Documentation-Issue-Tracker/issues/1159

**Comment by nalininsbs** [comment]
Published link https://make.wordpress.org/core/2023/10/17/script-loading-changes-in-wordpress-6-4/
