### ISSUE TITLE
[HelpHub] Spacer

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#119]
Article: https://wordpress.org/support/article/spacer-block/

## Updating for 5.7
- [ ] Show the Spacer block’s background on hover - [28129](https://github.com/WordPress/gutenberg/pull/28129)

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/taPw9yzX/70-spacer

**Comment by atachibana** [comment]
- [#28129](https://github.com/WordPress/gutenberg/pull/28129) improved user experience during block handling. It means there are no additional feature, so, not required to enhance it into user documentation.
- Updated screenshots to WordPress 5.9
<img width="191" alt="spacer-block-toolbar-all" src="https://user-images.githubusercontent.com/8876600/159282002-2c078011-f075-4676-9c1c-303145867468.png">
<img width="191" alt="spacer-block-toolbar-transform" src="https://user-images.githubusercontent.com/8876600/159282027-550f3db3-14c4-4906-a9cd-827a138e211d.png">
<img width="191" alt="spacer-block-toolbar-drag" src="https://user-images.githubusercontent.com/8876600/159282064-9d00260d-e2f1-4b9a-a7d3-afdd8f3b603f.png">
<img width="191" alt="spacer-block-toolbar-moving" src="https://user-images.githubusercontent.com/8876600/159282080-454d3dc6-d7f5-4404-ba74-638e425a1093.png">
<img width="282" alt="spacer-block-settings" src="https://user-images.githubusercontent.com/8876600/159282097-ad22d99c-d559-48dc-8aa8-abf089f71f26.png">
<img width="285" alt="spacer-height" src="https://user-images.githubusercontent.com/8876600/159282126-7644163b-e8f8-4564-aafe-162fc014b93f.png">

**Comment by atachibana** [comment]
@zzap 
Updated all screenshots and modified description for WordPress 5.9.

**Comment by zzap** [comment]
Thank you, great work :heart:
