### ISSUE TITLE
 Translator Handbook » Tools: "String locator (plugin)" links to "Force Update Translations (plugin)"

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#1198]
## Issue Description

On the [provided link](https://make.wordpress.org/polyglots/handbook/translating/glotpress-translate-wordpress-org/tools/#third-party-services-and-apps-1), the "String Locator" plugin is listed among translation tools. However, its link mistakenly directs to the previously mentioned "Force Update Translations" plugin page.

## URL of the Page with the Issue

https://make.wordpress.org/polyglots/handbook/translating/glotpress-translate-wordpress-org/tools/#third-party-services-and-apps-1

## Section of Page with the issue

String Locator (plugin)

## Why is this a problem?

Currently, the String Locator's link points to https://wordpress.org/plugins/force-update-translations/. It should instead point to https://wordpress.org/plugins/string-locator/.

## Suggested Fix

The URL to the plugin page should be corrected.

**Comment by zzap** [comment]
Hello @CalolanC , unfortunately, the Docs team is not managing Polyglot's handbook. It is best to report this in their [slack channel](https://wordpress.slack.com/archives/C059LE39BLG)
