### ISSUE TITLE
[HelpHub] [6.4] Site Editor > Patterns

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1204]
Article: https://wordpress.org/documentation/article/site-editor-patterns/

## Update for 6.4
- [x] Patterns: distinguish between theme patterns and template parts in category list. [52382](https://github.com/WordPress/gutenberg/pull/52382)
- [x] Rename Library to Patterns [52102](https://github.com/WordPress/gutenberg/pull/52102)
- [x] Update icons in the creation menu [52108](https://github.com/WordPress/gutenberg/pull/52108)
- [x] Add lock icon for theme patterns [51990](https://github.com/WordPress/gutenberg/pull/51990)
- [x] Reinstate manage all template parts page [51961](https://github.com/WordPress/gutenberg/pull/51961)
- [x] Add sync status to pattern details screen [51954](https://github.com/WordPress/gutenberg/pull/51954)
- [ ] Update pattern creation modal in library [51946](https://github.com/WordPress/gutenberg/pull/51946)
- [x] Reinstate manage all template parts page. [51961](https://github.com/WordPress/gutenberg/pull/51961)
- [x] Add renaming, duplication, and deletion options [52270](https://github.com/WordPress/gutenberg/pull/52270)
- [x] remove "apply globally" option from block settings [52160](https://github.com/WordPress/gutenberg/pull/52160)
- [x] Pattern focus mode DocumentActions should use the pattern icon [52031](https://github.com/WordPress/gutenberg/pull/52031)
- [x] Remove ability for user to toggle sync status after pattern creation [51998](https://github.com/WordPress/gutenberg/pull/51998)
- [x] Update template part icons in the library mosaic  [51963](https://github.com/WordPress/gutenberg/pull/51963)
- [x] Update custom patterns label to 'My patterns'  [51949](https://github.com/WordPress/gutenberg/pull/51949)
- [x] Reinstate my patterns category in site editor [54726](https://github.com/WordPress/gutenberg/pull/54726)
- [ ] Require a title in the creation modal [54717](https://github.com/WordPress/gutenberg/pull/54717)
- [ ] Add editing of pattern categories to site editor [54640](https://github.com/WordPress/gutenberg/pull/54640)
- [x] Update empty template part label [53842](https://github.com/WordPress/gutenberg/pull/53842)
- [ ] Add user categories to site editor sidebar navigation screen [53837](https://github.com/WordPress/gutenberg/pull/53837)
- [ ] Add categories to user patterns, and allow filtering by these in site and post editor [53835](https://github.com/WordPress/gutenberg/pull/53835)
- [ ] Enable focus mode editing [52427](https://github.com/WordPress/gutenberg/pull/52427)
- [x] Open detail view when duplicating pattern [53214](https://github.com/WordPress/gutenberg/pull/53214)
- [x] Add hint to show template part move [52395](https://github.com/WordPress/gutenberg/pull/52395)
- [x] Display all custom template part areas in sidebar nav [52355](https://github.com/WordPress/gutenberg/pull/52355)
- [x] Update section heading levels [52273](https://github.com/WordPress/gutenberg/pull/52273)
- [x] Sticky header and pagination on Patterns page [52663](https://github.com/WordPress/gutenberg/pull/52663)
- [x] Clarify the "Entity" message of the snackbar [54333](https://github.com/WordPress/gutenberg/pull/54333)
- [x] Switch to three column layout on huge screens [52927](https://github.com/WordPress/gutenberg/pull/52927)
- [x] Swap pattern creation options [52726](https://github.com/WordPress/gutenberg/pull/52726)
- [ ] Unify the delete button style in the dropdown menu with red  [52597](https://github.com/WordPress/gutenberg/pull/52597)
- [x] Remove "Theme patterns" heading in Pattern library [52570](https://github.com/WordPress/gutenberg/pull/52570)
- [x] Update locked pattern tooltips  [52497](https://github.com/WordPress/gutenberg/pull/52497)
- [x] Template Parts: Add further details to template part panel [52476](https://github.com/WordPress/gutenberg/pull/52476)
- [x] Update pattern library copy [52340](https://github.com/WordPress/gutenberg/pull/52340)
- [x] use the template actions component for template parts patterns [54173](https://github.com/WordPress/gutenberg/pull/54173)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by atachibana** [comment]
@femkreations
I have assigned myself to this issue.
I first check the tasks listed, those that have already been written in the page, and those that do not need to be written such as internal logic change.

**Comment by atachibana** [comment]
As a result of my triage, the following tasks are skipped, and already checked as Done.

These PRs are already reflected in the current screenshots and videos.

- Patterns: distinguish between theme patterns and template parts in category list. 52382
- Rename Library to Patterns 52102
- Update icons in the creation menu 52108
- Add lock icon for theme patterns 51990
- Reinstate manage all template parts page 51961
- Add sync status to pattern details screen 51954
-  Reinstate manage all template parts page. 51961
-  Add renaming, duplication, and deletion options 52270
- Pattern focus mode DocumentActions should use the pattern icon 52031
- Update template part icons in the library mosaic 51963
- Update custom patterns label to 'My patterns' 51949
- Reinstate my patterns category in site editor 54726
- Add hint to show template part move 52395
- Display all custom template part areas in sidebar nav 52355
- Sticky header and pagination on Patterns page 52663
- Swap pattern creation options 52726
- Remove "Theme patterns" heading in Pattern library 52570
- Template Parts: Add further details to template part panel 52476
- use the template actions component for template parts patterns 54173

These PRs are not relating to Site Editor Patterns.

- remove "apply globally" option from block settings 52160
- Remove ability for user to toggle sync status after pattern creation 51998

These PRs are internal logic, or not directly related to the page.

- Update empty template part label 53842
- Update section heading levels 52273
- Clarify the "Entity" message of the snackbar 54333

These PRs are improvement of User Experience.

- Open detail view when duplicating pattern 53214
- Switch to three column layout on huge screens 52927
- Update locked pattern tooltips 52497
- Update pattern library copy 52340

**Comment by atachibana** [comment]
I believe all remaining tasks will be covered by the following modifications. Please review them.

## My Patterns

... (cut) ...

If you click on the **Actions** (ellipsis) button next to each pattern, you will see options to rename, duplicate, export as JSON or delete that pattern.

![site-editor-patterns-6 4-my-patterns-actions](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/4e1ac821-ea7b-4937-9f2a-7bae3c9f454a)

... (cut) ...

## Create new patterns

There is a **create patterns (+)** icon next to the Patterns sidebar title you can click on to create new patterns. If you click on it, you will see three options: **Create pattern**, **Create template part**, and **Import pattern from JSON**.

![site-editor-patterns-6 4-create-patterns](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/6bc75deb-e92e-46b5-ad38-e1369cff9095)

### Create pattern

Specify the pattern name that describes what it’s for, and optionally assign the pattern to a category. Also, toggle the Synched option if you want to create [Synced pattern](https://wordpress.org/documentation/article/reusable-blocks/).

![site-editor-patterns-6 4-create-pattern](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/b2e92da4-a50c-4985-afe4-b6526e54a629)

### Create template part

Specify the template part name that describes what it’s for, and select an area of your site for your new template part: General, Header, or Footer.

![site-editor-patterns-6 4-create-template part](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/d65df4a7-eec0-4817-ada8-e75e8e724d30)

### Import pattern from JSON

Select the exported JSON file. To export a pattern, select Export as JSON from patterns Actions (ellipsis) button.

**Comment by nalininsbs** [comment]
Highlighted in Docs triage meeting November 14, 2023 for reviews needed to move this high priority item forward.

**Comment by abhansnuk** [comment]
First review completed. Thanks for all your time and work and reviewing the task itself @atachibana 

https://github.com/WordPress/Documentation-Issue-Tracker/issues/1204#issuecomment-1807036951
On this text, can we link 'eliipsis' to this definition https://make.wordpress.org/docs/style-guide/punctuation/ellipses/ ?

**Comment by atachibana** [comment]
@abhansnuk 
The "ellipsis" in the comment refers to the shape of the icon, and does not imply the omission mentioned in the style guide.
However, thinking about it, it is indeed ambiguous, so I would like to explicitly change the "ellipsis" to "three dots icon". Thanks.

**Comment by Leonardus-Nugraha** [comment]
2nd review done, added alt text to some images and changed the subheadings to sentence-case
