### ISSUE TITLE
[HelpHub] [6.4] Page List Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1206]
Article:  https://wordpress.org/documentation/article/page-list-block/

## Updates for 6.4
- [x] Update parent labels in page attributes panel and page list block. [54403](https://github.com/WordPress/gutenberg/pull/54403)
- [ ] Change modal text [52116](https://github.com/WordPress/gutenberg/pull/52116)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by anandau** [comment]
Hi @femkreations 

I am interested in working on it. Please assign me.

**Comment by anandau** [comment]
Updated the article. 

- Changed one screenshot. 
- Updated content to reflect the changed label 
- Updated changelog

**Comment by anandau** [comment]
@femkreations, it is ready for review. There was just a couple of changes, so I have updated the doc already.

**Comment by abhansnuk** [comment]
@anandau can you share the public preview of the post on this issue please. Thanks for getting this ready.

**Comment by anandau** [comment]
As the changes were small, so I have updated the post already. 
https://wordpress.org/documentation/article/page-list-block/

**Comment by Leonardus-Nugraha** [comment]
2nd review done, added alt text to a couple of images
Thanks @anandau !
