### ISSUE TITLE
[HelpHub] [6.4] Quote Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1207]
Article:  https://wordpress.org/documentation/article/quote-block/

## Updates for 6.4
- [x] Add transform to paragraph. [51809](https://github.com/WordPress/gutenberg/pull/51809)

## Reference
- [x] [Pls refer for the previous versions tasks here](https://github.com/WordPress/Documentation-Issue-Tracker/issues/956)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1nhpoc5eiR3I2Me8mji4OeYUitGz3kPC4QJt2Xx8HejI/edit

first review done

**Comment by Leonardus-Nugraha** [comment]
Article reviewed and updated both for 6.3 and 6.4! Thanks @ldhrmn @emmasophieyoung!

**Comment by nalininsbs** [comment]
To add to the props spreadsheet for HelpHub.
