### ISSUE TITLE
Special Strings in the "new_admin_email_content" filter documentation are incorrect

### ISSUE THREAD

**Issue by shawnhooper** [WordPress/Documentation-Issue-Tracker#1208]
## Issue Description

Special Strings in the "new_admin_email_content" filter documentation are incorrect.  They are missing the leading `###` characters. 

## URL of the Page with the Issue

https://developer.wordpress.org/reference/hooks/new_admin_email_content/

## Section of Page with the issue

Description 

## Why is this a problem?

Using the names specified in the documentation will result in the strings not being properly replaced when the new admin notification email is sent. 

## Suggested Fix

- `USERNAME###` should be changed to `###USERNAME###`
- `ADMIN_URL###` should be changed to `###ADMIN_URL###`
- `EMAIL###` should be changed to `###EMAIL###`
- `SITENAME###` should be changed to `###SITENAME###`
- `SITEURL###` should be changed to `###SITEURL###`

**Comment by dd32** [comment]
Fixed https://developer.wordpress.org/reference/hooks/new_admin_email_content/
