### ISSUE TITLE
[HelpHub] How to add a new block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#121]
Article: https://wordpress.org/support/article/adding-a-new-block/

## Updating for 5.7
- [x] Allow dragging blocks from the inserter into the canvas - [27669](https://github.com/WordPress/gutenberg/pull/27669)
- [ ] Make empty paragraphs take up the same space on the frontend, as in the editor - [27995](https://github.com/WordPress/gutenberg/pull/27995)

## General
- [x] update title to 'Adding and moving blocks'
- [x] reinstate the Add block icon at the bottom of a block if Gutenberg really does intend to deliver this insertion method. See https://github.com/WordPress/gutenberg/issues/22801
- [x] Need to add a section about the Add Block icon appearing within blocks - such as Group - which support block nesting.
- [x] Add a section and link about adding blocks through the Block Directory
- [x] make sure all screenshots are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/u9ffOKj0/13-how-to-add-a-new-block

**Comment by hannaw93** [comment]
I can pick up this issue :)

**Comment by femkreations** [comment]
Updated the page https://wordpress.org/support/article/adding-a-new-block/
