### ISSUE TITLE
[HelpHub] [6.4] Link Control Page

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1214]
Article:  https://wordpress.org/documentation/article/link-editing/

## Updates for 6.4
- [x] persist advanced settings toggle state to preferences if available. [52799](https://github.com/WordPress/gutenberg/pull/52799)
- [x]  Add Opens in new Tab control into Link Preview. [53566](https://github.com/WordPress/gutenberg/pull/53566)
- [x]  Adds 'nofollow' setting to inline links (rich text only). [53945](https://github.com/WordPress/gutenberg/pull/53945)
- [x]  Use gray color on link control advanced toggle. [54545](https://github.com/WordPress/gutenberg/pull/54545)

## Reference
- [ ] [Pls refer for the previous versions tasks here](https://github.com/WordPress/Documentation-Issue-Tracker/issues/970)

## General
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Good first issues
If you are looking for simpler tasks, take a look at related good first issues:

- [ ] Check ALT attributes: #1345  
- [ ] Check headings: #1346         
- [ ] Update screenshots: #1347       
- [ ] Update videos: #1348

**Comment by atachibana** [comment]
I would triage the PRs first.
These PRs are about improving the user experience and have nothing to do with HelpHub.

 - persist advanced settings toggle state to preferences if available. 52799
- Use gray color on link control advanced toggle. 54545

**Comment by atachibana** [comment]
For these PRs,

- Add Opens in new Tab control into Link Preview. 53566
- Adds 'nofollow' setting to inline links (rich text only). 53945

already  images and movies are assigned to 
https://github.com/WordPress/Documentation-Issue-Tracker/issues/1347
https://github.com/WordPress/Documentation-Issue-Tracker/issues/1348

This issue will modify texts in the Open location section with above updated images.

## Edit a link

To change a link's text or URL
1. Click on the link
2. Select the pencil icon
3. Modify the Text or Link
4. Click Save.

There are several options under the Advanced section.

#### Open in new tab
Turn on to open the new page in the new tab. Turn off to open the new page in the same tab.

#### Mark as nofollow
Turn on to tell search engines to ignore this link relationship. For more detail about nofollow, refer [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#nofollow).

## Remove a link

To remove a link
1. Click on the link
2. Select Unlink from toolbar or dialog

**Comment by atachibana** [comment]
I confirmed the everything were already enhanced in the page.
