### ISSUE TITLE
[HelpHub] [6.4] Image Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1217]
Article:  https://wordpress.org/documentation/article/image-block/

## Updates for 6.4
- [x] Image block: UI updates for the image lightbox (redo). [54509](https://github.com/WordPress/gutenberg/pull/54509)
- [x] Add aspect ratio to image placeholder. [54216](https://github.com/WordPress/gutenberg/pull/54216)
- [ ] ~Add aspect ratio support to lightbox. [52765](https://github.com/WordPress/gutenberg/pull/52765)~
- [x] Image block keep image size on replacing image. [49982](https://github.com/WordPress/gutenberg/pull/49982)
- [x] Add media previews to list view for gallery and image blocks [53381](https://github.com/WordPress/gutenberg/pull/53381)

## Reference
- [x] [Pls refer for the previous versions tasks here](https://github.com/WordPress/Documentation-Issue-Tracker/issues/278)

## General
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Good first issues
If you are looking for simpler tasks, take a look at related good first issues:

- [x] Check ALT attributes: #1337  
- [x] Check headings: #1338         
- [x] Update screenshots: #1339       
- [x] Update videos: #1340

**Comment by planningwrite** [comment]
The Image block allows you to insert an image onto your page or post. Images are visuals that make your content attractive. 

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/72626743/540323fb-7e25-44c8-baa3-acae7546c63b)

**Comment by planningwrite** [comment]
### How to Add the Image Block


The Image Block block can be added to a page by clicking on the Block Inserter (+) icon button.

**Comment by zzap** [comment]
Updates for 6.4 are completed. 

The lightbox seems to be dependent on theme.json settings, and the default theme doesn't have it, so we're not including it in the documentation to avoid frustrating users.

Thank you to everyone who contributed to this issue :heart: :cookie:
