### ISSUE TITLE
Theme unit test 'last updated' date fix

### ISSUE THREAD

**Issue by arafatjamil01** [WordPress/Documentation-Issue-Tracker#1239]
## Issue Description

The unit test data has been updated on 28/April/2023. Yet the date in the handbook and codex says, the last update date was - 30/January/2023, this needs to be fixed.

[Github link that proves the date](https://github.com/WordPress/theme-test-data)

## URL of the Page with the Issue

The issue is under the title - Test Environment Setup in number 1.
[WoredPress theme handbook unit test data page](https://make.wordpress.org/themes/handbook/review/theme-unit-test/)

The issue is under the title - Test Environment Setup min number 1
[Codex unit test data page](https://codex.wordpress.org/Theme_Unit_Test)

## Section of Page with the issue
Section title - Test Environment Setup

## Why is this a problem?
We often have older XML downloaded already, especially for someone who is working with themes every now and then. As long as the date on the documentation is not changed, developers are more likely to use their old unit test data file. This will cause a problem, because the newer posts will not appear in the unit testing data.

## Suggested Fix
Change the latest updated date to 28/April/2023 from 30/January/2023 on both pages.

**Comment by zzap** [comment]
Hello, thank you very much for the report, but that handbook belongs to the Themes team and should be reported in [their slack channel](https://wordpress.slack.com/archives/C02RP4Y3K). The Docs team does not maintain their handbook.
