### ISSUE TITLE
[HelpHub] Paragraph Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#124]
Article: https://wordpress.org/support/article/paragraph-block/

## Updating for 5.7
- [ ] Add Keyboard Input inline format - [26801](https://github.com/WordPress/gutenberg/pull/26801)

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] Video updates
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/mWOy1uu2/1-paragraph-block

**Comment by atachibana** [comment]
This issue will be fixed with #279.
