### ISSUE TITLE
[HelpHub] [6.4] [screenshots] Spacer block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1241]
Article:  https://wordpress.org/documentation/article/spacer-block/

## Task

Make sure all screenshots are relevant to the latest version. 

## Directions
- Compare existing screenshots (on the article link) to the actual interface in the latest WordPress version.
- Ensure you have the appropriate WordPress version and that new screenshots cover the same page area as the existing one.
- If something is different, make a new screenshot.
- Upload new screenshots to the comment on this issue.
- Request review by stating in the comment that the issue is ready for review.

## Resources
1. You can set WordPress install in one click by visiting https://playground.wordpress.net/ use InstaWP sandbox https://app.instawp.io/onboard
2. Watch the video on creating screenshots for the latest WordPress versions - [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

## Automation
- If you want, you can assign yourself to the issue and change the label for review by posting specific keywords in a comment. Read about our repo's automatisation [here](https://make.wordpress.org/docs/handbook/github-repository-and-projects/documentation-issue-tracker/#label-issues).

Thank you for contributing, have a cookie :cookie:

**Comment by nith53** [comment]
Attaching all the updated screenshots below.

**Comment by nith53** [comment]
spacer settings image needs to be updated as the latest version includes %


![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/141323754/f9449550-2f4b-46e9-a938-aac2d8039e79)

**Comment by nith53** [comment]
Fixed size flex control for Spacer block - attaching new image below


![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/141323754/485d76a6-02e9-441f-9d0d-26f28c4970c9)

**Comment by nith53** [comment]
Fill size flex control for Spacer block - attaching new image below


![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/141323754/f3ef67ed-d8e9-471c-9612-c05a367fb6cc)

**Comment by atachibana** [comment]
@nith53
Review completed. Thank you for updating screenshots.

When you replace the spacer settings image, please also modify the below text by adding "%".
> You can also change the unit by clicking on PX to display a dropdown with the other supported units- PX, EM, REM, VW, and VH.

**Comment by Leonardus-Nugraha** [comment]
Thank you @nith53 for contributing and @atachibana for reviewing
I've updated the content with the screenshots, also add the "%"  into the text.
