### ISSUE TITLE
[HelpHub] File

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#125]
Article: https://wordpress.org/support/article/file-block/

## Updating for 5.7
- [x] Move the URL button to the Block toolbar - [26602](https://github.com/WordPress/gutenberg/pull/26602)
- [x] Remove default value for allowedTypes property - [24318](https://github.com/WordPress/gutenberg/pull/24318)

## General
- [x] make sure all screenshots are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/OtwVzyoq/62-file

**Comment by nem-c** [comment]
@zzap I might give this one a run if you don't mind

**Comment by nem-c** [comment]
Changelog updates:

<img width="497" alt="Screenshot 2022-04-10 at 14 39 29" src="https://user-images.githubusercontent.com/8862106/162616275-ab339cd9-ece4-49c9-9c90-789170540b2a.png">

- Updated 2022-04-10
  - Updated new block toolbar settings
- Updated 2020-09-19
  - Updated new block toolbar features
  - Updated new block settings features
  - Updated 5.5 screenshots
- Updated 2020-06-18
  - Added ‘Link back to blocks’ to the top of the page
  - Converted the ‘Advance’ reusable block to regular block
  - Added the ‘Changelog’
- Created 2019-03-07

**Comment by zzap** [comment]
This one got me thinking for a while :joy: I thought that was a timestamp for the screenshot 

Can you rename of the file to be just `file` or `Uploaded file`?

**Comment by AndreeaCristinaRadacina** [comment]
Screenshots:
The replace options look different now:
<img width="267" alt="01_FileBlock_replace" src="https://user-images.githubusercontent.com/86592992/171654314-122eb033-60b3-4e53-91e6-b735221c3810.png">
There is a new icon for Reusable blocks and a new Lock option:
 
<img width="251" alt="02_FileBlock_moreoptions" src="https://user-images.githubusercontent.com/86592992/171654713-f8d5eee3-5a61-4efc-932b-76aa9608a438.png">

Changelog:
Updated on 2022-05-02
- Screenshots

**Comment by zzap** [comment]
https://user-images.githubusercontent.com/1508963/172370888-a3ba2df4-7604-46bd-892b-09d32846595d.mp4
