### ISSUE TITLE
[Theme Handbook Overhaul] Getting Started > Chapter Landing Page

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1257]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating the chapter landing page under Chapter 1: Getting Started.

This document is already drafted and ready for review in this Google Doc: https://docs.google.com/document/d/1eYYpodYiAMNHY8tjnoVQug0AVBVFhG8IDTrO8QCPejo/edit?usp=sharing

**Comment by justintadlock** [comment]
Note that this page is a replacement for the existing chapter landing page: https://developer.wordpress.org/themes/getting-started/

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
Page update: https://developer.wordpress.org/themes/getting-started/
