### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Chapter Landing Page

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1258]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating the chapter landing page for Chapter 2: Core Concepts.

This document is already drafted and ready for review in this Google Doc: https://docs.google.com/document/d/1pZ7mYg6ulhUFJrG2psExOzhsgK4Pgi_TdH_Zau6wPwI/edit?usp=sharing

**Comment by justintadlock** [comment]
This is in the Theme Handbook here: https://developer.wordpress.org/wp-admin/post.php?post=149331&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/core-concepts/
