### ISSUE TITLE
[HelpHub] WordPress Editor Page

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#126]
Article: https://wordpress.org/support/article/wordpress-editor/

## Updating for 5.7
- [ ] #395

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/zQHoNdgv/84-wordpress-editor-page

**Comment by femkreations** [comment]
Adding tasks to 6.0 https://github.com/WordPress/Documentation-Issue-Tracker/issues/302 and closing this issue
