### ISSUE TITLE
[HelpHub] About Block Directory

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#128]
Article: https://wordpress.org/support/article/block-directory/

## Updating for 6.1
- [ ] Adds CTA and external link to block inserter flow - [41112](https://github.com/WordPress/gutenberg/pull/41112)

## Updating for 5.6
- [ ] Add a "reinstall" button when a block type is not found - [22631](https://github.com/WordPress/gutenberg/pull/22631)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/8rZNgMks/98-about-block-directory

**Comment by samxmunoz** [comment]
**Reproduction steps for "reinstall":**

1. Add a block from block directory or plugin
2. Add the block to a page
3. Disable the block (now that button will display where the block was before).
4. Click "reinstall"

**Comment by femkreations** [comment]
Added tasks for 6.1

## Notes
1. Pls make 6.1 updates first 
2. Some of the PRs for 6.1 have great videos that can be added to the article

**Comment by jennimckinnon** [comment]
Just a note that I had a late start, but I'm on it.

**Comment by jennimckinnon** [comment]
@femkreations This update is done:

A) After the "How to use the Block Directory" heading

1. Select the “+” icon towards the top, left-hand corner of the editor.

![wordpress-block-directory-icon](https://user-images.githubusercontent.com/9810898/212947147-a08c827c-edac-4902-b613-7d891d18c403.png)

[ALT TEXT: The editor with icons displayed at the top, above the page content.]

[Please note: The point that was first "Type a keyword in the search field of the Inserter, like “team” or 'staff'" should be listed as number 2 on the list and so forth.

B) After point number 2, as noted above, and after "In the background, the system first searches the current site and if it doesn’t find a block, it also searches in the Block Directory, a special corner of the WordPress plugin repository, where single block plugins are available."

If no blocks are found in either case, a [link to the Block Editor Handbook](https://developer.wordpress.org/block-editor/) is displayed with details on how to create your own blocks.

![cta-external-link-block-inserter-flow-block-directory](https://user-images.githubusercontent.com/9810898/212944330-6fa3224b-98cb-4e22-8b3c-2d5f8e86f1a9.png)
[ALT TEXT: No results in the Block Directory, which displays a notice about creating your own block.]

C) Change "If it finds blocks, they will be displayed in the inserter, including a preview section." to:

If the search displays blocks in the results, they will be displayed in the inserter, including a preview section.

D) Update "Decide which block to use and click the button 'Add Block.'" to:

Decide which block to use and select it to add it to the page.

E) Change "In the background the single-block plugin is installed and activated, and the user can continue creating the team page." to remove "team" so it reads:

In the background the single-block plugin is installed and activated, and the user can continue creating the page.

F) Update "If the first choice not work out, you can go back to the search and select a different one that also will be installed." to:

If the first choice doesn't suit your needs, you can go back to the search and select a different one that also will be installed.

G) At the end of the article, before the changelog, add this section:

## How to reinstall a block

If a previously used block is no longer available on the site, you have the option to reinstall it.

When the page is first loaded, a search will be done in the background to check if that block is still available. If it has been found, a **Reinstall block** button will be displayed in the missing block on the page. Select the button to automatically reinstall the missing block.

<img width="797" alt="reinstall-block-keep-as-html" src="https://user-images.githubusercontent.com/9810898/212946724-e348f26f-d17d-4904-bb5b-7ac37acecb6c.png">
[ALT TEXT: Examples: Missing block with “Reinstall block” and “Keep as HTML” options, then a missing block with a “Keep as HTML” button.]

A **Keep as HTML** link will also be displayed, or it will be the only button present if no matching block was found when the page loaded.

You can choose that option instead. It lets you convert the content into a custom HTML block so you still have a chance to use the content of the block you had before.

You could also choose to remove the missing block and choose another one from the Block Directory using the steps outlined above.

**Comment by femkreations** [comment]
Thanks @samxmunoz and @jennimckinnon for the content. The page has been updated.
https://wordpress.org/documentation/article/block-directory/
