### ISSUE TITLE
[HelpHub] Media+Text Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#129]
Article: https://wordpress.org/support/article/media-text-block/

## Updating for 5.6
- [ ] set image size - [24688](https://github.com/WordPress/gutenberg/issues/24688)

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/wCU0qRld/6-mediatext-block

**Comment by marconmartins** [comment]
I'm checking this one.

**Comment by femkreations** [comment]
Adding tasks to 6.0 [#340 ](https://github.com/WordPress/Documentation-Issue-Tracker/issues/340) and closing this issue
