### ISSUE TITLE
[HelpHub] Twitter

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#130]
Article: https://wordpress.org/support/article/twitter-embed/

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/NPgZwdOV/22-twitter

**Comment by mrkdevelopment** [comment]
@zzap Ill take on this one and make the relevant updates

**Comment by mrkdevelopment** [comment]
@zzap this one is ready for your review
