### ISSUE TITLE
[HelpHub] Page Jump

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#132]
Article: https://wordpress.org/support/article/page-jumps/

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Add ALT tags for images
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/ctCN8KEy/113-page-jump

**Comment by leonidasmi** [comment]
I'm picking this up to update the screenshots

**Comment by leonidasmi** [comment]
**[HTML Anchor Syntax](https://wordpress.org/support/article/page-jumps/#html-anchor-syntax):**
![page-jump-01](https://user-images.githubusercontent.com/12400734/190138307-c7915fea-353c-44a1-9056-a07a3af12790.png)

**[Link to your HTML Anchor](https://wordpress.org/support/article/page-jumps/#link-to-your-html-anchor):**
![page-jump-02](https://user-images.githubusercontent.com/12400734/190138761-276173ca-c970-4834-90fd-d4ee23a90218.png)

Here are the new screenshots @zzap :)

**Comment by femkreations** [comment]
Thanks @leonidasmi The content looks great. Thanks for your work. We will add this to the WP article.

**Comment by samxmunoz** [comment]
I'll be updating this doc. 🚀

**Comment by samxmunoz** [comment]
@femkreations & @zzap - I updated this one and it's READY FOR REVIEW. 🚀 

**Note I added quite a bit to this doc, I added the fact that this could be done with various blocks any that have the `anchor` attribute within the Core Blocks Reference and added a video!**

**Comment by zzap** [comment]
Reviewed. Thank you @leonidasmi and @samxmunoz for awesome work :heart: 

I just edited `Changelog` heading to be level 2 (and set font size smaller) so that it doesn't appear as subheading for previous heading.
