### ISSUE TITLE
[HelpHub] Block Toolbar > More Options

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#133]
Article: https://wordpress.org/support/article/more-options/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] make sure all options are relevant for current version (5.9)
- [ ] update changelog at the end of the article
- [ ] update reusable block at HelpHub
- [ ] check if every block article is using reusable block

Issue migrated from Trello: https://trello.com/c/VGvs8HPb/105-block-toolbar-more-options

**Comment by jaz-on** [comment]
Ok I'm taking this one! :)

**Comment by jaz-on** [comment]
Quick note: this subtask "update reusable block at HelpHub" should be dealt in a separate issue.

**Comment by jaz-on** [comment]
@zzap I updated the post with my last screenshots + adding a quick tip about the name of the "remove block" option.
