### ISSUE TITLE
[HelpHub] List of Blocks

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#134]
Article: https://wordpress.org/support/article/blocks/

## General
- [x] make sure all blocks for current version (5.9) are listed
- [x] make sure all blocks are linked to existing articles
- [x] update changelog at the end of the article
- [x] create GitHub issue for each block without article

Issue migrated from Trello: https://trello.com/c/eNOYMnLw/11-list-of-blocks

**Comment by atachibana** [comment]
@zzap 
As a preliminary step, I compared with the Core Blocks Reference which is automatically generated by source code.
https://developer.wordpress.org/block-editor/reference-guides/core-blocks/
Note: It is not covering embedded block variations.

Missing Blocks in the HelpHub Blocks page:

Comment Author Avatar
Comment Author Name
Comment Content
Comment Date
Comment Edit Link
Comment Reply Link
Comment Template
Comments Pagination
(Comment) Next Page
(Comment) Page Numbers
(Comment) Previous Page
Comments Query Loop
?? Embed (internal only?)
Home Link
?? Unsupported (internal only?)
Navigation Area
Custom Link
Submenu
Pattern
Post Author
Post Author Name
Post Comment (deprecated)
Post Comments
Post Comments Count
Post Comments Form
Post Comments Link
Post Navigation Link
Post Template
Post Terms
Pagination
Next Page
Page Numbers
Previous Page
Query Title
?? Table of Contents  (internal only?)
Term Description
?? Text Columns (deprecated) (internal only?)

**Comment by zzap** [comment]
This is great @atachibana :heart: 

We should create an issue for each

**Comment by femkreations** [comment]
FYI, separate issues have been opened for the missing blocks. Refer to https://github.com/orgs/WordPress/projects/23/views/1. 
To find the tracker related to each item, clicking on the Item in the Title Column that opens a rich text editor with details.

**Comment by femkreations** [comment]
Updated https://wordpress.org/support/article/blocks/ with the list of blocks in the Block Inserter for 6.0, Added links for the pages that are ready. Also added info for Reusable blocks and Most Used blocks. Thanks.
