### ISSUE TITLE
[HelpHub] Custom HTML

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#135]
Article: https://wordpress.org/support/article/custom-html/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add missing sections (use other blocks to compare)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/QjFi6aZu/64-custom-html

**Comment by nishitlangaliya** [comment]
Hi @zzap ,

1.  How to take custom html block.
![image](https://user-images.githubusercontent.com/11435772/161048570-bfa3538d-5a68-4e6f-9b2f-f67c9d3f9b15.png)

2. How to add code into it
![image](https://user-images.githubusercontent.com/11435772/161050856-ac7674df-631c-4a38-874a-c92d1a6f1d23.png)

3.  Preview block.
![image](https://user-images.githubusercontent.com/11435772/161051008-ee260781-85eb-4ff4-b475-73dc0425ea84.png)


4. Block toolbar.
![image](https://user-images.githubusercontent.com/11435772/161051157-7375a863-d3b0-4e15-a83d-720321bae29f.png)

5. Block settings.
![image](https://user-images.githubusercontent.com/11435772/161051339-14975922-c9a7-4c8d-aba2-fa0dec507e5e.png)

Please let me know if any changes required. here.

Thanks

**Comment by zzap** [comment]
Hello @nishitlangaliya , thank you so much for working on this :heart: 

Would you like to update article yourself? If so, I'll need your wordpress.org username to give you the access.

**Comment by zzap** [comment]
![01-add-custom-html](https://user-images.githubusercontent.com/1508963/164263756-13d7432b-f385-4953-bcdb-73e8122ef430.png)
![02-custom-html](https://user-images.githubusercontent.com/1508963/164263762-91c8b6d3-985e-4b45-b908-cde86309fc05.png)
![03-custom-html-preview](https://user-images.githubusercontent.com/1508963/164263768-4e6a6c16-8e7c-4186-af0e-62464c6daf6c.png)
![04-custom-html-more](https://user-images.githubusercontent.com/1508963/164263771-7dd748fd-c64f-4556-b749-7ba84456828b.png)
![05-custom-html-settings](https://user-images.githubusercontent.com/1508963/164263778-594309aa-4b96-45bb-b6c7-ae650f226594.png)
