### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Security

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1359]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Security" under Chapter 7: Advanced Topics.

Note that this single doc is a wholesale replacement of the current [Theme Security](https://developer.wordpress.org/themes/theme-security/) chapter in the handbook, which has mostly been archived and already points to various docs in the [Security](https://developer.wordpress.org/apis/security/) chapter in the Common APIs handbook. This new doc consolidates and updates the existing content that we have for theme development.

The new draft for this page is in a Google Doc: https://docs.google.com/document/d/1wG0Yd4jg_m7lT-_wNP1XB4T3j_HyzBTUl9jSxpAKTYo/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc has been moved to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152068&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/advanced-topics/security/
