### ISSUE TITLE
[HelpHub] YouTube

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#136]
Article: https://wordpress.org/support/article/youtube-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/2NHkQGs1/24-youtube

**Comment by mrkdevelopment** [comment]
@zzap Ill work on the youtube block

**Comment by mrkdevelopment** [comment]
@zzap this is ready for review and submitted to the save for later.
