### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Privacy

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1361]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Privacy" under Chapter 7: Advanced Topics.

Note that this single doc is a wholesale replacement of the current [Theme Privacy](https://developer.wordpress.org/themes/theme-privacy/) chapter/page in the handbook and moves it under Advanced Topics as a sub-page.

The new draft for this page with updated text and some new content is drafted in a Google Doc: https://docs.google.com/document/d/1s-2slh3NrO2padUItBtbE60E0FMAJ5w1_wRme3SCJfc/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc has been moved to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152063&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/advanced-topics/privacy/
