### ISSUE TITLE
Incorrect example for `WP_HTML_Tag_Processor` class

### ISSUE THREAD

**Issue by crstauf** [WordPress/Documentation-Issue-Tracker#1362]
## Issue Description
> The examples in the documentation reference using the class parameter to query for an existing class on a tag. But the source code and code function documentation actually only suppor the `class_name` property:
The example under Modifying HTML attributes for a found tag should be:
> ```if ( $tags->next_tag( array( 'class_name' => 'wp-group-block' ) ) ) {```
> At least for me in WP 6.3.

Reported by @gaambo via User Contributed Notes.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/classes/wp_html_tag_processor/#modifying-html-attributes-for-a-found-tag

## Section of Page with the issue
Usage > Modifying HTML attributes for a found tag

## Why is this a problem?
Misrepresents how to use a method's class.

## Suggested Fix
Change `class` to `class_name`.

**Comment by atachibana** [comment]
@crstauf Thank you for the report.
To fix this issue, we need core ticket and its process. I opened a ticket as below and close this issue.
https://core.trac.wordpress.org/ticket/59891

**Comment by atachibana** [comment]
fyi
https://core.trac.wordpress.org/ticket/59891 was closed.
