### ISSUE TITLE
Typo in `remove_menu_page()` "More Information"

### ISSUE THREAD

**Issue by crstauf** [WordPress/Documentation-Issue-Tracker#1363]
Reported by @skithund via User Contributed Notes.

## Issue Description
> There’s a typo in the second paragraph of “More Information”.
>
> Calling it elsewhere might cause issues: either the function is not defined or the global $menu variable used but this function is not yet declared.
>
> Should be
>
> Calling it elsewhere might cause issues: either the function is not defined or the global $menu variable used by this function is not yet declared.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/remove_menu_page/#more-information

## Section of Page with the issue
More Information

## Suggested Fix
> Calling it elsewhere might cause issues: either the function is not defined or the global $menu variable used by this function is not yet declared.

**Comment by stevenlinx** [comment]
Thanks for filing.

I've made the revision.

I've also revised the link to remove_submenu_page() function from the Codex version to the DevHub version.
