### ISSUE TITLE
[HelpHub] How to use the preview function

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#137]
Article: https://wordpress.org/support/article/how-to-use-the-preview-function/

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/ofsa1S8g/97-how-to-use-the-preview-function

**Comment by mrkdevelopment** [comment]
@zzap I checked these and they don't look to need a change. Everything is relevant and up to date.

**Comment by zzap** [comment]
Thank you, we can close this then.
