### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Debugging

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1370]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Debugging" under Chapter 7: Advanced Topics.

This doc splits debugging into a single doc from its [original location as a sub-section](https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/#wp-debug).

The doc will be drafted in Google Docs here: https://docs.google.com/document/d/1bpEjd0WJdvN5IpLIbFEigHLub5hg5LUHduQTyLaaJIQ/edit?usp=sharing

**Comment by justintadlock** [comment]
This draft is now ready for review.

**Comment by justintadlock** [comment]
This post has been moved to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152066&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/advanced-topics/debugging/
