### ISSUE TITLE
Cite element missing text in Theme Handbook -  Global Settings and Styles - Styling elements section

### ISSUE THREAD

**Issue by andreawetzel** [WordPress/Documentation-Issue-Tracker#1375]
## Issue Description
The text in the bullet for `cite` under [Styling Elements](https://developer.wordpress.org/themes/global-settings-and-styles/styles/applying-styles/#styling-elements) end abruptly. 

## URL of the Page with the Issue
https://developer.wordpress.org/themes/global-settings-and-styles/styles/applying-styles/

## Section of Page with the issue
[Styling Elements 
](https://developer.wordpress.org/themes/global-settings-and-styles/styles/applying-styles/#styling-elements)

## Why is this a problem?
It currently reads `cite: Applied to the <cite> element when used for citations, such as` 

## Suggested Fix
Update bullet to include an example of where a citation appears in HTML. Perhaps:   
`cite: Applied to the <cite> element when used for citations, such as a citation inside a blockquote.`

**Comment by carolinan** [comment]
Thank you for the report, I have update the text to highlight that the `<cite>` is used with the quote and pullquote blocks.
