### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Build Process

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1377]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Build Process" under Chapter 7: Advanced Topics.

This will be drafted in this Google Doc: https://docs.google.com/document/d/1ws1XJkcjmgrTgWh0oO4JO_Xqja7E4zZCW4c0g-IRYeU/edit?usp=sharing

**Comment by justintadlock** [comment]
This doc draft is now complete and can be reviewed.

**Comment by justintadlock** [comment]
This draft has been moved to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152060&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/advanced-topics/build-process/
