### ISSUE TITLE
Typo in Theme Handbook - Core Concepts

### ISSUE THREAD

**Issue by c4rl0sbr4v0** [WordPress/Documentation-Issue-Tracker#1378]
## Issue Description

Hi there!
Reported by [@up1512001](https://profiles.wordpress.org/up1512001/) in [this support forum ticket.](https://wordpress.org/support/topic/spelling-mistake-in-them-core-concept-documentation/)

## URL of the Page with the Issue

https://developer.wordpress.org/themes/core-concepts/

## Section of Page with the issue

At the end of the paragraph with the title "Navigating this chapter"

`fee free to jump to the section you need:` should be `feel free to jump to the section you need:`

## Why is this a problem?

Fee is not the same as feel :-)

## Suggested Fix

Edit fee with feel

**Comment by gurusatya** [comment]
I'm ready to fix the issue and make my initial contribution.

**Comment by up1512001** [comment]
@c4rl0sbr4v0 can you assign this issue to me?

**Comment by c4rl0sbr4v0** [comment]
I don't have the permissions to do it 😢. Let's wait for docs issues coordinators.

**Comment by kafleg** [comment]
Fixed.
