### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Internationalization

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1383]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Internationalization" under Chapter 7: Advanced Topics.

This will be drafted in this Google Doc: https://docs.google.com/document/d/1twwX2P6XWISi6UbGdJ-fCSyodDz_TtiDNEUvXaI56no/edit?usp=sharing

**Comment by justintadlock** [comment]
Note that this a combination of the two existing documents: 

- https://developer.wordpress.org/themes/functionality/internationalization/ 
- https://developer.wordpress.org/themes/block-themes/internationalization/ 

The goal is to review and update the existing doc text and any screenshots.

**Comment by justintadlock** [comment]
This document is now ready for review.

**Comment by justintadlock** [comment]
This doc has been moved to the Theme Handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152057&action=edit

**Comment by kafleg** [comment]
Looks good to me. Ready to go.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/advanced-topics/internationalization/
