### ISSUE TITLE
Font Face: Server-side @font-face styles generator and printer

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#1386]
This ticket has been copied from the [ticket](https://github.com/WordPress/Documentation-Issue-Tracker/issues/1164) on the 6.4 documentation tracker. This dev note will accompany 6.5 when the Font Library is expected to ship.
Trac ticket: https://core.trac.wordpress.org/ticket/59165

Keyword on ticket: 

Ticket owner: hellofromTonya

Core committer: hellofromTonya

**Comment by stevenlinx** [comment]
Closing. Tracking using Project card.
