### ISSUE TITLE
[HelpHub] Keyboard Navigation & Shortcuts

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#139]
Article: https://wordpress.org/support/article/block-editor-keyboard-shortcuts/

From Trello card:
>The task is to prepare a comprehensive guide about all the Keyboard Navigation and shortcuts available in WordPress and how to use them.

## General
- [ ] check if all shortcuts are added, check for Linux too
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/brwjju3J/107-keyboard-navigation-shortcuts

**Comment by SJeca** [comment]
I'd like to work on this
https://wordpress.org/support/article/block-editor-keyboard-shortcuts/

**Comment by SJeca** [comment]
Everything is up to date. Functionalities are the same as they are in the previous version.

**Comment by zzap** [comment]
Thank you so much for checking this @SJeca :heart:
