### ISSUE TITLE
Importing Content: out of date content pointing to importers that no longer exist.

### ISSUE THREAD

**Issue by jordesign** [WordPress/Documentation-Issue-Tracker#1396]
## Issue Description
The 'Importing Content' document contains links to importing tools and plugins that no longer exist.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/importing-content/

## Section of Page with the issue

* https://wordpress.org/documentation/article/importing-content/#html - native HTML importer no longer exists
* https://wordpress.org/documentation/article/importing-content/#posterous - Wordpress.com tool no longer exists
* https://wordpress.org/documentation/article/importing-content/#yahoo-360 - WordPress.com tool no longer exists
* https://wordpress.org/documentation/article/importing-content/#vox - WordPress.com tool no longer exists

## Why is this a problem?
We shouldn't point to tools that don't exist :)

## Suggested Fix
These sections can be removed.

**Comment by jordesign** [comment]
/assign

I'm happy to make this change - but keen to push it through rapidly, and would like approval from the team first :)

**Comment by jordesign** [comment]
@WordPress/docs-issues-coordinators  Do I have the ok to go ahead with this? I just want to be sure before I go deleting sections :)

**Comment by zzap** [comment]
Sure, go ahead @jordesign

**Comment by jordesign** [comment]
Thanks @zzap  - all sorted out now.
