### ISSUE TITLE
Comma is missing after JSON property

### ISSUE THREAD

**Issue by saratheonline** [WordPress/Documentation-Issue-Tracker#1397]
In the block hooks example. A comma is missing after the first item in the JSON.

## Issue Description
There must be a comma after each JSON property. Here after the first item the comma is missing.

## URL of the Page with the Issue
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#block-hooks-optional

## Section of Page with the issue
Block Hooks section
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#block-hooks-optional

## Why is this a problem?
The example in this section is incorrect.

## Suggested Fix
Add a comma after the first item of the JSON.

<img width="751" alt="image" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/16861083/df61ccc2-61f5-4491-8819-89335480da0d">

**Comment by flexseth** [comment]
Checked this item, the PR has been merged into Gutenberg.
/assign 
/review ready!

**Comment by flexseth** [comment]
@saratheonline - this has been fixed and merged into the Gutenberg repository, if you could please close this issue! Thank you for bringing it to attention of the docs team
