### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Matheun** [WordPress/Documentation-Issue-Tracker#1399]
## Issue Description
A simple spelling error

## URL of the Page with the Issue
https://wordpress.org/documentation/article/what-is-an-excerpt-block-editor/#what-is-an-excerpt

## Section of Page with the issue
The description

## Why is this a problem?
'Excerpt is an optionnal text associated to a Post.'

'optionnal' is spelled wrong

## Suggested Fix
change it to 'optional'

**Comment by stevenlinx** [comment]
Thanks for filing.

Fixed.
