### ISSUE TITLE
Grammer/ Reading difficulty

### ISSUE THREAD

**Issue by Matheun** [WordPress/Documentation-Issue-Tracker#1400]
## Issue Description
Possible reading issues

## URL of the Page with the Issue
https://wordpress.org/documentation/article/what-is-an-excerpt-block-editor/#what-is-an-excerpt

## Section of Page with the issue
Below the image in section 'What is an excerpt'

## Why is this a problem?
'No finding the Excerpt editing box? Check your Document tab at the right of your page. The Excerpt box is just after the Featured Image section.'

where 'No finding the Excerpt editing box?' doesnt read easy/ feels awkward to read.

## Suggested Fix
This should probably be something like 'No luck finding the Excerpt editing box?' or 'Can`t find the Excerpt editing box?'

**Comment by itechwrite** [comment]
Hi! I'm a first-time contributor here, and I would like to fix this issue :)

**Comment by Matheun** [comment]
I would like to fix this myself aswell, but cant figure out how to get a account/ permissions to do so

**Comment by Roshan-narola** [comment]
Hello, I want to fix that issue can you please assign it to me. Thank you

**Comment by nerdontour** [comment]
Changed the wording to "Can't find the Excerpt editing box?". I'm closing this issue now.

**Comment by basicwp** [comment]
### Where to find Excerpt Box in the WordPress Dashboard

1. Click on the 'Edit' button on specific post or page.
2. On the Block Editor screen, look for the "Excerpt" section at the bottom right part of the screen.
3. Click the down arrow to expand the "Excerpt" section.
4. Enter the excerpt content and remember to click "Update" button to save changes.

**Comment by atachibana** [comment]
@nerdontour fixed the issue.
