### ISSUE TITLE
Broken or wrong link

### ISSUE THREAD

**Issue by ozanzeng** [WordPress/Documentation-Issue-Tracker#1401]
## Issue Description
The "pattern" header link, in this section does not work.
https://developer.wordpress.org/themes/core-concepts/theme-structure/#standard-folders 
​

## Section of Page with the issue
patterns ([Block Patterns] (https://developer.wordpress.org/themes/features/block-features/))

## Why is this a problem?
Broken link

## Suggested Fix
It should be, https://developer.wordpress.org/themes/features/block-patterns/

**Comment by flexseth** [comment]
> patterns ([Block Patterns](https://developer.wordpress.org/themes/features/block-patterns/)): Reusable patterns made up of one or more blocks that users can insert via the editor interface. WordPress will automatically register files included in this folder.

Link has been fixed. Marking this as closed! TY for reporting @ozanzeng
