### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Publishing Themes

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1409]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Publishing Themes" under Chapter 7: Advanced Topics.

This will be drafted in this Google Doc: https://docs.google.com/document/d/1yeM0r9NaA59_zySjaX-wfFEB_yoFL-3bVHuEURBEWZk/edit?usp=sharing

@alexdeborba will be working on this draft. 🎉

**Comment by alexdeborba** [comment]
I will be collaborating while writing this document.

**Comment by alexdeborba** [comment]
The document is now finished and ready for review.

**Comment by justintadlock** [comment]
@alexdeborba - I've given this an editing pass. For the most part, I just changed some stylistic stuff to match the doc standards and added some additional links. It's really good. 👍 

@kafleg - You may also want to give it a review or wait until we prep the entire Advanced Topics chapter for publishing (I think this could happen within the next week or so).

**Comment by kafleg** [comment]
I added my comments in the Doc. Please check it.

**Comment by justintadlock** [comment]
@kafleg - I made some more edits to this one, simplifying some of the language and cutting a few bits. The most up-to-date version is drafted in the handbook: https://developer.wordpress.org/wp-admin/post.php?post=152151&action=edit

It should be good to publish now. @alexdeborba addressed both mine and your feedback.

**Comment by kafleg** [comment]
Looks good to me. Please publish it.

**Comment by justintadlock** [comment]
This is now published here: https://developer.wordpress.org/themes/advanced-topics/publishing-themes/
