### ISSUE TITLE
[HelpHub] Quote Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#141]
Article: https://wordpress.org/support/article/quote-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/FA20cGRv/4-quote-block

**Comment by manuelaugustin** [comment]
I'd like to pick up this issue.

**Comment by manuelaugustin** [comment]
Overview video at beginning:

https://user-images.githubusercontent.com/27805437/152520228-cbd82eda-eb53-430e-b014-eb277dff046f.mp4

**Comment by femkreations** [comment]
Added content, screenshots, images and video for 6.0. Review complete. @zzap
