### ISSUE TITLE
"Improve it on Github" and "See list of changes" buttons don't work

### ISSUE THREAD

**Issue by avdi** [WordPress/Documentation-Issue-Tracker#1410]
## Issue Description

1. Go to a doc page, e.g. https://developer.wordpress.org/rest-api/reference/users/
2. Click on "Improve it on Github" or "See list of changes"

What should happen: find yourself here
What actually happens: nothing (well, it scrolls up to the top of the page)

**Comment by ndiego** [comment]
This is now fixed [here](https://github.com/WordPress/wporg-developer/pull/472).
