### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Testing

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1412]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used to add a new doc titled "Testing" under Chapter 7: Advanced Topics.

This will be drafted in this Google Doc: https://docs.google.com/document/d/1g3b1O_4qfqE6Hy-dhP-L2LmyBppez2M867m1KnicJTc/edit?usp=sharing

@alexdeborba will be working on this draft. 🎉

**Comment by alexdeborba** [comment]
I will be collaborating while writing this document.

**Comment by alexdeborba** [comment]
The proposed document is now complete and ready for your review.

While mindful of its detailed and potentially extended nature, I believe this depth serves to thoroughly address all pertinent information. Nevertheless, I remain open to the possibility that specific sections could be strategically relocated to separate documents, where they might contribute more effectively and receive focused attention.

**Comment by kafleg** [comment]
I see comments from @justintadlock in the above doc. Did you see it @alexdeborba ?

**Comment by alexdeborba** [comment]
@kafleg Missed comment notifications. Working on it and will address feedback.

**Comment by justintadlock** [comment]
I've went through and made a full edit of the doc. I figured this was going to be faster than trying to explain everything through Google Doc's suggestions/comments (mostly, just trying to push to get the rest of the Advanced Topics chapter live).

The biggest changes I made are:

- Simplified a lot of the language (we want to make sure this is readable for a wider audience).
- Removed a lot of unnecessary words to keep things clearer.
- Removed some sections altogether, mostly because they were mostly repeated content from previous sections.
- Added some links to additional standard tools.

Mostly, I wanted to cut out anything that would prevent the reader from just getting to the information/links they need. It probably feels a bit heavy-handed, but the conciseness should make for an easier read.

@kafleg - I think this is at a point where we can do a final review now.

**Comment by justintadlock** [comment]
@kafleg - I have moved this to the handbook as a draft: https://developer.wordpress.org/wp-admin/post.php?post=152083&action=edit

I made a few more minor edits, but it should be good to publish if you think it's ready.

**Comment by carolinan** [comment]
Calling the XML file "theme unit test" can be confusing since it is not what we would call a unit test when we for example test PHP files.

This can be handled separately, but eventually it would be good to move, refresh the content, and remove the codex page: https://codex.wordpress.org/Theme_Unit_Test

**Comment by kafleg** [comment]
Thank you @justintadlock 

Looks good to me.

**Comment by justintadlock** [comment]
This is now published here: https://developer.wordpress.org/themes/advanced-topics/testing/
