### ISSUE TITLE
[Theme Handbook Overhaul] Advanced Topics > Chapter Landing Page

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1417]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating the landing page content for Chapter 7: Advanced Topics.

The content for the new page is drafted in a Google Doc: https://docs.google.com/document/d/1IN8xCdJmghAHwkhBtSQyQ8TP6t9leSaXCWQPV1AapZ4/edit?usp=sharing

This draft is already written and can be reviewed.

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
The landing page has been updated here: https://developer.wordpress.org/themes/advanced-topics/

But we need to keep this ticket open until the remaining docs are published. We can close it once we get those published and the additional links added to this page.

**Comment by justintadlock** [comment]
Sub-docs have been added so closing this ticket now.
