### ISSUE TITLE
[HelpHub] Video Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#142]
Article: https://wordpress.org/support/article/video-block/

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/btHwtPKo/58-video-block

**Comment by michaelbriantina** [comment]
I guess I'll try updating this article :)

**Comment by michaelbriantina** [comment]
I made sure that all screenshots are relevant for WP 5.9 and I updated the changelog as well. Done!
