### ISSUE TITLE
[HelpHub] Feedback on Get started with WordPress

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1426]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/get-started-with-wordpress/

## Originally reported by

https://profiles.wordpress.org/bazzore1/

## Report content (issue description)

>The link shown as “Learn WordPress” takes me to a page that does not actually exist. A bit unhelpful – perhaps this can be refreshed?

**Comment by emmasophieyoung** [comment]
Learn WordPress link works and points to learn.wordpress.com
