### ISSUE TITLE
[HelpHub] Feedback on List View

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1429]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/list-view/

## Originally reported by

https://profiles.wordpress.org/randewoo/

## Report content (issue description)

> HI!
> 
> TYPO there:
> “WordPress 6.3 renamced Reusable Block to (Synced) Patterns”

**Comment by emmasophieyoung** [comment]
I can't find the typo, It is already fixed.
