### ISSUE TITLE
[HelpHub] Feedback on Spotify Embed

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1434]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/spotify-embed/

## Originally reported by

https://profiles.wordpress.org/photomaldives/

## Report content (issue description)

> Hi WP. When I follow these instructions, I only see a track PREVIEW of a few seconds on my website. It would be great if you could cover this.

**Comment by emmasophieyoung** [comment]
Update - the PREVIEW plays the entire song now.
