### ISSUE TITLE
[HelpHub] Feedback on Users Screen

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1435]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/users-screen/

## Originally reported by

https://profiles.wordpress.org/mcw0708/

## Report content (issue description)

>Explain the User roles and what it means if you change them. Also, how to notify Users of new posts?

**Comment by ndiego** [comment]
I added a note linking to https://wordpress.org/documentation/article/roles-and-capabilities/.
