### ISSUE TITLE
[HelpHub] Cover Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#144]
Article: https://wordpress.org/support/article/cover-block/

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/9ttURAdw/8-cover-block

**Comment by lnaima** [comment]
I'd like to work on this issue

**Comment by lnaima** [comment]
Since the "Transform group" old screenshots are showing styles, which I don't have so I'll post my screenshot here

![cover-group-v5 9](https://user-images.githubusercontent.com/6752710/152515300-db287189-42ab-46bb-8ae0-b7ffdf66c585.jpg)

**Comment by lnaima** [comment]
For the cover dimensions there's a new option about padding.

![cover-dimensions-v5 9](https://user-images.githubusercontent.com/6752710/152518441-2133d86a-2fe6-429e-874c-e1311ae40318.jpg)

**Comment by lnaima** [comment]
Color option is quite different, maybe a change on text should be necessary
![cover-overlay-v5 9](https://user-images.githubusercontent.com/6752710/152518811-85c583b2-c168-450a-a142-451541f78d78.jpg)
