### ISSUE TITLE
Broken links for jQuery plugins

### ISSUE THREAD

**Issue by crstauf** [WordPress/Documentation-Issue-Tracker#1443]
## Issue Description
> Old URLs were https://plugins.jquery.com/project/form/, https://plugins.jquery.com/project/color/
> New URLs are https://plugins.jquery.com/form/, https://plugins.jquery.com/color/

Reported by gerardreches via User Contributed Notes.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/wp_enqueue_script/#default-scripts-and-js-libraries-included-and-registered-by-wordpress

## Section of Page with the issue
Default Scripts and JS Libraries Included and Registered by WordPress

## Why is this a problem?
Broken links.

## Suggested Fix
Fix the links.

**Comment by Alucard0x1** [comment]
+1 for Broken Links.

**Comment by isheeba** [comment]
Updated jQuery Form and Color : also the below links

1. [Image Cropper](https://www.defusion.org.uk/) =>  https://defusion.org.uk/code/javascript-image-cropper-ui-using-prototype-scriptaculous/
2. [Jcrop](https://deepliquid.com/content/Jcrop.html) => https://github.com/tapmodo/Jcrop 
3. [MediaElement.js (WP 3.6+)](https://mediaelementjs.com/) => https://www.mediaelementjs.com/ 
4. [jQuery Schedule](https://trainofthoughts.org/blog/2007/02/15/jquery-plugin-scheduler/) => https://plugins.jquery.com/schedule
5. [jQuery Hotkeys](https://plugins.jquery.com/project/hotkeys) => https://plugins.jquery.com/hotkeys
6. [Tiny MCE](https://tinymce.moxiecode.com/) => https://www.tiny.cloud/docs-4x/
7. [imgAreaSelect](http://odyniec.net/projects/imgareaselect/) => https://github.com/odyniec/imgareaselect

### References 
Script Loader :  https://github.com/WordPress/WordPress/blob/master/wp-includes/script-loader.php#L867
Cropper Js file : https://github.com/WordPress/WordPress/blob/master/wp-includes/js/crop/cropper.js
JS folder : https://github.com/WordPress/WordPress/tree/master/wp-includes/js
