### ISSUE TITLE
[HelpHub] Feedback on WordPress Versions

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1449]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/wordpress-versions/

## Originally reported by

https://profiles.wordpress.org/wfmattr/

## Report content (issue description)

> Just checking if it is known that this page is out of date: https://wordpress.org/documentation/article/wordpress-versions/
> 
> It is missing 6.4.2, but also older versions like 5.1.16 and 5.1.17.

**Comment by stevenlinx** [comment]
This is fixed.
