### ISSUE TITLE
[HelpHub] Table

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#145]
Article: https://wordpress.org/support/article/table-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/s5oqm2cj/65-table

**Comment by SJeca** [comment]
I'd like to work on this
https://wordpress.org/support/article/block-editor-keyboard-shortcuts/

**Comment by dvarouxis** [comment]
![Add New Post ‹ kugama — WordPress (2)](https://user-images.githubusercontent.com/103357583/162612917-3351d422-e82b-4842-8922-ee4eff1ebfce.png)
![Add New Post ‹ kugama — WordPress (1)](https://user-images.githubusercontent.com/103357583/162612918-95a69446-06c0-43d8-810f-3d9966db0cba.png)
![Add New Post ‹ kugama — WordPress](https://user-images.githubusercontent.com/103357583/162612920-501485b9-ef1e-46a2-8e79-d8df0f3f7075.png)
@zzap

**Comment by zzap** [comment]
@dvarouxis thank you so much for working on this :heart: 

Would you like to update the article yourself? If so, I need your wp.org username to give you permissions.

**Comment by zzap** [comment]
![01-table-block-select](https://user-images.githubusercontent.com/1508963/164273160-d350a7cb-208e-4529-a378-b6e5a1f98f80.png)
![02-table-block-toolbar](https://user-images.githubusercontent.com/1508963/164273161-bc3a7e25-76a5-4213-af11-31953c782829.png)
