### ISSUE TITLE
Broken link on the Theme Handbook's Blocks section

### ISSUE THREAD

**Issue by wernerm** [WordPress/Documentation-Issue-Tracker#1452]
## Issue Description

On the [Blocks page](https://developer.wordpress.org/themes/global-settings-and-styles/settings/blocks/) of the [Theme Developer's Handbook](https://developer.wordpress.org/themes/), there is a broken link to the Color settings documentation. The erroneous section is quoted below:

> "For this example, you will create a custom color palette,  in the [color settings documentation](https://developer.wordpress.org/global-settings-and-styles/settings/color)."

The page at https://developer.wordpress.org/global-settings-and-styles/settings/color does not exist.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/global-settings-and-styles/settings/blocks/

## Section of Page with the issue
The [How Block Settings Work](https://developer.wordpress.org/themes/global-settings-and-styles/settings/blocks/#how-block-settings-work) section

## Why is this a problem?
There is a broken link.

## Suggested Fix

The correct resource seems to be at [https://developer.wordpress.org/themes/global-settings-and-styles/settings/color/](https://developer.wordpress.org/themes/global-settings-and-styles/settings/color/). However, since the page is discussed after the Blocks settings page, I suppose the text would have to change from "which you learned about" to something like "which you can learn more about".

**Comment by justintadlock** [comment]
Updated link and text with suggestions.
