### ISSUE TITLE
backslashes in htaccess

### ISSUE THREAD

**Issue by leendertvb** [WordPress/Documentation-Issue-Tracker#1456]
## Issue Description
In the documentation about the htaccess at https://developer.wordpress.org/advanced-administration/server/web-server/httpd/ almost all special characters are escaped using a backslash. This doesn't seem to be correct behavior as this will escape the characters rather than using the special meaning of these characters.

**Example:**
In the docs this line is given:
`RewriteRule ^index\\.php$ - \[L\]`
This will escape the square brackets, losing the special meaning of this grouping.
Also in a line like:
`RewriteCond %{REQUEST\_FILENAME} !-f`
the default variable for REQUEST_FILENAME will not work anymore as the underscore is escaped.

## URL of the Page with the Issue
https://developer.wordpress.org/advanced-administration/server/web-server/httpd/

## Section of Page with the issue
Sections "Basic WP" and "Multisite"

## Why is this a problem?
When copy-pasting the given code from the documentation to an actual Wordpress installation, this results in a 500 Internal Server Error.

## Suggested Fix
The backslashes should be removed from the htaccess snippet, like it has been before 2023-04-25.
The full code for the basic WP setup will become:
```
# BEGIN WordPress

RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]`
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

# END WordPress
```

Please note that the issue is also present in the Multisite snippet, and should be changed there as well.

**Comment by leendertvb** [comment]
https://github.com/WordPress/Advanced-administration-handbook/issues/318

**Comment by jani** [comment]
https://developer.wordpress.org/advanced-administration/server/web-server/httpd/ now is updated with the approved pull request https://github.com/WordPress/Advanced-administration-handbook/pull/320.
