### ISSUE TITLE
Missing link in JavaScript Best Practices documentation under jQuery

### ISSUE THREAD

**Issue by andreawetzel** [WordPress/Documentation-Issue-Tracker#1459]
## Issue Description

A "(link needed)" note is under the jQuery section

## URL of the Page with the Issue

https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/#jquery

## Section of Page with the issue

jQuery > Using $

## Why is this a problem?

Just a typo

## Suggested Fix

Either remove the (link needed) placeholder or link to jQuery documentation https://api.jquery.com/jQuery.noConflict/ (or somewhere else if there's a better source)

**Comment by ndiego** [comment]
@justintadlock would you be able to tackle this one?

**Comment by justintadlock** [comment]
Updated the link.

A new version of this doc is also being worked on here, so any additional feedback is welcome: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1418
