### ISSUE TITLE
[HelpHub] Actions Reference: actions links mostlybroken

### ISSUE THREAD

**Issue by HongPong** [WordPress/Documentation-Issue-Tracker#1462]
## Issue Description
Most of the Action Reference links are broken to the various actions. (.e.g. https://developer.wordpress.org/Plugin_API/Action_Reference/current_screen is linked from it.)

## URL of the Page with the Issue
https://developer.wordpress.org/apis/hooks/action-reference/

## Section of Page with the issue
Generally the majority

## Why is this a problem?
No redirects on the other side so it doesn't navigate well.

## Suggested Fix
I assume regex or find/replace to the new actions unless they are assembled in some other way

**Comment by jonathanbossenger** [comment]
Hey @HongPong thanks for logging this. I am tracking the updates for these two new developer handbook pages on #370 so I'm going to close this as a duplicate for now.
