### ISSUE TITLE
[HelpHub] Preformatted Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#147]
Article: https://wordpress.org/support/article/preformatted-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/2oO8WArE/74-preformatted-block

**Comment by agnieszkaszuba** [comment]
I'd like to take this issue :)

**Comment by agnieszkaszuba** [comment]
I updated the images and video and saved the changes for later (tomorrow).

I noticed some general things that still need to be updated in the article:

- Under 'Change block type or style' there is a part about being able to add background color when you transform the block type to Group. But I think now you can also do that in the Preformatted block.
- 'Drag' is now one of the standard controls. It needs to be added to the overview of standard controls.
- Some of the options under More rich text controls are now different. That section needs to be updated.
