### ISSUE TITLE
[HelpHub] Block Themes link broken in Customizer doc

### ISSUE THREAD

**Issue by macmanx2** [WordPress/Documentation-Issue-Tracker#1475]
## Issue Description
In the Customizer doc, "Block themes" is linked to `https://wordpress.org/documentation/article/block-themes/(opens%20in%20a%20new%20tab)`

## URL of the Page with the Issue
https://wordpress.org/documentation/article/customizer/

## Section of Page with the issue
https://wordpress.org/documentation/article/customizer/

## Why is this a problem?
Because the link is broken.

## Suggested Fix
Change the link to https://wordpress.org/documentation/article/block-themes/ and check "Open in new tab" in the editor if desired.

**Comment by estelaris** [comment]
Reviewed and updated all links in this article
