### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Joseph-wb** [WordPress/Documentation-Issue-Tracker#1477]
Is this an error in the documentation under block patterns? Shouldn’t this be unregister_block_pattern_category( ‘themeslug/custom’ );

https://developer.wordpress.org/themes/features/block-patterns/#unregistering-a-pattern-category

This example:
```
function themeslug_unregister_pattern_categories() {
register_block_pattern_category( 'themeslug/custom' );
}
```

It's meant to be this?

```
function themeslug_unregister_pattern_categories() {
unregister_block_pattern_category( 'themeslug/custom' );
}
```

**Comment by carolinan** [comment]
Thank you.
I have updated it.
(Note that because there is a known bug with the code block, the update placed the whole code example on one line).
