### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Introduction to Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1478]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Introduction to Patterns" under the "Patterns" chapter.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1LdDb-yMxZ6I-EPbM-UtrXOXrqH9oBarnbwOpd-eFYEU/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft for this doc is finished and can now be reviewed.

**Comment by carolinan** [comment]
The difficult part here is how to describe the difference between a synced and not synced pattern, -and decided what to call the not synced patterns. Lets make sure the name or phrase is the same in the editor UI, developer documentation, and user documentation (I did not look it up).

Parts of the description and screenshots are only for block themes. The pattern creation is not the same in classic themes and block themes.
It probably will be the same from WordPress 6.6.

**Comment by justintadlock** [comment]
Thanks for the review. I've went through and addressed each of the points.

> The difficult part here is how to describe the difference between a synced and not synced pattern, -and decided what to call the not synced patterns. Lets make sure the name or phrase is the same in the editor UI, developer documentation, and user documentation (I did not look it up).

I changed this to **Synced** and **Not synced**, which is what is shown in the UI for WordPress 6.5.

It does bug me when describing this because the English word for "not synced" should be "unsynced." But it's best to go with what's in the UI for consistency.

**Comment by kafleg** [comment]
What about mentioning copying patterns from patterns directory and paste in the post/page or site editor?

**Comment by justintadlock** [comment]
> What about mentioning copying patterns from patterns directory and paste in the post/page or site editor?

I'd think that's more of a user feature and not specifically relevant to developing a theme. 

The theme method of integrating with the Pattern Directory would be to include them in `theme.json`, which is covered here: https://developer.wordpress.org/themes/global-settings-and-styles/patterns/

**Comment by kafleg** [comment]
Looks good.

**Comment by justintadlock** [comment]
The draft for this has been moved to the handbook: https://developer.wordpress.org/wp-admin/post.php?post=153618&action=edit

**Comment by justintadlock** [comment]
This doc is now live: https://developer.wordpress.org/themes/patterns/introduction-to-patterns/
