### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Registering Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1479]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Registering Patterns" under the "Patterns" chapter.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1MQ1QBWXnkAMFcp_JnrW9nz7iov-X-BNlJ_Wq6wKsgr8/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this doc is finished and ready for review.

**Comment by kafleg** [comment]
Looks good.

As this is technical, that you for recommending the first method as recommended one. 

I added a small comment in the doc.

**Comment by justintadlock** [comment]
This is now live in the handbook: https://developer.wordpress.org/themes/patterns/registering-patterns/
