### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Using PHP in Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1480]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Using PHP in Patterns" under the "Patterns" chapter.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1b4K4w1GyW09Z-yJpwAODT3mPqQCDAG3H7Xr3kgqyWyg/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this doc is now ready for review.

**Comment by carolinan** [comment]
This s great, educational and detailed. It needs some minor cleanup of the text domains in the larger code examples.

I am not sure that unregistering patterns should be included in this document.

**Comment by justintadlock** [comment]
> This s great, educational and detailed. It needs some minor cleanup of the text domains in the larger code examples.

Thanks. Cleaned up the missing textdomain.

> I am not sure that unregistering patterns should be included in this document.

Removed that section from the notes. Just a copy/paste fail into the wrong doc. :)

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published in the handbook: https://developer.wordpress.org/themes/patterns/using-php-in-patterns/
