### ISSUE TITLE
[Devhub] Spelling error

### ISSUE THREAD

**Issue by AbudiMutamba** [WordPress/Documentation-Issue-Tracker#1487]
## Issue Description

A simple spelling error
## URL of the Page with the Issue

https://developer.wordpress.org/plugins/hooks/custom-hooks/
## Section of Page with the issue

Extensible Filter: Custom Post Type (Third paragraph)
## Why is this a problem?

'Also note that the retuned value is used directly by'
'retuned' is spelled wrong
## Suggested Fix

change it to 'returned'

**Comment by flexseth** [comment]
Fixed in a pull request, waiting for merge. 

- https://github.com/WordPress/developer-plugins-handbook/pull/6

@AbudiMutamba thanks for reporting! I will let you know when it is resolved in the docs and it's safe to close the issue.

**Comment by flexseth** [comment]
2/2 simple WordPress.org/plugins docs updated - this was entirely too complicated
