### ISSUE TITLE
[DevHub] Repeated Words 

### ISSUE THREAD

**Issue by AbudiMutamba** [WordPress/Documentation-Issue-Tracker#1488]
## Issue Description

Repeat of words in a sentence.
## URL of the Page with the Issue

https://developer.wordpress.org/plugins/hooks/custom-hooks/
## Section of Page with the issue

Extensible Filter: Custom Post Type  (third paragraph)
## Why is this a problem?

'Note that filters filters take data,'
'filters word is repeated twice.'
## Suggested Fix

Remove one filters word from the sentence.

**Comment by flexseth** [comment]
Gonna give this a try @anandau, @estelaris. I have the DevHub environment working locally but still not 100% sure on how to push changes upstream to contributors. Will report back

**Comment by flexseth** [comment]
This is fixed via PR
- https://github.com/WordPress/developer-plugins-handbook/pull/6

Waiting for approval and merge, then it will be OK to close the issue. 
Will ping back when it's good to go.

Thank you for reporting, @AbudiMutamba. 

@estelaris - I figured out how to access some of the DevHub resources!

**Comment by flexseth** [comment]
@AbudiMutamba thank you for bringing up these changes, docs are updated (1/2)
