### ISSUE TITLE
[HelpHub] More

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#149]
Article: https://wordpress.org/support/article/more-block/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/HGHAQs7r/68-more

**Comment by telmott** [comment]
I'm working on this one 👍

**Comment by telmott** [comment]
Here are the new screenshots
<img width="702" alt="01-more-block-result" src="https://user-images.githubusercontent.com/18164005/171618471-b03cd743-ba3d-4ce8-809c-ef12e50171e6.png">
<img width="279" alt="04-more-block-settings" src="https://user-images.githubusercontent.com/18164005/171618492-abeb4d10-87e8-460e-87e5-674664cea1e7.png">
<img width="711" alt="03-more-block-block" src="https://user-images.githubusercontent.com/18164005/171618497-b66306af-41a1-4387-be9f-dd0c7d70aaaf.png">
<img width="368" alt="02-more-block-insert" src="https://user-images.githubusercontent.com/18164005/171618500-559533c5-110b-443e-ba62-0b48e9f3be52.png">

**Comment by telmott** [comment]
@zzap here are the new screenshots. I just want to point out the on the posts page the "READ MORE" doesn't appear (first screenshot)

**Comment by telmott** [comment]
usage video

https://user-images.githubusercontent.com/18164005/171633770-7db03a8f-574b-44f0-889c-c4af1c4fc99f.mp4
