### ISSUE TITLE
[6.5 HelpHub] The Font Library

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#1490]
Draft:  https://docs.google.com/document/d/17tlcTMhp5Z7XWeoZA9p559Q0GQJt06jpehMOI-_0D3o/edit?usp=sharing

### Update for 6.5 

- [x] Change default fonts
- [x] Connect Google fonts
- [x] Add user own fonts
- [x] Remove fonts

### General

- [ ] Make sure all screenshots are relevant to the latest version
- [ ]  Make sure videos, if any, are up to date
- [ ]  Add ALT tags for the images
- [ ]  Make sure the headings are in sentence case
- [ ]  Convert all reusable blocks to a ‘regular block’.
- [ ]  Update the changelog at the end of the article

**Comment by Brianmitchtay** [comment]
Hi I'm at WCUS and working on getting this shipped for contributor day! 🥳

@Leonardus-Nugraha does this fall under your purview as a block editor doc since the font library lives in the styles panel?

**Comment by Brianmitchtay** [comment]
@estelaris The doc is ready for review/approval! 

https://docs.google.com/document/d/17tlcTMhp5Z7XWeoZA9p559Q0GQJt06jpehMOI-_0D3o/edit#heading=h.t4kfkeet2omp

Please let me know if you have any suggestions or questions!

**Comment by estelaris** [comment]
Article posted https://wordpress.org/documentation/article/the-font-library/
