### ISSUE TITLE
Missing "blueprints" directory in the blueprint JSON file path

### ISSUE THREAD

**Issue by vladutilie** [WordPress/Documentation-Issue-Tracker#1495]
## Issue Description
Hello! I have noticed the "blueprints" directory is missing from the `blueprint.json` file path in the last section of the page.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints

## Section of Page with the issue
[Committing a Blueprint to Subversion](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#committing-a-blueprint-to-subversion)

## Why is this a problem?
If the `blueprint.json` is not in the `blueprint` directory, it will not work.

## Suggested Fix
The `blueprint.json` file path should be `assets/blueprints/blueprint.json` as described in the docs above.

Regards,
Vlad

**Comment by sc0ttkclark** [comment]
This one hit me, I read through everything and finally realized some other area and another page referenced a "blueprints" directory of the "assets" directory and I put all the pieces together finally!

**Comment by flexseth** [comment]
> This one hit me, I read through everything and finally realized some other area and another page referenced a "blueprints" directory of the "assets" directory and I put all the pieces together finally!

Nice, @sc0ttkclark!

We're working on an overhaul of the documentation now. 
- https://github.com/WordPress/wordpress-playground/issues/772

**Comment by sc0ttkclark** [comment]
If it's quick and possible, it would be great to just tweak that text at the bottom to prevent people messing anything up.

**Comment by flexseth** [comment]
If you can provide links to the different pages and a text proposal for the
update, that will make it easier to track down and fix the docs!

If directly relative to this issue, right here is fine.

Seth Miller
***@***.***
(803) 292-4378

LinkedIn: http://linkedin.com/in/flexseth

Flex Perception :: http://flexperception.com

*Image management, media & design with finesse.*

**Comment by sc0ttkclark** [comment]
As noted in the original issue summary here, it's this one and I've linked it to the heading the wrong path reference is under: https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#committing-a-blueprint-to-subversion

`/assets/blueprint.json` should say `/assets/blueprints/blueprint.json`

**Comment by flexseth** [comment]
> `/assets/blueprint.json` should say `/assets/blueprints/blueprint.json`

I see, I made a PR about this, but it was bundled with another PR because I'm a newb.
 - https://github.com/WordPress/developer-plugins-handbook/pull/6/

Tuesday we have a docs meeting, should be able to get some eyes on it. 

/review

**Comment by sc0ttkclark** [comment]
Awesome, thank you so much @flexseth -- hopefully in the mean time people will find their way to the right path without losing too much time in SVN land trying to figure out why it's not working like I did 😂

**Comment by flexseth** [comment]
@sc0ttkclark this has been updated via PR, but isn't updated yet. It's possible there's some SVN magic that needs to happen for it to be updated on the Plugins Handbook. Asked some questions, we'll see what's up

**Comment by flexseth** [comment]
Merged, if you all run into any other issues please raise them in either
- [Documentation Issues Tracker repo](https://github.com/WordPress/Documentation-Issue-Tracker/issues)
- or the [Playground issues](https://github.com/WordPress/wordpress-playground/issues)

Thanks again for reporting, this was a critically important update!
