### ISSUE TITLE
[6.5 HelpHub] Box shadows

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#1498]
### Update for 6.5

- [x] Available on more blocks (Buttons, Column, Columns, and Images)
- [x] Box shadow support is now available on individual blocks when box shadow support is enabled under a Shadow panel in block settings under “Border & Shadow” or just “Shadow” if only shadows are enabled, making it easier to find and use.

 
### General
 
- [x] Make sure all screenshots are relevant to the latest version
- [x]  Make sure videos, if any, are up to date
- [x]  Add ALT tags for the images
- [x]  Make sure the headings are in sentence case
- [x]  Convert all reusable blocks to a ‘regular block’.
- [x]  Update the changelog at the end of the article

**Comment by atachibana** [comment]
Based on this page "Border Settings overview":
https://wordpress.org/documentation/article/border-settings-overview/
shadow option will be added. Also, the cateogory will be fixed to "Block Editor" from "Appearance".

# Border & Shadow Settinsgs

You can use the border and shadow settings in your block to set a visible border and/or shadow on specific blocks. ...
The border and shadow settings are ...

## How to access border and shoadow settings
(new image. See below)
The border and shadow settings can be ...

In the Border & Shadow section, the shadow option may be hidden. ... to explore all the border and shadow settings ...

## Type of settings
Each supported block comes with different border and shadow settings.

### Shadow
The shadow setting will give your block a shadow effect behind it.
Tips: If you don't see the shadow option in the Border & Shadow section, click the three vertical dots to the right of the section header and select Shadow option.
Click Drop shadow and select shadow effects.
(image. See below)
![Image](https://github.com/user-attachments/assets/1de02e39-e068-4938-ad77-5be61db5b4d8)
![Image](https://github.com/user-attachments/assets/702c379c-535f-4475-8c14-70fa6f030277)

**Comment by atachibana** [comment]
Done.
https://wordpress.org/documentation/article/border-settings-overview/
