### ISSUE TITLE
Outdated HTTP API link

### ISSUE THREAD

**Issue by atachibana** [WordPress/Documentation-Issue-Tracker#15]
This issue was moved from [HelpHub issue #307](https://github.com/WordPress/HelpHub/issues/307) by [GeoJunkie](https://github.com/GeoJunkie) and [ma0sm](https://github.com/ma0sm).

## Issue Description

In the [HTTP API](https://developer.wordpress.org/apis/handbook/http/) doc, the link to `Basic Authentication with the WordPress HTTP API` is outdated. [Current linked document](http://lud.icro.us/wordpress-http-api-basicauth/) was 301 redirected to [the document's current location](https://johnblackbourn.com/wordpress-http-api-basicauth/), but that 301 is gone now and the link is broken. ([Source: archives.org](https://web.archive.org/web/20170208004823/http://lud.icro.us/wordpress-http-api-basicauth/)).

## **Context**

Found this while learning the HTTP API, and it took some work to locate.

The link should be changed from `http://lud.icro.us/wordpress-http-api-basicauth/` to `https://johnblackbourn.com/wordpress-http-api-basicauth/`

## **Steps to reproduce:**

1. Go to  [External References section of HTTP API documentation](https://developer.wordpress.org/apis/handbook/http/#external-references) 
2. Click on the `Basic Authentication with the WordPress HTTP API` link

## **Expected Result:**
Read about basic documentation with the WordPress API
## **Actual Result:**

Server Not Found

<hr />

## 2. Comment by [ma0sm](https://github.com/ma0sm).

https://developer.wordpress.org/apis/handbook/http/#external-references doesn't seem to be a valid URL, nor is the one to the HTTP API doc (https://developer.wordpress.org/apis/handbook/http/)

**Comment by stevenlin-x** [comment]
As labeled, there are two issues with this ticket.

1.)
The linked text "In the HTTP API doc" in the issue text body above doesn't work.

It should be:
https://developer.wordpress.org/apis/

2.)
When you visit the "Common APIs Handbook" URL above and examine the pages, there are no text named "Basic Authentication with the WordPress HTTP API" as mentioned in "Issue Description" of the issue text body above.

The is also no "External References section of HTTP API documentation" as mentioned in "Steps to reproduce:" of the issue text body above.
