### ISSUE TITLE
[HelpHub] Page Break

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#150]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/page-break-block/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [x] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/s0QlQbk6/76-page-break

**Comment by marconmartins** [comment]
I'm checking this one.

**Comment by marconmartins** [comment]
<img width="552" alt="controls" src="https://user-images.githubusercontent.com/5478039/171639713-7d61e958-d269-4051-8d3f-1f5234f49c3c.png">

https://user-images.githubusercontent.com/5478039/171639717-40c88ae3-6e4c-4994-b8fc-355893b92053.mp4

<img width="712" alt="front-pagination" src="https://user-images.githubusercontent.com/5478039/171639818-60c74799-9901-48b4-8167-861f0794cec4.png">
<img width="274" alt="settings" src="https://user-images.githubusercontent.com/5478039/171639821-1df07250-fe04-436e-9646-4837eec2ed2e.png">
<img width="264" alt="slash-add" src="https://user-images.githubusercontent.com/5478039/171639826-7f6da7fe-0337-43b3-863d-1ea0f261667c.png">

**Comment by colorful-tones** [comment]
This is ready for review.

**Comment by zzap** [comment]
@femkreations all yours :point_up:

**Comment by femkreations** [comment]
Thank you @marconmartins for the screenshots. I have updated the page with them.

https://wordpress.org/support/article/page-break-block/
