### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Block Type Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1505]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating a new page titled "Block Type Patterns" under the "Patterns" chapter.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1xijKjfcMMOZLRYSpyTn1PdYEPYprK5HNCQguQ68PUS4/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft for this is now finished and can be reviewed.

**Comment by kafleg** [comment]
Looks good to me.

**Comment by kafleg** [comment]
Looks good to me. 

Thank you

**Comment by justintadlock** [comment]
Published in the handbook: https://developer.wordpress.org/themes/patterns/block-type-patterns/
