### ISSUE TITLE
Broken link on https://make.wordpress.org/mobile/

### ISSUE THREAD

**Issue by flexseth** [WordPress/Documentation-Issue-Tracker#1507]
[https://meta.trac.wordpress.org/ticket/7528](https://meta.trac.wordpress.org/ticket/7528)

Ticket has screenshot as to where the broken link is, for quick reference

## Issue Description
In the sidebar => "WordPress Apps => How Do I Start Contributing?" section:
"iOS app" text is linked to 404 page.

## URL of the Page with the Issue
[](https://make.wordpress.org/mobile/)

## Section of Page with the issue
In the right sidebar! 
iOS App link

## Why is this a problem?
It's broken.

## Suggested Fix
Link to: https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/README.md

**Comment by dd32** [comment]
I've updated the links in the Text widget to point to the GitHub repos directly, rather than the individual files.

Content on Make.WordPress.org/* is generally handled by the team responsible directly, rather than through the docs channels.

**Comment by flexseth** [comment]
> Content on Make.WordPress.org/* is generally handled by the team responsible directly, rather than through the docs channels.

So report this through Trac, correct? 

Coming up with a document for where the info should go
