### ISSUE TITLE
[HelpHub] Separator

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#151]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/separator-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/7wARjcp3/69-separator

**Comment by telmott** [comment]
@zzap Here are the new 6.0 updated screenshots and videos:

https://user-images.githubusercontent.com/18164005/171654064-16561032-058b-4434-883c-8c54a47e03f6.mp4

<img width="419" alt="01-separator-add" src="https://user-images.githubusercontent.com/18164005/171654172-0eb91e47-4276-4e0e-86cc-c7a9c572b4f1.png">
![separator-advanced](https://user-images.githubusercontent.com/18164005/171654174-b1737f9d-e23b-4f60-99e5-b293698cfd30.gif)
![separator-colors](https://user-images.githubusercontent.com/18164005/171654244-aff16dd1-d976-4e2e-b99f-c32dbf734e8a.gif)
<img width="254" alt="separator-interface" src="https://user-images.githubusercontent.com/18164005/171654325-3831afa2-c782-428f-884c-1ae7fab164ca.png">
<img width="277" alt="separator-settings" src="https://user-images.githubusercontent.com/18164005/171654329-8cdc0943-1ee6-45af-90f4-8406601e2d24.png">
<img width="279" alt="separator-styles" src="https://user-images.githubusercontent.com/18164005/171654332-5ee10afb-ce3d-4bb3-9ae9-ba8a3a14f67e.png">

**Comment by colorful-tones** [comment]
This is ready for review.

**Comment by zzap** [comment]
@femkreations another one for you :raised_hands:

**Comment by femkreations** [comment]
Looks great. Thank you @telmott for the screenshots and videos. The page has been updated with them.
https://wordpress.org/support/article/separator-block/
