### ISSUE TITLE
Inline code formatting broken on the front end

### ISSUE THREAD

**Issue by srikat** [WordPress/Documentation-Issue-Tracker#1516]
## Issue Description
The inline code where strings are enclosed in backticks is broken on the following URLs. The markup seems to be fine.

## URL of the Page with the Issue
https://developer.wordpress.org/rest-api/key-concepts/
https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#links

![CleanShot 2024-03-25 at 5  16 48@2x](https://github.com/WordPress/Documentation-Issue-Tracker/assets/2188656/f50f9e94-1408-4e74-a366-53728f77f614)

![CleanShot 2024-03-25 at 5  15 20@2x](https://github.com/WordPress/Documentation-Issue-Tracker/assets/2188656/82d27355-65f3-4277-8637-388211177e48)

**Comment by srikat** [comment]
Found another report that's most likely due to the same reason here: https://github.com/WP-API/docs/issues/150.

**Comment by flexseth** [comment]
Thanks for reporting @srikat - I'll take a look at this ASAP

If you see anything else while you're poking through the new developer docs, feel free to use this same ticket.

**Comment by flexseth** [comment]
> ## Issue Description
> The inline code where strings are enclosed in backticks is broken on the following URLs. The markup seems to be fine.
> 
> ## URL of the Page with the Issue
> https://developer.wordpress.org/rest-api/key-concepts/ https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#links
> 
> ![CleanShot 2024-03-25 at 5  16 48@2x](https://private-user-images.githubusercontent.com/2188656/316413730-f50f9e94-1408-4e74-a366-53728f77f614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTI0OTcsIm5iZiI6MTcxMTQxMjE5NywicGF0aCI6Ii8yMTg4NjU2LzMxNjQxMzczMC1mNTBmOWU5NC0xNDA4LTRlNzQtYTM2Ni01MzcyOGY3N2Y2MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDAxNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNiYmFhMThjZWIxZGM0YzBjZDQyMTA5MmE0MDU3YjFkYzA1Y2QwNWUzNTQ5Y2NlYWQ5ZDFlNWMzZDhhMzRiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ObZBbcix3O0p2MDzCO9ccMi_uXzQRek90XTJDKQ29ew)
> 
> ![CleanShot 2024-03-25 at 5  15 20@2x](https://private-user-images.githubusercontent.com/2188656/316413772-82d27355-65f3-4277-8637-388211177e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTI0OTcsIm5iZiI6MTcxMTQxMjE5NywicGF0aCI6Ii8yMTg4NjU2LzMxNjQxMzc3Mi04MmQyNzM1NS02NWYzLTQyNzctODYzNy0zODgyMTExNzdlNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDAxNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjUzOTRkYTBmMjY4M2JiZGI2ZWQxOTBkMGVhZTViMGFlZDY1ZWUwZTQ0ZDFjYjQ5OGUyODJjYWM4YTFkN2FjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g-cd5Xwo5yFV76MLfeodGa49z8wTTR46ThqjI-MS4mI)

Possible fix on this PR - need @zzap to /review
- https://github.com/WP-API/docs/pull/177

**Comment by flexseth** [comment]
> Found another report that's most likely due to the same reason here: [WP-API/docs#150](https://github.com/WP-API/docs/issues/150).

Have this on the docket to discuss tomorrow, @srikat

**Comment by flexseth** [comment]
@srikat - Fixed 
- https://github.com/WP-API/docs/pull/178

Thanks for bringing this up. There's some more formatting work needed over there that I'm going to take a look at next week.

**Comment by flexseth** [comment]
Bah, still a little formatting needed

**Comment by flexseth** [comment]
@srikat - fixed

- https://github.com/WP-API/docs/pull/182
