### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Locking Blocks in Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1518]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating a new page titled "Locking Blocks in Patterns" under the "Patterns" chapter.

The content for the new page will be drafted in a Google Doc: https://docs.google.com/document/d/1CJNY8w8Q5EJdP0dFCN5oTgq7NE-FtLLgCqohxJnaVZc/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft for this is now ready for review.

**Comment by kafleg** [comment]
Looks good.

Thank you

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/patterns/patterns-and-block-locking/
