### ISSUE TITLE
[Theme Handbook Overhaul] Patterns > Chapter Landing Page

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1519]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating the chapter landing page under Chapter 5: Patterns.

This document is already drafted and ready for review in this Google Doc: https://docs.google.com/document/d/1CIjdBwMsPtFBjyXU7FPZRaXGX1cyR740ajjEKTa4ly4/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this is now ready for review.

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
The draft for this doc has been moved to the handbook: https://developer.wordpress.org/wp-admin/post.php?post=153616&action=edit

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/patterns/
