### ISSUE TITLE
[HelpHub] Columns Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#152]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/columns-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/njLu3C14/9-columns-block

**Comment by femkreations** [comment]
Adding tasks to 6.0 [#272 ](https://github.com/WordPress/Documentation-Issue-Tracker/issues/272) and closing this issue
