### ISSUE TITLE
[Theme Handbook Overhaul] Publish Chapter: Patterns

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#1520]
Now that the Patterns chapter is fully drafted, it is time to begin moving this new chapter to the Theme Handbook.

This is a sub-tracking issue for https://github.com/WordPress/Documentation-Issue-Tracker/issues/816. I've created this ticket so that it's easier to manage and coordinate the process for this new chapter that is being added. We can also use this to add any notes for things we need to know as we move through the larger Theme Handbook Overhaul project.

## Docs to Publish

**Docs to publish under the Patterns chapter:**

- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1519
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1478
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1479
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1480
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1483
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1486
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1505
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1518

## Older Content to Update

This will replace a single document that is currently published. This page needs to be redirected to the new top-level chapter landing page:

- [ ] [Features: Block Patterns](https://developer.wordpress.org/themes/features/block-patterns/)

**Comment by justintadlock** [comment]
All of the articles for this chapter have been reviewed, so I'll start the process of moving this chapter to the handbook.

**Comment by kafleg** [comment]
Thank you for the hard work!

**Comment by justintadlock** [comment]
This new chapter has now been published in the handbook! 🎉 https://developer.wordpress.org/themes/patterns/

Thank you to both @poena and @kafleg for their work reviewing. 

Let's leave this ticket open for a couple of weeks for bug reporting.

**Comment by justintadlock** [comment]
I have also archived the older Features > Block Patterns page until I can get someone with access to redirect it to the new chapter: https://developer.wordpress.org/themes/features/block-patterns/
