### ISSUE TITLE
"Previews and Blueprints" — broken sample blueprint.json

### ISSUE THREAD

**Issue by squelchdesign** [WordPress/Documentation-Issue-Tracker#1523]
## Issue Description
On the "Previews and Blueprints" page the final sample `blueprint.json` has formatting issues and stops abruptly.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#blueprints

## Section of Page with the issue
"Blueprints" section. The first sample is fine, the second is broken.

## Why is this a problem?
Developers need to be able to see the sort of things they can achieve with `blueprint.json`. The most complete example on the page doesn't work, so they are missing out on valuable information.

## Suggested Fix
It looks like this is just a formatting issue which, once fixed, will make the sample readable again.

**Comment by squelchdesign** [comment]
That page has other issues as well… there's clearly an image missing from the section [Enabling Plugin Previews](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#enabling-plugin-previews):

> If a valid blueprint.json file is present, then the Preview button will be present for plugin committers only. In which case it will look like this:
> 
> It’s called Test Preview because that’s why it’s there: to allow plugin committers to test their plugin in the Playground environment and decide whether or not to make it easily available to the public.

(Note: no image between the paragraphs)

And, more importantly, there's conflicting information on where to upload `blueprint.json` to. The [Blueprints](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#blueprints) section says:

> The blueprint for your plugin should be committed to the assets folder with subversion as assets/blueprints/blueprint.json. Initially only the one blueprint file is supported, but we expect to allow multiple in future.

But the [Committing a Blueprint to Subversion](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#committing-a-blueprint-to-subversion) section says:

> You must commit your blueprint.json file to your plugin’s assets folder, named like this:
> /assets/blueprint.json

I followed the instructions in the final section and it didn't work, wp.org ignored the change.

Do I need to raise these as separate issues?

**Comment by flexseth** [comment]
> On the "Previews and Blueprints" page the final sample `blueprint.json` has formatting issues and stops abruptly.

There is a PR ready for this, I'm working with the Playground architect now on it.

---

> The blueprint for your plugin should be committed to the assets folder with subversion as assets/blueprints/blueprint.json. Initially only the one blueprint file is supported, but we expect to allow multiple in future.

This is correct, and addressed in the PR 

---

> there's clearly an image missing from the section [Enabling Plugin Previews](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/#enabling-plugin-previews)

Please understand this is very early stages. The image is on the documentation, just not on the WP.org Plugins Handbook yet. 

Please check the [Playground GitHub repo ](https://github.com/WordPress/wordpress-playground) for an issue and report the issue over there if no one else has already. 

Thank you for bringing up the missing screenshot. That does need to be addressed. 

Best/Seth

**Comment by flexseth** [comment]
> Do I need to raise these as separate issues?
- https://github.com/WordPress/wordpress-playground/issues/1172

Opened a ticket for that issue.

Marking this as resolved, the docs have been updated.

**Comment by flexseth** [comment]
Apologies, this isn't fixed yet. Adding to triage for next week.

**Comment by squelchdesign** [comment]
> > Do I need to raise these as separate issues?
> 
>     * [Missing WP.org/plugins preview screenshot wordpress-playground#1172](https://github.com/WordPress/wordpress-playground/issues/1172)
> 
> 
> Opened a ticket for that issue.

Nice one, thanks!
