### ISSUE TITLE
Support Handbook menu says "Support forums" but redirects to /documentation

### ISSUE THREAD

**Issue by flexseth** [WordPress/Documentation-Issue-Tracker#1525]
## Issue Description
"Support forums text" should read "Documentation"  ?
[Reported upstream from Meta Trac](https://meta.trac.wordpress.org/ticket/7537)

## URL of the Page with the Issue
https://make.wordpress.org/support/handbook/

## Section of Page with the issue
Main nav, top right
![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/3792502/74a8ea7d-f491-48aa-85ee-93169ff2be5e)

## Why is this a problem?
Possibly misleading or the incorrect link

## Suggested Fix
Clarify text or link to End-User Support (HelpHub) ?

**Comment by StevenDufresne** [comment]
I arrived here via the forums and would probably like a route back. We should consider updating this to forums instead of naming it to documentation.

**Comment by flexseth** [comment]
> We should consider updating this to forums instead of renaming it to documentation.

Through GitHub it's not possible to track how someone gets here, however, we could possibly improve the welcome message or README to better direct traffic. Better flows are in the works for this! Stay tuned.

**Comment by StevenDufresne** [comment]
Understood. What about having both links? [ Documentation, Forums, Handbook ]

**Comment by StevenDufresne** [comment]
I updated the link to point to forums for now. We can revisit this later.
