### ISSUE TITLE
spelling mistake on documentation

### ISSUE THREAD

**Issue by nupiyad68** [WordPress/Documentation-Issue-Tracker#1528]
## Issue Description

There is a spelling mistake on Theme development handbook. The word "Article" spelled as "Articleh"

## URL of the Page with the Issue

https://developer.wordpress.org/themes/basics/conditional-tags/#helpful-404-page

## Section of Page with the issue

The 7th word on  helpful-404-page section

## Suggested Fix

"articleh" -> "article"

**Comment by justintadlock** [comment]
Updated the misspelled word. Thanks for reporting, @nupiyad68.
