### ISSUE TITLE
[HelpHub] Latest Comments

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#153]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/latest-comments-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/fh2RcIEp/80-latest-comments

**Comment by samxmunoz** [comment]
I'll take this one. 👋🏼

**Comment by samxmunoz** [comment]
@colorful-tones yes I am still working on this one :)

**Comment by samxmunoz** [comment]
Here are the screenshots I will be adding & updating. (fyi @colorful-tones & @zzap)

**Other Updates:**

- I will also be updating some of the information as it is outdated (especially around alignment) and copying from the **[WordPress.tv Doc](https://wordpress.org/support/article/wordpress-tv-embed-block/)**
- There is no changelog so I will add that to this doc

<img width="684" alt="Latest Comments HelpHub SS - 1" src="https://user-images.githubusercontent.com/43501707/181227857-b8d8dcff-9ff3-43ac-8075-fbdbcdee76a0.png">
<img width="316" alt="Latest Comments HelpHub SS - 2" src="https://user-images.githubusercontent.com/43501707/181227858-d9134119-7fd1-40b1-b074-27f851bfc363.png">
<img width="666" alt="Latest Comments HelpHub SS - 3" src="https://user-images.githubusercontent.com/43501707/181227860-bb158654-2314-40eb-9cea-4afb137ca32b.png">
<img width="377" alt="Latest Comments HelpHub SS - 4" src="https://user-images.githubusercontent.com/43501707/181227862-907232e4-7fc5-4d3f-a7dd-28ef62717d5b.png">
<img width="356" alt="Latest Comments HelpHub SS - 5" src="https://user-images.githubusercontent.com/43501707/181227863-79de4056-afd4-45df-96d3-93eb228fff94.png">
<img width="332" alt="Latest Comments HelpHub SS - 6" src="https://user-images.githubusercontent.com/43501707/181227865-65791eb0-e8b9-4a59-912c-d0987c16d246.png">

**Comment by samxmunoz** [comment]
This has been updated & is ready to be closed - @colorful-tones care to do the honors?

https://wordpress.org/support/article/latest-comments-block

I've been speaking with @femkreations and @bph about templates & patterns for docs to help make the docs more consistent across the board - however, we're not ready with that yet - so the focus of this update was primarily on content updates (screenshots, changelog and a few smaller additions).

**Comment by colorful-tones** [comment]
closing this out. Thanks @samxmunoz !
