### ISSUE TITLE
Broken link on https://developer.wordpress.org/apis/wp-config-php/

### ISSUE THREAD

**Issue by nhrrob** [WordPress/Documentation-Issue-Tracker#1530]
## Issue Description

[Ryan Boren – SSL and Cookies in WordPress 2.6](http://boren.nu/archives/2008/07/14/ssl-and-cookies-in-wordpress-26/) 
takes to 404 page.

## URL of the Page with the Issue

https://developer.wordpress.org/apis/wp-config-php/

## Section of Page with the issue

[Security Keys](https://developer.wordpress.org/apis/wp-config-php/#security-keys)

## Why is this a problem?

Takes to 404 page

## Suggested Fix

Remove the link if it is not available

**Comment by zzap** [comment]
Fixed. Thank you
