### ISSUE TITLE
Broken link on blocks list documentation for Post Modified Date block

### ISSUE THREAD

**Issue by andreawetzel** [WordPress/Documentation-Issue-Tracker#1532]
## Issue Description

On the [blocks list documentation](https://wordpress.org/documentation/article/blocks-list/), the link to the "Post Modified Date" page is broken

## URL of the Page with the Issue

https://wordpress.org/documentation/article/blocks-list/

## Section of Page with the issue

Theme Blocks: https://wordpress.org/documentation/article/blocks-list/#theme-blocks 

## Why is this a problem?

Navigation to this block is broken

## Suggested Fix

Currently the link is `https://wordpress.org/documentation/article/post-modified-date-block/(opens%20in%20a%20new%20tab)` and it should be `https://wordpress.org/documentation/article/post-modified-date-block/`

**Comment by samxmunoz** [comment]
@zzap - this is updated & revision is scheduled for May 7, 2024 @ 12pm.

**Comment by estelaris** [comment]
reviewed
