### ISSUE TITLE
[HelpHub] Facebook embed block documentation has broken images

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/Documentation-Issue-Tracker#1534]
## Issue Description
@DanSoschin [reported on Core Trac](https://core.trac.wordpress.org/ticket/60873) that images are missing on the Facebook embed article.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/facebook-embed/

## Section of Page with the issue
multiple sections

## Suggested Fix

The block was discontinued in WordPress 5.6, but if the images and/or other content are worth keeping:

1. Upload the ten missing images from the [WayBack Machine archive](https://web.archive.org/web/20230214124502/https://wordpress.org/documentation/article/facebook-embed/), and use the text below as the alternative text.
2. For the other five of these images, which load properly, make sure Facebook is capitalized in the alternative text.

- [Facebook Embed block](https://web.archive.org/web/20230214124502im_/https://lh6.googleusercontent.com/Gqzis6hWvLioIzUBcGwMeOPy4ZWWthLxOuIJHbqBBvW4oeat6bChCFi-YbNm293tvVbv58MCUzsx7uUG2yRKQzN19jpxAudnd-gTpeWwTWe4SReloeCON4Vztf7XpGTo-8bYymr2gic9ab68kbbZ-4qSz-7KqjGv8eWCkwBye0LJrLcszm1V8nRbeA)
- [Copy the preferred link from Facebook post](https://web.archive.org/web/20230214124502im_/https://lh3.googleusercontent.com/ove5ZH-wF7o_IZPlUwdppZCwBOY2aWtKSzxkwFV9M3XAsXyRSwnoxI4a9vqCFpWpJeMvanFNRlC2vdPdt3aFfJXUYkRbGyN7tz96KUVSCy5Bvhwoo5Q7MhaxmbyKY3EHS12qKaaZsYuVCjWcs_9O5bUkav3inGvbBH-eo3hvoN9VAMkplDvPSxKbVg)
- [Inserting a Facebook embed block using the keyboard shortcut.](https://web.archive.org/web/20230214124502im_/https://lh6.googleusercontent.com/NVbeTBm2dKeZTqB3c0TyZ98kf3w66XhI5LE-KLEEPrEE1oHHh0vrTcv4C-taoX3ClZjSgOyEPA5zYUire6ap_NPCUg3axLDJ8bCjm6tt3m61fcrmb-fkrDhx8Ruz_Fzgv_flOiQnTDRQ4mnfyVxrBn3juW8z55DHCnl8kZuWlSjTpCylDlN9Ajz9PQ)
- [Embed the post into the block.](https://web.archive.org/web/20230214124502im_/https://lh3.googleusercontent.com/OhCWpDlRadXSpkbW-B5_IpcD78gbLMUUF4N4aqKy0-eJCebh7Zn_CEaPILH7r2XuJx-xF28dYJVRMzFAqsnWCmZ95Nd9zex7pl0-LM1_mwuCfPuOUktVpCAhELtMSYMpxjruJZQ_FUnJH06hpoljBjVAjz3C5fTD_GXuanjN_KjOCbVGRWz4j_W9gQ)
- [The message “Embedded content from facebook.com can’t be previewed in the editor” when you embed a Facebook post.](https://web.archive.org/web/20230214124502im_/https://lh5.googleusercontent.com/CnL06OdDtRU3PjcccODEwSSxIJ8sGG0AdGlxhiXGGfq1aMZH3xEnU6Se2WXwwo8uRo0vhd8cSanRnxW2tkuel77m6f6WRFdvluYjDbfAYnrNNXY8bpiL5KbN1jAFotNwInIgQFS-Pw1alS7C2WJ5LUqHPYKCD5BcdfgMn9o8_nyEgrVL6Zy385bGMw)
- (already uploaded to wp.org) [Preview of the Facebook embed post.](https://web.archive.org/web/20230214124502im_/https://wordpress.org/documentation/files/2022/09/Screen-Shot-2022-09-16-at-10.49.15-AM-768x753.png)
- (already uploaded to wp.org) [Block toolbar for the Facebook embed block](https://web.archive.org/web/20230214124502im_/https://wordpress.org/documentation/files/2022/09/Screen-Shot-2022-09-16-at-10.51.37-AM-768x196.png)
- [Transform tool in the Facebook embed block toolbar](https://web.archive.org/web/20230214124502im_/https://lh3.googleusercontent.com/HXRJtWLRlKNC2zRbmepnTx1uRCYMJR4xhSnSNnKRB43pTNkwvWqEbDj9Ze9PeXIW8yit120ZXdELU8IS2TqYM0xCKl7vzt9ipW3iGIuiu6zeyEvCsysPYIJWHr7rfEtZuHxHKBRadwfsePqyx6exElnKWAZw41VW5raoLucGR97xalyDPfIayubMvA)
- [Block moving tools in the Facebook embed block toolbar](https://web.archive.org/web/20230214124502im_/https://lh3.googleusercontent.com/CTUJJssQx2Yd41iAqJQ8SeAA1vwanBzRDTo1NIyDzDoXELsMP2mK2jv0ahqPn_c1mFfN-r99wecjy0L1BrCK3-Fe4aDKT8iH41DIE05ozucQEoVIMkwV0idOkXIALDSUXkxY0SxiswH-kkzGe4ITBwDIgwK0UVI12qWQP2K5VdMLxrOWiK1kQ81YSw)
- [Change alignment in the Facebook embed block toolbar](https://web.archive.org/web/20230214124502im_/https://lh3.googleusercontent.com/Z_18tUeI4FOrbxz49PGDvnAIdxEUNpFdv4A86S8rE8JCd7PlP4dHdT8tN9N7Vizn6rJDHoFnQJba71bcBGDiDM0TIf67dyCbXm7xgAfVQ3eUAVzLUq6Z4PYrlUpKjuopoGPi1oY0IrdHnRlEkVRGg0WPlaxKI9VQr0B90aK2mGve383KZhqmf_JdYw)
- (already uploaded to wp.org) [More options in the Facebook embed block](https://web.archive.org/web/20230214124502im_/https://wordpress.org/documentation/files/2022/09/Screen-Shot-2022-09-16-at-10.59.04-AM-768x206.png)
- [How to show the block settings sidebar](https://web.archive.org/web/20230214124502im_/https://lh4.googleusercontent.com/iqWmlCThtUouUx0HwHKPN-LdIVSGb6GPETcuwieBPTj_c861GaTnPi4EGRQUfuw8ogkMhUoHcSQh246tykKLpQYePQ-iUepV3nCrystQyqaSyi5AWMidL_WzDnc6K6HZo4Z0419ai3EQCcDN-bN7ywruhrv-zlxYoPn8VbjUTSnST10x1p0uzfHbpQ)
- (already uploaded to wp.org) [Media settings turned off in the Facebook embed block](https://web.archive.org/web/20230214124502im_/https://wordpress.org/documentation/files/2020/04/Screen-Shot-2020-04-20-at-9.29.46-AM.png)
- (already uploaded to wp.org) [Media settings turned on in the Facebook embed block](https://web.archive.org/web/20230214124502im_/https://wordpress.org/documentation/files/2020/04/Screen-Shot-2020-04-20-at-9.29.55-AM.png)
- [Advanced option in the selected Block](https://web.archive.org/web/20230214124502im_/https://lh6.googleusercontent.com/HCaeEAd-xkijY3husAGN8FkRfOokz6h-mLa1vQoT11JIf366WEE4Y3jtoy6CTOJGTpBZELgZPdIewg2ug8pURV5XtFciGwLHJiNwleOvlGte5WnWTug0SYe4p-qBR54_8oR1NwHM)

**Comment by dapobabs9511** [comment]
https://wordpress.org/documentation/article/facebook-embed/

All broken images have been updated and the Facebook capitalization issue on the Alt texts has also been resolved.

**Comment by dapobabs9511** [comment]
@sabernhardt this task has been updated please review using the URL and close it accordingly

**Comment by sabernhardt** [comment]
Thanks for fixing the images! I'll close the issue.

The last image could still be added to the HelpHub site in case it becomes unavailable through Google later, but the image is not broken.
