### ISSUE TITLE
[HelpHub][6.5][screenshots]: First Steps with WordPress (Block Editor)

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#1537]
Article:  [<https://wordpress.org/documentation/article/...>](https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/)

## Task

Make sure all screenshots are relevant to the latest version. 

## Directions
- Compare existing screenshots (on the article link) to the actual interface in the latest WordPress version.
- Ensure you have the appropriate WordPress version and that new screenshots cover the same page area as the existing one.
- If something is different in the latest version, make a new screenshot.
- Upload new screenshots to the comment on this issue.
- Request review by stating in the comment that the issue is ready for review.

## Resources
1. You can set WordPress install in one click by visiting https://playground.wordpress.net/ or use InstaWP sandbox https://app.instawp.io/onboard
2. Read about updating screenshots - [Updating screenshots](https://make.wordpress.org/docs/handbook/get-involved/getting-started-at-a-contributor-day/good-first-issues/#updating-screenshots)
3. Watch the video on creating screenshots for the latest WordPress versions - [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

## Automation
- If you want, you can assign yourself to the issue and change the label for review by posting specific keywords in a comment. Read about our repo's automatisation [here](https://make.wordpress.org/docs/handbook/github-repository-and-projects/documentation-issue-tracker/#label-issues).

Thank you for contributing, have a cookie :cookie:

**Comment by estelaris** [comment]
Here is the link https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/

**Comment by CalolanC** [comment]
Hello again @estelaris. There are only 3 images that have small changes, compared with version 6.5.2.
Please /review and let me know if something is missing.

![7-Creating_a_post_tutorial](https://github.com/WordPress/Documentation-Issue-Tracker/assets/82057148/55fd593f-e477-479a-893d-495b84e6d67f)
![8-Creating_a_post](https://github.com/WordPress/Documentation-Issue-Tracker/assets/82057148/e87b562b-4522-4105-bb27-5f1c58d5d31e)
![9-Using_WordPress_plugins](https://github.com/WordPress/Documentation-Issue-Tracker/assets/82057148/80c74fb0-cd80-4b39-97af-117da23782de)

**Comment by zzap** [comment]
Article is updated, thank you @CalolanC :heart: :cookie:
