### ISSUE TITLE
Google Form Shortcode Not Displaying in Documentation

### ISSUE THREAD

**Issue by ikamal7** [WordPress/Documentation-Issue-Tracker#1539]
## Issue Description
The documentation page fails to display Google Form shortcode due to unsupported URL format.

## URL of the Page with the Issue
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/setting-up-your-wordcamp-theme/shortcode-embeds/

## Section of Page with the issue
Google Forms https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/setting-up-your-wordcamp-theme/shortcode-embeds/#google-forms

## Why is this a problem?
Because of unsupported URL.

## Suggested Fix
Correct google form URL it should be fix.

**Comment by estelaris** [comment]
@ikamal7 please report this issue on meta or the community team. You can read more about what this repository is about https://github.com/WordPress/Documentation-Issue-Tracker
