### ISSUE TITLE
[HelpHub] Categories

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#154]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/categories-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/npjZxKEl/79-categories

**Comment by evrpress** [comment]
Let me work on this

**Comment by evrpress** [comment]
Here are the new screenshots

### List of categories
![dev local_wp-admin_post php_post=13 action=edit](https://user-images.githubusercontent.com/881729/171645293-1e2bb75a-23a0-4bd3-927f-15f4845548dc.png)

### quickselect with /
<img width="250" alt="image" src="https://user-images.githubusercontent.com/881729/171645789-4860b79c-d94b-4740-ae8d-c2876ee6b37c.png">

### alignment options
<img  alt="image" src="https://user-images.githubusercontent.com/881729/171645989-37664b5b-98cc-42dc-a43f-4a4ca1527bf1.png">

### block settings
![dev local_wp-admin_post php_post=13 action=edit (2)](https://user-images.githubusercontent.com/881729/171647244-cc4fef5b-819e-45e5-89d1-c2e33acb6d34.png)


### Display as Dropdown
<img width="187" alt="image" src="https://user-images.githubusercontent.com/881729/171646403-5e1d5bc0-9d42-45a7-a91e-49e2ed525129.png">

### Show Hierarchy
![dev local_wp-admin_post-new php](https://user-images.githubusercontent.com/881729/171647777-2cce2e2a-a3ac-433e-83bb-436d68b3e820.png)

### Show Post Count
![dev local_wp-admin_post-new php (1)](https://user-images.githubusercontent.com/881729/171647939-ebeb8c27-7976-4c57-a037-cf7e45b633cd.png)


Let me know if this works

**Comment by colorful-tones** [comment]
This is ready for review. It just needs to be assigned and reviewed.

**Comment by femkreations** [comment]
Thank you @evrpress for the screen captures. I've updated the page with them https://wordpress.org/support/article/categories-block/
