### ISSUE TITLE
[HelpHub][6.5][screenshots]: Amazon Kindle Embed screenshots are broken

### ISSUE THREAD

**Issue by josevarghese** [WordPress/Documentation-Issue-Tracker#1542]
Article:  <https://wordpress.org/documentation/article/amazon-kindle-embed/>

## Task
The images for the article are broken as the images are linked from Google Drive and the document is now private or deleted

## Directions
- Compare existing screenshots (on the article link) to the actual interface in the latest WordPress version.
- Ensure you have the appropriate WordPress version and that new screenshots cover the same page area as the existing one.
- If something is different in the latest version, make a new screenshot.
- Upload new screenshots to the comment on this issue.
- Request review by stating in the comment that the issue is ready for review.

## Resources
1. You can set WordPress install in one click by visiting https://playground.wordpress.net/ or use InstaWP sandbox https://app.instawp.io/onboard
2. Read about updating screenshots - [Updating screenshots](https://make.wordpress.org/docs/handbook/get-involved/getting-started-at-a-contributor-day/good-first-issues/#updating-screenshots)
3. Watch the video on creating screenshots for the latest WordPress versions - [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

## Automation
- If you want, you can assign yourself to the issue and change the label for review by posting specific keywords in a comment. Read about our repo's automatisation [here](https://make.wordpress.org/docs/handbook/github-repository-and-projects/documentation-issue-tracker/#label-issues).

Thank you for contributing, have a cookie :cookie:

**Comment by josevarghese** [comment]
As the tagline for the broken images are existing on the article, I used the tagline as points so the Documentation team can upload the image easily to fix this.

1) Preview of Amazon Kindle block with book details
![Preview-Amazon-kindle-block-with-book-details](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/18503f06-f9ab-487d-9998-07f648328045)


2) Block toolbar for Amazon Kindle block
![amazon-kindle-block-toolbar](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/71b51f35-9bb7-4c71-8b23-7c404b843e6c)


3) Transform to option in the Amazon Kindle block
![transform-to-amazon-kindle-block](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/d10ca95a-a3f3-437c-896f-e6d814fc380f)


4) Block moving tools in the Amazon Kindle block
![moving-amazon-kindle-block](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/19c5ac03-4cfb-4607-b853-7628389de073)


5) Change alignment in the Amazon Kindle block
![change-alignment-amazon-kindle-block](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/392eb579-b696-47c9-a087-5d7babba2afc)


6) Edit URL in the Amazon Kindle block
![edit-url-amazon-kindle-block](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/dbc32c34-0538-4e69-a038-83327f607f6e)


7) More options in the Amazon Kindle block
![more-options-amazon-kindle-block](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/71a57e1d-fee6-46d4-a600-3659c505e839)


8) How to show the Block settings sidebar from the cog icon
![show-block-settings-from-the-cog-icon](https://github.com/WordPress/Documentation-Issue-Tracker/assets/34977009/58326bfa-0fc5-49e8-8362-1c8c9fdea5a9)

**Comment by josevarghese** [comment]
This issue is ready for review

/review

**Comment by dapobabs9511** [comment]
https://docs.google.com/document/d/1cYZpRCRHR6qvPqrMGieYOZlVRUBZcEQZLBjNm66t5-c/edit?usp=sharing

/review

**Comment by atachibana** [comment]
@dapobabs9511
It looks good to me. Do you want to enhance the HelpHub page by yourself or ask it to someone?

**Comment by dapobabs9511** [comment]
@atachibana 

Updates have been made to this doc. please review it and ensure everything is in place.

**Comment by atachibana** [comment]
@dapobabs9511 
Thank you for the updates. 
Sorry for the delay in noticing but is this photo saying TRULY DEEPLY copyright free? I don't think so. Please replace it by other copyright free photo or image

**Comment by dapobabs9511** [comment]
@atachibana 
Fixed

**Comment by atachibana** [comment]
@dapobabs9511 Thank you for the updates.
