### ISSUE TITLE
[HelpHub] Archives

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#155]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/archives-block/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/tn6xQTAf/78-archives

**Comment by mileamadalin** [comment]
Looking on this one

**Comment by mileamadalin** [comment]
The first image to update: 

"01. When it’s embedded."

<img width="677" alt="01  When it’s embedded" src="https://user-images.githubusercontent.com/6906834/171650626-744c462d-1b55-4f6c-abef-7cdc157eb592.png">

"02. Add Archives block."

<img width="332" alt="02 Add Archives block" src="https://user-images.githubusercontent.com/6906834/171651113-38f748c3-d143-44dd-b789-749bb7948355.png">

"03. Aligning Archives"

<img width="339" alt="03  Aligning Archives" src="https://user-images.githubusercontent.com/6906834/171651577-0918fa1e-439b-4fd6-9074-b3e3743aee7f.png">

"04. Block Settings"

<img width="334" alt="04  Block Settings" src="https://user-images.githubusercontent.com/6906834/171653154-8f771c27-41f0-4c69-9f66-30b9c4313c56.png">


"05. Archives Settings"

<img width="280" alt="05  Archives Settings" src="https://user-images.githubusercontent.com/6906834/171652730-5c8c56ab-7fb5-4c56-9347-8339d6897331.png">

The last image for "Advanced" it's the same, so no change is needed.

**Comment by colorful-tones** [comment]
This is ready for review. Just needs to be assigned and reviewed.

**Comment by femkreations** [comment]
Thank you for your work @mileamadalin. The page has been updated with the screenshots.

https://wordpress.org/support/article/archives-block/
