### ISSUE TITLE
404 Page on Rest API - Schema

### ISSUE THREAD

**Issue by timotei-litespeed** [WordPress/Documentation-Issue-Tracker#1554]
## Issue Description
There is a 404 error on section: [API Schema JSON](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#json)

## URL of the Page with the Issue
https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#json

## Section of Page with the issue
JSON

## Why is this a problem?
The link from words **easier to understand introduction to JSON Schema** are linked to a 404 page

## Suggested Fix
Possible new links: [https://json-schema.org/overview/what-is-jsonschema](https://json-schema.org/overview/what-is-jsonschema) OR [https://json-schema.org/learn/getting-started-step-by-step](https://json-schema.org/learn/getting-started-step-by-step)

Thank you!

**Comment by flexseth** [comment]
@timotei-litespeed - thank you for reporting...

I've introduced a pull request to get the link updated. Will close out the issue when it's merged.

**Comment by flexseth** [comment]
Fixed - marking as closed

**Comment by timotei-litespeed** [comment]
💯
