### ISSUE TITLE
Broken links on "File structure of a block"

### ISSUE THREAD

**Issue by rmorse** [WordPress/Documentation-Issue-Tracker#1557]
## Issue Description
There are some broken links on the "File structure of a block" page.
https://developer.wordpress.org/block-editor/getting-started/fundamentals/file-structure-of-a-block/

It looks like only this sentence has the bad links 

> This file includes the block name, description, [attributes](https://developer.wordpress.org/block-editor/getting-started/fundamentals/file-structure-of-a-block/docs/block-editor/reference-guides/block-api/block-attributes.md), [supports](https://developer.wordpress.org/block-editor/getting-started/fundamentals/file-structure-of-a-block/docs/block-editor/reference-guides/block-api/block-supports.md), and more, as well as the locations of essential files responsible for the block’s functionality, appearance, and styling.

## Suggested Fix
It looks like they're referencing markdown files whereas the rest of the docs is not.

**Bad link:**
https://developer.wordpress.org/block-editor/getting-started/fundamentals/file-structure-of-a-block/docs/block-editor/reference-guides/block-api/block-attributes.md

**Good link:** 
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/

**Comment by jybrahmbhatt1994** [comment]
@rmorse I guess redirection is added for the broken link and it is working fine now.

**Comment by estelaris** [comment]
it has been fixed
