### ISSUE TITLE
Broken links in Common APIs Filter Reference page

### ISSUE THREAD

**Issue by gillycheesesteak** [WordPress/Documentation-Issue-Tracker#1558]
## Issue Description

The links in the bulleted list at the top of the page are all broken (copied below)

[Plugin API](https://developer.wordpress.org/Plugin_API).
[Writing a Plugin](https://developer.wordpress.org/Writing_a_Plugin).
[Plugin API/Action Reference](https://developer.wordpress.org/Plugin_API/Action_Reference).
[Plugin API/Hooks 2.0.x](https://developer.wordpress.org/Plugin_API/Hooks_2.0.x).

## URL of the Page with the Issue

https://developer.wordpress.org/apis/hooks/filter-reference/

## Section of Page with the issue

First section bulleted list

**Comment by flexseth** [comment]
@gillycheesesteak - There are quite a few broken links throughout the Common APIs handbook.

Please see - I've put in a good bit of work on it (spreadsheet in that thread) but haven't yet completed

- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1484

It's been a very time-intensive and mundane process, but I do intend on finishing up at some point :)

Marking as closed, please see the issue mentioned here for more info on the broken links. 
Thank you for reporting!
