### ISSUE TITLE
[HelpHub] Calendar Widget Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#156]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/calendar-block/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/0j8GgHv7/18-calendar-widget-block

**Comment by colorful-tones** [comment]
@marconmartins are all screenshots in here? ☝️

**Comment by femkreations** [comment]
@marconmartins Thank you. Awesome work getting the screenshots. I've updated the page with them.

https://wordpress.org/support/article/calendar-block/
