### ISSUE TITLE
Conflict between `manage_media_columns` and `manage_{$screen->id}_columns` Filter

### ISSUE THREAD

**Issue by narenin** [WordPress/Documentation-Issue-Tracker#1560]
There is a conflict between `manage_media_columns` and `manage_{$screen->id}_columns` Filter when we are using `manage_{$screen->id}_columns` for media screen.

The error is coming because the `manage_media_columns` filter hook in `wp-admin/includes/class-wp-media-list-table.php` passes two arguments.

`<?php
$column_headers[ $screen->id ] = apply_filters( "manage_{$screen->id}_columns", array() );`

## Issue Description
There is a conflict between `manage_media_columns` and `manage_{$screen->id}_columns` Filter when we are using `manage_{$screen->id}_columns` for media screen.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/hooks/manage_screen-id_columns/

## Section of Page with the issue
We need to mention in the doc that we need to pass two arguments when we are using `manage_{$screen->id}_columns` Filter for `media` screen.

## Why is this a problem?
There is a conflict between `manage_media_columns` and `manage_{$screen->id}_columns` Filter when we are using `manage_{$screen->id}_columns` for `media` screen.

## Suggested Fix
We can mention in the doc that we need to pass two arguments when we are using `manage_{$screen->id}_columns` Filter for `media` screen.

**Comment by narenin** [comment]
@sagargurnani99 Could you please take a look.

**Comment by narenin** [comment]
@samxmunoz Could you please check this.

**Comment by atachibana** [comment]
This issue is for the Core reference and will be tracked in another ticket.
https://core.trac.wordpress.org/ticket/61220

Prior to this, More Information section was added to the relevant page and Narendra's comments were transcribed.
