### ISSUE TITLE
[HelpHub] RSS Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#157]
Article: https://wordpress.org/support/article/rss-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/9IxuhwMI/15-widgets-rss-block

**Comment by manuelaugustin** [comment]
I'd like to pick up this issue.

**Comment by manuelaugustin** [comment]
## Intro
![Intro RSS feed 5 9 Large](https://user-images.githubusercontent.com/27805437/152539186-866a1204-19ae-4379-9520-49934234cbbd.jpeg)
![Intro add Large](https://user-images.githubusercontent.com/27805437/152539196-d012caa6-e50a-4249-8b80-b6b5aac23506.jpeg)
![Intro feed simple Large](https://user-images.githubusercontent.com/27805437/152539220-95f9e0e2-0924-4322-b3d0-b8afd43c0b80.jpeg)

## Block Toolbar
![Block toolbar](https://user-images.githubusercontent.com/27805437/152539257-98f94c12-7671-4e27-ba6a-916c2c587887.jpeg)

## Alignment
![Alignment](https://user-images.githubusercontent.com/27805437/152539296-309c4221-7cb0-4220-8d25-f88fd49f0c56.jpeg)

## List
![List Large](https://user-images.githubusercontent.com/27805437/152539468-2e227fc4-7698-4577-b41c-f34bdf202259.jpeg)

## Grid
![Grid](https://user-images.githubusercontent.com/27805437/152539609-7e724052-483e-4842-bdd8-4b71c4b49dd2.jpeg)

## More Options
![More Options](https://user-images.githubusercontent.com/27805437/152539524-e2c0bf55-b0c6-457f-9a98-a6c90469837b.jpeg)


## Block Settings
![Block Settings](https://user-images.githubusercontent.com/27805437/152539563-d46d29b3-d928-4d0a-8db5-d5afb8dcd8d4.jpeg)

## Advanced
![Advanced](https://user-images.githubusercontent.com/27805437/152539586-e78a4e26-345d-49b9-8433-25e8bd311e17.jpeg)

**Comment by zzap** [comment]
Updated post with all screenshots.
