### ISSUE TITLE
wordpress website error.

### ISSUE THREAD

**Issue by Tsvangie** [WordPress/Documentation-Issue-Tracker#1573]
![aaq](https://github.com/WordPress/Documentation-Issue-Tracker/assets/23018642/3cd9b8df-2408-4d97-ad78-2843a1ead538)

**There has been a critical error on your website.

[Learn more about debugging in WordPress.](https://wordpress.org/support/article/debugging-in-wordpress/)**

This is coming when i try to access the website . What maybe the problem.

**Comment by jybrahmbhatt1994** [comment]
Hey @Tsvangie 
You can debug by enabling debug mode. You can do it by editing wp-config.php
Find - define('WP_DEBUG', false); and set the value to true like define('WP_DEBUG', true);
By doing this you can see the exact error and solve accordingly.

And for development related issues you can create topic [here](https://wordpress.org/support/forum/wp-advanced/) as this repo is for tracking documentation related issues.

**Comment by estelaris** [comment]
@Tsvangie and @jybrahmbhatt1994 the issue tracker is to address and fix issues with the WordPress documentation, not for giving support with your sites. 
Next time, visit the Forums in WordPress.org for support

**Comment by jybrahmbhatt1994** [comment]
@estelaris I know issue tracker is not for site support and that's why I also mentioned in my comment that visit forums for development related issues.

Thanks.
