### ISSUE TITLE
Theme handbook does not link to issue tracker

### ISSUE THREAD

**Issue by cweiske** [WordPress/Documentation-Issue-Tracker#1574]
## Issue Description
I found a problem on the [theme handbook](https://developer.wordpress.org/themes/) and wanted to report a bug.
The "credits" page has a "[feedback](https://developer.wordpress.org/themes/credits/feedback/)" section that does not link to this bug tracker.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/credits/feedback/

## Section of Page with the issue
Giving Feedback

## Why is this a problem?
It's harder than necessary to report problems.

## Suggested Fix
Link to this issue tracker.

**Comment by justintadlock** [comment]
The plan is to have a Contributing chapter, as noted in this ticket: https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 It's not been outlined yet, but a complete guide will be included in the future.

For now, I added a link to this repository in the existing list.
