### ISSUE TITLE
distorted page

### ISSUE THREAD

**Issue by Iliya5digital** [WordPress/Documentation-Issue-Tracker#1576]
## Issue Description
The Russian page about installing Wordpress is garbled. In the first screen you can immediately see that the logo has been distorted with white and black colors. When you hover over the logo, a black rectangle around the logo is highlighted. At the footer of the page, everything goes down in a list.

## URL of the Page with the Issue
https://codex.wordpress.org/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0_WordPress

## Section of Page with the issue
On the page header and on the page footer

## Why is this a problem?
Because this is the first time this problem has occurred and it needs to be fixed because the page is worn out and distorted

## Suggested Fix
Return the logo to its original place on both the main page and the footer. Eliminate the footer of the page, which contains a list. Everything is visible in the screenshots

![Без имени](https://github.com/WordPress/Documentation-Issue-Tracker/assets/115736491/824670d4-bd99-4226-9566-09ee88de8d9c)
![Без имени2](https://github.com/WordPress/Documentation-Issue-Tracker/assets/115736491/5f184f78-f204-4424-a2f3-c7d094534874)
![Без имени3](https://github.com/WordPress/Documentation-Issue-Tracker/assets/115736491/bf3592e3-fc5a-427c-a6f2-1bb2cb086e55)

**Comment by estelaris** [comment]
This is a Codex issue and we are not updating Codex any longer. We recommend that  you meet with the translation team and check if they will be translating the documentation into Russian.
