### ISSUE TITLE
WordCamp Europe Contributor Day - June 13, 2024 

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1577]
https://europe.wordcamp.org/2024/contributor-day/

Table leads:
- @estelaris 
- @Leonardus-Nugraha 
- @zzap 

# Everyone

## 1. Start Contributor Day

**If you attend this Contributor Day, please comment below with your WordPress.org username.** 

## 2. Start contributing

When you find the issue you'd like to work on (take a look at the list below), please leave a comment on that issue so that we can assign you and avoid more people working on the same issue. If you know which docs the project issue belongs to, you can tag [the project rep](https://make.wordpress.org/docs/handbook/the-team/) as well.

## 3. You'll probably need WordPress

For a quick fresh WordPress install, you can use WordPress Playground by going to https://playground.wordpress.net/

---------------------------------------------------------------------------------------------------------------------------------------------------------------

# New contributors

If this is your first time contributing to the Documentation team, please make sure you have the following accounts:
- [WordPress.org account](https://login.wordpress.org/register).
- [WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
- [GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).

Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :) 

The following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:
- [General overview](https://make.wordpress.org/docs/handbook/get-involved/onboarding-sessions/overview/)
- [End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
- [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)
- [All Documentation team onboarding sessions](https://make.wordpress.org/docs/2022/06/13/live-onboarding-sessions-for-the-documentation-team/)

For general details on how GitHub works, check out [GitHub’s Getting Started Guide](https://docs.github.com/en/get-started/quickstart/hello-world).

When you find issue you'd like to work on in the [Docs Team Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) here on GitHub:

1.  Please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue, and
2. In that comment, also be sure to tag the [team rep responsible for the handbook](https://make.wordpress.org/docs/handbook/the-team/) that your chosen task is about.

For example, if your task is for the Block Editor End-User documentation, you would tag @Leonardus-Nugraha.

Check out the [Team page in the Documentation Team Handbook](https://make.wordpress.org/docs/handbook/the-team/) for a list of team reps.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Tasks we plan to work on during the day:

1. [Mobile App documentation (new document, review content and screenshots)](https://github.com/WordPress/Documentation-Issue-Tracker/labels/mobile%20app) Reqs: Download the mobile app https://wordpress.org/mobile/
2. [[6.5 end-user documentation (review content, new docs, update articles, screenshots)](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+6.5)
3. [Localization/translation end-user documentation to ES (Spanish from Spain)](https://github.com/orgs/WordPress/projects/195)

**Comment by freddallica** [comment]
Fredde Battel (battelfred)

**Comment by luislard** [comment]
Hello from the contribution day documentation table with cookies!

**Comment by marconmartins** [comment]
@marcomartins 🍪

**Comment by vicheva** [comment]
@vickyvicheva

**Comment by zzap** [comment]
Thank you everyone for participating. All of you who didn't already have a badge now do have a Docs contributor badge :cookie: hope to see you in the [#docs](https://wordpress.slack.com/archives/C02RP4WU5) channel sometime
