### ISSUE TITLE
[6.6 HelpHub] Advancing the new Data Views in the Site Editor

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#1578]
6.5 issue in the works: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1499 

Review video and compare with 6.5 workflow: https://drive.google.com/file/d/1hVfUqeVsTnvDg8AZuTo-DdK4EhpKdjhI/view?usp=drive_link
Full video library (DO NOT USE THESE VIDEOS IN THE ARTICLES): https://drive.google.com/drive/u/1/folders/1VhZp-yXgovLy6hubPEp9Nq1j3hohInMJ

### Update for 6.6

- [x] Manage all templates
- [x] Manage all template parts
- [x] Manage all pages (1.12 min)

### General
 
- [ ] Make sure all screenshots are relevant to the latest version
- [ ]  Make sure videos, if any, are up to date
- [ ]  Add ALT tags for the images
- [ ]  Make sure the headings are in sentence case
- [ ]  Update the changelog at the end of the article

**Comment by moranjosep** [comment]
\assign

**Comment by atachibana** [comment]
Page: https://wordpress.org/documentation/article/site-editor/

## To browse the templates and template parts
(replace video)
https://github.com/user-attachments/assets/9482bf35-a4a0-4cd4-a507-91199d4191d8

### To manage the site’s templates
WordPress uses templates to create the layout and structure for specific page types on your site. The Site Editor displays the template choices that you can add to your site and lets you create custom templates using the Template Editor.

From the Appearance > Editor, you will be shown a view that includes a sidebar with your list of Templates and Patterns that includes the list of template parts.
https://github.com/user-attachments/assets/5634ef63-2024-4a62-828d-f9f06dd2cf33

(And, we can remove all other sentenced thanks to UI improvements).

### To manage the template parts
(Replace 2nd paragraph and video)
From the Appearance > Editor, click the Patterns option. From All templates parts, you can access to them.
https://github.com/user-attachments/assets/d58637ec-94f3-4225-91d8-467b507dc5b7

### To mange pages
(replate the video)
https://github.com/user-attachments/assets/1a4245eb-c8da-447e-a8e9-0a59024b54f9

**Comment by atachibana** [comment]
As no one seems to have commented on it, it has been published.
https://wordpress.org/documentation/article/site-editor/
