### ISSUE TITLE
[HelpHub] Tag Cloud Widget Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#158]
Article: https://wordpress.org/support/article/tag-cloud-block/ 

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] add changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/Keo75uIU/17-tag-cloud-widget-block

**Comment by evrpress** [comment]
I'll handle that

**Comment by zzap** [comment]
Thank you so much @evrpress :heart: 

For the block settings it seems like you had Group block selected. Here's the screenshot for Tag cloud block

![tag-cloud-settings](https://user-images.githubusercontent.com/1508963/172211472-5dc12f20-ca4e-4877-a33a-b58722888942.png)

**Comment by zzap** [comment]
@evrpress do you want to update the article yourself? If so I'll give you access to dashboard. 

It's also OK not to want this :grimacing: just let me know :raised_hands:

**Comment by femkreations** [comment]
Review completed. Updated the article for 6.0 with the screenshots and content and added in ALT tags and a changelog.
