### ISSUE TITLE
[HelpHub] Search Widget Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#160]
Article: https://wordpress.org/support/article/search-block/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/P8mRd8p4/16-search-widget-block

**Comment by agnieszkaszuba** [comment]
I will start with this issue

**Comment by agnieszkaszuba** [comment]
I partially updated the article (until the ‘Change button position’ section) and saved the changes for later.

**Comment by AndreeaCristinaRadacina** [comment]
I will work on this one.

**Comment by AndreeaCristinaRadacina** [comment]
Screenshots:
Added a new screenshots, to contain the Bold / Italic options:
<img width="699" alt="01_SearchBlock_blocktoolbar" src="https://user-images.githubusercontent.com/86592992/171637817-1dfcc3c3-281c-4f02-988b-0fa311836668.png">
There is a new icon for the reusable blocks and one more option called Lock.
<img width="252" alt="02_SearchBlock_moreoptions" src="https://user-images.githubusercontent.com/86592992/171637822-b62f5519-a7e2-48ab-81ab-5b473b48ca0d.png">

**Comment by femkreations** [comment]
Updated screenshots, added and tweaked the content, and added ALT tags for the images. Review complete @zzap
