### ISSUE TITLE
[6.6 HelpHub] Create individual typography and color variations to level up design options

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#1613]
Draft
Article:  https://wordpress.org/documentation/article/styles-overview/

## Update for 6.6
- [x] [Color & Typography Variations for WP 6.6](https://github.com/WordPress/gutenberg/issues/61215)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’
- [ ] Update the changelog at the end of the article

**Comment by atachibana** [comment]
(Under the Style variations section...)

### Color and typography style variations

Color and typography variations are subsets of the existing global style variations system that were introduced in WordPress 6.6. Color and typography variations are limited in scope to—as their names imply—colors and typography.

When they are available, these variations appear as new options in the Appearance > Editor > Styles sidebar panel and elsewhere:


https://github.com/user-attachments/assets/3946c9e1-e1e4-4408-b5bd-da91034111a4

**Comment by atachibana** [comment]
As no one seems to have commented on it, it has been published.
https://wordpress.org/documentation/article/styles-overview/
