### ISSUE TITLE
[6.6 HelpHub] Grid Block

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#1615]
## New page for 6.6
- [x] Create a new article for the Grid block
- [x] Make sure the URL slug under Permalink is: grid-block
- [x] At the top of the page, under the title, add the  ‘Link to the list of blocks’ reusable block.

## Update for 6.6
- [x] Add toggle for grid types and stabilise Grid block variation [59051](https://github.com/WordPress/gutenberg/pull/59051) and [59116](https://github.com/WordPress/gutenberg/pull/59116)
- [x] Add support for column and row span in grid children [58539](https://github.com/WordPress/gutenberg/pull/58539)
- [x] Add Grid interactivity [59052](https://github.com/WordPress/gutenberg/pull/59052)
- [x] Allow blocks to be grouped as a Grid [59853](https://github.com/WordPress/gutenberg/pull/59853)
- [x] Stabilise grid layout visualiser and resizer [61640](https://github.com/WordPress/gutenberg/pull/61640)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by atachibana** [comment]
I worte the draft page. Please review it.
https://wordpress.org/documentation/?post_type=helphub_article&p=16360665&preview=true

**Comment by atachibana** [comment]
No one in particular seems to have commented on it, so I have released it.
https://wordpress.org/documentation/article/grid-block/
