### ISSUE TITLE
Error appeared when we used `$feedname` parameter (started with _ ) with `add_feed()` function 

### ISSUE THREAD

**Issue by narenin** [WordPress/Documentation-Issue-Tracker#1616]
**Core Trac:** https://core.trac.wordpress.org/ticket/59945#comment:10

## Issue Description
Error appeared when we used `$feedname` parameter (started with _ ) with `add_feed()` function. This is happening because the `_` at the beginning of the feed name is removed in the `do_feed` function. 

This process results in an action name of `'do_feed_' . 'feed2'` when `$feed` is `'_feed2'`.

Since this is not done in the add_feed function and the action name specified in the add_action function is 'do_feed_' . '_feed2', since the two action names do not match, which resulting in the error indicated in the response.

## URL of the Page with the Issue

https://developer.wordpress.org/reference/functions/add_feed/

## Section of Page with the issue
We need to mention in the doc that  `$feedname` parameter should not start with `_`

## Why is this a problem?
This process results in an action name of 'do_feed_' . 'feed2' when $feed is '_feed2'. Since this is not done in the add_feed function and the action name specified in the add_action function is 'do_feed_' . '_feed2', since the two action names do not match, which resulting in the error indicated in the response.

## Suggested Fix
We should mention in the doc that  `$feedname` parameter should not start with `_`

**Comment by atachibana** [comment]
@narenin

Below sentence was inserted to More Information section of [add_feed()](https://developer.wordpress.org/reference/functions/add_feed/) reference, because it can be reflected without code changes.

> `$feedname` parameter should not start with ‘`_`‘. Please refer [#59945](https://core.trac.wordpress.org/ticket/59945).
