### ISSUE TITLE
[ 6.6 HelpHub]: Use keyboard shortcuts

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#1617]
Article: https://wordpress.org/documentation/article/keyboard-shortcuts-block-editor/

## Update for 6.6
- [x] In Block shortcuts, add shortcut to group blocks, see [46972](https://github.com/WordPress/gutenberg/pull/46972)
- [x] Add keyboard shortcut to collapse list view items other than the focused item [59978](https://github.com/WordPress/gutenberg/pull/59978)
- [x] Show copy shortcut in block options [60339](https://github.com/WordPress/gutenberg/pull/60339)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by atachibana** [comment]
## Windows
After the "Insert a new block after the selected block(s)"

Create a group block from the selected multiple blocks    Ctrl + G 

## Mac

After the "Insert a new block after the selected block(s)"

Create a group block from the selected multiple blocks    Cmd + G 

## Create a group block from the selected multiple blocks

Suppose you have selected multiple blocks.

![use-keyboard-shortcuts-ctrl-g-1](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/4a3d25d0-43d0-41a4-a018-481f7798961e)

If you press Ctrl + G or Cmd + G, all the selected blocks are transformed to a single group block. This shortcut will not allow to create a group block if a single block is selected.

![use-keyboard-shortcuts-ctrl-g-2](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/6652a016-b407-4f52-b14e-3bb455993872)

**Comment by atachibana** [comment]
- Show copy shortcut in block options (#60339) ... n/a. This is UI improvement.
- Add keyboard shortcut to collapse list view items other than the focused item (#59978) ... See below

## Windows
(bottom of the table)
List view shortcuts
- Collapse all other items    Alt + L

## Mac
(bottom of the table)
List view shortcuts
- Collapse all other items    ⌥ + L

(at the bottom of the page)
## List view shortcuts
These shortcuts are specific to the List View.

### Collapse all other items

You can collapse all other nested groups except the one you have selected by pressing Alt + L or option + L.

https://github.com/user-attachments/assets/34d0faba-7529-4192-8d3f-ee8a11325f5c

ALT: Pressing Alt + L or ⌥ + L collapse all other nested groups except the one you have selected.

**Comment by atachibana** [comment]
I modified the page with above suggestions.
