### ISSUE TITLE
[HelpHub] Feedback on an external link that opens to a page that doesn't exist 

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Documentation-Issue-Tracker#1619]
## URL of the Page with the Issue
https://make.wordpress.org/support/handbook/appendix/adding-screenshots-on-the-forums/#embedding-a-screenshot-on-the-forums

## Originally reported by
https://profiles.wordpress.org/kel-dc/

## Report content (issue description)
A link to Imgur opens to a page that doesn't exist. 

## Section of Page with the issue
In Embedding a Screenshot on the Forums: 

> To get started, [upload your screenshot to Imgur](https://help.imgur.com/hc/en-us/articles/210076663-Uploading-Content), then copy the resulting URL of what you uploaded.

The  link  to "upload your screenshot to Imgur" is https://help.imgur.com/hc/en-us/articles/210076663-Uploading-Content which opens to a page that doesn't exist: 
<img width="1382" alt="Screenshot 2024-06-30 at 16 06 52" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/36863633/58a2d872-fbc5-405d-a567-f769193c75fe">

## Why is this a problem?
The external link opens to a page that doesn't exist. 

## Suggested Fix
Change the link to an article on how to upload content like images: https://help.imgur.com/hc/en-us/articles/26512175044763-Uploading-Content

**Comment by macmanx2** [comment]
Changes made to https://make.wordpress.org/support/handbook/appendix/adding-screenshots-on-the-forums/ and https://wordpress.org/support/forum-user-guide/block-editor/#adding-screenshots

Thanks!
