### ISSUE TITLE
[HelpHub] SoundCloud

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#162]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/soundcloud-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/EnWxL1fo/27-soundcloud

**Comment by marconmartins** [comment]
I'm working on this.

**Comment by marconmartins** [comment]
<img width="335" alt="01-slash-add" src="https://user-images.githubusercontent.com/5478039/171649571-37c83d1e-a47e-4218-b42a-9d0a3420450b.png">
<img width="672" alt="02-add-url" src="https://user-images.githubusercontent.com/5478039/171649580-4100a8e8-873a-4850-8647-e605ad71a316.png">
<img width="694" alt="03-add-error" src="https://user-images.githubusercontent.com/5478039/171649581-7da7306c-f02a-4cb3-8f63-ff68e27ef0ae.png">
<img width="668" alt="04-preview-playlist" src="https://user-images.githubusercontent.com/5478039/171649583-cc1599ce-2955-47b2-b0c3-e05c5e8cfbff.png">
<img width="674" alt="04-preview-track" src="https://user-images.githubusercontent.com/5478039/171649608-5d918a7a-eafb-48d0-a96e-1e3c5dff5483.png">
<img width="287" alt="05-block-toolbar" src="https://user-images.githubusercontent.com/5478039/171649635-935a766c-9a60-4b90-8628-27874de2e074.png">
<img width="326" alt="06-block-transform" src="https://user-images.githubusercontent.com/5478039/171649646-0d9b5519-1706-47c7-a4a3-bee6e04788b2.png">
<img width="1035" alt="07-block-transform-2" src="https://user-images.githubusercontent.com/5478039/171649647-60332bee-ccf7-46cf-8ab3-9dda06b646b5.png">
<img width="668" alt="08-block-transform-3" src="https://user-images.githubusercontent.com/5478039/171649675-f0c77ee8-3dc9-41eb-9764-76704311f23b.png">
<img width="360" alt="09-block-alignment" src="https://user-images.githubusercontent.com/5478039/171649696-b2d699db-ba7f-46f5-8b88-2eee0978ab16.png">
<img width="677" alt="10-edit-url" src="https://user-images.githubusercontent.com/5478039/171649704-70b546a0-1ec2-4458-8014-951ca9bd3d51.png">
<img width="266" alt="11-block-settings" src="https://user-images.githubusercontent.com/5478039/171649707-638fb5b0-7280-4e6d-a866-76ba50d02d0c.png">

**Comment by colorful-tones** [comment]
@marconmartins are all screenshots attached for this? Thanks for your help!

**Comment by femkreations** [comment]
Thank you @marconmartins for the screenshots. The page has been updated with them.

https://wordpress.org/support/article/soundcloud-embed/
