### ISSUE TITLE
Unclear "See why" in codex doc of header files

### ISSUE THREAD

**Issue by smileBeda** [WordPress/Documentation-Issue-Tracker#1620]
## URL of the Page with the Issue
https://codex.wordpress.org/Theme_Development

## Section of Page with the issue
https://codex.wordpress.org/Theme_Development#Document_Head_.28header.php.29

## Why is this a problem?
> Use [wp_title()](https://codex.wordpress.org/Function_Reference/wp_title) to set the <title> element. [See why](https://codex.wordpress.org/Function_Reference/wp_title#Note).

The `see why` leads to https://developer.wordpress.org/reference/functions/wp_title/#Note which explains nothing.

## Suggested Fix
Very likely this `#note` (which probably would be very valuable) got lost from old to new codex, so if old codex is still available, port it to this new codex.

**Comment by estelaris** [comment]
There is no new Codex and the old Codex is not being maintained as it will eventually go offline. If you need any developers reference, you can review the [Developer Resources](https://developer.wordpress.org/). 

Closing this issue as wontfix

**Comment by smileBeda** [comment]
Thanks. The Code has been updated via https://core.trac.wordpress.org/ticket/61555

I disagree that just because something _will go away_, wrong or borked information should stay in place. The new Dev resources also is _incomplete_, which makes it a bit worse IMO.
Anyway, solved through the trac.
