### ISSUE TITLE
DocCode block issues for Registering a pattern category documentation.

### ISSUE THREAD

**Issue by itzmekhokan** [WordPress/Documentation-Issue-Tracker#1621]
There is duplicate function opener `register_block_pattern_category(` in code block mentioned in here - https://developer.wordpress.org/themes/patterns/registering-patterns/#registering-a-pattern-category

For reference, this issue was reported [via Slack](https://wordpress.slack.com/archives/C02RP4WU5/p1719893992098459) by @wpbt

## Issue Description
Duplicate function opener `register_block_pattern_category(` in code block

## URL of the Page with the Issue
https://developer.wordpress.org/themes/patterns/registering-patterns/#registering-a-pattern-category

## Section of Page with the issue
[Registering a pattern category](https://developer.wordpress.org/themes/patterns/registering-patterns/#registering-a-pattern-category)

## Suggested Fix
Remove extra function opener `register_block_pattern_category(`

**Comment by juanmaguitar** [comment]
For reference, this issue was reported [via Slack](https://wordpress.slack.com/archives/C02RP4WU5/p1719893992098459) by @wpbt

> The circled line should be removed!
 
![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/422576/bfb3a0eb-7d62-4834-9d31-acc4de9e07dd)
