### ISSUE TITLE
In the Template Hierarchy, the "query string" link redirects to a different page.

### ISSUE THREAD

**Issue by deepakrohillas** [WordPress/Documentation-Issue-Tracker#1623]
In Template Hierarchy "query string" link(https://wordpress.org/support/article/glossary/#query-string) redirect to another page. 

URL  : https://developer.wordpress.org/themes/templates/template-hierarchy/
## Issue Description
In the Template Hierarchy section of the WordPress developer documentation (https://developer.wordpress.org/themes/templates/template-hierarchy/), the link to the "query string" redirects to another page: https://wordpress.org/documentation/article/wordpress-glossary/#query-string.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/templates/template-hierarchy/

## Section of Page with the issue
query string

## Why is this a problem?
query string link

## Suggested Fix
Replace the link https://wordpress.org/support/article/glossary/#query-string with https://wordpress.org/documentation/article/wordpress-glossary/#query-string.

Screenshot : https://ibb.co/1nwHRFz

**Comment by justintadlock** [comment]
Link updated.
