### ISSUE TITLE
[HelpHub] Spotify

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#163]
Article: https://wordpress.org/support/article/spotify-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/tl3WPWGv/28-spotify

**Comment by anyk17** [comment]
Updated screenshots, the text might need some changes too

![003-spotify_album_example](https://user-images.githubusercontent.com/19748471/160733227-d8135415-79ca-492e-bb33-afe3dbbb27da.jpg)
![03-add_block](https://user-images.githubusercontent.com/19748471/160733230-fa473de3-734a-4b47-8036-8c9ea4ac3551.jpg)
![04-embed_button](https://user-images.githubusercontent.com/19748471/160733231-4fecd13b-9920-4643-aa80-682f499799cd.jpg)
![05-spotify_preview](https://user-images.githubusercontent.com/19748471/160733232-3b725228-e105-499c-a819-07e2a64126dc.jpg)
![06-spotify_wrong_link](https://user-images.githubusercontent.com/19748471/160733233-79195304-2f98-472e-82e3-fa2889aa220b.jpg)
![07-embed_podcast](https://user-images.githubusercontent.com/19748471/160733234-2e53a7ec-acfc-49bb-accf-46ee2ab2f110.jpg)
![08-embed_album](https://user-images.githubusercontent.com/19748471/160733238-a84c869b-4ead-477f-be1b-e790fc1dbe1c.jpg)
![09-spotify_toolbar](https://user-images.githubusercontent.com/19748471/160733239-7be12764-02f3-458d-b7f9-0e9114fe8adc.jpg)
![10-transform_to](https://user-images.githubusercontent.com/19748471/160733240-58de4dff-d3c8-4524-b543-c13dc49929e3.jpg)
![11-group_color](https://user-images.githubusercontent.com/19748471/160733242-7686139e-3f19-4c90-beac-b0f8f63a8cc4.jpg)
![12-spotify_color_example](https://user-images.githubusercontent.com/19748471/160733243-b977dda4-a44e-445e-b971-41617b3d4b78.jpg)
![13-alignment](https://user-images.githubusercontent.com/19748471/160733244-b5c2dad2-c6ce-431b-af57-9c68acedfb36.jpg)
![14-edit_url](https://user-images.githubusercontent.com/19748471/160733245-c0850765-b845-44d7-93f2-14b7a0a889a6.jpg)
![15-hide_blocking_settings](https://user-images.githubusercontent.com/19748471/160733246-400a9c29-09fe-4172-af7b-2997265d79d3.jpg)
![16-edit_html](https://user-images.githubusercontent.com/19748471/160733247-9af71f49-bacd-448a-bcdb-b6fb6eaffb9e.jpg)
![17-media_settings_enabled](https://user-images.githubusercontent.com/19748471/160733248-b04274e2-2ebf-4617-a649-6b90456797af.jpg)
![18-media_settings_disabled](https://user-images.githubusercontent.com/19748471/160733249-8c0ea7c9-381f-42eb-9305-4f0442facc0a.jpg)
![19-advanced_settings](https://user-images.githubusercontent.com/19748471/160733250-585607be-686a-4baa-b682-732069c61e8a.jpg)
![001-spotify_track_example](https://user-images.githubusercontent.com/19748471/160733252-9d433100-1df8-4e05-bba6-7baab68203c8.jpg)
![01-spotify_copy_link](https://user-images.githubusercontent.com/19748471/160733253-7ffb4d60-1017-4a89-bc59-f8add49d6de5.jpg)
![002-spotify_podcast_example](https://user-images.githubusercontent.com/19748471/160733254-e1561ac5-2a86-4189-a759-372c0eb33ea4.jpg)
![02-spotify_copy_link_desktop](https://user-images.githubusercontent.com/19748471/160733256-a3fdd441-149e-457a-b7f0-7681019a13c7.jpg)

**Comment by zzap** [comment]
Hello @anyk17 , thank you so much for working on this :star2: 

You are right, text needs to be modified for alignment settings. You can find the updated list here: https://wordpress.org/support/article/video-block/#block-toolbar 

Also, this sentnece needs to be removed: 

```
“Wide width” and “Full width” alignment need to be enabled by the Theme of your site. 
```

Would you like to update the article? If so, give me your wordpress.org username so I can give you the access. Thanks

**Comment by anyk17** [comment]
Hi @zzap thanks! Yes, I'd like to work on it. My username in wordpress.org is @anyk17

**Comment by zzap** [comment]
Hi @anyk17 , you should have permissions to update article. Let me know if you need any help :raised_hands:

**Comment by anyk17** [comment]
Thanks @zzap I've completed the changes, let me know if anything else is needed 😃

**Comment by zzap** [comment]
Thank you so much for working on this :heart:
