### ISSUE TITLE
[HelpHub] WordPress.tv

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#165]
Article: https://wordpress.org/support/article/wordpress-tv-embed-block/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/94mSETBN/53-wordpresstv

**Comment by samxmunoz** [comment]
I'll take this one. 👋🏼

**Comment by samxmunoz** [comment]
### Screenshots:
![WordPress tv Embed Doc SS 1](https://user-images.githubusercontent.com/43501707/180497412-15c8d2dd-983f-4473-bf7d-746e1550c338.png)
![WordPress tv Doc SS 2](https://user-images.githubusercontent.com/43501707/180497418-d4a0e446-b060-42b6-a4b9-8960eda456b6.png)
<img width="451" alt="WordPress tv Doc SS 3" src="https://user-images.githubusercontent.com/43501707/180497424-0e34d5d7-5914-436d-b12b-5ded8e25012a.png">
<img width="671" alt="WordPress tv Doc SS 4" src="https://user-images.githubusercontent.com/43501707/180497430-5617d45c-fd84-4e1d-b6dc-e0822a076faa.png">

<img width="680" alt="WordPress tv Embed Doc SS 5" src="https://user-images.githubusercontent.com/43501707/180497484-c870b141-2939-4f8b-932b-59c0fb53a9f2.png">
<img width="675" alt="WordPress tv Embed Doc SS 6" src="https://user-images.githubusercontent.com/43501707/180497488-aa4a440d-fc25-42f5-861f-8bbbaa406306.png">
<img width="685" alt="WordPress tv Embed Doc SS 7" src="https://user-images.githubusercontent.com/43501707/180497489-37bade0e-bace-407e-b7b2-c8a0a51bfc7a.png">
<img width="299" alt="WordPress tv Embed Doc SS 8" src="https://user-images.githubusercontent.com/43501707/180497491-65d7445b-2e92-41ba-8e04-2c2e0f8b7aa1.png">
<img width="699" alt="WordPress tv Embed Doc SS 9" src="https://user-images.githubusercontent.com/43501707/180497492-026f602f-8c23-4f7d-aa93-c3cc660c7653.png">
<img width="687" alt="WordPress tv Embed Doc SS 10" src="https://user-images.githubusercontent.com/43501707/180497493-94777d90-c0c1-4665-a81f-4b1119763447.png">
<img width="686" alt="WordPress tv Embed Doc SS 11" src="https://user-images.githubusercontent.com/43501707/180497494-c3b2172e-04a7-4987-bf9a-e11d599f6fb8.png">
<img width="711" alt="WordPress tv Embed Doc SS 12" src="https://user-images.githubusercontent.com/43501707/180497495-02747ef2-7aaf-40d6-87fd-745b774a7ad3.png">
<img width="703" alt="WordPress tv Embed Doc SS 13" src="https://user-images.githubusercontent.com/43501707/180497498-e544a6d0-0745-4afc-81c3-9a983e66d11f.png">


### In addition, there are edits that could be made to the Doc:

**Block Toolbar**
Transform To:
- The block can also be transformed to **Columns** see Screenshot 9.

Alignment:
- Additional alignment options are available "None, Wide Width, Full width" see Screenshot 13.

**Comment by samxmunoz** [comment]
Hello @zzap / @femkreations! All done with the screenshots & some suggestions to update the doc. Happy to make the updates myself if I have the proper permissions :)

**Comment by zzap** [comment]
You have needed access now, @samxmunoz . Thank you so much for contribution :heart:

**Comment by samxmunoz** [comment]
This has been updated! 🎉

**Comment by colorful-tones** [comment]
Nice work @samxmunoz ! Closing this out.
