### ISSUE TITLE
Two version(6.4.4 and 6.5.5) missing in wordpress version page.

### ISSUE THREAD

**Issue by deepakrohillas** [WordPress/Documentation-Issue-Tracker#1653]
Versions 6.4.5 and 6.4.4 are currently missing from the page at https://wordpress.org/documentation/article/wordpress-versions/. Despite listing versions up to 6.4.3 under Version 6.4, two additional versions were released but are not included.

## Issue Description
 Please add the following versions to the WordPress versions page:

Version 6.4.4, released on April 9, 2024

## URL of the Page with the Issue
https://wordpress.org/documentation/article/wordpress-versions/. 

## Section of Page with the issue
Version 6.4.4, released on April 9, 2024  both released are missing in wordpress versions page

## Why is this a problem?
Version 6.4.4, released on April 9, 2024  both released are missing in wordpress versions page , mentioned till 6.4.3 only.

## Suggested Fix
 Please add the following versions to the WordPress versions page:

Version 6.4.4, released on April 9, 2024

https://wordpress.org/documentation/wordpress-version/version-6-4-4/

Version 6.4.5, released on June 24, 2024
https://wordpress.org/documentation/wordpress-version/version-6-4-5/
 
More Detail Please check ticket here : https://meta.trac.wordpress.org/ticket/7719

**Comment by Leonardus-Nugraha** [comment]
Hi @deepakrohillas, thank you for reporting!
I have updated the page, and now 6.4.4 and 6.4.5 are included. However, I didn't link to any announcement blog as I didn't find any at https://wordpress.org/news/category/releases/ 
Also, can you confirm if the database version remains the same for those two versions? (56657)

**Comment by deepakrohillas** [comment]
yes there was no announcement in https://wordpress.org/news/category/releases/ page. 6.4.4 was maintenance update and 6.4.5 was security update.

DB version was same ie. 56657
Blog url https://wordpress.org/documentation/wordpress-version/version-6-4-4/#maintenance-updates

there was the across-site scripting (XSS) vulnerability and npm packages with bugfixes.

in 6.4.5 DB version was same ie. 56657 security fixes and due to this security release 6.4.5 was important to update
https://wordpress.org/documentation/wordpress-version/version-6-4-5

**Comment by Leonardus-Nugraha** [comment]
@deepakrohillas table updated with the links to the respective blog page and database version

**Comment by deepakrohillas** [comment]
@Leonardus-Nugraha : Thanks it's fine now. Thanks again!

**Comment by estelaris** [comment]
fixed

**Comment by deepakrohillas** [comment]
@estelaris @Leonardus-Nugraha  Since i have made contributions to the documentation and would appreciate it if you could assign the corresponding badge
