### ISSUE TITLE
Doc Update: Replace Broken Images 

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Documentation-Issue-Tracker#1659]
## Issue Description

There are broken images in the documentation. 

## URL of the Page with the Issue
 https://wordpress.org/documentation/article/imgur-embed/
 
## Section of Page with the issue
- Under Step 2. Add an Imgur Embed block to your post. "How to quickly add an imgur embed block using the slash command"  

Image link: https://wordpress.org/documentation/files/2022/08/image-1-2.png 

- and in "Error when embedding an Imgur post"  

Image link: https://wordpress.org/documentation/files/2022/08/image-1-3-1024x318.png 

## Why is this a problem?
The images are broken and open to a 404 file not found. 

## Suggested Fix
Reupload or replace the image.

**Comment by dapobabs9511** [comment]
@kspilarski 
Can you assign me to this task?

**Comment by kspilarski** [comment]
Hi @dapobabs9511  I am not able to make edits to the assignees. @Miral-addweb please check if you can still work on this issue or make edits to the assignees. Thank you both!

**Comment by dapobabs9511** [comment]
@Miral-addweb If you're not working on this can you assign me to work on it?

**Comment by kspilarski** [comment]
I've also pinged Miral in Make WordPress slack to ask if this issue is something they'll work on, otherwise assign the issue to dapobabs9511 instead.

**Comment by dapobabs9511** [comment]
@kspilarski thanks

**Comment by DrewAPicture** [comment]
This is done.
