### ISSUE TITLE
[HelpHub] Mixcloud

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#166]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/mixcloud-embed/

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/z1hs0XIr/44-mixcloud

**Comment by colorful-tones** [comment]
I've updated all the screenshots for 6.0, added a quick video walkthrough and updated the changelog. Closing this out.
