### ISSUE TITLE
[HelpHub] VideoPress

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#167]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/videopress-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/sqkQTVTm/55-videopress

**Comment by hannaw93** [comment]
I will pick this one up :)

**Comment by shabnam611** [comment]
I will pick this one

**Comment by shabnam611** [comment]
[https://docs.google.com/document/d/19IF6H_ZrkS8RlONzmnptp31rV3Pl0_F73ycj9tV_qys/edit#](url)

Update screenshots - Steps to Embed a video from VideoPress:
step 3
Updated screenshots - Steps to Embed a video from VideoPress:
step 4 [first and third image]
Update screenshots - Change Alignment
Update screenshots - Edit URL
Update screenshots - More Options
Edited the headings in sentence case

**Comment by zzap** [comment]
This document is not available, can you please re-share it @shabnam611 ?

**Comment by shabnam611** [comment]
Hi Milana,

Thank you for the notification. I have changed the URL and am sorry for the
mistake.

Thank you

**Comment by femkreations** [comment]
Thanks @shabnam611 for the awesome work. The page looks great. I updated the Changelog heading to H2 level so it displays well in the TOC (without the bullets)
