### ISSUE TITLE
Fix typo in Template Parts doc 

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Documentation-Issue-Tracker#1673]
## Issue Description
Fix typo in the text 

## URL of the Page with the Issue
https://wordpress.org/documentation/article/template-part-block/#imporing-widget-area

## Section of Page with the issue
"Imporing widget area" 

## Why is this a problem?
It's a typo. 

## Suggested Fix
Change **"Imporing widget area"** to **Importing**

**Comment by estelaris** [comment]
fixed
