### ISSUE TITLE
[HelpHub] TikTok

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#168]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/tiktok-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/PgPwEKcr/99-tiktok

**Comment by iolandasequino** [comment]
I'm picking up this issue :D

**Comment by iolandasequino** [comment]
I've update the screenshots of this article to reflect the layout in the 6.0.2 version. I've edited the `Hide Block settings` heading to `Hide more settings` and added the "None" option to the `Change alignment` section.

Here is the document I created: https://docs.google.com/document/d/117B4dSdHK5rM03RTnVFHpzK2Y4cbnoekAD4LoAk8stA/edit?usp=sharing

**Comment by samxmunoz** [comment]
I can implement @iolandasequino's updates from the document into the article.

**Comment by zzap** [comment]
Any progress on this @samxmunoz ?

**Comment by samxmunoz** [comment]
Working on this tomorrow @zzap !!

**Comment by samxmunoz** [comment]
Hi @zzap & @femkreations - this article is updated & ready for review.

Thanks @iolandasequino for grabbing all of the screenshots :)

**Comment by femkreations** [comment]
Reviewing this article.

**Comment by abhansnuk** [comment]
Hello. A couple of suggestions on this useful article:
- 2nd par: "although it should be public." - suggest changing 'it' to 'video' to make it clear what 'it' refers to. 
- lower case 'e' at the beginning of 'Steps to Embed a video from TikTok'
- 'Detailed instructions on adding blocks can be found here' - can we avoid using 'here' for link descriptive text as it is difficult for accessibility
- "If it’s a link that can be successfully embedded you will see a preview in your editor." Given the audience level of experience that this audience seems to be aimed at, I am unsure readers will know 'can be successfully embedded' will mean
- Block toolbar section. Suggest avoiding adding a link to headings as this can be unhelpful for accessibility
- I am sure this will be already on the list to do, alt text for videos and photos
- add 'button' in the text after for eg Transform to, Change Alignment, Edit URL. This will help give them context and relate it more to the section above

Thanks.

**Comment by femkreations** [comment]
Thank you for adding the content @samxmunoz Reviewed and looks good. 
Thanks for reviewing @abhansnuk I've updated the content as per your comments.
