### ISSUE TITLE
In the WordPress developer documentation article titled "Updating WordPress," several links are redirecting to different destinations.

### ISSUE THREAD

**Issue by deepakrohillas** [WordPress/Documentation-Issue-Tracker#1683]
In the WordPress developer documentation article titled "Updating WordPress," several links are redirecting to different destinations.

## Issue Description
In the WordPress developer documentation article titled "Updating WordPress," several links are redirecting to different destinations.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/updating-wordpress/

## Section of Page with the issue
In Back up wordpress  on anchor tag of WordPress Backup link is redirecting to
https://developer.wordpress.org/advanced-administration/security/backup/
Similarly In Manual Update :- extended upgrade and more detailed upgrade instructions both words anchor tag link redirecting to 
https://developer.wordpress.org/advanced-administration/upgrade/upgrading/
And
File Ownership " Changing File Permissions" link redirecting on  https://developer.wordpress.org/advanced-administration/server/file-permissions/

## Why is this a problem?
different link are 301 redirecting another links
## Suggested Fix
The link should be updated because the current redirects to other pages could impact performance by increasing server load, cascading redirects, and processing time.
https://wordpress.org/documentation/article/wordpress-backups/ 
should be replaced by 
https://developer.wordpress.org/advanced-administration/security/backup/ URL.

https://wordpress.org/documentation/article/changing-file-permissions/
should be replaced by
https://developer.wordpress.org/advanced-administration/server/file-permissions/

https://wordpress.org/documentation/article/upgrading-wordpress-extended-instructions/
should be replaced by
https://developer.wordpress.org/advanced-administration/upgrade/upgrading/

screenshot : https://ibb.co/Fs2Xy8S
https://ibb.co/9WY4GJZ

**Comment by atachibana** [comment]
@deepakrohillas Thank you.
All your suggestions were enhanced to the page. Also, that included another fix of restore your backup link
from https://wordpress.org/documentation/article/restoring-your-database-from-backup/
to https://developer.wordpress.org/advanced-administration/security/backup/
