### ISSUE TITLE
Fix aria landmark tools link for Accessibility Ready guidelines in the Theme Handbook

### ISSUE THREAD

**Issue by joedolson** [WordPress/Documentation-Issue-Tracker#1687]
## Issue Description

The tools link at https://make.wordpress.org/themes/handbook/review/accessibility/required/#aria-landmark-roles currently points to https://accessibility.oit.ncsu.edu/tools/aria-landmark-inspector/, and needs to be updated to point to https://accessibility-bookmarklets.org/install.html, as the previous link is now a 404 with no replacement.

## URL of the Page with the Issue

https://make.wordpress.org/themes/handbook/review/accessibility/required/

## Section of Page with the issue

#aria-landmark-roles

## Why is this a problem?

The link is no longer valid.

## Suggested Fix

Replace the link per the above comment.

**Comment by justintadlock** [comment]
Link updated.
