### ISSUE TITLE
[HelpHub] Feedback on File block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1695]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/file-block/

## Originally reported by

As noted below

## Report content (issue description)

> We (many WP users) really need guidance on editing the size of the font in the filename of the file block (for PDF uploads.) Thanks.
> + Losing the functionality of the important! override for editor styling is causing chaos!
> 
By https://profiles.wordpress.org/siriusmw/

>How to override settings to force show the PDF on mobile view? Currently mobile view doesn’t show at all pdf/image. I have tried using css to override the display:none but doesn’t help at all because the file is dynamically loaded via javascript.

By https://profiles.wordpress.org/tnchuntic/

> I cannot figure out how to have the link description different from the link. For example: I want the text “Term 3 Timetable” pointing to “2024term3.pdf”. I ended up editing the HTML but that is not something I can teach part-time volunteer editors.
> 
> The other problem is that the download button has dark blue text on black background (unreadable) but I cannot change the text color. Accidentally I discovered that selecting the “Highlight” option shows a color menu which allows me to chose a readable FG/BG combination. Why is it called “Highlight” when it should be “Colors”?

By https://profiles.wordpress.org/manfred2p718/

**Comment by ndiego** [comment]
> We (many WP users) really need guidance on editing the size of the font in the filename of the file block (for PDF uploads.) Thanks.
> 
> How to override settings to force show the PDF on mobile view? Currently mobile view doesn’t show at all pdf/image. I have tried using css to override the display:none but doesn’t help at all because the file is dynamically loaded via javascript.

This feedback refers to customizing the block beyond what is available in Core, so it's out of scope for this doc. 

> I cannot figure out how to have the link description different from the link. For example: I want the text “Term 3 Timetable” pointing to “2024term3.pdf”. I ended up editing the HTML but that is not something I can teach part-time volunteer editors.

The doc explains you can edit the file name by clicking on the text.

> The other problem is that the download button has dark blue text on black background (unreadable) but I cannot change the text color. Accidentally I discovered that selecting the “Highlight” option shows a color menu which allows me to chose a readable FG/BG combination. Why is it called “Highlight” when it should be “Colors”?

This is likely theme related as it does not occur in Twenty Twenty-Four. 

Because of these factors, I'm closing this out as no changes to the doc are needed as a direct result of this feedback.
