### ISSUE TITLE
Plugin handbook shortcode example code is incorrect

### ISSUE THREAD

**Issue by atachibana** [WordPress/Documentation-Issue-Tracker#17]
This issue was moved from [HelpHub issue #314](https://github.com/WordPress/HelpHub/issues/314) reported by [oskar-fagerfjall](https://github.com/oskar-fagerfjall).

## **Issue Description**

In the [Shortcodes with Parameters](https://developer.wordpress.org/plugins/shortcodes/shortcodes-with-parameters/) chapter in the plugin handbook, the complete example at the end is incorrect. It works fine for shortcodes without content, but when adding content that content is echoed twice.

## **Context**

The problematic code is the following
```php
    if ( ! is_null( $content ) ) {
        // secure output by executing the_content filter hook on $content
        $o .= apply_filters( 'the_content', $content );
 
        // run shortcode parser recursively
        $o .= do_shortcode( $content );
    }
```
This code appends the content variable to the output twice, once without running the shortcode parser recursively, and once without properly securing the output. 

## **Steps to reproduce:**

1. Copy the example code into a plugin
2. Activate the plugin
3. Make a new post containing  `[wporg title="A"][wporg title="B"]test[/wporg][/wporg]` 
4. Preview the post

## **Expected Result:**

The shortcode should result in
```html
<div><h2>A</h2><div><h2>B</h2>test</div></div>
```
## **Actual Result:**
The shortcode results in
```html
<div><h2>A</h2><div><h2>B</h2></div>test<div><h2>B</h2></div>test</div>[/wporg]
```

**Comment by leogermani** [comment]
Error confirmed.

Parsing shortcodes recursively is not a common usage, so I removed that and also improved the documentation for what the content is and clarifying that the example is only one of the things you could do with your content.

Also clarified that the `$content` parameter is just what is inside the shortcode and not the whole content of the post.

**Comment by theMikeD** [comment]
Thanks @leogermani
