### ISSUE TITLE
[HelpHub] Issuu

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#170]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/issuu-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/M7CX4G0X/38-issuu

**Comment by mayankguptadotcom** [comment]
@zzap - i'm happy to work on this one. 
Not clear about the second point - Make sue videos are up to date, there aren't any videos on that page.

**Comment by femkreations** [comment]
Hi @mayankguptadotcom I've assigned the task to you. Thanks for your help. If there is no video on the page, you can ignore that item on the checklist.

**Comment by mayankguptadotcom** [comment]
![issuu-block-controls](https://user-images.githubusercontent.com/8931305/196313143-a1dd1ff0-e222-4957-b324-81fb4f900dde.jpg)
![issuu-alignment](https://user-images.githubusercontent.com/8931305/196313144-2c7e85e4-6a66-40d6-ba15-732033c939f4.jpg)
![issuu-group-block-controls](https://user-images.githubusercontent.com/8931305/196313146-9e4ac66f-4997-4ee0-a1ae-9ef9adfb3f4a.jpg)
![issuu-share-copy-link](https://user-images.githubusercontent.com/8931305/196313147-b31c588e-9247-4a5c-9747-6a6609e09c98.jpg)
![issuu-transform-block](https://user-images.githubusercontent.com/8931305/196313149-58b861f8-c387-458a-8e0c-9881bec7694e.jpg)
![issuu-with-blue-background](https://user-images.githubusercontent.com/8931305/196313150-9405747d-74de-49be-8b76-eefd1b6b93b6.jpg)
![more-block-settings](https://user-images.githubusercontent.com/8931305/196313152-424be50d-cafc-4f0e-826a-47ae7034691d.jpg)
![edit-as-html](https://user-images.githubusercontent.com/8931305/196313153-90501884-191e-4eeb-9751-cdf7ca9d82af.jpg)

@femkreations - These are the updated images. 
I don't have the edit access, how can I get it to update the article?

**Comment by mayankguptadotcom** [comment]
@femkreations @zzap - One thing I noticed though, Issuu wants users to upgrade now for embedding actual content.
It does embed the document - but shows an overlay saying "Why I can't see my embed"

do we add that information in the document or is it not of our concern?

**Comment by mayankguptadotcom** [comment]
Updated the article.

* [x]  Make sure all screenshots are relevant to the latest version
* [ ]  Make sure videos are up to date - **Not applicable.**
* [x]  Add ALT tags for the images
* [x]  Make sure the headings are in sentence case
* [x]  Convert all reusable blocks to a ‘regular block’.
* [x ]  Update the changelog at the end of the article

@femkreations - can you please review it from your side.

**Comment by mayankguptadotcom** [comment]
@femkreations - Thank you!!
