### ISSUE TITLE
[HelpHub] Feedback on List block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1702]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/list-block/

## Report content (issue description)

> As far as I can tell, includes the ID attribute, but this is not implemented, and indeed is rejected by WP and the Gutenberg editor.
> 
> https://www.w3.org/TR/2012/WD-html-markup-20121025/global-attributes.html
> 
> Please explain this or a workaround for adding anchors to list items.

By https://profiles.wordpress.org/ejnwebmaster/

>The HTML anchor (ID tag) for a list block is not appearing in the right hand bar. Has this been disabled?

By https://profiles.wordpress.org/ejnwebmaster/

**Comment by atachibana** [comment]
> Please explain this or a workaround for adding anchors to list items.

You can set anchor for a List block as like as other block, and it will generate ul tag with id attribute (see below). It works !

> The HTML anchor (ID tag) for a list block is not appearing in the right hand bar. Has this been disabled?

You cannot set anchor for a list item block, but can set for a list block.


![Image](https://github.com/user-attachments/assets/e2ddc5a5-0050-47d5-b19a-f34bcad04281)
![Image](https://github.com/user-attachments/assets/7fbbe6bf-630d-43c3-978e-befe4a352c56)
