### ISSUE TITLE
[HelpHub] Feedback on Posts screen

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1710]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/posts-screen/

## Originally reported by

https://profiles.wordpress.org/ladyhawk012018/

## Report content (issue description)

> Struggling to find better info about adding back comment section on posts and adding back featured images. Last night I accidentally deleted the main menu. After hours I figured out how to rebuild the menu, but the comment sections on posts were gone and my features pictures for my posts as well as main pages were gone. Still looking. Read several info sites but no help. For example, images are not listed and cannot be added to the All Posts page where I can look at them. I went and clicked the box that said “allow comments”, and it doesn’t work either. Comments are allowed on each of the posts, but no comment section appears. Very frustrating.

**Comment by ndiego** [comment]
This feedback should be directed to the support forum, and I do not believe it's actionable for documentation.
