### ISSUE TITLE
[HelpHub] Feedback on Gallery block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1712]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/gallery-block/

## Originally reported by

https://profiles.wordpress.org/dchapple/

## Report content (issue description)

> BUG REPORT:
> 
> Style Settings
> You can access the Style settings for the Gallery and Image block by clicking on the Styles tab.
> 
> YOU CAN NOT ACCESS THIS FEATURE IN WP 6.6.1.
> It is missing.

**Comment by ndiego** [comment]
Styles are available for both the Gallery and Image blocks in WordPress 6.7, so I do not believe this comment is actionable.
