### ISSUE TITLE
[HelpHub] Feedback on Twenty Twenty-One changelog

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1715]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/twenty-twenty-one-changelog/

## Originally reported by

https://profiles.wordpress.org/zodiac1978/

## Report content (issue description)

> The readme.txt for Twenty Twenty One has a changelog entry for 2.3:
> https://themes.svn.wordpress.org/twentytwentyone/2.3/readme.txt
> 
> It is just a link to https://wordpress.org/documentation/article/twenty-twenty-one-changelog/#Version_2.3
> 
> But this page only contains changelogs until Version 2.2 – there is no 2.3 🙁

**Comment by sabernhardt** [comment]
The changelog has details for version 2.3 (again?) today.

**Comment by ndiego** [comment]
Version 2.3 details are present in the article, so closing this out.
