### ISSUE TITLE
[HelpHub] Feedback on Twenty Twenty-Four changelog

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1716]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/twenty-twenty-four-changelog/

## Originally reported by

https://profiles.wordpress.org/w-sky/

## Report content (issue description)

>No info about version 1.2 which is already released

**Comment by sabernhardt** [comment]
The [WayBack archives](https://web.archive.org/web/20241008160130/https://wordpress.org/documentation/article/twenty-twenty-four-changelog/) from earlier this month show a broken page, but the changelog page somehow has its contents again today. Version 1.2 is at the beginning.
