### ISSUE TITLE
[HelpHub] Feedback on RSS block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1722]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/rss-block/

## Report content (issue description)

>Can this block be edited to display images of the RSS feed? If not, when will the block be updated to include this feature?

By https://profiles.wordpress.org/webcodedesigner/

**Comment by ndiego** [comment]
This feedback is not actionable.
