### ISSUE TITLE
[HelpHub] Feedback on Twenty Twenty-Four

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1725]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/twenty-twenty-four/

## Report content (issue description)

>In paragraph “Category and Tag list blocks” the first word reads “Caterogy”

By https://profiles.wordpress.org/w-sky/

**Comment by ndiego** [comment]
It looks like this has been fixed and is no longer actionable.
