### ISSUE TITLE
[HelpHub] Feedback on Site Logo block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1726]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/site-logo-block/

## Report content (issue description)

>“When you add an image to the Site Logo block, the change applies to all Site Logo block in your website.” needs plural like ‘all Site Logo blocks in’

By https://profiles.wordpress.org/dixonds/

**Comment by ndiego** [comment]
Fixed.
