### ISSUE TITLE
[HelpHub] Feedback on Edit Media

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1727]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/edit-media/

## Report content (issue description)

>Typo in the Edit Image Button paragraph — it says “… it’s original …” instead of “its”.

By https://profiles.wordpress.org/dixonds/

**Comment by ndiego** [comment]
> Typo in the Edit Image Button paragraph — it says “… it’s original …” instead of “its”.

Fixed.
