### ISSUE TITLE
[HelpHub] Feedback on Plugins screen

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1729]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/plugins-screen/

## Report content (issue description) its author

>My DHL plugin is saying “This plugin has not been tested with your current version of Worldpress”. Can assist please .

By https://profiles.wordpress.org/recoverymarketing/

**Comment by ndiego** [comment]
This feedback is not actionable.
