### ISSUE TITLE
[HelpHub] ReverbNation

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#173]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/reverbnation-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/lj4Ttc4o/47-reverbnation

**Comment by pls78** [comment]
I'm picking it up :)

**Comment by pls78** [comment]
The updated article can be found [here](https://docs.google.com/document/d/1kQ-ep3bjYVFQAQhdJPqLe7-g6PiBpbtCuxESV1O4jM0/edit?usp=sharing).
* Some of the screenshots have been updated: please note I have also update all the screenshots where the artist is present, for consistency, as the ReverbNation artist page changed over time
* Screenshots filenames have been kept consistent with the previous ones; this means that:
  * If the filename contained the WordPress version for which it has been created (5.5 in this case), that version number has been updated to 6.0
  * The filename has been kept the same if no WordPress version has been specified
Alt text has been added for each picture (it is attached to each picture as a comment in the Google Doc)
* 'Block settings' section header has been changed to sentence case
* 'Change Alignment – use reusable Block' section header has been changed to 'Change Alignment'
* In the 'More Options' section: 
  *  'Hide Block Settings' has been changed to 'Hide More Settings'
  * 'Lock' sub-section has been added
* 'Remove Block' section header has been changed to 'Remove ReverbNation'

**Comment by femkreations** [comment]
Thanks for working on this @pls78 The article looks great. I've done the following
-Screenshots and content updated for 6.1
-Styled and removed More options content and linked to the More options page for details
-Added ALT tags for images

https://wordpress.org/support/article/reverbnation-embed/
