### ISSUE TITLE
[HelpHub] Feedback on What’s the difference between WordPress.org and WordPress.com?

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1733]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/

## Report content (issue description) its author

>Video embed isn’t embedded in this page, It should be from this page: https://wordpress.tv/2022/02/28/what-is-the-difference-between-wordpress-com-and-org/

By https://profiles.wordpress.org/freewebmentor/

**Comment by ndiego** [comment]
The video seems to be displaying correctly now, so closing this out.
