### ISSUE TITLE
[HelpHub] Feedback on Screencast embed

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1734]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/screencast-block/

## Report content (issue description) its author

> Hi friends!
> I have reached this page from a link “Add New Sites Screen” on the page https://developer.wordpress.org/advanced-administration/multisite/admin/#Sites, which is obviously a wrong link.
> You can easily fix it!
> 😉

By https://profiles.wordpress.org/isemplice/

**Comment by ndiego** [comment]
This looks like it's been fixed.
