### ISSUE TITLE
[HelpHub] Feedback on Block Error: Unexpected or Invalid Content

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1737]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/block-error-unexpected-or-invalid-content/

## Report content (issue description) its author

> This block has encountered an error and cannot be…
> I can’t access the above suggestions to recover blocks or anything and it’s across every single editor page. Template and block. Front end looks fine but I can’t edit anything, update or manage the website. Please help me!

By https://profiles.wordpress.org/natashapanetta/

**Comment by ndiego** [comment]
This is a support request and not actionable.
