### ISSUE TITLE
[HelpHub] Feedback on Users Add New screen

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1738]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/users-add-new-screen/

## Report content (issue description) its author

>No, the article was not helpful. I was not able to register a new user.
>I would appreciate some help.

By https://profiles.wordpress.org/vogtr/

**Comment by ndiego** [comment]
This feedback is not actionable.
