### ISSUE TITLE
[HelpHub] Feedback on Editor Command Palette

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1739]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/site-editor-command-palette/

## Report content (issue description) its author

> The article says “The Editor Command Palette is only available when you install and activate a Block theme on your site.”
> 
> This isn’t true – the command palette is available in the post editor even on classic themes.

By https://profiles.wordpress.org/dean/

**Comment by ndiego** [comment]
> The article says “The Editor Command Palette is only available when you install and activate a Block theme on your site.”
> 
> This isn’t true – the command palette is available in the post editor even on classic themes.

This feedback is correct. All fixed.
