### ISSUE TITLE
[HelpHub] SmugMug

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#174]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/smugmug-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/FMuEYiMF/48-smugmug

**Comment by samxmunoz** [comment]
I'll grab this one.

**Comment by samxmunoz** [comment]
This is ready for REVIEW @zzap & @femkreations !!! 🎉

**Comment by Leonardus-Nugraha** [comment]
Thanks @samxmunoz for the content! Reviewed this one and everything is great!
