### ISSUE TITLE
[HelpHub] Feedback on List view

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1741]
## URL of the Page with the Issue

https://wordpress.org/documentation/article/list-view/

## Report content (issue description) its author

> The currently labeled “list view” was referred, among other things, as “document overview” for example in the release statement when it came out as is: https://make.wordpress.org/core/2022/11/09/whats-new-in-gutenberg-14-5-9-november/
> 
> In fact in the code base it is referred as “Document overview” and that’s how the button is labeled in the editor DOM.
> 
> The problem is there is not a single mention of this on this page, which is confusing. I spent 10 minutes to look for the documentation about this element to send to a client and I have 10 years of WP experience… I just could not remember how it’s called, looked at the code and searched for “document overview”.
> 
> I doubt I am the only one to have had this problem.
> A name used in the editor page should maybe be used in the corresponding docs? Maybe? I dunno. A suggestion.

By https://profiles.wordpress.org/julianoe/

**Comment by ndiego** [comment]
Good feedback. I have added "Document Overview" when referring to the button in the toolbar.
