### ISSUE TITLE
[HelpHub] Meetup.com

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#175]
Article: https://wordpress.org/support/article/meetup-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/2Sz862uP/40-meetupcom

**Comment by anyk17** [comment]
@zzap I was going to work on this one, but the /meetup block doesn't show for me. Is this still supported?

**Comment by zzap** [comment]
@anyk17 it has been removed (see [#35085](https://github.com/WordPress/gutenberg/issues/35085)). Let's leave this one for discussion at meeting to see how are we going to deal with it.

**Comment by femkreations** [comment]
Unpublishing the page as the Meetup block is not available any more.
