### ISSUE TITLE
[HelpHub] CloudUp

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#176]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/cloudup-embed/

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/onm9XcYp/34-cloudup

**Comment by mayankguptadotcom** [comment]
@femkreations I can pick this one.

**Comment by mayankguptadotcom** [comment]
@zzap - apologies, I haven't been able to work on it. And it seems that won't be able to work on it either until Cloudup gives me an account. I've applied for it - but haven't received it yet.

**Comment by femkreations** [comment]
No worries @mayankguptadotcom Thanks for the update
