### ISSUE TITLE
[HelpHub] Dailymotion

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#177]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/dailymotion-embed/

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/sik2TV0t/33-dailymotion

**Comment by samxmunoz** [comment]
I can take this one! 👋🏼

**Comment by samxmunoz** [comment]
Hello! This has been updated & a video walkthrough created. 🎉 

https://wordpress.org/support/article/dailymotion-embed/ 

Please review @zzap @femkreations - thank you!

**Comment by femkreations** [comment]
Awesome work @samxmunoz. Closing this task
