### ISSUE TITLE
[HelpHub] Reddit

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#178]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/reddit-embed/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/g9hKR2gN/45-reddit

**Comment by colorful-tones** [comment]
@respectyoda is attempting to work on this with internal guidance.

**Comment by respectyoda** [comment]
Here are all the screenshots to update the documentation. Please note that in versions older than 5.9, one could transform the embed into a Paragraph or a Groups block. But with 5.9 and newer, they can additionally transform it into a Columns block. I have attached screenshots for this new type of block.

<img width="656" alt="Reddit-screenshot-1" src="https://user-images.githubusercontent.com/3604751/180486257-2824cc3d-5927-467f-9171-d63b3a22a020.png">
<img width="629" alt="Reddit-screenshot-2" src="https://user-images.githubusercontent.com/3604751/180486281-a9819b9d-861f-40e8-a59f-4345fadbe5d2.png">
<img width="1178" alt="Reddit-screenshot-3" src="https://user-images.githubusercontent.com/3604751/180486290-e5feacee-758f-49f1-9994-c82d8df44215.png">
![Reddit-screenshot-4](https://user-images.githubusercontent.com/3604751/180486317-7bf19437-229c-45bb-97fa-c5c7e5c0ecdd.png)
<img width="361" alt="Reddit-screenshot-5" src="https://user-images.githubusercontent.com/3604751/180486347-211e17c0-2c0e-4dad-a93a-84c98a062108.png">
<img width="689" alt="Reddit-screenshot-6" src="https://user-images.githubusercontent.com/3604751/180486350-d773c355-00b2-4eb5-a584-e619df07f283.png">
<img width="656" alt="Reddit-screenshot-7" src="https://user-images.githubusercontent.com/3604751/180486356-cb671bf9-84f4-45ea-974c-f9485b75f019.png">
<img width="291" alt="Reddit-screenshot-8" src="https://user-images.githubusercontent.com/3604751/180486387-2e671910-ad5b-4206-b4ce-c8ac986024fe.png">
<img width="399" alt="Reddit-screenshot-9" src="https://user-images.githubusercontent.com/3604751/180486390-1183fd88-e308-4498-aaf6-bfc970b86adb.png">
<img width="656" alt="Reddit-screenshot-10" src="https://user-images.githubusercontent.com/3604751/180486409-cd7fc522-bbe0-4acd-bb3d-f7a68d9b5485.png">
<img width="674" alt="Reddit-screenshot-11-columns" src="https://user-images.githubusercontent.com/3604751/180486410-b94f3c3b-40a5-4b8e-aeed-8a65d82f1329.png">
<img width="1109" alt="Reddit-screenshot-11-groups-color" src="https://user-images.githubusercontent.com/3604751/180486423-afac01c9-fe6f-4e45-ab55-fce9f011d0be.png">
<img width="695" alt="Reddit-screenshot-11-groups-orange-background" src="https://user-images.githubusercontent.com/3604751/180486437-08c9a871-65d2-43fc-9cd7-6584f22a765f.png">
<img width="675" alt="Reddit-screenshot-11-groups" src="https://user-images.githubusercontent.com/3604751/180486445-1ccc347f-b3b2-45e1-af58-9a70314ab7c0.png">
<img width="655" alt="Reddit-screenshot-13" src="https://user-images.githubusercontent.com/3604751/180486453-7bf3be6a-2fea-4784-ab2f-a6538c461a08.png">
<img width="696" alt="Reddit-screenshot-14" src="https://user-images.githubusercontent.com/3604751/180486463-2ba68ead-a96c-48dd-b640-1ba39bcdba93.png">
<img width="409" alt="Reddit-screenshots-12" src="https://user-images.githubusercontent.com/3604751/180486471-322be02c-25c4-4ea3-99f7-604574daced6.png">

**Comment by colorful-tones** [comment]
@femkreations @zzap can either of you assign this to @respectyoda please?

I'm doing a preliminary review right now of the work and will leave pertinent feedback. Thanks!

**Comment by colorful-tones** [comment]
@femkreations @zzap this is ready for review and updating (if there is no further feedback). I took a run through with Aaron.

Thanks @respectyoda for working through this! 👏

**Comment by respectyoda** [comment]
Thank you for bringing me onboard! @colorful-tones

**Comment by colorful-tones** [comment]
@zzap may I have access to [this site](https://wordpress.org/support/article/reddit-embed/) so I can update the screenshots please?

**Comment by colorful-tones** [comment]
The [original post](https://wordpress.org/support/article/reddit-embed/) has been updated and Changelog has been updated at the bottom of post. Closing this out.

Thanks for your awesome work @respectyoda !
