### ISSUE TITLE
[6.7 HelpHub]: Link Control / Link editing.

### ISSUE THREAD

**Issue by bph** [WordPress/Documentation-Issue-Tracker#1789]
Article: https://wordpress.org/documentation/article/link-editing/

## Update for 6.7

- [x] LinkControl: Refined the display of the link preview title and URL when both are same. ([61819](https://github.com/WordPress/gutenberg/pull/61819))
- [x] Update URL to uppercase. ([62231](https://github.com/WordPress/gutenberg/pull/62231))

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
- Some PRs have great videos that can be added to the article.

**Comment by atachibana** [comment]
N/A - This is UI improvement.
- LinkControl: Refined the display of the link preview title and URL when both are same. (61819)

Modified the movie that was including the string "url" (lowercase).
- Update URL to uppercase. (62231)
