### ISSUE TITLE
[HelpHub] Slideshare

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#179]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/slideshare-embed/

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/AXg5p3Ro/49-slideshare

**Comment by samxmunoz** [comment]
I can take this one! 👋🏼

**Comment by samxmunoz** [comment]
@zzap - this has been updated. Can you or @colorful-tones review & close this issue?

https://wordpress.org/support/article/slideshare-embed

**Comment by femkreations** [comment]
@samxmunoz This looks great. Thank you.

**Comment by colorful-tones** [comment]
@samxmunoz you rock! Closing this out.
