### ISSUE TITLE
Add filter for wp_force_plain_post_permalink function

### ISSUE THREAD

**Issue by sovetski** [WordPress/Documentation-Issue-Tracker#1792]
Hi,

The function `wp_force_plain_post_permalink()` is used on the function `get_post_permalink()`, when the post is on the status `draft` for example, it returns `true` but in some cases I want to force it to `false`.

Is it possible to add a filter to give the ability to edit this behaviour?

**Comment by atachibana** [comment]
@sovetski 
Here is the repository for the documentation.
For the enhancement request, please open the core ticket at https://make.wordpress.org/core/reports/
