### ISSUE TITLE
[6.7 HelpHub]: update changelogs for bundled themes

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/Documentation-Issue-Tracker#1798]
(previously: #1031, #1275, #1517, #1654)

All the bundled themes need to update their changelogs when they are released. Below, I'll create a comment with a draft for each new version that releases with WordPress 6.7.

The heading IDs/anchors should be in the [pattern](https://github.com/WordPress/wordpress-develop/blob/ed59f778ba7e275c7f34f3f8dd5795abcb07ca91/src/wp-content/themes/twentytwentyfour/readme.txt#L19) of `#Version_1.2`.

See the full [log of all theme changes](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/?rev=59289&stop_rev=58572&verbose=on) from 6.6-RC1 to 6.7-RC2. If you want to see commits by each theme, add the directory name to the link, such as [Twenty Seventeen's log](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyseventeen/?rev=59289&stop_rev=58572&verbose=on).

**Comment by sabernhardt** [comment]
## [Twenty Ten](https://wordpress.org/documentation/article/twenty-ten-changelog/)

Version 4.3

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Respect user-defined font size settings in Table and Calendar blocks, and adjust the `line-height` for a different font size. ([#58362](https://core.trac.wordpress.org/ticket/58362))
- Fix Gallery block caption styles when the Gallery is inside a different block. ([#50376](https://core.trac.wordpress.org/ticket/50376))
- Document the `$css` parameter in `twentyten_remove_gallery_css()`. ([[59219]](https://core.trac.wordpress.org/changeset/59219))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Eleven](https://wordpress.org/documentation/article/twenty-eleven-changelog/)

Version 4.8

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Remove floating and absolute positioning to make post navigation links clickable on small screens and to match the visual order of the post navigation and post date to the markup order. ([#62008](https://core.trac.wordpress.org/ticket/62008))
- Fix Gallery block caption styles when the Gallery is inside a different block. ([#50376](https://core.trac.wordpress.org/ticket/50376))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Respect user-defined font size settings in Code blocks. ([#61753](https://core.trac.wordpress.org/ticket/61753))
- Add missing `initial-scale` value in viewport meta tag. ([[59026]](https://core.trac.wordpress.org/changeset/59026))
- Document the `$instance` parameter in Ephemera widget form. ([[59200]](https://core.trac.wordpress.org/changeset/59200))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Twelve](https://wordpress.org/documentation/article/twenty-twelve-changelog/)

Version 4.4

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Prevent navigation submenus from hiding behind page content by increasing their `z-index` to `99999`. ([#55892](https://core.trac.wordpress.org/ticket/55892))
- Respect user-defined font size settings in Code blocks. ([#61753](https://core.trac.wordpress.org/ticket/61753))
- Fix Code block font family difference in editors. ([#61808](https://core.trac.wordpress.org/ticket/61808))
- Fix Button block Outline style text color on the front end. ([#61846](https://core.trac.wordpress.org/ticket/61846))
- Fix Navigation block submenus, preventing them from being cut off. ([#61672](https://core.trac.wordpress.org/ticket/61672))
- Add missing `initial-scale` value in viewport meta tag. ([[59026]](https://core.trac.wordpress.org/changeset/59026))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Thirteen](https://wordpress.org/documentation/article/twenty-thirteen-changelog/)

Version 4.3

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Respect user-defined font size settings in Code blocks. ([#61697](https://core.trac.wordpress.org/ticket/61697))
- Add missing `initial-scale` value in viewport meta tag. ([[59026]](https://core.trac.wordpress.org/changeset/59026))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Fourteen](https://wordpress.org/documentation/article/twenty-fourteen-changelog/)

Version 4.1

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Update border styles for Table blocks plus editor styles for figure captions, including `font-weight` and alignment. ([#61563](https://core.trac.wordpress.org/ticket/61563))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Add missing `initial-scale` value in viewport meta tag. ([[59026]](https://core.trac.wordpress.org/changeset/59026))
- Adjust comment spacing and punctuation to meet coding standards. ([#62098](https://core.trac.wordpress.org/ticket/62098))
- Document the `$args` parameter in `Featured_Content::hide_featured_term()`. ([[59210]](https://core.trac.wordpress.org/changeset/59210))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Fifteen](https://wordpress.org/documentation/article/twenty-fifteen-changelog/)

Version 3.9

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Fix microformat information by moving the visibly hidden "Author" text outside the `vcard` container. ([#46233](https://core.trac.wordpress.org/ticket/46233))
- Fix link hover effect in editor styles. ([#61844](https://core.trac.wordpress.org/ticket/61844))
- Fix Pullquote block issues with text color and border. ([#59801](https://core.trac.wordpress.org/ticket/59801))
- Fix Code block font family in the iframe editor. ([#61571](https://core.trac.wordpress.org/ticket/61571))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Fix padding for List blocks with a background color in the non-framed editor. ([#60197](https://core.trac.wordpress.org/ticket/60197))
- Add missing `initial-scale` value in viewport meta tag. ([[59026]](https://core.trac.wordpress.org/changeset/59026))
- Document the `$more` parameter in `twentyfifteen_excerpt_more()`. ([#62079](https://core.trac.wordpress.org/ticket/62079))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Sixteen](https://wordpress.org/documentation/article/twenty-sixteen-changelog/)

Version 3.4

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Fix editor styles for Table and Calendar blocks and captions. ([#58355](https://core.trac.wordpress.org/ticket/58355))
- Fix Pullquote block spacing and borders, and add theme preset border colors. ([#59754](https://core.trac.wordpress.org/ticket/59754))
- Respect user-defined typography settings in Button blocks. ([#58609](https://core.trac.wordpress.org/ticket/58609))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Match the Quote block border color to its text color in the editor. ([#56565](https://core.trac.wordpress.org/ticket/56565))
- Set Quote block border width to 4 pixels, regardless of font size. ([#60239](https://core.trac.wordpress.org/ticket/60239))
- Fix Code block typography and padding in editor styles. ([#61700](https://core.trac.wordpress.org/ticket/61700))
- Respect user-defined typography settings in the Pullquote block. ([#59919](https://core.trac.wordpress.org/ticket/59919))
- Edit `initial-scale` value in viewport meta tag to `1.0` instead of `1`. [[59026]](https://core.trac.wordpress.org/changeset/59026)
- Adjust comment spacing to meet coding standards. ([#62160](https://core.trac.wordpress.org/ticket/62160))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Seventeen](https://wordpress.org/documentation/article/twenty-seventeen-changelog/)

Version 3.8

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Add spacing between each Reply heading and its Cancel reply link in the comments template. ([#59334](https://core.trac.wordpress.org/ticket/59334))
- Restrict front page panels to show only pages with 'publish' or 'private' status, and show a placeholder in the Customizer if the page has a different status. ([#46604](https://core.trac.wordpress.org/ticket/46604))
- Remove extra spacing from floated images when they are the first image. ([#46785](https://core.trac.wordpress.org/ticket/46785))
- Respect user-defined font weight settings in Button blocks. ([#60937](https://core.trac.wordpress.org/ticket/60937))
- Fix Gallery block caption styles when the Gallery is inside a different block. ([#50376](https://core.trac.wordpress.org/ticket/50376))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Fix Pullquote block text color settings in the editor. ([#46080](https://core.trac.wordpress.org/ticket/46080))
- Fix Search block button styles in the editor. ([#61888](https://core.trac.wordpress.org/ticket/61888))
- Edit `initial-scale` value in viewport meta tag to `1.0` instead of `1`. [[59026]](https://core.trac.wordpress.org/changeset/59026)
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Nineteen](https://wordpress.org/documentation/article/twenty-nineteen-changelog/)

Version 3.0

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Add spacing between each Reply heading and its Cancel reply link in the comments template. ([#59334](https://core.trac.wordpress.org/ticket/59334))
- Use the same "Published in" link text for any attachment page, repurposing text from the image template. ([#45473](https://core.trac.wordpress.org/ticket/45473))
- Fix navigation with multiple links in a right-to-left language. ([#46658](https://core.trac.wordpress.org/ticket/46658))
- Fix avatar image size in Avatar and Author blocks without changing the size for the Comments section. ([#60664](https://core.trac.wordpress.org/ticket/60664), [#62096](https://core.trac.wordpress.org/ticket/62096))
- Add center alignment to Archives and Categories List blocks in the editor. ([#61186](https://core.trac.wordpress.org/ticket/61186))
- Fix Pullquote block font size and citation display. ([#61507](https://core.trac.wordpress.org/ticket/61507))
- Respect user-defined typography settings in the Button block. ([#61437](https://core.trac.wordpress.org/ticket/61437))
- Reduce spacing below the Audio block's `audio` element by setting it to `display: block`. ([#53681](https://core.trac.wordpress.org/ticket/53681))
- Edit `initial-scale` value in viewport meta tag to `1.0` instead of `1`. [[59026]](https://core.trac.wordpress.org/changeset/59026)
- Remove the use of empty rulesets in Sass files. ([#61933](https://core.trac.wordpress.org/ticket/61933))
- Add missing documentation for helper function parameters, and edit spacing for DocBlocks. ([#62112](https://core.trac.wordpress.org/ticket/62112))
- Document the `$defaults` parameter in `twentynineteen_comment_form_defaults()`. ([[59218]](https://core.trac.wordpress.org/changeset/59218))
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Twenty](https://wordpress.org/documentation/article/twenty-twenty-changelog/)

Version 2.8

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Adjust margins in the Customizer so that the widget edit buttons are not obstructed on smaller screens. ([#49008](https://core.trac.wordpress.org/ticket/49008))
- Correct `font-size` for Code block and other preformatted elements. ([#61845](https://core.trac.wordpress.org/ticket/61845))
- Show the Verse block in the same font family in the editor as it has on the front end. ([#61140](https://core.trac.wordpress.org/ticket/61140))
- Reorganize color styles so that selecting a background color does not override selected text colors—in any block—or the color chosen for a Separator block. ([#57544](https://core.trac.wordpress.org/ticket/57544))
- Adjust the border styles for Quote blocks that set alignment with classes. ([#61132](https://core.trac.wordpress.org/ticket/61132))
- Add missing Plain style for the Quote block. ([#56011](https://core.trac.wordpress.org/ticket/56011))
- Respect user-defined font size settings in Table and Calendar blocks. ([#56157](https://core.trac.wordpress.org/ticket/56157), [#59996](https://core.trac.wordpress.org/ticket/59996))
- Respect user-defined typography settings in the Pullquote block. ([#55975](https://core.trac.wordpress.org/ticket/55975))
- Fix the alignment of centered block captions on screens narrower than 1,000 pixels. ([#50317](https://core.trac.wordpress.org/ticket/50317))
- Remove extra space from viewport meta tag. [[59026]](https://core.trac.wordpress.org/changeset/59026)
- Load block patterns on the `init` hook to avoid triggering notices caused by loading the translations too early. ([#62237](https://core.trac.wordpress.org/ticket/62237))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Twenty-Two](https://wordpress.org/documentation/article/twenty-twenty-two-changelog/)

Version 1.9

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Add instructions for updating the Comments block from the legacy version to the newer version introduced in WordPress 6.1. ([#56496](https://core.trac.wordpress.org/ticket/56496))
- Fix custom Search block border by setting it to zero width instead of removing all borders. ([#60669](https://core.trac.wordpress.org/ticket/60669))
- Update schema version in style variation files to ensure that settings and styles are properly handled by code editors that support schema. ([#61789](https://core.trac.wordpress.org/ticket/61789))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Twenty-Three](https://wordpress.org/documentation/article/twenty-twenty-three-changelog/)

Version 1.6

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Fix unnecessary borders for linked images in the Whisper variation. ([#57368](https://core.trac.wordpress.org/ticket/57368))
- Make index template heading text translatable. ([#61951](https://core.trac.wordpress.org/ticket/61951))
- Update schema version in style variation files to ensure that settings and styles are properly handled by code editors that support schema. ([#61789](https://core.trac.wordpress.org/ticket/61789))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by sabernhardt** [comment]
## [Twenty Twenty-Four](https://wordpress.org/documentation/article/twenty-twenty-four-changelog/)

Version 1.3

Released: November 12th, 2024 with [WordPress 6.7](https://wordpress.org/documentation/wordpress-version/version-6-7/)

- Fix typos in pattern descriptions. ([#61682](https://core.trac.wordpress.org/ticket/61682))
- Update schema version in style variation files to ensure that settings and styles are properly handled by code editors that support schema. ([#61789](https://core.trac.wordpress.org/ticket/61789))
- Add contributors to copyright notices. ([#61943](https://core.trac.wordpress.org/ticket/61943))

**Comment by carolinan** [comment]
All logs have been copied over and published, thank you.

**Comment by sabernhardt** [comment]
Thanks for updating them!

I noticed one more thing to change: [Twenty Twelve's changelog](https://wordpress.org/documentation/article/twenty-twelve-changelog/#Version_4.3) has Version 4.3 twice.

**Comment by carolinan** [comment]
Fixed!
