### ISSUE TITLE
[HelpHub] Animoto

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#180]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/animoto-embed/

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/6SYoxSBx/31-animoto

**Comment by leonidasmi** [comment]
I'm picking this up to update the screenshots!

**Comment by femkreations** [comment]
Thank you @leonidasmi The content looks great. We will add this to the article.

**Comment by mayankguptadotcom** [comment]
@femkreations - I can review the rest.

**Comment by femkreations** [comment]
Thanks @leonidasmi The page content looks great. I changed the heading level in Changelog to h2 so it looks good in the TOC without the bullet
