### ISSUE TITLE
[HelpHub] Speaker Deck

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#181]
Article: https://wordpress.org/support/article/speaker-deck-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/QTtiClWE/50-speaker-deck

**Comment by nishitlangaliya** [comment]
Hi @zzap , 

**1. Add the Speaker Deck block from the block list.**

![image](https://user-images.githubusercontent.com/11435772/161037725-85bd3595-c839-4312-93c0-ec6f9c70a21b.png)

**2.  Add the Deck link into the URL box** 

![image](https://user-images.githubusercontent.com/11435772/161038851-7a051c65-9e37-4a4f-8d55-47c48b334253.png)

**3.  Click the “Embed” button**

![image](https://user-images.githubusercontent.com/11435772/161039067-69b1a744-1aa1-4b7e-b2a9-323e43832089.png)

**4. Wrong url error message.**
![image](https://user-images.githubusercontent.com/11435772/161039572-ca4f6d43-3d9c-4195-9de2-32f31e620bcf.png)

**5. Block toolbar**

![image](https://user-images.githubusercontent.com/11435772/161039947-ef59200b-6e10-4f53-9ec4-9022fcd50990.png)

**6.  Change alignment** 

![image](https://user-images.githubusercontent.com/11435772/161040849-29b189d4-05b5-4825-bd36-cf46077089b8.png)

**7. Block toolbar - set to group for edit colors and other property.**

![image](https://user-images.githubusercontent.com/11435772/161040416-6121804a-2642-4fa5-bad5-a639c4fa44e6.png)

**8. Edit URL**

![image](https://user-images.githubusercontent.com/11435772/161041061-35fc54ec-4b16-4d11-b18f-00fed34568ec.png)

**9. Block settings**
![image](https://user-images.githubusercontent.com/11435772/161041297-6d03d9f2-9360-499f-9717-8ba388292afa.png)

**10.  More options**

![image](https://user-images.githubusercontent.com/11435772/161041540-0e641e7b-ced0-4602-a3fd-b542d970eec4.png)

**11 Edit as html.**
![image](https://user-images.githubusercontent.com/11435772/161041722-40e82de1-f9cc-4799-830c-c919ade1c186.png)

Let me know if any changes need.

Thanks

**Comment by zzap** [comment]
Hello @nishitlangaliya , thank you for working on this :raised_hands: 

Everything looks awesome. I have just one small request. Can you crop 10. screenshot so it matches the one we already have? Thanks

Cuurent one :point_down: 
![screenshot](https://i0.wp.com/wordpress.org/support/files/2020/09/Screen-Shot-2020-09-04-at-12.46.34-PM.png)

**Comment by md-codechallenge** [comment]
Hi @zzap ,

Thanks for your response. Response to your feedback I have added cropped scrrenshot.

![image](https://user-images.githubusercontent.com/59202898/161681971-5444f523-1b6f-4f60-80fe-d0a767630953.png)

Let me know if any changes need.

Thanks

**Comment by zzap** [comment]
Looks great, thanks :raised_hands: 

Would you like to update the article as well? If so, give me your wordpress.org username so I can give you the access.

**Comment by nishitlangaliya** [comment]
HI @zzap ,

Thanks for your response. I would like to update the article. But currently somehow I am not able to give time. I am happy to do contribution. :)

Thanks

**Comment by zzap** [comment]
![toolbar](https://user-images.githubusercontent.com/1508963/164016766-bdbd8008-0e92-465d-ab5a-d0c98ea62d49.png)
