### ISSUE TITLE
[HelpHub] Imgur

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#182]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/imgur-embed/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/Lqd6Xl10/37-imgur

**Comment by dreamwhisper** [comment]
Let me know if anything else is needed.

<img width="456" alt="imgur" src="https://user-images.githubusercontent.com/1271053/180569829-28045eda-6b71-4768-97fe-92920cb20cd5.png">

<img width="329" alt="imgur-add" src="https://user-images.githubusercontent.com/1271053/180569712-e5a81a54-6b95-454f-8799-333e413589ff.png">

<img width="676" alt="imgur-embed" src="https://user-images.githubusercontent.com/1271053/180569737-80f61158-5757-4fdc-9881-6636020f4458.png">

<img width="461" alt="imgur-editor" src="https://user-images.githubusercontent.com/1271053/180569778-e456e004-5fb1-4ae2-a2a3-c7e7bab14ef4.png">

<img width="818" alt="imgur-embed-error" src="https://user-images.githubusercontent.com/1271053/180569869-d82afe1d-1f87-4e1a-8e23-c4738abc1885.png">

<img width="456" alt="imgur-preview" src="https://user-images.githubusercontent.com/1271053/180570136-530af3b6-a545-4a84-a03a-251cd40e9bc0.png">

<img width="461" alt="imgur-toolbar" src="https://user-images.githubusercontent.com/1271053/180570549-80245b1b-4cdf-453c-8aca-cd8dc9720491.png">

<img width="455" alt="imgur-transform" src="https://user-images.githubusercontent.com/1271053/180569938-f553905f-cc11-4808-8c61-d9a4f51bef0c.png">

<img width="1000" alt="imgur-transform-group" src="https://user-images.githubusercontent.com/1271053/180569951-f6b6bfa3-eae4-42a9-80af-06f467dded71.png">

<img width="538" alt="imgur-front-end-transform" src="https://user-images.githubusercontent.com/1271053/180569977-3d6377d0-039e-4330-9545-6281c3a50ffb.png">

Transform > Columns is new:

<img width="1000" alt="imgur-transform-columns" src="https://user-images.githubusercontent.com/1271053/180569987-6d8fb90a-f072-43cd-a6a2-23edbbb21135.png">

<img width="455" alt="imgur-alignment" src="https://user-images.githubusercontent.com/1271053/180570649-22328e87-7e7d-4839-8f15-30bebad766d1.png">

<img width="674" alt="imgur-edit" src="https://user-images.githubusercontent.com/1271053/180570676-07c878cc-2d0c-47a0-b8f7-92f05c60a8a6.png">

<img width="271" alt="imgur-more" src="https://user-images.githubusercontent.com/1271053/180570722-3e7fed35-0a51-4667-81d7-9b8a347f9b68.png">

<img width="668" alt="imgur-html" src="https://user-images.githubusercontent.com/1271053/180570754-c4aceae2-13a7-4d7b-bab5-bea59fb93dbd.png">

<img width="281" alt="imgur-advanced" src="https://user-images.githubusercontent.com/1271053/180570778-c99f7828-ad45-4afa-8e97-623fddefc6c8.png">

**Comment by colorful-tones** [comment]
@femkreations This is ready for review and publishing. Screenshots are all updated. Nice job @dreamwhisper 👏

**Comment by femkreations** [comment]
Thank you for your work @colorful-tones and @dreamwhisper. The page is published with updates. I also updated the changelog and added ALT tags for the images.

https://wordpress.org/support/article/imgur-embed/
