### ISSUE TITLE
[HelpHub] Facebook

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#184]
Article: https://wordpress.org/support/article/facebook-embed/

Discontinued in WordPress 5.6.

## General
- [ ] make sure all screenshots/videos are relevant for the last WordPress version that supports it (5.6)
- [ ] update changelog at the end of the article
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/I9hzt2m2/25-facebook

**Comment by Ignasrimkunas** [comment]
@femkreations heya i will take this one

**Comment by Ignasrimkunas** [comment]
@femkreations @zzap  ready for review https://docs.google.com/document/d/1xUIuKR2jCwmncahS_viduwIPb-eGolxa8mB3Zi3ovC8/edit?usp=sharing

**Comment by femkreations** [comment]
Thanks for your work @Ignasrimkunas Reviewed and updated the page.
https://wordpress.org/support/article/facebook-embed/
