### ISSUE TITLE
[HelpHub] TED

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#185]
Article: https://wordpress.org/support/article/ted-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/W9PCz7KJ/54-ted

**Comment by anyk17** [comment]
Screenshots update
![02-embed_link](https://user-images.githubusercontent.com/19748471/164078542-ce35231a-3c68-44a6-a444-bb3e95f25b06.jpg)
![03-ted_video](https://user-images.githubusercontent.com/19748471/164078545-f0e6ffd6-0d17-41f2-81f9-cf520e90fe04.jpg)
![04-preview](https://user-images.githubusercontent.com/19748471/164078548-f84c9d85-1629-483b-b0e6-5d2f44a5e05b.jpg)
![05-transform](https://user-images.githubusercontent.com/19748471/164078549-a1896cb8-829b-40c9-b455-cbaf7fd1a0aa.jpg)
![06-background]
![17-media_settings_enabled](https://user-images.githubusercontent.com/19748471/164078585-fd44d6e7-caad-499d-a137-12787b7b4609.jpg)
![18-media_settings_disabled](https://user-images.githubusercontent.com/19748471/164078587-ccbf9fae-609b-464e-bc2a-2fa9606ff4ba.jpg)
![19-advanced_settings](https://user-images.githubusercontent.com/19748471/164078592-f7736d98-39d6-42f3-86d7-d0214d81c444.jpg)
(https://user-images.githubusercontent.com/19748471/164078550-b8e79876-66ba-413a-b56a-3aac70b80559.jpg)
![07-background_preview](https://user-images.githubusercontent.com/19748471/164078551-e5d90e2a-e5ef-453c-9407-4a569d942612.jpg)
![08-alignment](https://user-images.githubusercontent.com/19748471/164078552-e6521bcd-d1de-40db-8c0e-8b084f3c704c.jpg)
![09-edit_url](https://user-images.githubusercontent.com/19748471/164078554-4dfd2532-6046-4bee-8f50-f6a4e9ebeabf.jpg)
![10-hide_block](https://user-images.githubusercontent.com/19748471/164078557-235e989d-5dc7-4b71-8f46-2bee8e705074.jpg)
![11-edit_html](https://user-images.githubusercontent.com/19748471/164078559-1cfb7d52-ff39-4545-b1ad-7c0b1cc0c96d.jpg)
![toolbar](https://user-images.githubusercontent.com/19748471/164078561-39630be0-6ccb-4968-8013-f4a44c0e30de.jpg)
![01-ted_block](https://user-images.githubusercontent.com/19748471/164078564-df44d78a-18f4-4b31-887b-9802d4d18d8a.jpg)
d

**Comment by anyk17** [comment]
Yes, definitely. I can take care of the update 😄

**Comment by zzap** [comment]
Thank you :heart:
