### ISSUE TITLE
[HelpHub] Scribd

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#186]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/scribd-embed/

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/Ib6QK6B8/51-scribd

**Comment by samxmunoz** [comment]
I can take this one. 👋🏼

**Comment by samxmunoz** [comment]
@femkreations / @zzap - This article has been updated & is ready for review! 🎉

**Comment by femkreations** [comment]
Looks good @samxmunoz Thank you.
