### ISSUE TITLE
[HelpHub] WordPress

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#187]
Article: https://wordpress.org/support/article/wordpress-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/pbHaV7GM/26-wordpress

**Comment by authentic29** [comment]
mm

**Comment by Codebrother1** [comment]
### Part 1

**This fixes #109** 
**An Example:**
![2022-02-22_16-56-36](https://user-images.githubusercontent.com/20616836/155233584-f1b85b8b-fbdb-434c-b950-66a0d407bc3a.png)

**Go to your post or page**
**Add the WordPress block**
![2022-02-22_16-48-34](https://user-images.githubusercontent.com/20616836/155233245-60b63bd9-46d1-4251-9420-029355e70d4b.png)

**Paste the link into the text box and click the “Embed” button**
![2022-02-22_17-01-45](https://user-images.githubusercontent.com/20616836/155234216-7240c98a-ea04-49d2-b2bd-4b4198802b63.png)

**If it’s a link that can be successfully embedded you will see a preview in your editor.**
Still working on this one check below 👇🏾

**If you’re using a link that cannot be embedded, the block shows a message, Sorry, this content could not be embedded**

![2022-02-22_17-09-12](https://user-images.githubusercontent.com/20616836/155235027-68807f45-152e-4a4e-bb9e-94cc1b137ab6.png)


**Click on “Preview” to see how it will look on the front-end.**
![2022-02-22_17-12-15](https://user-images.githubusercontent.com/20616836/155235324-a8004734-1843-4c87-838f-ff49d041cac3.png)

**Block Toolbar**
![2022-02-22_17-17-23](https://user-images.githubusercontent.com/20616836/155236019-ba09c31c-890a-4d1f-a488-91327e3568f3.png)

**Transform to**
![2022-02-22_17-19-41](https://user-images.githubusercontent.com/20616836/155236194-b9245d2f-62b1-4740-92c8-ae57ff1446d4.png)

**You can transform a WordPress embed to a Group. This would give you the ability to change the background color around the WordPress embed.**


Change alignment
Edit URL, and
More Options. 

To be continued.....

**Comment by zzap** [comment]
Looking good @Codebrother1 , thank you so much :heart: 

Would you like to update the article yourself?

**Comment by Codebrother1** [comment]
Yes @zzap , I will update!

**Comment by Codebrother1** [comment]
@zzap The article is updated with a changelog at the end of the article 2022-04-19

https://wordpress.org/support/article/wordpress-embed/
