### ISSUE TITLE
[HelpHub] Vimeo

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#188]
Article: https://wordpress.org/support/article/vimeo-embed/

## General
- [ ] make sure all screenshots/videos are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/YstvNPmR/30-vimeo

**Comment by Codebrother1** [comment]
This fixes #188
**Embedded Vimeo Video**
![2022-02-15_10-47-18](https://user-images.githubusercontent.com/20616836/154610847-fc01cf39-6b77-4740-b980-5686f759e2db.png)

**Add a Vimeo Embed block to your post**
![2022-02-15_10-48-41](https://user-images.githubusercontent.com/20616836/154610911-499e540a-bf01-401d-96f0-e565ce5ecd8b.png)

**Paste the Vimeo URL from Step 1**
![2022-02-15_10-49-56](https://user-images.githubusercontent.com/20616836/154611012-737d1d90-6025-4fee-80b3-f392358c0989.png)

**Click the Embed button**
![2022-02-15_10-51-28](https://user-images.githubusercontent.com/20616836/154611091-621c5a68-d277-4370-ac78-369fe5fcbb79.png)

**"Sorry, this content could not be embedded.” **
![2022-02-15_10-53-31](https://user-images.githubusercontent.com/20616836/154611179-0282aa12-ac54-4f3f-b20e-0142a72a7ab7.png)

**You’ll see the Vimeo player on your WordPress editor if you successfully embed a Vimeo video**
![2022-02-15_10-47-18](https://user-images.githubusercontent.com/20616836/154611301-7c5f2415-737f-4055-964f-c9b68baa0ce7.png)

Transform to
Change alignment
Edit URL, and
More Options
![2022-02-15_10-57-10](https://user-images.githubusercontent.com/20616836/154611389-012a95a5-dabb-448a-8323-ba52144952be.png)

**Transform to**

![2022-02-15_10-59-52](https://user-images.githubusercontent.com/20616836/154611481-81e9e9fd-f127-4b55-989d-facf2a5701ad.png)

**You can transform a Vimeo embed block into a Group. This would give you the ability to change the background color around the Vimeo embed.**
![2022-02-15_11-01-10](https://user-images.githubusercontent.com/20616836/154611534-5547c992-45a4-471c-a925-c83ee6816432.png)

**Change Alignment**

![2022-02-17_21-00-57](https://user-images.githubusercontent.com/20616836/154611609-181208d6-8a52-4813-9418-8df683e4cdd9.png)

**Via the Edit URL, you can change the TikTok Embed URL in the embed block. Overwrite the existing URL and click on the Embed button.**

![2022-02-17_21-02-20](https://user-images.githubusercontent.com/20616836/154611683-c2f565bf-f547-4b2e-8264-921b61b190fe.png)


**More Options**

![2022-02-17_21-03-40](https://user-images.githubusercontent.com/20616836/154611719-1b75e6f3-e77c-4f68-b508-15fbd6d68ee2.png)

**Comment by zzap** [comment]
Hello @Codebrother1, thank you so much for making these :heart: 

I have two requests, if it's possible. 

1. Can you create a screenshot of video with changed background color. Currently we have it with gray

![image11-edited-2](https://user-images.githubusercontent.com/1508963/154949756-e13857e9-9626-4bb8-ab20-68b8b9163d2b.png)

2. Can you edit out grammarly logo from screenshots. It's important to show only what is in default WordPress.

Thank you.

**Comment by Codebrother1** [comment]
Sure thing! This fixes 
I created a screenshot of the video with a background color changed to grey.
I removed the Grammarly logo from your screenshots.

**Embedded Vimeo Video**
![2022-02-21_22-28-58](https://user-images.githubusercontent.com/20616836/155063476-17381b5f-9a8e-443a-a16c-2deddbae81ee.png)

**Add a Vimeo Embed block to your post**
![2022-02-21_22-34-28](https://user-images.githubusercontent.com/20616836/155063799-65e65fa8-901f-43f8-a1be-ae8a982c7be5.png)

**Paste the Vimeo URL from Step 1**
![2022-02-21_22-36-30](https://user-images.githubusercontent.com/20616836/155063970-818f8002-c690-47e9-a900-520b6fdaceda.png)

**Click the Embed button**
![2022-02-21_22-38-30](https://user-images.githubusercontent.com/20616836/155064169-f8522b2d-b38b-4159-8c0b-974e22c09361.png)

**Sorry, this content could not be embedded.**
![2022-02-21_22-43-04](https://user-images.githubusercontent.com/20616836/155064459-fb7c56f3-c4d4-4b48-a0e8-093d852bf681.png)

**You’ll see the Vimeo player on your WordPress editor if you successfully embed a Vimeo video**
![2022-02-21_22-28-58](https://user-images.githubusercontent.com/20616836/155064604-ae7c6863-7102-4f2a-aa38-2bfc3ad8190d.png)


**Vimeo embed with a gray background-color**

![2022-02-21_22-59-13](https://user-images.githubusercontent.com/20616836/155066043-fe63b6af-d1a8-4bf9-88b3-c31e855cec33.png)

**Comment by zzap** [comment]
Looking great, thank you so much. Do you want to update the article yourself?

**Comment by Codebrother1** [comment]
Yes, I'd like to give it a try
