### ISSUE TITLE
[Theme Review Handbook] Creating a FAQ page for Theme Review 

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#189]
Theme authors regularly ask similar questions on Slack. Some authors post a question over a weekend and wait for a long time for a response. It would be helpful for both authors and reviewers to have a list of frequently asked questions on the Review Handbook where everyone can quickly look for an answer. 

Please note that the list of FAQs is not meant to add additional requirements. It is for clarification purposes only. 

Here are some of the questions. 

Q.  Can I include custom controls or options to my block theme?
A. No. Any custom controls or options are considered a plugin territory. Anything that would be deleted after users switching themes should not be included in a theme. 

Q. My theme requires a plugin in order to work. Can I include a plugin in the theme?
A. No. Themes are not allowed to include a plugin. Learn more about the [requirements](https://make.wordpress.org/themes/handbook/review/required/#6-plugins). 

Q. Can I change the name of my theme that is already on the directory? 
A. No. It is not possible to rename themes in the directory. 

Q. Can my screenshot look like my demo site even though I use a plugin to create a demo site? 
A. Yes, a screenshot is to give an idea how the theme would look. You can recommend a plugin or let user know which plugin you uses to build the demo site.

**Comment by joyously** [comment]
Is this like https://make.wordpress.org/themes/handbook/faq/  ?

**Comment by TeBenachi** [comment]
👀 Yes!!
I had no idea there was one already!  Thanks for the link!

**Comment by zzap** [comment]
@TeBenachi can we close this issue now or is there something else you'd like to use it for?

**Comment by TeBenachi** [comment]
Yep I can do that. I was planning on creating a new list of QA but it is taking longer than I was hoping. I will create a new ticket then. Thanks!
