### ISSUE TITLE
v5.6 configuring-automatic-background-updates and WP_AUTO_UPDATE_CORE

### ISSUE THREAD

**Issue by TonyGravagno** [WordPress/Documentation-Issue-Tracker#191]
## Issue Description
Info for WP_AUTO_UPDATE_CORE needs more work for WP 5.6+. It's missing detail and the original update to this text for v5.6 is ambiguous.

## URL of the Page with the Issue
https://wordpress.org/support/article/configuring-automatic-background-updates/

## Section of Page with the issue
Constant to Configure Core Updates

## Why is this a problem?
Text from the page:
> For development sites, the default value of WP_AUTO_UPDATE_CORE is true. For other sites, the default value of WP_AUTO_UPDATE_CORE is minor.
> Starting WordPress 5.6, the default value of WP_AUTO_UPDATE_CORE for new WordPress installations is true. For new website, the default value of WP_AUTO_UPDATE_CORE is minor.

- The first paragraph should be past-tense.
- The second paragraph is contradictory.
- Default is not clear for a v5.6+ development site.
- It looks like it's making a distinction of "new installation" and "new website", but this doesn't make sense (to me) even in the context of a multi-site installation.

Also Ref: [https://make.wordpress.org/core/2020/11/02](https://make.wordpress.org/core/2020/11/02/introducing-auto-updates-interface-for-core-major-versions-in-wordpress-5-6/)
According to that, the value of WP_AUTO_UPDATE_CORE can also be `beta` or `rc` - not yet documented on this page.

## Suggested Fix
I'm hoping we can take this slow. This isn't just a text edit.

It might be good to give pre-v5.6 only a casual mention, or maybe a separate page. Current functionality should be profiled in clear text, bullets, table, whatever. I'm trying to avoid having old data profiled along with current data, which would only confuse newcomers who don't care about the history. That's the condition of the text right now.

I think a matrix would be helpful, though it might be overkill - I dunno yet. Consider a table:   
Columns are for the potential values of WP_AUTO_UPDATE_CORE : true, false, minor, beta, rc.  
Rows are for possible installation types : production, development, beta, rc.  
Each cell of the table might identify exactly what gets auto-updated in that installation type with that setting.

On creation of such a table it might be evident that this is much simpler than it seems - or that more columns or rows are required.

But a table might also make all of the filter options very clear. Right now it's not clear if the documented filters apply to pre-5.6 and/or v5.6+. It's also not clear if "beta" and "rc" are considered "dev" systems. If positioned in the table this would be very clear.

I can take a shot at a table or new text, if someone with insight thinks its a good idea. I have to wonder if someone already has a table like this, perhaps created when v5.6 was being modified, or for QA. It will take a while for me to research all of this - though I am motivated as right now I'm writing code that integrates with all of this.

Thanks for your time.

**Comment by zzap** [comment]
Hello @TonyGravagno , thank you very much for reporting this. 

As, at the moment, we don't have documentation based on pased versions (even though it is planned for the future), we are focusing only on current possibilities. So everything that's not true for current version has to go. 

If you are willing and still motivated, it would be great if you'd take this task on you. After all, you are in the topic right now, as you said. Thank you.

**Comment by TonyGravagno** [comment]
OK, I'll take this on and do my best to create brief new content that is completely current. Please keep this open and assign to me if you wish. Thanks.
