### ISSUE TITLE
[HelpHub] Site Logo 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#193]
## What is the new page you are requesting?

New article required for the Site Logo block

## General

- [x] make sure all screenshots are relevant for the current version (5.9)
- [x] update changelog at the end of the article

**Comment by zzap** [comment]
Duplicate of #88

**Comment by femkreations** [comment]
https://wordpress.org/support/article/site-logo-block/ New page created and updated for 6.0 with screenshots, content and video. @zzap
