### ISSUE TITLE
[HelpHub] Site Tagline

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#194]
## What is the new page you are requesting?
New article required for the Site Tagline block

## General
- [ ] make sure all screenshots are relevant for the current version (5.9)
 - [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap The page is ready for review: https://wordpress.org/support/article/site-tagline-block/
I didnt see any updates for 6.0 (refered to Birgit's 6.0 End User documenation.) Hence published the page.
Thanks!

**Comment by zzap** [comment]
Looks great! Awesome job, as usual :heart:
