### ISSUE TITLE
[HelpHub] Site Title 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#195]
## What is the new page you are requesting?
New article required for the Site Title block

## General
 - [ ] make sure all screenshots are relevant for current version (5.9)
 - [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap This page is ready and primed for 6.0. It is currently scheduled to be published on May 24, 2022.
Pls review:
https://wordpress.org/support/?post_type=helphub_article&p=15525633
Thanks!

**Comment by zzap** [comment]
Looking great. Thank you :heart:
