### ISSUE TITLE
[HelpHub] Post Title

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#196]
## What is the new page you are requesting?

New article required for the Post Title block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap The page is ready for review: https://wordpress.org/support/article/post-title-block/

**Comment by zzap** [comment]
Looks great. Thank you @femkreations :heart:
