### ISSUE TITLE
[HelpHub] Post Content

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#197]
## What is the new page you are requesting?

New article required for the Post Content block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap: The page is ready: https://wordpress.org/support/article/post-content-block/ . Thanks!

**Comment by zzap** [comment]
Looks awesome :raised_hands: Thank you so much :heart:
