### ISSUE TITLE
[HelpHub] Post Date

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#198]
## What is the new page you are requesting?

New article required for the Post Date block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap The page is ready for review: https://wordpress.org/support/article/post-date-block/

**Comment by femkreations** [comment]
@zzap  Thanks for catching that. I updated to remove the wrong screenshot.

**Comment by zzap** [comment]
Awesome, thanks :raised_hands:
