### ISSUE TITLE
[HelpHub] Post Excerpt

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#199]
## What is the new page you are requesting?

New article required for the Post Excerpt block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap: This page is ready for review: https://wordpress.org/support/article/post-excerpt-block/

**Comment by zzap** [comment]
Great work, as always. Thank you :heart:
