### ISSUE TITLE
Repeating names in headers on the loop doc page

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#2]
On page https://developer.wordpress.org/themes/basics/the-loop/ , the last two headers seem to have some duplication in them (repeating the function name twice).

**Comment by joyously** [comment]
It seems to be a problem with the headings containing links.
> Using rewind_posts()
> Using wp_reset_postdata()
> Using wp_reset_query()

Perhaps the Table of Contents plugin is messing it up.

**Comment by atachibana** [comment]
@joyously 

Thank you. You are 100% correct.
The heading that includes function name with parentheses causes this duplicating error. I modified the heading string (by removing parentheses) and fixed this issue.
