### ISSUE TITLE
[HelpHub] Post Featured Image

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#200]
## What is the new page you are requesting?

New article required for the Post Featured Image block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap The page is ready for review: https://wordpress.org/support/article/post-featured-image/

**Comment by zzap** [comment]
Awesome work :heart:
