### ISSUE TITLE
[HelpHub] Login/out 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#203]
## What is the new page you are requesting?

New article required for the Login/out block

## New page 
- [ ] Create a new article for the Login/out block 
- [ ] Make sure the URL slug under Permalink is: login-out-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Update for 6.1
- [ ] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by hannaw93** [comment]
I will pick this one up :)

**Comment by hannaw93** [comment]
Started on a new article :) https://wordpress.org/support/wp-admin/post.php?post=16008957&action=edit

**Comment by femkreations** [comment]
@hannaw93 are you still working on this?

**Comment by sagargurnani99** [comment]
I have created a new article (saved as draft). Request someone to review it.
cc - @zzap 

Article URL: https://wordpress.org/documentation/wp-admin/post.php?post=16359310&action=edit

**Comment by atachibana** [comment]
@sagargurnani99 

It looks good to me. 
Please add ALT text for two screenshots. After that, you can publish this page.

> 6.1 update

No, you don't need do anything for it. As you say, this PR is developer related.

**Comment by sagargurnani99** [comment]
Thank you so much @atachibana. I have added the alt text to all the screenshots in the article and published the same.
• https://wordpress.org/documentation/article/login-out-block/

This issue can be closed now.
