### ISSUE TITLE
[HelpHub] Amazon Kindle

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#205]
## What is the new page you are requesting?

New article required for the Amazon Kindle block

## New page for 6.0
- [ ] Create a new article for the Amazon Kindle Embed block
- [ ] Make sure the URL slug under Permalink is: amazon-kindle-embed-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Add ALT tags for images
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@zzap @femkreations Heya will take this one

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1cby9XFLIWjWYdrJhcOz-NTV_4PVwKI5RWcFPsRBkDIQ/edit

@Ignasrimkunas edited, @femkreations 1st review is done, ready for you

**Comment by femkreations** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung for the content and review.  I've added the content to the article.

https://wordpress.org/support/article/amazon-kindle-embed-block/

Also updated the link in the blocks main page and the embeds page to point to this page. Thanks
