### ISSUE TITLE
Duplicate headers in API reference

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#21]
On https://developer.wordpress.org/rest-api/reference/users/, there are duplication on the topics list for entries: "Update a User", "Retrieve a User", "Delete a User".

I would suggest distinguish between them by change them to, e.g., "Update Any User" or "Update a User by ID" and "Update the User Currently Logged In".

**Comment by zzap** [comment]
Same as the other REST API issues, #9 and #10 , this one should be reported in [REST API repo](https://github.com/WP-API/docs/issues). Thanks
