### ISSUE TITLE
[HelpHub] Embed

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#218]
## What is the new page you are requesting?

New article required for the Embed block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by anyk17** [comment]
Hey! I'd like to work on this task

**Comment by anyk17** [comment]
I've created this draft https://wordpress.org/support/wp-admin/post.php?post=15596148&action=edit. Let me know if it's ok to publish

**Comment by femkreations** [comment]
@anyk17 This page looks great. I added in the ALT tags for the images and published it.

https://wordpress.org/support/article/embed-block/
