### ISSUE TITLE
[HelpHub] Home Link

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#219]
## What is the new page you are requesting?

New article required for the Home Link block

## New page for 6.0
- [ ] Create a new article for the Home Link block 
- [ ] Note that this block is visible only when the user is in the Navigation block (contextual)
- [ ] Make sure the URL slug under Permalink is: home-link-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by blogsmithteam** [comment]
I could take this too @femkreations

**Comment by femkreations** [comment]
@blogsmithteam Assigned this to you as well Let me know if you don't want to work on this any more. Thanks much

**Comment by femkreations** [comment]
@blogsmithteam Pls let us know if you are working on this and have any updates. Thanks

**Comment by pls78** [comment]
# Home Link Block
The _Home link_ block allows you to automatically add a link to your site's homepage.

**Note**: the _Home link_ block is only available as a sub-block of the _Navigation_ block

## How to Use the Home Link Block

To add a _Home link_ block, you first need to create a _Navigation_ block in a post or Site Editor.  For a detailed explanation about the _Navigation_ block see [this link](https://wordpress.com/support/site-editing/theme-blocks/navigation-block/).

With the _Navigation_ block selected, there are three ways you can use to add a _Home link_ block:
* through the sidebar 
* through the _Navigation_ block contextual menu 
* by converting an existing block

## Adding the Home Link through the sidebar

With the _Navigation_ block selected, click on the (**+**) icon in the sidebar, and either select the _Home link_ block from the list of your recently used blocks or click on _Browse all_ to show all the available blocks and select it from there. 

![sidebar_AdobeExpress](https://user-images.githubusercontent.com/68744851/232058336-08886952-5922-4bf4-ab6c-d50932c1e819.gif)

## Adding the Home Link Through the Navigation Block Contextual Menu
With the _Navigation_ block selected, click on the (**+**) icon inside the _Navigation_, and either select the _Home link_ block from the list of your recently used blocks or click on _Browse all_ to show all the available blocks and select it from there. 

![Add_after_other_AdobeExpress](https://user-images.githubusercontent.com/68744851/232063559-0d1d7d56-21db-4c04-87bd-f339e681096e.gif)

## Adding the Home Link by Converting an Existing Block

Select an already-existing sub-block inside the _Navigation_ block and click on the icon to the left of the _Drag_ tool, which represents the actual sub-block. Select the _Home link_ block from the drop-down menu.

![convert_AdobeExpress](https://user-images.githubusercontent.com/68744851/232065572-0d6b6269-7fd6-436f-ba2a-c287245763f4.gif)

**Comment by pls78** [comment]
@zzap The above is ready to be reviewed 🙂

**Comment by femkreations** [comment]
Thank you for the content. I have created a new page and added the content you provided. Also added in the missing details for Block settings and Block toolbar, added ALT tags and created the page.

https://wordpress.org/documentation/article/home-link-block/
