### ISSUE TITLE
Using Caddy to harden WordPress

### ISSUE THREAD

**Issue by basilhendroff** [WordPress/Documentation-Issue-Tracker#22]
---

## Issue Description

Only Apache examples are provided,
## URL of the Page with the Issue

[Hardening WordPress](https://wordpress.org/support/article/hardening-wordpress/)
## Sections of the Page with the issue

[Securing wp-includes](https://wordpress.org/support/article/hardening-wordpress/#securing-wp-includes)
[Securing wp-config.php](https://wordpress.org/support/article/hardening-wordpress/#securing-wp-config-php)
## Why is this a problem?

Examples for other webservers will make these sections more useful.
## Suggested Fixes

Immediately after the text...

### Securing wp-includes [#](https://wordpress.org/support/article/hardening-wordpress/#securing-wp-includes)

>A second layer of protection can be added where scripts are generally not intended to be accessed by any user. One way to do that is to block those scripts using mod_rewrite in the .htaccess file. **Note:** to ensure the code below is not overwritten by WordPress, place it outside the `# BEGIN WordPress` and `# END WordPress` tags in the .htaccess file. WordPress can overwrite anything between these tags.

```
# Block the include-only files. 
<IfModule mod_rewrite.c> 
RewriteEngine On 
RewriteBase / 
RewriteRule ^wp-admin/includes/ - [F,L] 
RewriteRule !^wp-includes/ - [S=3] 
RewriteRule ^wp-includes/[^/]+\.php$ - [F,L] 
RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F,L] 
RewriteRule ^wp-includes/theme-compat/ - [F,L] 
</IfModule> 

# BEGIN WordPress
```
> Note that this won’t work well on Multisite, as `RewriteRule ^wp-includes/[^/]+\.php$ - [F,L]` would prevent the ms-files.php file from generating images. Omitting that line will allow the code to work, but offers less security.

... add in the following text...

>For a Caddy web server, use a named matcher set to secure the include paths while still allowing access to `ms-files.php` for multisite.
```
    @forbidden {
        not path /wp-includes/ms-files.php
        path /wp-admin/includes*
        path /wp-includes*
    }
    respond @forbidden "Access denied" 403
```

... and immediately after the text...

### Securing wp-config.php [#](https://wordpress.org/support/article/hardening-wordpress/#securing-wp-config-php)

> You can move the `wp-config.php` file to the directory above your WordPress install. This means for a site installed in the root of your webspace, you can store `wp-config.php` outside the web-root folder.
>
>**Note:** Some people assert that [moving wp-config.php has minimal security benefits](http://wordpress.stackexchange.com/q/58391/3898) and, if not done carefully, may actually introduce serious vulnerabilities. [Others disagree](http://wordpress.stackexchange.com/a/74972/24425).
>
>Note that `wp-config.php` can be stored ONE directory level above the WordPress (where wp-includes resides) installation. Also, make sure that only you (and the web server) can read this file (it generally means a 400 or 440 permission).
>
>If you use a server with .htaccess, you can put this in that file (at the very top) to deny access to anyone surfing for it:
```
<files wp-config.php> 
order allow,deny 
deny from all 
</files>
```
... add in the following text...

>For a Caddy web server, add the `wp-config.php` path to the named matcher set described under [Securing wp-includes](https://wordpress.org/support/article/hardening-wordpress/#securing-wp-includes).  This will prevent access to `wp-config.php` in the webroot,
```
        path /wp-config.php
``` 
## Links to relevant resources
1. The suggested text and code was discussed extensively with Caddy core maintainers in this Caddy forum thread [Using Caddy to harden WordPress](https://caddy.community/t/using-caddy-to-harden-wordpress/13390).

**Comment by zzap** [comment]
Same as #23 

Thanks

**Comment by basilhendroff** [comment]
Hi @zzap,

> I suggest writing a blog post/tutorial and submitting link to review for possible `See Also` resource.

I would be pleased to do this for the issue, however, I have adopted exactly this approach with issue #6 and it also was rejected. There does not appear to be a consistent methodology between doc maintainers.

Can I also suggest that issues are not closed initially, but feedback provided to contributors? This will allow contributors a chance to respond to the feedback.  This will save the contributor from having to open the issue a second time.

**Comment by basilhendroff** [comment]
@zzap Please consider adding the following link for a `See Also` resource:

[Using Caddy to harden WordPress](https://caddy.community/t/using-caddy-to-harden-wordpress/13575)

**Comment by zzap** [comment]
I'm adding `external links` label and reopening issue so that we can discuss relevance for external resource. For reference see https://github.com/WordPress/Documentation-Issue-Tracker/issues/8#issuecomment-915085945

**Comment by javiercasares** [comment]
Maybe the documentation about Caddy should be at the Hosting Documentation

**Comment by atachibana** [comment]
New repository "Advanced Administration" was created, and this page will be moved to there. Continue the discussion at this issue:
https://github.com/WordPress/Advanced-administration-handbook/issues/152
