### ISSUE TITLE
[HelpHub] Custom Link

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#222]
## What is the new page you are requesting?

New article required for the Custom Link block

## New page for 6.0
- [x] Create a new article for the Custom Link block 
- [x] Note that this block is visible only when the user is in the Navigation block (contextual)
- [x] Make sure the URL slug under Permalink is: custom-link-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by blogsmithteam** [comment]
Can I take this one @femkreations?

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by blogsmithteam** [comment]
@zzap @femkreations Here: https://docs.google.com/document/d/1uww5LqEqQiNeMwhUyGKEmrFYChm3QHkNHpV_tq8nmTY/edit?usp=sharing

**Comment by Leonardus-Nugraha** [comment]
Thanks @blogsmithteam for the great article! It's published here: https://wordpress.org/support/article/custom-link-block/
@femkreations, I've added the page to https://wordpress.org/support/article/blocks/ as a sub-item of Navigation block (previously there's no sub-item for that)
