### ISSUE TITLE
[HelpHub] Post Author Biography

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#226]
## What is the new page you are requesting?

New article required for the Post Author Biography block

## New page for 6.0
- [ ] Create a new article for the Post Author Biography block 
- [ ] Make sure the URL slug under Permalink is: post-author-biography-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Add ALT tags for images
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by leon-nugraha** [comment]
@femkreations I'll work on this

**Comment by leon-nugraha** [comment]
@femkreations ready for review
https://docs.google.com/document/d/1xsih9lU4TolixS3uQSVGGfv5ARdHDuuVP5Dc1H2LGGg/edit

**Comment by emmasophieyoung** [comment]
i'll review this

**Comment by emmasophieyoung** [comment]
@femkreations - This is reviewed and ready for you 

Style match the rest of the pages
Screenshots are updated
Headings are all sentence case

Didn't do ->  ALT tags are in for the images

**Comment by Leonardus-Nugraha** [comment]
@femkreations seems like this issue is a duplicate of https://github.com/WordPress/Documentation-Issue-Tracker/issues/267 and there's an article already for this article. Should this issue be closed?

**Comment by femkreations** [comment]
Closing this as this is a duplicate.
