### ISSUE TITLE
[HelpHub] Post Comments Form

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#232]
## What is the new page you are requesting?

New article required for the Post Comments Form block

## New page 
- [ ] Create a new article for the Post Comments Form block
- [ ] Make sure the URL slug under Permalink is: post-comments-form-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Updates for 6.1
- [ ] Add button that enables commenting to warning. [41603](https://github.com/WordPress/gutenberg/pull/41603)
- [ ] Improve the logic for warnings for Post Comments Form placeholder. [40563](https://github.com/WordPress/gutenberg/pull/40563)
- [ ] Add "proper" visual representation in the editor. [40368](https://github.com/WordPress/gutenberg/pull/40368)
- [ ] Fix layout quirks. [40359](https://github.com/WordPress/gutenberg/pull/40359)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@femkreations Heya, assign me this one. Thanks!

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1sIilM3SQENjy0szjIwAc12Xe8SVR_Rwb2CuFeQUnKOg/edit

**Comment by emmasophieyoung** [comment]
i'll review this

**Comment by emmasophieyoung** [comment]
@femkreations - This is reviewed and ready for you 

Style match the rest of the pages
Screenshots are updated
Headings are all sentence case

Didn't do ->  ALT tags are in for the images

**Comment by femkreations** [comment]
Adding tasks for 6.1 .

## Notes
1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by Ignasrimkunas** [comment]
@femkreations Heya, I've reworked the article: https://docs.google.com/document/d/1sIilM3SQENjy0szjIwAc12Xe8SVR_Rwb2CuFeQUnKOg/edit?usp=sharing

- Went over the updates for 6.1 section, added new information along with GIF (similar to the one found in PR)
- Updated all the screenshots along with the More options button section (some functionality was removed, like the "Select parent block" button)
- Only left placeholders for Block settings while removing all the rest of the content

**Comment by carolinan** [comment]
Text content and images look correct to me 👍

**Comment by femkreations** [comment]
Looks great. Thanks @Ignasrimkunas and @carolinan for your work. I added the Transform to option in the Block toolbar.
Finished page: https://wordpress.org/support/article/post-comments-form-block/
