### ISSUE TITLE
[HelpHub] Post Navigation Link

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#234]
## What is the new page you are requesting?

New article required for the Post Navigation Link block

## General

- [x] make sure all screenshots are relevant for the current version (5.9)
- [x] update changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha I will take this one

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1g7L7QMmwn4VjlBnasqJNOEp-z8UNlEGJPsJVI6TvLig/edit

@Leonardus-Nugraha this one is good to go

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas & @emmasophieyoung!
Published here: https://wordpress.org/support/article/post-navigation-link-block/
