### ISSUE TITLE
[HelpHub] Post Template

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#235]
## What is the new page you are requesting?

New article required for the Post Template block

## New page 
- [ ] Create a new article for the Post Template block 
- [ ] Make sure the URL slug under Permalink is: post-template-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Updating for 6.1
- [ ] Template for specific category: only load posts from that category in post template block [43699](https://github.com/WordPress/gutenberg/pull/43699)
- [ ] Add typography supports [43342](https://github.com/WordPress/gutenberg/pull/43342)
- [ ] Fix alignments for children of Query block [44144](https://github.com/WordPress/gutenberg/pull/44144)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by yogskr** [comment]
Hi @femkreations! I want to work on this issue.

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article

**Comment by Leonardus-Nugraha** [comment]
Draft: https://docs.google.com/document/d/1Qy9HzUG90VVXPHPxoSAS86YM1K6dtPuA28N3lElyb7A/edit?usp=sharing (written by @yogskr) Waiting for edits/review (cc: @emmasophieyoung)
Commenting here to update the progress :sweat_smile:

**Comment by emmasophieyoung** [comment]
@femkreations 1st review done, ready for you

**Comment by femkreations** [comment]
Thanks @Leonardus-Nugraha @emmasophieyoung and @yogskr for working on the content for this article.
Published the page https://wordpress.org/support/article/post-template-block/
