### ISSUE TITLE
[HelpHub] Previous Post

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#240]
## What is the new page you are requesting?

New article required for the Previous Post  block

## New page
- [x] Create a new article for the Previous Post  block 
- [x] Make sure the URL slug under Permalink is: previous-post-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

## Update for 6.2
- [x] Add arrows to post navigation link [40684](https://github.com/WordPress/gutenberg/pull/40684)

## Update for 6.1
- [x] Post Navigation Link: add design controls  [41378](https://github.com/WordPress/gutenberg/pull/41378)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by blogsmithteam** [comment]
@femkreations I'll take this one if available :)

**Comment by femkreations** [comment]
@blogsmithteam Assigned to you. Let me know if you still want to work on this one as well.

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by carolinan** [comment]
I am not up to date with all the discussions, so I am sorry if this has already been answered.
Is it set in stone that the previous post and the next post should be presented as separate blocks?
Because they are block variations. The actual block is called post navigation link.

**Comment by pls78** [comment]
I'm picking this up 🙂

**Comment by zzap** [comment]
A quick guideline https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/guides/new-article-block-editor.md

**Comment by zzap** [comment]
@carolinan 
> I am not up to date with all the discussions, so I am sorry if this has already been answered. Is it set in stone that the previous post and the next post should be presented as separate blocks? Because they are block variations. The actual block is called post navigation link.

End users don't really know what block variation is, nor should they. The only criteria for end-user docs is "can they see and use it in their dashboard". These blocks can be selected separately from the inserter, so we have to document it. We can and will explain the purpose of these blocks (and how they are used by themes), but we still need to document and explain everything that is user-facing in WordPress.

**Comment by pls78** [comment]
# Previous Post Block
Use the _Previous Post_ block to display a `Previous` link which automatically points to the previous post or page  to the one currently being viewed.

 
<img width="1728" alt="Screenshot 1" src="https://user-images.githubusercontent.com/68744851/231994490-35aa1af1-525f-42cc-8b89-555b6febcff9.png">

Click the (**+**) icon to open the block inserter pop-up window and search for the _Previous post_ blocks. 

![recording_1_AdobeExpress](https://user-images.githubusercontent.com/68744851/232001499-2d09711f-23cc-4332-a600-e5286b850f52.gif)

You can also use the keyboard shortcut _/previous-post_ to quickly add the _Previous post_ block. 

Detailed instructions on adding blocks can be found [here](https://wordpress.org/documentation/article/adding-a-new-block/).

## Block toolbar

To view the block toolbar, click on the block, and the toolbar will be displayed.

Every block comes with unique toolbar icons. These block-specific controls allow you to manipulate the block right in the editor.

The _Previous post_ block shows seven buttons in the block toolbar:

<img width="306" alt="Screenshot 2" src="https://user-images.githubusercontent.com/68744851/232003929-071dd973-63ac-4aa2-af32-8f8ba41fd899.png">

* Transform to
* Drag
* Move up/down
* Change text alignment
* Bold
* Italic
* Options

### Transform to
The transform button on the Previous post block toolbar

Click on the **Transform** button to convert the _Previous post_  block into a _Columns_ or _Group_ block. 

### Drag icon
The drag icon on the Previous post block toolbar

To drag and drop the block to a new location on the page template, click and hold the rectangle of dots, then drag it to the new location. The blue separator line indicates where the block will be placed. Release the left mouse button when you find the new location to place the block.

### Move arrows
The move arrows on the Previous post block toolbar

The **up** and **down** arrow icons can be used to move the block up and down on the page.

Detailed instructions on moving a block within the editor can be found [here](https://wordpress.org/documentation/article/moving-blocks/).

### Change text alignment
Change alignment tool on the Previous post block toolbar

Use the change text alignment tool to change the text alignment for the Post Navigation Link blocks. The following is a list of the block width options:
* Align text left
* Align text center
* Align text right

### Bold
You can select the text in the Previous post block and use the _Bold_ option or <kbd>Ctrl</kbd>+<kbd>b</kbd> or <kbd>Cmd</kbd>+<kbd>b</kbd> on your keyboard to bold it, which is usually heavier than the surrounding text.

### Italic
You can select any text inside the Previous post block and use the _Italic_ option or<kbd>Ctrl</kbd>+<kbd>i</kbd> or <kbd>Cmd</kbd>+<kbd>b</kbd> on your keyboard to italicize it, which usually appears slanted to the right.

### Options
<img width="523" alt="Screenshot 3" src="https://user-images.githubusercontent.com/68744851/232009543-bed75bc1-a9fc-45f1-bf8b-833c4f65f2bd.png">

Options on a block toolbar gives you more features to customize the block.
* _Copy block_ adds the Previous post block to the clipboard. Then, you can paste it anywhere you want in the block editor. 
* _Duplicate_ creates a copy of the selected block that appears after the current block.
* _Insert Before_ inserts a new block before the selected block(s).
* _Insert After_ inserts a new block after the selected block(s).
* _Move to_ lets you use a blue line on the editor to indicate the new position for the selected block. Use your keyboard’s up and down arrows to move the blue line. When the line is in the desired position, press Enter to move the selected block to that position.
* Group allows you to create a group of blocks and treat them as a unit. You can, for instance, add a common background color or other blocks to the group.
* Remove Post Navigation Link deletes the selected block from the content.

#WIP

**Comment by pls78** [comment]
@zzap The above is ready for review 🙂

**Comment by dottxado** [comment]
@zzap I will wait for your review on this issue to update the issue #238  I'm working on 😄

**Comment by Leonardus-Nugraha** [comment]
Content reviewed and published. Thanks @pls78!
