### ISSUE TITLE
[HelpHub] Text Columns 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#245]
## What is the new page you are requesting?

New article required for the Text Columns (deprecated) block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by marconmartins** [comment]
I'm checking this one.

**Comment by femkreations** [comment]
This is a deprecated block and is listed under https://wordpress.org/support/article/blocks/#deprecated. Closing this issue.
