### ISSUE TITLE
[HelpHub] Pinterest

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#247]
## What is the new page you are requesting?

New article required for the Pinterest block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by bph** [comment]
- [GitHub PR with screenshot and information](https://github.com/WordPress/gutenberg/pull/34895)
- [Core Trac Ticket](https://core.trac.wordpress.org/ticket/53448)

**Comment by rmartinezduque** [comment]
Hi! I've been recently working on the article for the Pinterest embed block. I followed the structure of similar articles, such as the [Twitter embed](https://wordpress.org/support/article/twitter-embed/).

- [Google doc for review](https://docs.google.com/document/d/1yffQ3eqAk4aJuaKcp0Tku3OdIEPCjEG-3MhEl8qRngQ/edit?usp=sharing)
- [Screenshots folder](https://drive.google.com/drive/folders/1DpIsEK3_PkDJscf8iioPMTUf2a66s-HY?usp=sharing).

Could you please review it and let me know your thoughts? Thank you!

**Comment by zzap** [comment]
Hi @rmartinezduque , thank you so much for working on this. Text is great, I just left a comment to remove one sentence. As for screenshots being in Spanish, I made those same ones with English. Here they are:

![Pinterest-1](https://user-images.githubusercontent.com/1508963/159518788-98f221a9-6041-4c78-ad41-44a5d302ab49.png)
![Pinterest-2](https://user-images.githubusercontent.com/1508963/159518796-d015af58-0965-4472-8835-161bea0664a2.png)
![Pinterest – bg](https://user-images.githubusercontent.com/1508963/159518801-f0e969af-1041-40be-a2d0-ae472d8a1ff5.png)

Let me know what's your WordPress.org username so I can give you permissions to create new article :tada:

**Comment by rmartinezduque** [comment]
@zzap Thank you for reviewing this so quickly and sending these screenshots! I'll make the changes in the draft now. My WordPress.org username is `rmartinezduque`. 🙂

**Comment by rmartinezduque** [comment]
@zzap just an update here: I included one more screenshot of an embedded Pinterest profile (I was able to get it in English) at the beginning of the article as I thought it would be nice to have another example. If for some reason you think it doesn't fit well, please feel free to let me know. Thank you again!

**Comment by rmartinezduque** [comment]
Hi @zzap! Thanks for the detailed instructions. The preview looked to me, so I went ahead and published it: https://wordpress.org/support/article/pinterest-embed/!

If you could double-check in any case that everything is as it's supposed to be, I'd also appreciate it! Thank you! 🙌

**Comment by zzap** [comment]
>Edit: I've realized that the Changelog is not being displayed in the Topics table. How can I change that?

You can change that by making word `Changelog` a heading. H2 would be semantically correct. Thanks

**Comment by rmartinezduque** [comment]
Done, thank you so much!
