### ISSUE TITLE
Upadte Must Use Plugins DOC

### ISSUE THREAD

**Issue by TukuToi** [WordPress/Documentation-Issue-Tracker#25]
## Issue Description
[This information](https://wordpress.org/support/article/managing-plugins/#must-use-plugins) seems wrong, or at least contradicting to https://wordpress.org/support/article/must-use-plugins/

MU Plugins can by my knowledge be used as well in single installs. It is long time ago that these where `multi user` plugins, now those are `must use` plugins.

## URL of the Page with the Issue
https://wordpress.org/support/article/managing-plugins/

## Section of Page with the issue
https://wordpress.org/support/article/managing-plugins/#must-use-plugins

## Why is this a problem?
It is a main landing page of the WordPress help tabs, and holds what seems wrong information.

## Suggested Fix
Update the section reflecting that MU Plugins are just that: Must Use Plugins. Not related to MultiUser in any way, at least, not anymore.

Hope I am not wrong on this :)

**Comment by atachibana** [comment]
@TukuToi 
I completely agree with you. [This information](https://wordpress.org/support/article/managing-plugins/#must-use-plugins) must be older one and just renamed from `multi-user` to `must use` later.
How about replacing whole section by excerpted sentences from must-use-plugin page? 
For example,

## Must-Use Plugins
Must-use plugins (a.k.a. mu-plugins) are plugins installed in a special directory inside the content folder and which are automatically enabled. Must-use plugins do not show in the default list of plugins on the Plugins page of Administration Screens and cannot be disabled except by removing the plugin file from the must-use directory, which is found in wp-content/mu-plugins by default.
For more details, please refer [Must Use Plugins](https://wordpress.org/support/article/must-use-plugins/).

**Comment by TukuToi** [comment]
Makes perfect sense to me!

**Comment by atachibana** [comment]
@TukuToi Thank you for the confirmation. I modified the section.
https://wordpress.org/support/article/managing-plugins/#must-use-plugins
