### ISSUE TITLE
[HelpHub] Posts List

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#250]
## What is the new page you are requesting?

New article required for the Posts List block

## New page for 6.0
- [ ] Create a new article for the Post List block
- [ ] Make sure the URL slug under Permalink is: posts-list-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Leonardus-Nugraha** [comment]
I'll take this one

**Comment by Leonardus-Nugraha** [comment]
@femkreations adding this block will effectively output the query loop block. Should we merge into the query loop block's article or should we write something to direct readers to the query loop block?
![image](https://user-images.githubusercontent.com/65521329/193704719-ffbfcdb3-da05-4925-8a90-52605bb00324.png)

**Comment by femkreations** [comment]
@Leonardus-Nugraha The Posts List block is a variation of the query loop. It was only created for one purpose: To give it an easier name. "Query loop" was considered too technical.

https://github.com/WordPress/gutenberg/issues/32268

Since this block is available in the front end, lets have a separate article and write up something to direct readers to the query loop article. Thanks

**Comment by Leonardus-Nugraha** [comment]
https://docs.google.com/document/d/1ZxPLx-mbgLs2WW1wk1u7zNXR82jQ2LyoxsS48mLVcH4/edit?usp=sharing
Wrote instructions how to add the block then link it to Query Loop block

**Comment by emmasophieyoung** [comment]
@femkreations 1st review done, ready for you

**Comment by femkreations** [comment]
This page is published now. Thanks @Leonardus-Nugraha and @emmasophieyoung for working on the content.
