### ISSUE TITLE
Documentation for the Pattern Directory creator/submission process

### ISSUE THREAD

**Issue by tellyworth** [WordPress/Documentation-Issue-Tracker#252]
## What is the new page you are requesting?

The WordPress.org Pattern Directory will soon be open to the public to create and submit new patterns. We'll need some new docs and doc updates to reflect that. 

I think at a minimum, probably:
* An extra section on the [Pattern Directory doc page](https://wordpress.org/support/article/block-pattern-directory/) linking to the creator/submission tool (final URL TBC but probably https://wordpress.org/patterns/new-pattern/)
* Something for end-users about using third-party patterns, reporting inappropriate/spam patterns, etc.

I'm not sure if a doc page about the creator/editor tool itself is warranted as well. It will have some inline docs. 

We can give early access to docs team members as needed. What other help and materials do we need to provide?

## How will this new page help you?

It will help both designers/creators who want to submit patterns to the Pattern Directory; and end-users who will include those patterns in their WP posts.

**Comment by bph** [comment]
@tellyworth could you also provide to the meta.trac ticket(s) It might help with the discovery and speed up the process or creating these document, if the writer can read up on the discussion around the new features.

Yes, I would think that documentation about the submission process would certainly be valuable.

**Comment by bph** [comment]
A list of issues/PRs with information can be found in the project [Pattern Directory creator](https://github.com/WordPress/pattern-directory/projects/2)

**Comment by bph** [comment]
After testing the submission process, I created a first draft of the  new page and could use a  [review via Google Doc](https://docs.google.com/document/d/1i1XKACiuCyOhi0OZNi9psmgxzBKF-IZOiHLiFFLW1e4/edit#), regarding current content and what's missing. (don't worry about typos and grammar) 
@tellyworth @zzap

**Comment by bph** [comment]
- [ ] Added report a pattern section on the [block patten directory page](https://wordpress.org/support/article/block-pattern-directory/)
- [ ] Created new page **Submit Your Block Pattern to the Directory** [(public preview link)](https://wordpress.org/support/?
p=15489182&post_type=helphub_article&preview=1&_ppp=41be0c95b2)
