### ISSUE TITLE
Link to 404 page in Block Pattern Directory post

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#254]
## Issue Description
Link to 404 page in Block Pattern Directory post

## URL of the Page with the Issue
https://wordpress.org/support/article/block-pattern-directory/

## Section of Page with the issue
Resource links

## Why is this a problem?
The link [Submit a pattern to the directory](https://wordpress.org/support/article/submit-your-block-pattern-to-the-directory/) link to a 404 page.
The link is correct but the post isn’t yet published.

## Suggested Fix
Use the updates extented plugin to schedule the update or publish the post

**Comment by bph** [comment]
Just publish the article. It's been reviewed before. 
Also, if there are instructions for the "extended plugin to schedule the update or publish the post" that would be quite helpful.

**Comment by jennydupuy** [comment]
ok cool!
but I just noticed that the Schedule updates plugin is no longer active on fr.wordpress.org/support and it's the same for wordpress.org/support
