### ISSUE TITLE
fixed typo: removing an unnecessary 's'

### ISSUE THREAD

**Issue by SadeqSp** [WordPress/Documentation-Issue-Tracker#255]
## Issue Description
it's a typo

## URL of the Page with the Issue
https://developer.wordpress.org/themes/functionality/administration-menus/#example

## Section of Page with the issue
Determining Location for New Menus > Example

## Why is this a problem?
there is an unnecessary 's' in the example code

## Suggested Fix
...
function register_my_theme_more_settings_menu() {
    add_submenu_page(
        "my-themes-settings-menu",  >>>  "my-theme-settings-menu",
        ...

**Comment by stevenlin-x** [comment]
@SadeqSp , good catch.

$menu_slug of add_menu_page()

corresponds to

$parent_slug of add_submenu_page()

I've fixed the typo.
