### ISSUE TITLE
How to install WordPress: incorrect link

### ISSUE THREAD

**Issue by mikachan** [WordPress/Documentation-Issue-Tracker#261]
## Issue Description

On the How to install WordPress page (https://wordpress.org/support/article/how-to-install-wordpress/), there is a link for 'Before you install' under the 'Things to Know Before Installing WordPress' title. It's currently set to go to https://wordpress.org/support/installation/before-you-install/, but this redirects to https://wordpress.org/support/topic/before-you-install/. I believe it should be linking to https://wordpress.org/support/article/before-you-install/.

## URL of the Page with the Issue

https://wordpress.org/support/article/how-to-install-wordpress/

## Section of Page with the issue

'Things to Know Before Installing WordPress'
https://wordpress.org/support/article/how-to-install-wordpress/#things-to-know-before-installing-wordpress

## Why is this a problem?

This is confusing for people who are trying to find more information on what they need to know before installing WordPress, as the page is currently incorrectly redirecting to the support forum rather than another documentation page.

## Suggested Fix

Fix the redirect and/or replace the link.

**Comment by stevenlin-x** [comment]
It seems @Otto42 has already fixed the link.
