### ISSUE TITLE
[HelpHub] Fix wording on Gallery block for Remove Gallery

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#262]
## URL of the Page with the Issue
 https://wordpress.org/support/article/gallery-block/#more-options

## Section of Page with the issue
 On the section **More options**, the last item is described as **Remove block** and the image and the actual settings refer to this as **Remove Gallery**

## Why is this a problem?
 Cause the settings say something different

## Suggested Fix
Change headline to Remove Gallery and make sure the description still matches.

**Comment by femkreations** [comment]
Made the edit. Thanks

**Comment by fclaussen** [comment]
> @estelaris Made the edit. Thanks
@femkreations sorry, I'm new to collaborating. Does this mean this issue should now be closed?

**Comment by estelaris** [comment]
@fclaussen yes, this issue is now closed.
