### ISSUE TITLE
[HelpHub] Site Title block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#265]
Article:  https://wordpress.org/support/article/site-title-block/

## Updating for 6.0
- [x] Add the transform between Site Title and Site Logo block. [37920](https://github.com/WordPress/gutenberg/pull/37920)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by luminuu** [comment]
<img width="250" alt="Bildschirmfoto 2022-06-02 um 11 18 12" src="https://user-images.githubusercontent.com/7585600/171609089-a8ae48fa-4002-474e-bb24-0c919366c548.png">

There's just this screenshot that's a bit more different for 6.0. The other screenshots fit perfectly fine for 6.0.

**Comment by femkreations** [comment]
Updated the page and the screenshot.
