### ISSUE TITLE
[HelpHub] Avatar block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#269]
## New page for 6.0
- [ ] Create a new article for the Avatar block [39728](https://github.com/WordPress/gutenberg/pull/39728)
- [ ] Make sure the URL slug under Permalink is: avatar-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by justintadlock** [comment]
Just noting that I'm working on the article for this ticket (we couldn't yet assign it to me in the docs meeting).

**Comment by blogsmithteam** [comment]
@justintadlock let me know if you haven't made progress and have moved on from this and I'd be happy to take over!

**Comment by femkreations** [comment]
@justintadlock are you still working on this? @blogsmithteam would you still be open to taking over this if Justin is not working?

**Comment by justintadlock** [comment]
Sorry about that.  I missed the replies.  @blogsmithteam, feel free to go ahead with it.

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2.Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by femkreations** [comment]
@blogsmithteam Pls let us know if you are working on this and have any updates. Thanks

**Comment by Leonardus-Nugraha** [comment]
https://wordpress.org/documentation/wp-admin/post.php?post=16356898&action=edit
Ready for review

**Comment by femkreations** [comment]
Looks great. Thanks for working on this @Leonardus-Nugraha.
