### ISSUE TITLE
[HelpHub] Columns block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#272]
Article:  https://wordpress.org/support/article/columns-block/

Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

## Updating for 6.1
- [ ] Add axial block spacing to Columns block. [44101](https://github.com/WordPress/gutenberg/pull/44101)
- [ ] Prevent single Columns blocks from transforming into Columns. [43641](https://github.com/WordPress/gutenberg/pull/43641)
- [ ] Add typography supports . [43253](https://github.com/WordPress/gutenberg/pull/43253)
- [ ] Adopt typography supports-column block. [43252](https://github.com/WordPress/gutenberg/pull/43252)
- [ ] Change title of one third/two thirds column variation to 66/33. [41734](https://github.com/WordPress/gutenberg/pull/41734)
- [ ] Add border support to column blocks. [39967](https://github.com/WordPress/gutenberg/pull/39967)

 
## Updating for 6.0
- [ ] Add Block Spacing support. [40122](https://github.com/WordPress/gutenberg/pull/40122)
- [ ] Add border support. [31737](https://github.com/WordPress/gutenberg/pull/31737)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by luminuu** [comment]
**Block Toolbar**
<img width="665" alt="Bildschirmfoto 2022-06-02 um 14 27 56" src="https://user-images.githubusercontent.com/7585600/171640131-c88a5f85-ff99-468e-bb2e-97a0f1a0b2d7.png">

**Transform to**
<img width="665" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171639928-baf13cfd-4906-46c9-b7fd-84a7f9a89ac4.png">

**Group**
<img width="1383" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171640434-dd2b4969-1d3b-4c8f-932d-cd16bb732cbd.png">

**Change alignment**
<img width="342" alt="Bildschirmfoto 2022-06-02 um 14 30 46" src="https://user-images.githubusercontent.com/7585600/171640719-f69438a4-6c98-4a64-8338-cd079b79075a.png">

**More options**
<img width="252" alt="Bildschirmfoto 2022-06-02 um 14 32 40" src="https://user-images.githubusercontent.com/7585600/171641060-6b0c989f-5c64-4136-9a06-c7410c78c27e.png">

**Color (Sidebar only)**
<img width="266" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171641650-ef9b9a9e-1ad2-4461-890b-470e34ca461d.png">

**Color (Color panel opened)**
<img width="570" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171641735-c0aa7a9f-44f2-4ae2-ab1d-68522d3bef56.png">

**Columns property**
<img width="264" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171643496-a1a849a8-382f-4691-bd8a-5833ec4fd89e.png">

**Spacing / Dimensions**
<img width="264" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171643869-c040c6eb-db68-4034-a859-5f68013a1319.png">

**Border (new)**
<img width="264" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171644079-00c803a4-0ed0-4a46-a7f2-42f901484b18.png">

**Comment by Riyadh1734** [comment]
I am reviewing this

**Comment by femkreations** [comment]
Added 6.1 tasks

## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by nielsbroekzitter** [comment]
I will make make 6.1 updates

**Comment by nielsbroekzitter** [comment]
![Color Settings](https://user-images.githubusercontent.com/117441367/199975382-3ac3e617-bdc0-4e8d-ab87-3abc09c8e814.jpg)
![Columns](https://user-images.githubusercontent.com/117441367/199975386-b9cc7775-6f28-4133-a17f-b71015ec31e8.jpg)
![Editor view of columns as a Group with Color settings controls](https://user-images.githubusercontent.com/117441367/199975387-afb72296-f958-4ca9-9b64-51a37ef110fa.jpg)

https://user-images.githubusercontent.com/117441367/199975388-200e5b01-f42a-4a5a-bafb-08d669e0f283.mp4

![Adjusting the amount of columns](https://user-images.githubusercontent.com/117441367/199975393-3619361f-0045-4a67-97e8-0e738885c4fe.gif)

https://user-images.githubusercontent.com/117441367/199975402-009b2421-7489-4440-ba1f-d08269102e0d.mp4


https://user-images.githubusercontent.com/117441367/199975406-b6473bd1-9f08-444c-bad2-6dead8b4fd25.mp4

**Comment by nielsbroekzitter** [comment]
Also made a video about the new typography function

https://user-images.githubusercontent.com/117441367/199979393-977f5a2f-7716-46b5-91b2-c6d8a032f8dd.mp4

**Comment by alianschiavoncini** [comment]
These are new screenshots for Dimesions and Border.

**Dimensions**
![Schermata 2022-11-11 alle 10 59 54](https://user-images.githubusercontent.com/42210724/201317388-903a4088-f3e5-4c0d-a5d6-230adb92f89d.png)

**Border**
![Schermata 2022-11-11 alle 11 01 52](https://user-images.githubusercontent.com/42210724/201317392-510f6b05-d8d6-455b-81f7-34f1a95ffd63.png)

**Comment by femkreations** [comment]
Thank you @luminuu @nielsbroekzitter and @alianschiavoncini for sharing screenshots. I've updated the page with content, screenshots, and video for 6.1. Also added block settings for Column block
https://wordpress.org/support/article/columns-block/
