### ISSUE TITLE
[HelpHub] Heading block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#277]
Article:  https://wordpress.org/support/article/heading-block/

## Updating for 6.0
- [x] Add note: remove anchor when transforming Heading to a Paragraph. [38604](https://github.com/WordPress/gutenberg/pull/38604)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/123)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by suascat** [comment]
I will work on this issue...

**Comment by suascat** [comment]
As tested in WP Version 6.0-RC2, transforming Heading to a Paragraph automatically removes the anchor text. 

Some screenshots that need to be updated:

More Text Editing Options
![more-text-editing-options](https://user-images.githubusercontent.com/9716719/168265737-4640cdbf-12be-4c71-a243-54a63f21586b.png)

More Options
![more-options](https://user-images.githubusercontent.com/9716719/168265793-20807218-1bc2-44bf-9131-f77730ef3aed.png)

Block settings
![block-settings](https://user-images.githubusercontent.com/9716719/168266210-6844d862-9036-4444-aab4-e1815475d41a.png)

Advanced settings
![advanced-settings](https://user-images.githubusercontent.com/9716719/168266471-fa384d97-22a9-4e33-b4cf-efc85ab99d2b.png)

**Comment by femkreations** [comment]
The Block Toolbar section needs to be updated with content and screenshots as we don't have 'Change alignment' in the block toolbar for the heading block.

Since we are moving the Block Settings to a separate new page and revamping all the block articles by linking to the new page, we don't need to update the Block Settings for the Heading block.

**Comment by femkreations** [comment]
This page has been reviewed and looks great. Thanks for the screenshots @suascat
