### ISSUE TITLE
[HelpHub] Site Logo block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#287]
## New page for 6.0
- [x] Create a new article for the Site Logo block
- [x] Make sure the URL slug under Permalink is: site-logo-block
- [x] At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Add option to set site icon from the Site Logo block settings. [35892](https://github.com/WordPress/gutenberg/pull/35892)
- [x] Add transform between core/site-logo and core/site-title blocks. [37920](https://github.com/WordPress/gutenberg/pull/37920)
- [x] Add duotone to placeholders for site logo and featured image. [40085](https://github.com/WordPress/gutenberg/pull/40085)
- [x] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/193)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are relevant for the current version (6.0)
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by lechatinformatique** [comment]
![site-logo-block](https://user-images.githubusercontent.com/52913621/171615162-59b64c08-90af-4b4f-8964-1b80dba3b23b.png)
![site-logo-duotone](https://user-images.githubusercontent.com/52913621/171615167-f4a98633-9d85-4b98-a142-4818d03147a8.png)
![site-logo-settings](https://user-images.githubusercontent.com/52913621/171615175-aa5d5ff0-ef29-4209-8189-f2d89d18f4e9.png)
![site-logo-default](https://user-images.githubusercontent.com/52913621/171615173-f29c9176-d229-49b7-a719-eef444c9c962.png)
![site-logo-rounded](https://user-images.githubusercontent.com/52913621/171615170-dde58d71-58a5-4c85-a5c9-52466e7b1823.png)

**Comment by femkreations** [comment]
https://wordpress.org/support/article/site-logo-block/ New page created and updated for 6.0 with screenshots, content and video. @zzap
