### ISSUE TITLE
[HelpHub] Row block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#295]
## New page 
- [ ] Create a new article for the Row block
- [ ] Make sure the URL slug under Permalink is: row-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## Updating for 6.0 
- [ ] New Group, Stack, Row block descriptions. [40176](https://github.com/WordPress/gutenberg/pull/40176)
- [ ] Add Gap support. [37459](https://github.com/WordPress/gutenberg/pull/37459)
- [ ] Add the typography support. [37456](https://github.com/WordPress/gutenberg/pull/37456)
- [ ] Add transform to row variation. [36202](https://github.com/WordPress/gutenberg/pull/36202)
- [ ] Turn the wrap to multiple lines option off by default on the row block. [40171](https://github.com/WordPress/gutenberg/pull/40171)
- [ ] Improve Stack and Row setup states. [39935](https://github.com/WordPress/gutenberg/pull/39935)
- [ ] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/246)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by bph** [comment]
I am not sure that the Row and the Stack need their own pages, as they are variations of the Group block.

**Comment by ravahdati** [comment]
@femkreations | every block in gutenberg needs a seperate page and users hasn't be confused.

**Comment by Ignasrimkunas** [comment]
@femkreations heya will take this one

**Comment by emmasophieyoung** [comment]
@femkreations first review done, ready for you. 
https://docs.google.com/document/d/1djP8tX1dPKKx_xAt7rG7Dxiv6-cXDcogslEpDeNdiSU/edit

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung 
@femkreations, I've reviewed and published the article: https://wordpress.org/support/article/row-block/
Link to the page also added to https://wordpress.org/support/article/blocks/
