### ISSUE TITLE
[HelpHub] Page List block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#298]
## New page for 6.0
- [ ] Create a new article for the Page List block 
- [ ] Make sure the URL slug under Permalink is: page-list-block
- [ ] At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Simplify loading state [38983](https://github.com/WordPress/gutenberg/pull/38983)
- [ ] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/204)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by blogsmithteam** [comment]
@femkreations can you assign me to this one? Happy to take it!

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by blogsmithteam** [comment]
@zzap @femkreations Here: https://docs.google.com/document/d/1vo3DSJUzJ1ukiyYDHBj_qbFun0lBxy_vZKhTPmi8xpc/edit?usp=sharing

**Comment by femkreations** [comment]
Thanks @blogsmithteam for working on this page content. Bonus points for adding the Alt tag text under each screenshot!

This page has been published https://wordpress.org/support/article/page-list-block/
