### ISSUE TITLE
The example code of code reply script is broken

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#3]
The example code of code reply script (https://developer.wordpress.org/themes/basics/including-css-javascript/#the-comment-reply-script) is broken:
```
if ( is_singular() &amp;amp;amp;&amp;amp;amp; comments_open() &amp;amp;amp;&amp;amp;amp; get_option( 'thread_comments' ) ) {
    wp_enqueue_script( 'comment-reply' );
}
```

And the example code in the next section ("Combining Enqueue Functions") as well.

**Comment by atachibana** [comment]
@JanisE 
Thank you. I fixed those errors. 
https://developer.wordpress.org/themes/basics/including-css-javascript/

fyi.
To tell the truth, this content was in the one large Class block and couldn't be modified simply. If I edit any line, whole content was garbled... I had to convert them to usual blocks...
