### ISSUE TITLE
Missing semicolon in Theme Header Doc

### ISSUE THREAD

**Issue by TukuToi** [WordPress/Documentation-Issue-Tracker#311]
## Issue Description
In the [DOC for Theme Headers](https://developer.wordpress.org/themes/functionality/custom-headers/) there is a Code Snippet in the [initial section](https://developer.wordpress.org/themes/functionality/custom-headers/#custom-header). That snippet misses a Semicolon `;` resulting in a Fatal Error if copy pasted to a theme functions.php file.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/functionality/custom-headers/

## Section of Page with the issue
https://developer.wordpress.org/themes/functionality/custom-headers/#custom-header

## Why is this a problem?
It produces a fatal error and should be amended to be correct code.

## Suggested Fix
Change the code snippet to this:
```
function themename_custom_header_setup() {
    $args = array(
        'default-image'      => get_template_directory_uri() . 'img/default-image.jpg',
        'default-text-color' => '000',
        'width'              => 1000,
        'height'             => 250,
        'flex-width'         => true,
        'flex-height'        => true,
    );
    add_theme_support( 'custom-header', $args );
}
add_action( 'after_setup_theme', 'themename_custom_header_setup' );
```

**Comment by stevenlin-x** [comment]
I've revised the code.
