### ISSUE TITLE
[HelpHub] Comment block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#314]
## New page
- [ ] Create a new article for the Comments block.
- [ ] Make sure the URL slug under Permalink is: comments-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Updating for 6.1
- [ ] Prevent comments rendering on password protected posts [40755](https://github.com/WordPress/gutenberg/pull/40755)
- [ ] Add Post Comments Form block to Comments Query Loop template [40256](https://github.com/WordPress/gutenberg/pull/40256)
- [ ] Comment Content: Show moderation message [40612](https://github.com/WordPress/gutenberg/pull/40612)

## Updating for 6.0
**These were PRs for the Comments Query Loop block which has been renamed to Comments block in 6.1**
- [ ] Handle nested comments. [36065](https://github.com/WordPress/gutenberg/pull/36065)
- [ ] Fix comment pagination with nested replies. [38187](https://github.com/WordPress/gutenberg/pull/38187)
- [ ] Add comments pagination to the default Comments. [37610](https://github.com/WordPress/gutenberg/pull/37610)
- [ ] Add discuss options to the block. [37297](https://github.com/WordPress/gutenberg/pull/37297)
- [ ] Update default template. [40165](https://github.com/WordPress/gutenberg/pull/40165)
- [ ] Link to the Pagination block page #237 for the pagination details

**These PRs are not valid for the new block**
- [ ] Improve context handling in inner blocks. [37196](https://github.com/WordPress/gutenberg/pull/37196)
- [ ] Rename next and previous to newer an older. [38143](https://github.com/WordPress/gutenberg/pull/38143)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/217)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by yogskr** [comment]
Hi @Leonardus-Nugraha. I will work on this one!

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1i3yUo9zhWZb4qqtM2NGPUn8i79flXmpvw1zFRfT-Ius/edit#
@Leonardus-Nugraha  reviewed and ready for you

**Comment by Leonardus-Nugraha** [comment]
Thanks @yogskr and @emmasophieyoung!
The article is published here: https://wordpress.org/support/article/comments-block/
