### ISSUE TITLE
[HelpHub] Comments Pagination block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#316]
## New page for 6.0
- [x] Create a new article for the Comments Pagination block [36872](https://github.com/WordPress/gutenberg/pull/36872)
- [x] Make sure the URL slug under Permalink is: comments-pagination-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/213)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by leon-nugraha** [comment]
@femkreations can you assign me for this one?

**Comment by femkreations** [comment]
Done. Thank you!

**Comment by leon-nugraha** [comment]
@femkreations 
Ready for review: 
https://docs.google.com/document/d/16ZuKEBfpGLSEj5FMAInnVirRU0EpkkUuPfp8vItECtk/edit?usp=sharing

Gif file on the doc:
![wordpress-comment-pagination](https://user-images.githubusercontent.com/108468349/181195618-69469ff4-26ea-4798-a0dd-9336180f003d.gif)

**Comment by leon-nugraha** [comment]
@femkreations Draft ready for review
https://docs.google.com/document/d/16ZuKEBfpGLSEj5FMAInnVirRU0EpkkUuPfp8vItECtk/edit?usp=sharing
Gif file:
![wordpress-comment-pagination](https://user-images.githubusercontent.com/108468349/181747144-d9a6902a-704b-4c2e-8217-7c1277a6e8fe.gif)

**Comment by femkreations** [comment]
Thank you for your awesome work @leon-nugraha I have created the page with the contents.

https://wordpress.org/support/article/comment-pagination-block/
