### ISSUE TITLE
[HelpHub] Comment Author Avatar block 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#317]
## New page for 6.0
- [ ] Create a new article for the Comment Author Avatar block 
- [ ] Make sure the URL slug under Permalink is: comment-author-avatar-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Add x2 to URL string that defines the image size by default. [39728](https://github.com/WordPress/gutenberg/pull/39728)
- [ ] Add spacing support. [36322](https://github.com/WordPress/gutenberg/pull/36322)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/206)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by leon-nugraha** [comment]
@femkreations I want to work on this

**Comment by Leonardus-Nugraha** [comment]
Hi, I just found out that the comment author avatar in the comment query loop block uses the general avatar block, which already has separate tracker (https://github.com/WordPress/Documentation-Issue-Tracker/issues/269)
Do we still need a document for this?
![image (11)](https://user-images.githubusercontent.com/65521329/178675966-faddda97-5620-4aea-aad1-77f59cec478c.png)

**Comment by leon-nugraha** [comment]
Hi, I just found out that the comment author avatar in the comment query loop block uses the general avatar block, which already has separate tracker (https://github.com/WordPress/Documentation-Issue-Tracker/issues/269)
Do we still need a document for this?
![178675966-faddda97-5620-4aea-aad1-77f59cec478c](https://user-images.githubusercontent.com/108468349/178683690-54d734f0-7f25-4dab-a834-20efd21b5eee.png)

**Comment by zzap** [comment]
> @zzap would we create a page for this block and point to the Avatar block page similar to this one https://wordpress.org/support/article/button-block/

Yes, that would be consistent.

**Comment by femkreations** [comment]
Added this block to the list of deprecated blocks in the https://wordpress.org/support/article/blocks/#deprecated page. Closing this issue.
