### ISSUE TITLE
[HelpHub] Comment Author Name block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#318]
## New page for 6.0
- [x] Create a new article for the Comment Author Name block 
- [x] Make sure the URL slug under Permalink is: comment-author-name-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/207)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are relevant for the current version (6.0)
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by Leonardus-Nugraha** [comment]
@femkreations hey, I want to work on this. Can you please assign me?

**Comment by leon-nugraha** [comment]
@femkreations hey, I want to work on this, can you assign me please?

**Comment by leon-nugraha** [comment]
@femkreations the draft is ready for review 
https://docs.google.com/document/d/1kQSZ5JF5x3jAyVtNUy-nGisVcOmh0xCgxb8eX-CwEtA/edit?usp=sharing

Also, this is one of the gif file in the doc. Attaching it here to make it easier for publishing.
![wordpress-comment-author-name](https://user-images.githubusercontent.com/108468349/180108202-bb6bb26b-c204-4ad8-9467-afc1043d1f82.gif)

Let me know if you have any feedback

**Comment by femkreations** [comment]
@leon-nugraha Thank you for the awesome work. The content looks great. I have created the article in WordPress 
https://wordpress.org/support/article/comment-author-name-block/
Thanks!
