### ISSUE TITLE
[HelpHub] Comment Date block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#319]
## New page for 6.0
- [ ] Create a new article for the Comment Date block 
- [ ] Make sure the URL slug under Permalink is: comment-date-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/209)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@femkreations heya, here's the article https://docs.google.com/document/d/1K93zOq58NKaq4OPmRe-CcL-H-sDnDiO8jw8kG_VmEqI/edit?usp=sharing

**Comment by femkreations** [comment]
Thanks, @Ignasrimkunas and @emmasophieyoung for your help. This page has been published with the content and screenshots you provided. Awesome work.

https://wordpress.org/support/article/comment-date-block/
