### ISSUE TITLE
Breadcrumb overlays the page title on mobile screen

### ISSUE THREAD

**Issue by kharissulistiyo** [WordPress/Documentation-Issue-Tracker#32]
## Issue Description
Breadcrumb overlays the page title on smaller screen when the breadcrumb contains at lest 3 lines.

![IMG_6627](https://user-images.githubusercontent.com/1859092/132933137-5a9f01cf-7869-4a50-b7c2-2ecd3078a1ae.PNG)

## URL of the Page with the Issue
https://make.wordpress.org/polyglots/handbook/for-editors/translation-collaboration-team-building-tips/guide-organize-a-local-event-on-global-wordpress-translation-day/

## Section of Page with the issue
Breadcrumb

## Why is this a problem?
It is ugly and makes the breadcrumb and page title poor readability.

## Suggested Fix
I checked with my web browser's inspector tool and seems likely we couldn't add media query CSS to fix this issue due to absolute positioning on breadcrumb and the below CSS code presents: 

```
@media only screen and (min-width: 876px) {
    .single-handbook .handbook-breadcrumbs ~ #primary {
        padding-top: 7rem;
    }
}
```

Probably adding additional breadcrumb element that is shown only on mobile creen and put it inside `DIV#primary` before the page title part would fix. Don't forget to hide the current `.handbook-breadcrumbs` on desktop.

**Comment by hitendrachopda-multidots** [comment]
Hello kharissulistiyo ,

To fix this issue, it's required to add more padding in media CSS given the below.

`@media (max-width: 876px)
.single-handbook .handbook-breadcrumbs ~ #primary {
    padding-top: 9rem;
}`

Hope this solution will work.

Best,

**Comment by kharissulistiyo** [comment]
@hitendrachopda-multidots, 

Thanks for the code. 

I am thingking  that the breadcumb line could potentially increase.

**Comment by zzap** [comment]
This is overal meta issue because it applies to all handbooks. It will most likelye be fixed with the new design for the whole wp.org. If not, I suggest opening a ticket in meta Track with component `Handbooks` - https://meta.trac.wordpress.org/newticket.
