### ISSUE TITLE
[HelpHub] Comment Content block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#320]
## New page for 6.0
- [ ] Create a new article for the Comment Content block 
- [ ] Make sure the URL slug under Permalink is: comment-content-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/208)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Its all yours:-) Thank you

**Comment by Ignasrimkunas** [comment]
all done :) https://docs.google.com/document/d/1bF4rvlqea8E8vRRRlQjwFFFSiSx7W77SsydO0aIk1Vs/edit?usp=sharing

**Comment by femkreations** [comment]
Thank you @Ignasrimkunas I've reviewed the content and created the new page.  Awesome work!
https://wordpress.org/support/article/comment-content-block/
