### ISSUE TITLE
[HelpHub] Comment Reply Link block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#321]
## New page for 6.0
- [ ] Create a new article for the Comment Reply Link block 
- [ ] Make sure the URL slug under Permalink is: comment-reply-link-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/211)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@femkreations heya assign me to this done, thanks!

**Comment by Ignasrimkunas** [comment]
All done https://docs.google.com/document/d/15ZnpcmQA3MKJZnUOjgY2kzM532Mm5f23-9aSdL4yRkE/edit#heading=h.i0h9yjf1adgz

**Comment by femkreations** [comment]
Thanks, @Ignasrimkunas. The content looks great. I've created a new page for this block with the info.

https://wordpress.org/support/article/comment-reply-link-block/
