### ISSUE TITLE
[HelpHub] Comment Edit Link block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#322]
## New page for 6.0
- [ ] Create a new article for the Comment Edit Link block 
- [ ] Make sure the URL slug under Permalink is: comment-edit-link-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Add the missing comment edit link icon. [36565](https://github.com/WordPress/gutenberg/pull/36565)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/210)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@femkreations heya assign me to this done, thanks!

**Comment by femkreations** [comment]
Done. Thank you @Ignasrimkunas

**Comment by Ignasrimkunas** [comment]
https://docs.google.com/document/d/1E78Vsio4krKGLhRXPiRkarLDHMSl5nmGioAiqQB2AwA/edit#heading=h.i0h9yjf1adgz All done

**Comment by femkreations** [comment]
Thank you for your work. The content looks great, I've created a new page for this block.

https://wordpress.org/support/article/comment-edit-link-block/

**Comment by hannaw93** [comment]
I can pick this up :)
