### ISSUE TITLE
[HelpHub] Comment Pagination Previous Page block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#325]
## New page for 6.0
- [ ] Create a new article for the Comment Pagination Previous Page block ([36912](https://github.com/WordPress/gutenberg/pull/36912))
- [ ] Make sure the URL slug under Permalink is: comment-previous-page-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are relevant for the current version (6.0)
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@femkreations heya assign me to this one, thanks!

**Comment by Ignasrimkunas** [comment]
All done: https://docs.google.com/document/d/1OS4CrEssu4VQqa9BOj2es0aRSeWaGWNa3NmPxh--eNk/edit?usp=sharing 

This should be the last of comments blocks

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1lerABYls6_cAp2WvFAGazKg4HyOhWlT7m2xJp2iil7g/edit
@femkreations ready for review (also from Ignas ^^)

**Comment by femkreations** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung for this content.

We discussed this block in the [Slack channel](https://wordpress.slack.com/archives/C02RP4WU5/p1660056199303179) and it was decided to have one page documenting all the Pagination blocks - Previous, Page numbers, and Next blocks.

Hence closing this issue.

We can reuse the content in this google doc to create the content for the Pagination block page.
