### ISSUE TITLE
Release Work: Tracking Issue for Field Guide "But Wait, There is More!" responses from component maintainers

### ISSUE THREAD

**Issue by bph** [WordPress/Documentation-Issue-Tracker#326]
Resource links: 

- [Publishing Field Guide](https://make.wordpress.org/core/handbook/tutorials/publishing-the-field-guide/)
- [Tracking issue Component Outreach ](https://github.com/WordPress/gutenberg/issues/40609)(should have been started in this repo)

The items for the section are collected in the comments. 
Suggested format: 
`Component Name: Trac Ticket Summary (#Trac-Number).`

**Comment by bph** [comment]
Media: Store file size media metadata [#41412](https://core.trac.wordpress.org/ticket/49412) - The internal code for image uploading has been updated to store the file size for each generated image size, not just the original.
props @desrosj

**Comment by bph** [comment]
Upgrade/Install: Add filter to modify description in plugin card [#55480](https://core.trac.wordpress.org/ticket/55480)
Paul Biron to write a draft for `Misc Dev Note`

**Comment by bph** [comment]
**Build/Test Tools**

- A .git-blame-ignore-revs file has been added to the repository with a curated list of “pinking shear” commits (ones only applying stylistic changes), making the blame feature on GitHub much more useful [#55422](https://core.trac.wordpress.org/ticket/55422)

- Webpack and all related build processes/scripts have been updated to version 5 [#51750](https://core.trac.wordpress.org/ticket/51750).

- The npm install command has been fixed for contributors using an Apple M series silicone by updating the grunt-contrib-qunit dev dependency [#52690](https://core.trac.wordpress.org/ticket/52690).

props @desrosj

**Comment by bph** [comment]
**Comments:** Speeding up Dashboard and Comment moderation SQL load - #[19901](https://core.trac.wordpress.org/ticket/19901)
props @imath

**Comment by bph** [comment]
**External libraries:**

- The Underscore.js and Backbone.js libraries have been updated to the latest versions [#55547](https://core.trac.wordpress.org/ticket/55547).
- PHPMailer has been updated to the latest version [#55277](https://core.trac.wordpress.org/ticket/55277).
- Sodium Compat has been updated to the latest version [#55453](https://core.trac.wordpress.org/ticket/55453).
- Random_Compat has been updated to the latest version [#55181](https://core.trac.wordpress.org/ticket/55181).
- Other libraries that have been updated to their latest versions: jQuery Color, Jcrop, Moment.js, Clipboard.js, formdata-polyfill, polyfill-library , [#55547](https://core.trac.wordpress.org/ticket/55547), [#55016](https://core.trac.wordpress.org/ticket/55016), [#54035](https://core.trac.wordpress.org/ticket/54035).

propbs @desrosj

**Comment by bph** [comment]
**Network/Sites**: Improve cache key generation in WP_Site_Query [#55462](https://core.trac.wordpress.org/ticket/55462)

props Jonny Harris

**Comment by bph** [comment]
**i18n**

- List item separator should be a WP_Locale property [#39733](https://core.trac.wordpress.org/ticket/39733)
- Allow languages path in register_block_type [#54797](https://core.trac.wordpress.org/ticket/54797)

Props @swissspidy

**Comment by bph** [comment]
Thank you @sabernhardt. - I added it to our [Misc Dev note](https://docs.google.com/document/d/1Zlq7Ep14nZPaC1GUEvI_spgPxV4xfCWPl4T9tKVPn_I/edit#) Document as is.

**Comment by zzap** [comment]
Marking published/added to FG with :+1:

**Comment by bph** [comment]
Huge thank you to @zzap for putting the Fieldguide together for 6.0
