### ISSUE TITLE
Theme.json backward compatibility list contains wrong information.

### ISSUE THREAD

**Issue by daviedR** [WordPress/Documentation-Issue-Tracker#33]
## Issue Description

The theme.json backward compatibility equivalences list contains wrong information.

![image](https://user-images.githubusercontent.com/1287713/133027006-f9619062-187d-4cb9-b8cc-d643aad8b62a.png)

## URL of the Page with the Issue

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#backward-compatibility-with-add_theme_support

## Section of Page with the issue

Section: "Backward compatibility with add_theme_support"
Look at the table's first row.

## Why is this a problem?

The "theme.json setting" column value of the first row is wrong:
"Set `typography.customLineHeight` to `false`."

## Suggested Fix

The correct text should be:
"Set `typography.customLineHeight` to `true`."

**Comment by mkaz** [comment]
Good catch, thanks! Would you like to update the official documentation here: https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/theme-json.md

The documentation contributor guide is here: https://developer.wordpress.org/block-editor/contributors/documentation/

**Comment by daviedR** [comment]
Hi @mkaz 

I just created a pull request: https://github.com/WordPress/gutenberg/pull/34791. But I can't find a way to add the `[Type] Documentation` label in the pull request.

**Comment by mkaz** [comment]
Closed in https://github.com/WordPress/gutenberg/pull/34791 :+1:
