### ISSUE TITLE
Linting all things in IDE - the ultimate doc

### ISSUE THREAD

**Issue by kimmenbert** [WordPress/Documentation-Issue-Tracker#34]
## Document how to setup code linting / fixing in IDE for following WordPress coding standards
Hi,
I think it would be great to have a go-to doc for all tools recommended for linting PHP, JS, CSS etc to follow WP coding standards.

Including how to setup and utilize this linting in the most popular IDE's (vscode, phpstorm)

Linting php: `wp-coding-standards/wpcs`
Linting js / css / md / json: npm packages in gutenberg, `@wordpress/scripts` includes the things needed, but the eslint / prettier / csslint etc. setup could maybe be extracted from this, so you can use it in your own build tools / even if you don't use build tools.

## How will this new page help you?
I would hope it could help plugin and theme developers with writing code the WordPress way. And give an onramp for core contributors.
I also think it would help WordPress agencies as a go-to guide for new hires.

**Comment by Kenshino** [comment]
@atachibana - potentially a guide in the Common API handbook?

**Comment by Kenshino** [comment]
Also seems like this is partially covered in #35 ?

**Comment by zzap** [comment]
I proposed this as an article for Core Dev Blog: https://github.com/WordPress/developer-blog-content/discussions/320

**Comment by jrfnl** [comment]
I wonder if there should be multiple articles for different target groups ?

* How to set things up & get it running locally for contributing to WP Core
* Best practices for setting things up for a plugin/theme and how to integrate it into CI
* How to set up your local tooling environment in general (project vs global, IDEs etc)
