### ISSUE TITLE
[HelpHub] RSS block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#341]
Article:  https://wordpress.org/support/article/rss-block/

## Updating for 6.0
- [ ] RSS: Update max items. [39819](https://github.com/WordPress/gutenberg/pull/39819)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by hdvos** [comment]
Working on this

**Comment by hdvos** [comment]
<img width="618" alt="Screenshot 2022-05-13 at 11 10 05" src="https://user-images.githubusercontent.com/26040749/168251764-3fe0c7fa-b6c6-44a6-b9d8-2d6d00f5cfb9.png">
<img width="598" alt="Screenshot 2022-05-13 at 11 14 50" src="https://user-images.githubusercontent.com/26040749/168252278-229f6db5-d5a8-4087-b276-2029381c2934.png">
<img width="281" alt="Screenshot 2022-05-13 at 11 16 18" src="https://user-images.githubusercontent.com/26040749/168252534-487cf108-edb2-42bf-9fd7-09cb0963572e.png">
<img width="230" alt="Screenshot 2022-05-13 at 11 19 04" src="https://user-images.githubusercontent.com/26040749/168252998-960e1253-3ae5-4d2e-929c-b3c7b6568b91.png">
<img width="591" alt="Screenshot 2022-05-13 at 11 20 50" src="https://user-images.githubusercontent.com/26040749/168253304-a865c7b4-e659-4b79-9e33
-14f3da033888.png">
<img width="601" alt="Screenshot 2022-05-13 at 11 21 57" src="https://user-images.githubusercontent.com/26040749/168253545-794b4100-1248-4657-8890-f74f95e131fb.png">
<img width="262" alt="Screenshot 2022-05-13 at 11 23 54" src="https://user-images.githubusercontent.com/26040749/168253819-df6b77db-a2be-40ae-9f24-98a429295480.png">
Block Settings screenshot is identical. Just for redundancy:
<img width="271" alt="Screenshot 2022-05-13 at 11 27 15" src="https://user-images.githubusercontent.com/26040749/168254406-8f439c5d-44b7-4f63-a60c-5430d515a171.png">
Advanced is also identical but:
<img width="270" alt="Screenshot 2022-05-13 at 11 28 32" src="https://user-images.githubusercontent.com/26040749/168254747-a8166752-13fe-4155-ae8d-b1256f8652b2.png">

**Comment by samxmunoz** [comment]
@femkreations - I can update this article with the screenshots provided by @hdvos, please assign to me!

**Comment by samxmunoz** [comment]
@femkreations / @zzap - this doc has been updated. Can one of you give it a quick review? Thanks!

**Comment by femkreations** [comment]
Looks great. Thank you @samxmunoz
