### ISSUE TITLE
Theme developer handbook: Add a dedicated page for patterns

### ISSUE THREAD

**Issue by carolinan** [WordPress/Documentation-Issue-Tracker#342]
## What is the new page you are requesting?

A dedicated page about how to register and use block patterns.
A page that will refer back to the block editor handbook page at https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/

## How will this new page help you?

Right now, it seems that information about block patterns in themes is spread out over several pages:
https://developer.wordpress.org/themes/?s=block+patterns

Block patterns can be added in classic themes and block themes, but they can register them in different ways. Both the PHP function and the method with placing patterns inside the patterns folder should be covered. 

For help with writing the content, you can refer to the dev notes:
https://make.wordpress.org/core/2022/05/03/page-creation-patterns-in-wordpress-6-0/
https://make.wordpress.org/core/2022/05/02/new-features-for-working-with-patterns-and-themes-in-wordpress-6-0/

**Comment by colorful-tones** [comment]
@carolinan @kafleg @TeBenachi - this new doc is ready for review. This is my first contribution. Thanks!

@zzap I've moved label to `Content Review`. Is this correct process? 

For overall group, I added in the certain links to Learn videos, which I'm not sure is a standard, but I thought it would be helpful to allow different learning modalities. It could like be a maintenance burden. I'm curious on any guidance around this.

**Comment by zzap** [comment]
Yes, that's great @colorful-tones. As for Learn videos, I'd hold on with that. We do plan to link documentation to Learn resources but they are in the process of merging lessons and videos so the URLs might change very soon. This is why we are waiting with any sort of inner linking. But great thinking, nevertheless. It is what we plan eventually.

**Comment by colorful-tones** [comment]
> As for Learn videos, I'd hold on with that. We do plan to link documentation to Learn resources but they are in the process of merging lessons and videos so the URLs might change very soon. This is why we are waiting with any sort of inner linking. But great thinking, nevertheless. It is what we plan eventually.

@zzap thanks for clarifying. I've removed the links to video resources for now. 👍

**Comment by TeBenachi** [comment]
@colorful-tones  thank you so much. Great write-up! 
Looks great to me! It’s so clear and concise. 

Just a couple of small minor points I noticed, if I may. 


> There are two methods currently for registering or including patterns in your theme and both approaches are compatible with classic and block themes:

_currently_ may not be necessary for easier maintenance. 


> You can create patterns of blocks within the block editor and then copy **from the code editor**, and paste them into the 'content' property. The 'content' property contains the markup that your pattern will output when inserted in the block editor.

Adding “**from the code editor**” might help some developers clarify a little further. 

I think the pattern topic can go under the [Advanced Theme Topics](https://developer.wordpress.org/themes/advanced-topics/) or create a new top-level category. 


Thanks

**Comment by colorful-tones** [comment]
@TeBenachi thanks for the feedback. I've integrated both of your suggestions.

> I think the pattern topic can go under the [Advanced Theme Topics](https://developer.wordpress.org/themes/advanced-topics/) or create a new top-level category.

I do not have the ability to add this new doc here. May I have access please? Or, are Themes Team reps only allowed to access and add?

**Comment by richtabor** [comment]
I'd consider moving the PHP registration as the secondary method for adding patterns, as its simpler and less involved technically speaking. I would also add a bit of what use cases should lead to one method v. the other.

**Comment by carolinan** [comment]
@colorful-tones the themes team do not have user management permission for the docs in order to give you permission.

**Comment by carolinan** [comment]
I can see the list of users names that has access, but I do not see yours. I am also not sure which the correct user role would be.

**Comment by colorful-tones** [comment]
> I'd consider moving the PHP registration as the secondary method for adding patterns, as using `/patterns/` is simpler and less involved technically speaking. 

Great point and I agree. I'll fix that up when I'm at my desk.

> I would also add a bit of what use cases should lead to one method v. the other. 

@richtabor I would have to lean on your experience and knowledge here. I'm not clear on the indicators of choosing one over the other and the value of adding that additional context?

**Comment by colorful-tones** [comment]
> @colorful-tones the themes team do not have user management permission for the docs in order to give you permission.

@carolinan thanks for checking and clarifying. I'll reach out to the Docs team to see if they're able to give me access. 👍

**Comment by richtabor** [comment]
> I'm not clear on the indicators of choosing one over the other and the value of adding that additional context?

I'd say that themes _should_ use the `/patterns` method, with the caveat that those patterns will not be available to sites running < WordPress 6.0. But if you're building a block theme, you should use the `/patterns` method 100% of the time.

**Comment by richtabor** [comment]
Plugins that register patterns (though there aren't many) would need to use the PHP method.

**Comment by colorful-tones** [comment]
@richtabor I swapped the sequence for `patterns/` and `PHP registration` sections. I also updated and added a small addition here:

> - patterns/ folder (recommended for block themes)
> - PHP registration - uses the [register_block_pattern()](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern)

Do you think that is adequate guidance?

**Comment by colorful-tones** [comment]
I've submitted the post for review: "Block Patterns" under the "Advanced Theme Topics" (parent) on the Developer site.

Once approved, it would appear here: `https://developer.wordpress.org/themes/advanced-topics/block-patterns/`

Heads up @carolinan @kafleg @TeBenachi - I'm assuming it is you folks that will review and publish it? 

Thanks everyone for your guidance! 🥳

**Comment by colorful-tones** [comment]
Adding a note here to add in a new section to this doc that addresses how to conditionally load 3rd party blocks in patterns. As flagged by @carolinan [in Slack](https://wordpress.slack.com/archives/C015GUFFC00/p1658529329831819?thread_ts=1658476772.718039&channel=C015GUFFC00&message_ts=1658529329.831819).

**Comment by colorful-tones** [comment]
@carolinan @justintadlock - I added a new section: "Using 3rd-party blocks". Please review and let me know if there is any feedback. Thanks!

**Comment by annezazu** [comment]
@colorful-tones not sure if this is desired to be included but wanted to note some of the fun stuff from the [curating the editor doc](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/#utilizing-patterns). Perhaps just linking off to this one is more than enough for now but it would be great to talk about locking, prioritizing patterns, etc.

**Comment by colorful-tones** [comment]
> @colorful-tones not sure if this is desired to be included but wanted to note some of the fun stuff from the [curating the editor doc](https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/#utilizing-patterns). Perhaps just linking off to this one is more than enough for now but it would be great to talk about locking, prioritizing patterns, etc.

@annezazu I think that is suitable for this doc and would be happy to add. I mostly want to get this published for now and could even add something while publishing the final doc, but just getting something published is better than nothing. 😄 

I'll leave this open for another day or two for feedback, but then will likely publish and iterate from there.

**Comment by annezazu** [comment]
I hear you there :D Sounds great.

**Comment by colorful-tones** [comment]
@zzap I've just clicked the 'Submit for Review' [on this draft](https://developer.wordpress.org/wp-admin/post.php?post=141733&action=edit). Curious, what team might be reviewing? Should I ping somebody?

**Comment by carolinan** [comment]
Please no more pings 😄 once is enough unless you don't hear anything for several weeks.

**Comment by carolinan** [comment]
@colorful-tones Are you still editing? The post is still locked.

**Comment by colorful-tones** [comment]
@carolinan no, I am no longer editing.

**Comment by carolinan** [comment]
I have some **suggestions**.

In the first paragraph it says:
"They offer a means to expedite and elevate the editorial experience by offering users a preset arrangement of blocks to start building right away."

As a non native English speaker, the use of expedite and elevate and editorial experience is just confusing to me.
My actual reaction was "Elevate? you mean like elevating an element in the design by adding a box shadow?"
Can this be simplified and shortened?

---
The first code example was missing a translation function for part of the text. I have added it.

----
Below the first code example it says:
"The title and slug properties in the pattern's header are required."
Can we explain what these are? Part of that information is included for the PHP function, but not for the patterns folder.

And for the PHP function, it says that title and content are required, but it does not mention the slug.

----

In the translation code example, the text is escaped but not echoed.
How we can best explain the difference between the methods here?
In the PHP file in the patterns folder, the text needs to be echoed, but if we are using the PHP function to register the pattern, the text can't be echoed because we are _returning_ the whole `content`...
This difference got me more than once when I switched to using the patterns folder ;)

----

Linking assets code example
Nit picking: Can we explain that this is not a full code example for the cover block? Because if someone tries to copy paste that code it will not work. In the cover block, the image source is used twice. Would it be easier to use an complete image block?

----

At the bottom, we should include a changelog. The first item will only show when the page was published.
I have added this.

**Comment by carolinan** [comment]
OK a few more things that came to mind after I posted the comment above:

1. Should it not include instructions for how to display the pattern in a template in a full site editing theme, using the pattern block?
3. Can we link to [Converting customizer settings to block patterns]( https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/)?

**Comment by carolinan** [comment]
On this list item `patterns/ folder (recommended for block themes)` can we add that it only works from 6.0?

**Comment by colorful-tones** [comment]
@carolinan thanks for all this awesome feedback! I'm going to look to incorporate it directly in the Make draft post. I'll drop a note here once it is all updated. 👍

**Comment by colorful-tones** [comment]
> In the first paragraph it says:
> "They offer a means to expedite and elevate the editorial experience by offering users a preset arrangement of blocks to start building right away."
> 
> As a non native English speaker, the use of expedite and elevate and editorial experience is just confusing to me.
> My actual reaction was "Elevate? you mean like elevating an element in the design by adding a box shadow?"
> Can this be simplified and shortened?

I've changed to read: "They offer a means to refine the editorial experience by offering users a preset arrangement of blocks to start building right away." Does this seem clearer? 

<hr>

> The first code example was missing a translation function for part of the text. I have added it.

Thank you! 👍 

<hr>

> Below the first code example it says:
> "The title and slug properties in the pattern's header are required."
> Can we explain what these are? Part of that information is included for the PHP function, but not for the patterns folder.
> 
> And for the PHP function, it says that title and content are required, but it does not mention the slug.

I believe I've addressed this. Please peek and let me know.

<hr>

> In the translation code example, the text is escaped but not echoed.
> How we can best explain the difference between the methods here?
> In the PHP file in the patterns folder, the text needs to be echoed, but if we are using the PHP function to register the pattern, the text can't be echoed because we are returning the whole content...
> This difference got me more than once when I switched to using the patterns folder ;)

I've added clarification around this as well. Let me know.

<hr>

> Linking assets code example
> Nit picking: Can we explain that this is not a full code example for the cover block? Because if someone tries to copy paste that code it will not work. In the cover block, the image source is used twice. Would it be easier to use an complete image block?

I've converted the example from a Cover block to an Image block. Let me know.

> At the bottom, we should include a changelog. The first item will only show when the page was published.
> I have added this.

You rock! Thank you! ❤️ 

<hr>

>OK a few more things that came to mind after I posted the comment above:
> 1. Should it not include instructions for how to display the pattern in a template in a full site editing theme, using the pattern block?
> 2. Can we link to [Converting customizer settings to block patterns](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/)?

I've addressed these as well.

<hr>

> On this list item patterns/ folder (recommended for block themes) can we add that it only works from 6.0?

I've added this with a link to the Make post announcing the addition of this feature.

<hr>

### Summary

@carolinan ☝️  

Again, thanks for the review and feedback. Please let me know if you have anything further. I hope you enjoy your weekend and get some relaxing cross-stitching in. 🕺

**Comment by carolinan** [comment]
The page is published and added to the menu. Thank you!
