### ISSUE TITLE
Theme developer handbook: Update "Creating new themes using the Site Editor" for 6.0

### ISSUE THREAD

**Issue by carolinan** [WordPress/Documentation-Issue-Tracker#343]
## Issue Description

The Site Editor export function has been improved or extended in WordPress 6.0, and the article refers to more limited features in WordPress 5.9.

## URL of the Page with the Issue

https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor/

## Why is this a problem?

The information is out of date and does not reflect how this feature can be used.

## Suggested Fix

Update the content to describe the current feature.

**Comment by carolinan** [comment]
You can assign this issue to me

**Comment by carolinan** [comment]
@TeBenachi @kafleg 

I have written an update and scheduled it for publishing on May 25, I hope that is enough time to review the changes and make adjustments.

**Comment by kafleg** [comment]
@carolinan Thank you for the update. 
What about adding a link to know how to upload the theme in the WordPress repo in the **Sharing your new theme** section?

**Comment by carolinan** [comment]
Good idea, added.
