### ISSUE TITLE
Theme developer handbook: Update the theme.json page for 6.0

### ISSUE THREAD

**Issue by carolinan** [WordPress/Documentation-Issue-Tracker#344]
## Issue Description

The page should be updated to include information about style variations added in 6.0.

## URL of the Page with the Issue

https://developer.wordpress.org/themes/advanced-topics/theme-json/

## Why is this a problem?

It is missing information about new features.

## Suggested Fix

The information about style variations can be moved from the block editor handbook:
https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/#global-styles-presets

The page needs a "read-through" to see if there are any other 6.0 additions or changes that should be added.

**Comment by carolinan** [comment]
It feels short, can we explain what it is used for, maybe give an example from Twenty Twenty-two color and font variation?

**Comment by TeBenachi** [comment]
Good point 😅  

Revised below :)

===

Global Styles variations

A theme can have multiple JSON files for offering different styles at the top-level settings. When users select the additional style, it will overwrite the styles on the default theme.json. There are several requirements to keep in mind. 

- The minimum required WordPress version is 6.0. 
- The default theme.json must be located in the root directory and is required to declare using theme.json version 2. 
-  Additional JSON files must be placed in the `/styles` directory. 


`Title` can be added to the additional JSON files to label each style variation. The users will see the title on the site editor. If `title` is missing from a JSON file, the file name will be used as the label instead. 

With the below example, the users see “Dark” as the label for this style variation under the Browse Styles in the side editor. Also, in this example, the background and the text color properties will overwrite the default style when a user selects the ‘Dark” style. 

```
{
    "version": 2,
    "title": "Dark",
    "styles": {
        "color": {
            "background": "black",
            "text": "white"
        }
    }
}
```

**Comment by carolinan** [comment]
_When users select the additional style_

Where? :)

**Comment by TeBenachi** [comment]
Thank you so much for reviewing Carolina!
I keep forgetting this is a brand new feature ☺️

_When users select the additional style under the Browse Styles in the side editor._

I update the theme.json page with the new content at the bottom of the page. 
https://developer.wordpress.org/themes/advanced-topics/theme-json/?preview_id=136564&preview_nonce=d04e0a1fa2&preview=true

**Comment by carolinan** [comment]
Let's close this as completed.
