### ISSUE TITLE
Broken Link on Meta Handbook Page

### ISSUE THREAD

**Issue by SavPhill** [WordPress/Documentation-Issue-Tracker#346]
## Issue Description

The Meta Handbook page contains a broken link in the About section. I submitted this issue on the Meta Trac (https://meta.trac.wordpress.org/ticket/6314 ) but later realised that it should be submitted here.

## URL of the Page with the Issue

The URL which references the broken link: https://make.wordpress.org/meta/handbook/
## Section of Page with the issue

The link for the ‘Entire Team’ leads to a missing page. Once you visited
the page it displays the text:

“Apologies, but the page you requested could not be found. Perhaps
searching will help”

The broken URL:

https://make.wordpress.org/meta/handbook/about/team/

## Why is this a problem?

The required page is not accessible at the link.
## Suggested Fix

We can correct the fix with the correct URL, or by removing the hyperlink (if this does not exist). We can consider creating the page at a later date if it no longer exists.

**Comment by stevenlin-x** [comment]
What you did in the trac ticket was correct.

The editing of the Meta Handbook content does not belong here.

As indicated in the Readme of this repo, here is the coverage:

> Please report issues here if your suggestion is related to the following
> 
> Our development documentation located at https://developer.wordpress.org/ (Code named DevHub)
> Our end-user documentation located at https://wordpress.org/support/ (Code named HelpHub)
> The Documentation Team's handbook located at https://make.wordpress.org/docs/handbook/

In addition, you can also try drop by in the Meta Slack channel: the link is in the contact section on the top right of this page
https://make.wordpress.org/meta/handbook/
