### ISSUE TITLE
wp-config.php on HelpHub is too technical

### ISSUE THREAD

**Issue by Kenshino** [WordPress/Documentation-Issue-Tracker#349]
## Issue Description

wp-config.php on HelpHub is too technical

Whereas there's no explanation of it in DevHub

## URL of the Page with the Issue

https://wordpress.org/support/article/editing-wp-config-php/

## Suggested Fix

I'll be moving most of the content to DevHub and restructure the content left on HelpHub

**Comment by Kenshino** [comment]
Removing the entire section

<img width="874" alt="image" src="https://user-images.githubusercontent.com/4746365/169657138-7942af01-a552-4b6d-a5b8-fdc262995216.png">

There's no point for us to provide this - this info should be gotten from the host and we're well past the years where installation could fail because of wrong values added / not added by the host

**Comment by Kenshino** [comment]
New DevHub page created on the Common API handbook page - https://developer.wordpress.org/apis/wp-config-php/

**Comment by Kenshino** [comment]
HelpHub page fully simplified to suggest that users won't really need to edit wp-config.php

**Comment by tobifjellner** [comment]
Remember to include a link in the userdoc to https://wordpress.org/support/article/debugging-in-wordpress/ which contains descriptions of those actions a "normal user" may need to actually do.

**Comment by javiercasares** [comment]
There are some tools about wp-config (one is mine):

- https://wpconfig.wpsysadmin.com/
- https://generatewp.com/wp-config/
- https://developer.wordpress.org/apis/wp-config-php/
- https://github.com/romslf/wp-config-generator
- https://developer.wordpress.org/cli/commands/config/

Also, I documented practically all the wp-config options here some time ago.

https://en.wpsysadmin.com/security/wordpress/wp-config/

**Comment by theMikeD** [comment]
FYI we do not make links to external (non-WordPress owned) sites.

**Comment by javiercasares** [comment]
Added into https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/3

**Comment by javiercasares** [comment]
File: [wordpress/wp-config.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/wp-config.md)

- [#15](https://github.com/WordPress/Advanced-administration-handbook/issues/15) Content is migrated.
- [#89](https://github.com/WordPress/Advanced-administration-handbook/issues/89) Reviewed
