### ISSUE TITLE
Small typographical error in Query Controls Component documentation

### ISSUE THREAD

**Issue by xconsau** [WordPress/Documentation-Issue-Tracker#350]
## Issue Description
On the Block Editor Components documentation, there is a small typo inside the onCategoryChange section. The word 'author' should be changed to 'category'.

## URL of the Page with the Issue
https://developer.wordpress.org/block-editor/reference-guides/components/query-controls/#oncategorychange

## Section of Page with the issue
The "onCategoryChange" section.

## Why is this a problem?
Probably, while copying the same text from the "onAuthorChange" section, it mistakenly remained as "author" instead of the "category".

## Suggested Fix
"A function that receives the new **category** value. If this is not specified, the category controls are not included."

![w1](https://user-images.githubusercontent.com/11784237/169851392-b6c48085-433d-472b-915f-ea82bdbc218c.png)

Besides that, a huge thanks to the documentation team for writing such a detailed reference guide.

**Comment by stevenlin-x** [comment]
This issue doesn't belong in this repo.

It belongs to the gutenberg repo:
https://github.com/WordPress/gutenberg

As you see next to the title "QueryControls", there is an GitHub edit button which bring you to the PR screen.
https://github.com/WordPress/gutenberg/edit/trunk/packages/components/src/query-controls/README.md

**Comment by xconsau** [comment]
Thank you, Steven. And my apologies for posting in the wrong repo. Thank you for the correct link.
