### ISSUE TITLE
Code typo mistake : Remove unused square bracket

### ISSUE THREAD

**Issue by krupal-panchal** [WordPress/Documentation-Issue-Tracker#353]
## Issue Description

There is a code snippet block on this page, including an unused square bracket on the first line. So it needs to remove and indent the code according to a coding standard for a better view.

## URL of the Page with the Issue

https://developer.wordpress.org/plugins/javascript/ajax/#client-side-summary

## Section of Page with the issue

[Client Side Summary](https://developer.wordpress.org/plugins/javascript/ajax/#client-side-summary)

## Why is this a problem?

That code might be copy-paste from somewhere with the unused square bracket.

## Suggested Fix

- Remove the unused square bracket.
- Indent the code according to coding standards.

**Comment by stevenlin-x** [comment]
It's fixed.

Thanks for reporting @krupal-panchal

**Comment by krupal-panchal** [comment]
Thanks @stevenlin-x
