### ISSUE TITLE
QTags handbook page has a broken code example

### ISSUE THREAD

**Issue by tomjn** [WordPress/Documentation-Issue-Tracker#357]
## Issue Description

The code provided for adding buttons to quick tags in the docs doesn't work properly in WordPress 6.0, and uses a non-standard approach.

## URL of the Page with the Issue

https://developer.wordpress.org/apis/handbook/quicktags/

## Section of Page with the issue

The code blocks

## Why is this a problem?

Because it's bad code that doesn't work

## Suggested Fix
Instead of manually adding hardcoded javascript with `wp_script_is` on the admin footer hook, instead, use the inline JS API to add the JS when quicktags are enqueued.

e.g.

```php
function add_quicktag_paragraph() {
    wp_add_inline_script(
        'quicktags',
        "QTags.addButton( 'eg_paragraph', 'p', '<p>', '</p>', 'p',     'Paragraph tag', 1 );"
);
add_action( 'wp_enqueue_scripts', 'add_quicktag_paragraph' );
```

Infact the codex has a better example that works:

https://codex.wordpress.org/Quicktags_API

**Comment by atachibana** [comment]
@tomjn

Please refer issue #13. I tried to brush up this page as much as possible. Please add any comment there.
