### ISSUE TITLE
Add new Autoloaded options section to Optimization article

### ISSUE THREAD

**Issue by bethanylang** [WordPress/Documentation-Issue-Tracker#358]
## Issue Description
The [Performance Lab plugin](https://wordpress.org/plugins/performance-lab/), part of the work of the WP Performance Team, includes a health check for autoloaded options (see https://github.com/WordPress/performance/issues/92). We'd like to add a new section to the [Optimization article](https://wordpress.org/support/article/optimization/) to link to directly from the health check report, so that users have a better idea of next steps for resolving the warning for too many autoloaded options.

## URL of the Page with the Issue
https://wordpress.org/support/article/optimization/

## Section of Page with the issue
Add new section to https://wordpress.org/support/article/optimization/#Improve_WordPress_Performance for "Autoloaded options" with an anchor of #autoload 

## Why is this a problem?
There currently is not any documentation regarding autoloaded options.

## Suggested Fix
Add the following text in the new Autoloaded options section:

Autoloaded options are configuration settings for plugins and themes that are automatically loaded with every page load in WordPress. Each plugin and theme defines their own options and which options are autoloaded. Having too many autoloaded options can slow down your site. Generally, you should try to keep your site’s autoloaded options under 800kb.

By default, autoloaded options are saved in the `wp_options` table. Autoload can be turned off on an option-by-option basis within this table. For step-by-step instructions on viewing and changing autoloaded options, check with your hosting provider and see the guides below for examples as the solution for your provider may be similar.

#### Further reading
Kinsta: [How to Clean up Your wp_options Table and Autoloaded Data](https://kinsta.com/knowledgebase/wp-options-autoloaded-data/)
WP Engine: [WordPress Database Optimization: Autoloaded Data](https://wpengine.com/support/database-optimization-best-practices/#Autoloaded_Data)
Pantheon: [Optimize Your wp-options Table and Autoloaded Data](https://pantheon.io/docs/optimize-wp-options-table-autoloaded-data)
Servebolt: [Clean up autoloaded options in WordPress](https://servebolt.com/help/article/clean-up-autoloaded-options-in-wordpress/)

**Comment by bethanylang** [comment]
@stevenlin-x Thanks for picking this one up! I have editing access now via @zzap so I'm going to make this update myself.  :) Reassigning to me.

**Comment by stevenlin-x** [comment]
They are here:

#external-linking-policy
https://make.wordpress.org/docs/tag/external-linking-policy/

**Comment by bethanylang** [comment]
Actually, reopening this as I've reviewed the linked external linking policy more closely, and it looks like those requirements explicitly refer to the Plugin Developer Handbook but not end user documentation. @zzap Can you clarify please?

**Comment by bethanylang** [comment]
Closing as per [discussion in Slack](https://wordpress.slack.com/archives/C02RP4WU5/p1656507618205849), the policy applies to all documentation.
