### ISSUE TITLE
Incomplete sentence in Additional guide to using the Site Editor

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#368]
## Issue Description
In the post [Additional guide to using the Site Editor](), a sentence is incomplete.

## URL of the Page with the Issue
You can find this at https://wordpress.org/support/article/additional-guide-to-using-the-site-editor

## Section of Page with the issue
How to customize your home page > Static Page > Follow these steps to create a new template:

## Why is this a problem?
In this list, the sentence on 5 is incomplete:
1.From your wp-admin dashboard, head to Pages > All Pages.
2.From the list of pages, select the option to edit page you have set as your home page.
3.Once in the editor, open the settings sidebar.
4.Under “Template”, select New.
5.This will
6.When you’re done, select “Update” to save the changes."

## Suggested Fix
This will open the Site Editor to add blocks for create your template for your static homepage.

**Comment by stevenlin-x** [comment]
I've revised the sentence.
