### ISSUE TITLE
out of date More Info on code reference for get_option

### ISSUE THREAD

**Issue by joyously** [WordPress/Documentation-Issue-Tracker#376]
## Issue Description
The "More Information" for the `get_option` function has a link to https://codex.wordpress.org/Option_Reference .
The list of commonly-used options says
> 'upload_path' – Default upload location; set in Miscellaneous Options.

but there is no longer any Miscellaneous Options page in WordPress, and
> 'template' – The current theme’s name; set in Presentation.

but there is nothing called Presentation in WordPress.
Also, this list is partially alphabetical, but a weird order overall.
Some of the options like `blogname` could match better what the label says on the Options page in the admin.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/get_option/

## Section of Page with the issue
More Information

## Why is this a problem?
It refers to Codex and an options page that does not exist (Miscellaneous Options).

**Comment by jaedm97** [comment]
@zzap I would like to work on this issue. Can you please add me? 

Thank you.

**Comment by jaedm97** [comment]
Hi @zzap Sorry about the delay.

The content should be something I wrote below: 

===========================================================================

A concise list of commonly-used options is below.

* 'admin_email' – E-mail address of blog administrator.
* 'blogname' – Weblog title; set in General Options.
* 'blogdescription' – Tagline for your blog; set in General Options.
* 'blog_charset' – Character encoding for your blog; set in Reading Options.
* 'date_format' – Default date format; set in General Options.
* 'default_category' – Default post category; set in Writing Options.
* 'home' – The blog’s home web address; set in General Options.
* 'siteurl' – WordPress web address; set in General Options. Warning: This is not the same as get_bloginfo( 'url' ) (which will return the homepage url), but as get_bloginfo( 'wpurl' ).
* 'template' – The current theme’s name; set in Presentation.
* 'start_of_week' – Day of week calendar should start on; set in General Options.
* 'upload_path' – Default upload location; set in Miscellaneous Options.
* 'users_can_register' – Whether users can register; set in General Options.
* 'posts_per_page' – Maximum number of posts to show on a page; set in Reading Options.
* 'posts_per_rss' – Maximum number of most recent posts to show in the syndication feed; set in Reading Options.

There are many more options available, a lot of which depend on what plugins you have installed.

===========================================================================

Please let me know if there is any question. This is my very first contribution to the documentation, very excited.

**Comment by joyously** [comment]
Hi @jaedm97 
Please fix the other problems listed in the issue description. It looks like the only thing changed was the removal of the codex link.

**Comment by jaedm97** [comment]
Hi @joyously Sorry about it. I have corrected it. 

- Removed **set in Miscellaneous Options**
- Removed **set in Presentation**
- Corrected the order.

@zzap Please check and let me know any questions. Thank you.

**Comment by zzap** [comment]
This has been fixed and reported in [Trac ticket](https://core.trac.wordpress.org/ticket/57162) for the transparency with core team. 

Thank you both :heart:
