### ISSUE TITLE
Facebook oEmbed deprecation link broken

### ISSUE THREAD

**Issue by gamebits** [WordPress/Documentation-Issue-Tracker#377]
## Issue Description

A malformed link fails to cite the source for Facebook's deprecation of oEmbed in October 2020.

## URL of the Page with the Issue

https://wordpress.org/support/article/facebook-embed/

## Section of Page with the issue

The first sentence, "Due to Facebook’s decision to close the oEmbed end point for embedding Facebook links", includes a link that points here:

```
http://Facebook%20announced%20updates%20to%20their%20Marketing%20API
```

[The Wayback Machine](https://web.archive.org/web/20201002070505/https://wordpress.org/support/article/facebook-embed/)'s capture of this documentation page confirms it has always contained a malformed, invalid link.

## Why is this a problem?

The URL is broken (404) and prevents developers from getting more details.

## Suggested Fix

This contemporaneous post from the official Facebook blog appears to a viable primary source we can use instead:

https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8

**Comment by stevenlin-x** [comment]
I've revised the link.

Thanks for reporting.
