### ISSUE TITLE
Dead link for 'Mac App Store 1-click install for WordPress' should be removed

### ISSUE THREAD

**Issue by christinavoudouris** [WordPress/Documentation-Issue-Tracker#378]
## Issue Description
The link described below takes me to a page which then prompts me to open the App Store on my mac. When I do that, the App Store gives me another prompt saying 'App Not Available.'

## URL of the Page with the Issue
[Installing WordPress On Your Own Computer](https://wordpress.org/support/article/installing-wordpress-on-your-own-computer)

## Section of Page with the issue
The [Mac App Store 1-click install for WordPress](https://itunes.apple.com/us/app/bitnami-stack-for-wordpress/id588981362?mt=12) link under [Local Installation Instructions](https://wordpress.org/support/article/installing-wordpress-on-your-own-computer/#local-installation-instructions).

## Why is this a problem?
The link is dead / dated / not useful. 

## Suggested Fix
The link should be removed.

**Comment by stevenlin-x** [comment]
It seems the Bitnami stack for WordPress no longer exist on the Mac app store.

I've removed the link.

Thanks for reporting.
