### ISSUE TITLE
Data module section needs practical code examples.

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/Documentation-Issue-Tracker#379]
## Issue Description
Working with any of the data modules provided by WordPress can be very confusing. When looking at the Data Modules section in the handbook, there are almost no code examples for developers to use as reference. I would love to see an example for each action or selector that is exposed for use.

## URL of the Page with the Issue
https://developer.wordpress.org/block-editor/reference-guides/data/ and subpages.

## Why is this a problem?
Looking at these references does not provide any sort of context on how to use them. Providing even the simplest but practical example would go a long way to drive adoption.

## Suggested Fix
Add an `@example` tag to each docblock. This will be picked up by the documentation generator and added to the handbook.

**Comment by stevenlin-x** [comment]
It seem this issue need to be closed.

The Block Editor Handbook is not the scope of this repo.

**Comment by ryanwelcher** [comment]
> The Block Editor Handbook is not the scope of this repo.

There are other tickets for the block editor handbook in this repo - https://github.com/WordPress/Documentation-Issue-Tracker/labels/block%20editor. Is there some documentation I have missed that explicitly states that?

**Comment by stevenlin-x** [comment]
The https://github.com/WordPress/Documentation-Issue-Tracker/labels/block%20editor label refers to the HelpHub documentation with respect to the block editor, which is in this repo.

But editing the content in Block Editor Handbook is the domain of the gutenberg repo:
https://github.com/WordPress/gutenberg/tree/trunk/docs

For example, on the "[Data Module Reference](https://developer.wordpress.org/block-editor/reference-guides/data/)" page, if you click "Edit" next to the title, it will lead you to the following file of the gutenberg repo.
https://github.com/WordPress/gutenberg/edit/trunk/docs/reference-guides/data/README.md

**Comment by ryanwelcher** [comment]
@stevenlin-x I was told by my @zzap to create this kind of tracking ticket here for docs work that is being done in the Gutenberg repo.

**Comment by zzap** [comment]
@stevenlin-x we are trying to prepare a proposal for Block editor team to have a more PHP devs friendly documentation. This is not just docs update here and there, this is improving the whole section the way Documentation team sees it.

@ryanwelcher kindly offered to work on this and we want to prepare everything here first and then go to Gutenberg repo with all the examples and arguments.

So @ryanwelcher, please continue here as planned. Thank you so much.
