### ISSUE TITLE
Team Handbook landing page

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#384]
## Issue Description
This page is unclear about what it represents and where to go next.

## URL of the Page with the Issue

https://make.wordpress.org/docs/handbook/

## Why is this a problem?
Because it's not very helpful to people who go there to learn how to get involved with the team.

**Comment by zzap** [comment]
Analysing other teams Handbook landing pages:

- [Core](https://make.wordpress.org/core/handbook/) - who is it for, ways to contribute, best practices, tutorials, how to get help (more or less, sidebar navigation is outlined)
- Design - style guide in general, core treatment, wp.org treatment, other sites treatment (basically, outlining projects)
- [Accessibility](https://make.wordpress.org/accessibility/handbook/) - what's in handbook, team's mission, call to join
- [Polyglots](https://make.wordpress.org/polyglots/handbook/) - what's in handbook and how it is organised, about the team, what are i18n and l10n, translation process, about the platform, about locales, specific team's vocabulary
- [Mobile](https://make.wordpress.org/mobile/handbook/) - intro to apps, quick links
- [Support](https://make.wordpress.org/support/handbook/) - what's in handbook, quick links to places, links to other places in case this is not what you've been looking for 
- [Themes](https://make.wordpress.org/themes/handbook/) - introduced review process, required items, call to join
- [Plugins](https://make.wordpress.org/plugins/handbook/) - notice about not accepting new members, what's in handbook, very outdated note
- [Community](https://make.wordpress.org/community/handbook/) - list all the other handbooks they have 
    - [Community team](https://make.wordpress.org/community/handbook/community-team/) - what the team is doing, mission, why is this team's work important, list of links to different types of events
    - [Community Deputy Handbook](https://make.wordpress.org/community/handbook/community-deputy/) - what is the role, why these roles exist, what do they do, helpful prior knowledge, resources, call to join

**Comment by theMikeD** [comment]
That's the "Plugin Reviewer's Handbook" not the "Plugin Developer's Handbook," for clarity :)

As for the initial observation...there is a section in the TOC literally called "Get Involved" that is sufficient for that purpose...?

**Comment by zzap** [comment]
Get involved page should give a quick overview how to get started but I'm trying to figure out how to make landing page more useful.

**Comment by zzap** [comment]
Docs team handbook outline

- Accounts needed 
- Places where things are happening
- Meetings
- Reporting issues
- Onboarding
- Projects

**Comment by zzap** [comment]
## Documentation Contributor Handbook

This handbook contains information about how to contribute to WordPress documentation and be a member of the Documentation team.

**Comment by colorful-tones** [comment]
@zzap I made a few grammatical updates to your post (still creepy that I can Edit your words). This seems like an overall improvement to me. 👏 

The only thing I wonder about... the current page has a small callout about the Codex, which I feel like we might want to still consider having it? However, I would encourage us to push it towards the bottom and maybe give it special callout styling treatment (blue or even red background). Similar to what you see on this page: https://make.wordpress.org/plugins/handbook/

![Screen Shot 2022-07-26 at 11 24 11 AM](https://user-images.githubusercontent.com/405912/181046185-ab40613d-1058-4688-b188-9a2a9ba55703.png)

Otherwise, I say ship it! :shipit:

**Comment by zzap** [comment]
Thank you for review @colorful-tones :raised_hands:
