### ISSUE TITLE
Wrong link added in submit feedback section in each article 

### ISSUE THREAD

**Issue by pratiweb** [WordPress/Documentation-Issue-Tracker#386]
https://wordpress.org/support/article/categories-block/

## Issue Description
When you are logged in wordpress org. you will get **Was this article helpful? How could it be improved?** section to add improvements in each support documentation. 

There is link mention for official wordpress support forum which have unuseful id section name like 
https://wordpress.org/support/forums/#bbpress-forums

![documentation-issue](https://user-images.githubusercontent.com/37148199/179910554-da0b8162-aca9-4bea-9075-870a900abd1a.PNG)

Correct link should be https://wordpress.org/support/forums/

**Comment by Renda02** [comment]
Hi @pratiweb, I am interested in resolving this issue. May you kindly guide me?

**Comment by zzap** [comment]
This issue is being worked on in this Trac ticket: https://meta.trac.wordpress.org/ticket/5758
