### ISSUE TITLE
Spelling mistake in plugin handbook

### ISSUE THREAD

**Issue by jopdop30** [WordPress/Documentation-Issue-Tracker#390]
## Issue Description

On the 'Server Side PHP and Enqueuing' page of the plugin handbook there is spelling mistake where the author wrote the word 'sould' instead of 'should'.

## URL of the Page with the Issue

https://developer.wordpress.org/plugins/javascript/enqueuing/#:~:text=to%20someone%20who-,sould,-not%20use%20it

## Section of Page with the issue

The information box underneath the 'Localize' heading.

## Why is this a problem?

'sould' is not a real English word.

## Suggested Fix

The letter 'h' should be added after the letter 's' to make the word 'should'.

**Comment by jagirbahesh** [comment]
I am interested  to resolve this issue.
I have also read the readme.md but i am not getting how to start.
Can any one guid for the same?

**Comment by theMikeD** [comment]
Done.
