### ISSUE TITLE
[HelpHub] Content review in similar articles

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#394]
## Issue Description

The articles **Adding and moving blocks** and **Moving blocks** have similar content at the end.

## URL of the Page with the Issue

[Adding and moving blocks](https://wordpress.org/support/article/adding-a-new-block) and [Moving blocks](https://wordpress.org/support/article/moving-blocks/)

## Section of Page with the issue

https://wordpress.org/support/article/adding-a-new-block/#moving-blocks

## Why is this a problem?
 duplicated content

## Suggested Fix
 Remove the section [moving blocks](https://wordpress.org/support/article/adding-a-new-block/#moving-blocks) from the article as well as the words **moving blocks** from the title.
There is no need to change URL or anything else.

**Comment by femkreations** [comment]
@estelaris Thanks for catching this. I've added a link in the Add Block page to point to the Move page and moved the content to the Move page.
Also refreshed the content and title.

https://wordpress.org/support/article/adding-a-new-block/
https://wordpress.org/support/article/moving-blocks/
