### ISSUE TITLE
Plugin Handbook: two different addresses to get to same page

### ISSUE THREAD

**Issue by joyously** [WordPress/Documentation-Issue-Tracker#397]
## Issue Description
A callout paragraph has two different links that resolve to the same page.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/

## Section of Page with the issue
First section, yellow callout

## Why is this a problem?
It appears that there are two pages about the same topic, thus more to research before understanding the concept.

## Suggested Fix
Adjust the link to https://developer.wordpress.org/plugins/the-basics/uninstall-methods/
to be https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/ and remove the last sentence with the second link.

_There is actually another link under the Deactivation section that also links using "the-basics" but resolves to "plugin-basics"._

**Comment by theMikeD** [comment]
Done.
