### ISSUE TITLE
Broken Link: wp-config-sample.php goes to a 4.4.2 trac tag that's not working

### ISSUE THREAD

**Issue by garretthyder** [WordPress/Documentation-Issue-Tracker#399]
## Issue Description
In the 'Default wp-config-sample.php' section - https://developer.wordpress.org/apis/wp-config-php/#default-wp-config-sample-php
The link to wp-config-sampe.php - https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-config-sample.php#L0
Is broken and goes to a dead trac tag.

Should be linked to trunk maybe? https://core.trac.wordpress.org/browser/trunk/wp-config-sample.php

## URL of the Page with the Issue
https://developer.wordpress.org/apis/wp-config-php/#default-wp-config-sample-php

## Section of Page with the issue
"In the 'Default wp-config-sample.php' section"

## Why is this a problem?
It's a broken link that goes to a dead trac tag.

## Suggested Fix
Should be linked to trunk maybe? https://core.trac.wordpress.org/browser/trunk/wp-config-sample.php
Or a more evergreen stable url.

**Comment by kkoppenhaver** [comment]
We have updated this link to the link to trunk as part of WCUS 2022 Contributor Day.
