### ISSUE TITLE
Documentation section of Core Contributor Handbook needs content

### ISSUE THREAD

**Issue by mkaz** [WordPress/Documentation-Issue-Tracker#4]
Navigating to Core Contributor Handbook and then Contribute with Docs leads me to this page which is empty
https://make.wordpress.org/core/handbook/docs/

It probable should directly link to: https://make.wordpress.org/docs/handbook/

**Comment by audrasjb** [comment]
Hello! Thanks for pointing this out. I added a short introduction and a link to the Documentation Team Handbook.
--> https://make.wordpress.org/core/handbook/docs/
