### ISSUE TITLE
Theme developer handbook: Add a page for theme resources/tools 

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#401]
## What is the new page you are requesting?

As more tools are coming onto the scene for getting started with block themes, I think it makes sense to gather them in one place for folks to explore and find what fits their needs. Here's the list I have:

- [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/) by theme contributors. 
- [Theme Generator](https://fullsiteediting.com/block-theme-generator/) by Carolina Nymark 
- [ThemeGenApp](https://www.themegen.app/) by David Gwyer.
- [Block Theme Generator](https://www.pootlepress.com/wordpress-theme-builder/) by Jamie Marsland.

WP Engine is also working on an alpha theme studio. You can [sign up here](https://docs.google.com/forms/d/e/1FAIpQLSf8qbReVvMLERvEe9ErhdGZ7FkJNgo5nz_Dw1CGc_-D5WDiQg/viewform) to get early access but there doesn't seem to be an official link just yet.

To level up the page, I think it would be neat to offer a comparison chart of some sort too so folks can pick what makes sense for them. Perhaps something like this: 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d1f7352a-7fff-f7d0-4fb2-2ec0d706d683"><div dir="ltr" style="margin-left:0pt;" align="left">

Tool | Child theme options? | Template creation? | Theme.json Controls
-- | -- | -- | --
Create block plugin | Yes | Yes | No
Theme Generator | No | Yes | Yes
ThemeGenApp | No | Yes | Yes
Block Theme Generator | No | Yes | No

</div><br /></b>

## How will this new page help you?

It will help folks use community tools to get started faster!

**Comment by annezazu** [comment]
Happy to draft something/collaborate with someone/etc. Just let me know how best to proceed as I haven't yet contributed to the Theme Handbook just yet!

**Comment by theMikeD** [comment]
In general we do not link to third party sites.

**Comment by jeffikus** [comment]
@theMikeD ok, at the very least Create Block Theme plugin is a WordPress project, so we should link to that somehow in the same manner we do for Create Block package here -> https://developer.wordpress.org/block-editor/getting-started/create-block/

**Comment by zzap** [comment]
I would link to [Create Theme Plugin](https://wordpress.org/plugins/create-block-theme/) and [Theme Generator](https://fullsiteediting.com/block-theme-generator/) from fullsiteediting.com. Fullsiteediting site is extremely valuable resource, created by make team member solely for the open source benefit. It could have easily been under wp.org if we had the place for it at the time.

For the other two resources we can not guarantee they would still exist in the future, remain free/open source, or that are made without intent of advertising other products and services by the author. I'm not saying that any of this is the case, just that we, as maintainers of WordPress documentation, can not guarantee either way and keeping them would mean we need a person to regularly check on them and make sure they are remaining in the best intention for the documentation users. Not to mention other tools that might be created in the future or already exists and their authors demanding to be listed at wp.org just as others are.

**Comment by annezazu** [comment]
Thanks for clarifying! What's the process for getting the first two added in that case? Happy to write up a proposed blurb. I might defer a bit to @poena considering one of those tools is hers/due to her history with the theme team in navigating how best to approach adding these resources.

**Comment by zzap** [comment]
> Thanks for clarifying! What's the process for getting the first two added in that case? Happy to write up a proposed blurb. I might defer a bit to @poena considering one of those tools is hers/due to her history with the theme team in navigating how best to approach adding these resources.

As this is Themes handbook I don't want to interfere with what Themes team have in plan regarding structure and the info provided. I would suggest though, from the documentation user perspective, to keep the comparison table, that's a nice touch. Also, I'd love clearly noted reasons when I would use each tool and why. Which problem does it solve (better than other?) and which problem does it introduce? Why would I use it over manual creation? Sort of pros and cons list but also some code examples on how to overcome some problems/cons (if this is applicable).

**Comment by carolinan** [comment]
Maybe there could be a resource page for both classic themes and block themes.
The Theme Check plugin and the [PHP code sniffer rules](https://github.com/WPTT/WPThemeReview) could also be added there.
But Theme Check and several other resources are already on the [Testing page](https://developer.wordpress.org/themes/releasing-your-theme/testing/)

**Comment by carolinan** [comment]
It would be good to have an extensive description of how to use the create a block theme plugin, not only a link.

**Comment by annezazu** [comment]
I really dig that idea. I'll rename this issue to be about theme resources and will work on getting more info for create block theme plugin. Would you be game to collaborate on this otherwise, @carolinan ?

**Comment by annezazu** [comment]
[Here's a draft either way.](https://docs.google.com/document/d/1FH4bqRi2MUjWyBJP8EWvaoyt-LJ2JF-k6qK0IxX-B_4/edit?usp=sharing) I propose it lives under either Getting Started or Theme Basics. My instinct is Theme Basics at the very end but I trust you all here :D

**Comment by carolinan** [comment]
@dingo-d Would you like to write something short about https://github.com/WPTT/WPThemeReview for the theme developer handbook?

**Comment by dingo-d** [comment]
I can't make any promises, currently, I need to focus on the WordPress PHP Coding Standards handbook PRs. After this is done, I could probably write something about it 🙂

**Comment by colorful-tones** [comment]
@annezazu I would be happy to collaborate here. I aim to review [your Doc](https://docs.google.com/document/d/1FH4bqRi2MUjWyBJP8EWvaoyt-LJ2JF-k6qK0IxX-B_4/edit?usp=sharing) today and provide any feedback. Thanks for getting all of this going! 👏

**Comment by annezazu** [comment]
Amazing! Thank you!

**Comment by colorful-tones** [comment]
@annezazu awesome job covering all the good stuff. 😄 

I made a few minor edits and added a blurb on _s (Underscores) and the WordPress Coding Standards for PHP_CodeSniffer. 

I would say this is good to go. I agree that putting it at the bottom of the list under Theme Basics would seem logical.

One thing I would like to throw out for consideration: should we add a screenshot of both Create Block Theme plugin (can grab from the plugin's page) and the Theme Generator? Or, does it not offer enough value and maintaining would outweigh the value of the addition?

@carolinan I have access to add the page in Theme Developer Handbook, but I would love your final input before publishing. Is there anything else we might be missing or considering? Thanks!

**Comment by annezazu** [comment]
Thank you so much for stepping in here! This is a huge help. As for screenshots, I don't feel strongly either way. In my mind, it's one more thing to keep up to date but it also might add some nice visuals to an otherwise text heavy doc.

**Comment by carolinan** [comment]
@colorful-tones Thank you!
The PHPCS standards for WordPress core are different from the standards for themes released on WordPress.org:
https://github.com/WPTT/WPThemeReview
I think the page should include both, and the specific use case for the theme standard should be mentioned (themes intended to be published in the official theme directory).

**Comment by dingo-d** [comment]
@carolinan @annezazu left some suggestions in the abovementioned doc, hope this is ok 🙂

**Comment by annezazu** [comment]
Thank you! I have resolved all open comments and made slight changes. I imagine it just needs another read over and confirmation by @carolinan and/or @colorful-tones to finally ship 🥳

**Comment by carolinan** [comment]
I think it is ready to be published. 
If there are other resources that we can think of they can be added over time.

**Comment by colorful-tones** [comment]
> The PHPCS standards for WordPress core are different from the standards for themes released on WordPress.org

@carolinan, I'm so happy you pointed that out! 👍 

I would be happy to get this into the Theme Handbook this afternoon. Thanks, team!

**Comment by colorful-tones** [comment]
Ok, the page has been created and submitted for review on the Theme Handbook site. So, pending review for now.

**Comment by colorful-tones** [comment]
@carolinan would you have time to review the Pending draft this week please?

**Comment by carolinan** [comment]
It is published -What menu item should it go under?

**Comment by colorful-tones** [comment]
I would nest it under Theme Basics and make it the bottom (maybe priory 100). Thanks @carolinan

**Comment by annezazu** [comment]
Sounds good to me! Going to close this out. Thanks, all <3 <3

**Comment by colorful-tones** [comment]
I'm reopening until we have this showing in the main navigation. I'm seeing that it is assigned to the Theme Basics as the Parent but I'm not seeing it appearing in the navigation. It might be caching and want to verify before closing this all out.

**Comment by carolinan** [comment]
The menus are not set up to include new articles automatically, they need to be added on the menu screen.

**Comment by carolinan** [comment]
Added.

**Comment by colorful-tones** [comment]
Verifying that I'm seeing the published page and it is at the bottom of the Theme Basics menu. Thanks @carolinan amd @annezazu 

This is all set.
