### ISSUE TITLE
Create manifest.json

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#404]
Since we want Advanced administration handbook to be generated from GitHub repository, we will need to create manifest.json, for which we will have to know the exact structure/sitemap of the handbook.

Here are a couple of examples:
- Coding standards handbook: https://github.com/WordPress/wpcs-docs/blob/master/manifest.json
- Docs style guide: https://github.com/WordPress/WordPress-Documentation-Style-Guide/blob/main/manifest.json

**Comment by zzap** [comment]
Since we want Advanced administration handbook to be generated from GitHub repository, we will need to create manifest.json, for which we will have to know the exact structure/sitemap of the handbook.

Here are a couple of examples:
- Coding standards handbook: https://github.com/WordPress/wpcs-docs/blob/master/manifest.json
- Docs style guide: https://github.com/WordPress/WordPress-Documentation-Style-Guide/blob/main/manifest.json

**Comment by javiercasares** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/2

**Comment by javiercasares** [comment]
Related:
- [#41](https://github.com/WordPress/Advanced-administration-handbook/issues/41)
- [#84](https://github.com/WordPress/Advanced-administration-handbook/issues/84)
