### ISSUE TITLE
Code Reference: need More Information on WP_Filesystem

### ISSUE THREAD

**Issue by joyously** [WordPress/Documentation-Issue-Tracker#405]
## Issue Description
There are a few confusing things regarding `WP_Filesystem` docs. 

1. The code in the function `WP_Filesystem` uses a variable to instantiate a class, so the docs parser doesn't link the pages.
```
$method = "WP_Filesystem_$method";
$wp_filesystem = new $method( $args );
```
There is no link to the base class mentioned in the summary.
2. The return value is not really explained. Basically, the More Information section needs to say what happens using the defaults.
3. The More Information section needs to link to the API page so the full explanation can be found on how to use this function. 
https://developer.wordpress.org/apis/handbook/filesystem/
4. The contributed code examples on this function and on [WP_Filesystem_Base](https://developer.wordpress.org/reference/classes/wp_filesystem_base/) all call the function with defaults and no getting credentials, which is how it is explained on the API page.
5. The More Information section should mention the earliest available hook of `admin_init` like the API page does.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/wp_filesystem/
and feedback on https://developer.wordpress.org/reference/classes/wp_filesystem_base/

## Section of Page with the issue
missing More Information section

## Why is this a problem?
A developer can't find the information needed to use the function.

## Suggested Fix
Add a More Information section with links to the classes and the API page, with the details needed to use the function.

**Comment by stevenlinx** [comment]
1.) This item is not the domain of the Docs team to fix. This is the domain of the Meta team. If you want to see the class methods linked, you 'll want to ask Meta. At best, we can manually add the links to the More Information section, which is what I've done.

2.) & 4.) I assume the "direct" method is used if no parameters are specified.

3.) I've added the link from the Common APIs Handbook to the More Information section.

5.) I've added content about `admin_init` from the Common APIs Handbook to the More Information section.
