### ISSUE TITLE
Format API Example Broken Links

### ISSUE THREAD

**Issue by trinadin** [WordPress/Documentation-Issue-Tracker#408]
## Issue Description

The page https://developer.wordpress.org/block-editor/how-to-guides/format-api/ has two links, "complete format-api example" and "format-api example" that both point to a GitHub page (https://github.com/WordPress/gutenberg-examples/tree/trunk/format-api) that 404s.

I think the correct GitHub page is here: https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/format-api

## URL of the Page with the Issue

https://developer.wordpress.org/block-editor/how-to-guides/format-api/

## Section of Page with the issue

https://developer.wordpress.org/block-editor/how-to-guides/format-api/#before-you-start
https://developer.wordpress.org/block-editor/how-to-guides/format-api/#conclusion

## Why is this a problem?

Link is broken and results in 404.

## Suggested Fix

Replace links with:
https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/format-api

**Comment by kkoppenhaver** [comment]
Just created a PR that addresses this and I will come back and update this issue when that PR is merged.

**Comment by kkoppenhaver** [comment]
Not sure who has the permission to close this, but the above PR has been merged and this issue is resolved. @zzap @bph

**Comment by estelaris** [comment]
Closing as resolved
