### ISSUE TITLE
Initial Handbook structure

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Documentation-Issue-Tracker#409]
There is some need for a structure in the new Advanced Administration Handbook.

As we don't know how the final structure will be, some general big "categories" can be added, and then we can create documentation inside them. Initial idea:

- Server: information about Server / Hosting / sysadmin documentation.
- WordPress: information about WordPress configuration (advanced wp-config.php, advanced email, etc.)
- Plugins: not user / developer documentation
- Themes: not user / developer documentation
- Resources: general resources / whatever (not sure yet about this)
- More Documentation: links to external sites (one page only)

This structure can help with [#404](https://github.com/WordPress/Documentation-Issue-Tracker/issues/404).

**Comment by zzap** [comment]
> More Documentation: links to external sites (one page only)

Just to mention that we have External Linking Policy in making and these would need to follow some rules. We still don't have all the rules set but here are things to consider when linking to external resource from wp.org: https://make.wordpress.org/docs/tag/external-linking-policy/

**Comment by javiercasares** [comment]
Yes, that "More Documentation" or the "Resources" was related to #328 ;)

**Comment by zzap** [comment]
Thank you. Just wanted to be sure we're on the same page :)

**Comment by javiercasares** [comment]
I created a Doc having a first idea (it's going to change, so no problem changing documents from one section to another...).

https://docs.google.com/document/d/1fVIw3DztzyVY18RDPCGk-kDYTO6gzHtx81o7aitGijo/

**Comment by javiercasares** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/1

**Comment by thomas-price** [comment]
The suggested initial structure includes:
...
L2 - Security
L2 - Performance / Optimization
L2 - Debugging
...

Could I suggest this structure be aligned more closely to ISO20000, ITIL, ITSM, etc...
...
L2 - Security Management
        (HTTPS, SSL, Hardening WordPress, Brute Force, 2FA, WAF, Testing, etc.)
L2 - Continuity Management
        (Backup, Recovery, Planning, Testing, etc)
L2 - Capacity Management
        (Active Monitoring, Logging, Performance, Optimization, etc.)
...
