### ISSUE TITLE
Repeated text "while while" in working with users page

### ISSUE THREAD

**Issue by mhimon** [WordPress/Documentation-Issue-Tracker#411]
Repeated text 'while while'

## Issue Description
wp_create_user() creates a user using only the username, password and email parameters **while while**

## URL of the Page with the Issue
[https://developer.wordpress.org/plugins/users/working-with-users/](https://developer.wordpress.org/plugins/users/working-with-users/)

## Section of Page with the issue
![Screen Shot 2022-08-17 at 6 56 31 AM](https://user-images.githubusercontent.com/27549230/185010475-6c45afe9-c20e-4067-bb7b-3c14d29382a3.png)

## Suggested Fix
remove one while

**Comment by theMikeD** [comment]
Fixed thanks @mhimon
