### ISSUE TITLE
WordPress 6.1 release docs contributors

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#413]
WordPress 6.1 release is at the beginning. Docs focus leads are preparing everything for documenting. Meanwhile we're calling contributors to help out and learn how WordPress release is being documented. 

**This issue will be used for volunteering and keeping track of all people who volunteered to participate. Once we have work ready, we will contact volunteers in WordPress [slack](https://make.wordpress.org/chat/).**

| Name | WordPress.org username | GitHub username |
| --- | --- | --- |
| Bright Emeka | brightemeka | brightcemeka-zz |
| Emma | emmaht | emmasophieyoung |
| Tahmid ul Karim | tahmidulkarim | tahmid-ul |
| Damon Cook | colorful-tones | colorful-tones |

----------------------------------------------
If you want to join, please leave comment below with following info:
- your WordPress.org username
- your GitHub username
----------------------------------------------

### Useful release links
- WordPress 6.1: https://make.wordpress.org/core/6-1/
- GitHub project: https://github.com/orgs/WordPress/projects/45/views/1
- Block editor Dev Notes Tracking issue: https://github.com/WordPress/gutenberg/issues/42961
- Trac tickets: https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=closed&status=new&status=reopened&status=reviewing&milestone=6.1&group=component&col=id&col=summary&col=status&col=milestone&col=owner&col=type&col=priority&order=priority
- Project issues: https://github.com/WordPress/Documentation-Issue-Tracker/labels/6.1

### Further reading/viewing
- [Kick-off WordPress 6.1 release docs](https://make.wordpress.org/docs/2022/08/10/kick-off-wordpress-6-1-release-docs/)
- [Documenting WordPress release videos](https://www.youtube.com/playlist?list=PLYcXltkbcVtGdO_8wCVvaJZwyWE3Fk2ly)

**Comment by tahmid-ul** [comment]
Hello @zzap, I would like to contribute to Wordpress 6.1 release docs.

Wordpress.org - **tahmidulkarim** 
Github -  **tahmid-ul**

**Comment by tanazmasaba** [comment]
Hi @zzap 👋 I'd love to contribute to WordPress 6.1 release docs. 

WordPress.org - tanazmasaba
Github - tanazmasaba

**Comment by leon-nugraha** [comment]
Hi @zzap, I'd also love to contribute to WP 6.1 release docs

WordPress.org - leonnugraha
GitHub - leon-nugraha

**Comment by colorful-tones** [comment]
Count me in @zzap 

WordPress.org - colorful-tones
Github - colorful-tones
Slack - colorful-tones
