### ISSUE TITLE
Review content in WordPress widgets

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#414]
## Issue Description

This article has references to the widget API (DevHub) and several links in the resources part to the Codex.

## URL of the Page with the Issue

https://wordpress.org/support/article/wordpress-widgets/

## Section of Page with the issue

[Widget API reference](https://wordpress.org/support/article/wordpress-widgets/#widget-areas)
[Outdated links to Codex and external site](https://wordpress.org/support/article/wordpress-widgets/#widget-areas)

## Why is this a problem?

Outdated information

## Suggested Fix

- [ ] Remove 3 resource links, perhaps leave the WordPress widgets announcement link as a historical reference.
- [ ] Remove the paragraph that refers to the Widgets API

**Comment by atachibana** [comment]
@estelaris
Thank you for the heads up.
I have corrected the document as you indicated.
