### ISSUE TITLE
Code Reference: More Info for WP_Query post_name__in parameter

### ISSUE THREAD

**Issue by joyously** [WordPress/Documentation-Issue-Tracker#416]
## Issue Description
The sentence is from past perspective, where 4.4 is future.
>  (Will be available in version 4.4)

## URL of the Page with the Issue
https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters

## Section of Page with the issue
Post & Page Parameters

## Why is this a problem?
Other references in same paragraph indicate versions as past.
> (available since version 3.6)

## Suggested Fix
Verify that the option was indeed added in version 4.4 and change it to (available since version 4.4).

**Comment by stevenlinx** [comment]
Thank you for reporting.

Yes, the option `post_name__in` was added since v4.4 as shown in the Core trac ticket below.

https://core.trac.wordpress.org/ticket/33065

I've made the revision.
