### ISSUE TITLE
Duplicated article Pages and Create a New Page

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#422]
## Issue Description

Two articles with similar information

## URL of the Page with the Issue

[Pages](https://wordpress.org/support/article/pages/)
[Creating a new page](https://wordpress.org/support/?post_type=helphub_article&p=11927012&preview=true) - draft

## Section of Page with the issue

Entire page

## Why is this a problem?

duplicated content

## Suggested Fix

- [x] review and update content in Pages
- [x] add screenshots to Pages
- [x] delete the draft article

**Comment by femkreations** [comment]
@estelaris I have updated the page, and rewrote several parts with screenshots, and updated content. Also deleted the draft. 

https://wordpress.org/support/article/pages/

**Comment by estelaris** [comment]
issue fixed
