### ISSUE TITLE
Code Reference: Found extra bracket in do_action_ref_array document

### ISSUE THREAD

**Issue by dilipbheda** [WordPress/Documentation-Issue-Tracker#423]
## Issue Description
Found an extra `<` bracket in the more information section 

Ref: https://tinyurl.com/2g7u4w4h

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/do_action_ref_array/

## Section of Page with the issue
I have found this issue in more information section.
https://developer.wordpress.org/reference/functions/do_action_ref_array/#more-information

## Suggested Fix
`<` Remove bracket before do_action_ref_array

**Comment by stevenlinx** [comment]
Thank you for reporting.

1.)
I've removed the bracket `<` in question.

2.)
There are two other problems that I also fixed.

The `<pre></pre>` tag in the first two sample code are redundant.

I've removed them as well.
