### ISSUE TITLE
[HelpHub] Content review for Creating a Search page

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#430]
## Issue Description

The page is focused on developer information but needs to refocus for Helphub end-users.

## URL of the Page with the Issue

[Creating a search page](https://wordpress.org/support/article/creating-a-search-page/)

## Section of Page with the issue

full article

## Why is this a problem?

developer jargon/content review

## Suggested Fix

- [ ]  Review and update content in the context of the Site Editor

**Comment by pekkakortelainen** [comment]
As discussed in Slack during triage on 12th September 2023, I'll work on this.

**Comment by sagargurnani99** [comment]
We can remove all the content from this page and replace it with the one I suggest below.

# Create a search page
A Search Page is a WordPress [Page](https://codex.wordpress.org/Pages) with a custom [Page template](https://codex.wordpress.org/Pages#Page_Templates) to give users more information for searching your site.

### How to create it?

1. On the [Administration Screen](https://codex.wordpress.org/Administration%20Screens) go to Pages > Add New.
2. In the title field enter **Search**.
3. [Add a new block](https://wordpress.org/documentation/article/adding-a-new-block/)  named "**Search**".
4. Publish the page.

### How to test it?

1. Leave the Admin Area and go to the User Area.
2. Click on the Search link from the Menu to land on the newly created Search page.
3. In the search field, type the keyword to search and submit.
4. The search results must appear on the same page.
5. If no post is found with the keyword then "No posts were found." message would appear.

**Comment by Leonardus-Nugraha** [comment]
Hiya @sagargurnani99 
I think the opening sentence on your draft can be replaced as it's repeating the opening sentence of the article (_A Search Page is a WordPress Page with a custom Page template to give users more information for searching your site._)

I would suggest something like "Follow these steps to create a search page using the the custom page template:"

Other than that, this draft is ready to go!

**Comment by sagargurnani99** [comment]
Thanks @Leonardus-Nugraha, I will make the changes as per your suggestion.
