### ISSUE TITLE
[HelpHub] Three articles on keyboard shortcuts?

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#432]
## Issue Description

There are 3 articles on keyboard shortcuts. Is there a reason for the draft article?

## URL of the Page with the Issue

[Keyboard shortcuts in Block Editor?](https://wordpress.org/support/?post_type=helphub_article&p=11032287) draft
[Keyboard shortcuts in Classic Editor](https://wordpress.org/support/article/keyboard-shortcuts/)
[Keyboard shortcuts in Block Editor](https://wordpress.org/support/article/block-editor-keyboard-shortcuts/)

## Section of Page with the issue

full article

## Why is this a problem?

duplicated article?

## Suggested Fix

- [x] Review and remove draft if it is duplicated

**Comment by justincatches** [comment]
I'd like to work on this issue.

**Comment by justincatches** [comment]
I have reviewed the draft file [Keyboard shortcuts in Block Editor?](https://wordpress.org/support/?post_type=helphub_article&p=11032287).

It is an almost exact duplicate of [Keyboard shortcuts in Classic Editor](https://wordpress.org/support/article/keyboard-shortcuts/).

I recommend removing this doc: [Keyboard shortcuts in Block Editor?](https://wordpress.org/support/?post_type=helphub_article&p=11032287).

**Comment by estelaris** [comment]
Fixed during the migration from /support/ to /documentation/
