### ISSUE TITLE
Writing Posts page has a broken link (Screen Options)

### ISSUE THREAD

**Issue by robinwpdeveloper** [WordPress/Documentation-Issue-Tracker#433]
## Issue Description

Writing Posts page (dedicated to classic editor) has a broken link. 
In the Screen Options section, there is a link called Screen Options  (Content from the page: There are more editing fields available to you than you see on first login. The [Screen Options](https://wordpress.org/getting-started/administration-screens/#screen-options) area allows you ...).

This link redirects to 404 page.

## URL of the Page with the Issue

https://wordpress.org/support/article/writing-posts/

## Section of Page with the issue

https://wordpress.org/support/article/writing-posts/#screen-options

## Why is this a problem?

No links should redirect to 404. If link is not available then we may need to update the doc by removing the link with plain text.

## Suggested Fix

Add a correct link or remove the link from the text.

## Screenshot:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/86726198/188280318-4e8d2a9b-b107-4760-8dba-cc52527b52ee.png">

**Comment by robinwpdeveloper** [comment]
@atachibana please review and let me know what is the correct url for this.

**Comment by atachibana** [comment]
@robinwpdeveloper 
Please remove this link. We don’ t have Screen Options anymore in Gutenberg, so won't prepare the specific page of it.

**Comment by robinwpdeveloper** [comment]
Link Removed. We can close this ticket now.
Thanks @atachibana for your help.
