### ISSUE TITLE
Move "Block Themes" above "Classic Themes" in sidebar

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#437]
## Issue Description

It's a small thing, but I think it's important that we're showcasing block themes ahead of classic themes in the handbook.  Currently, the sidebar displays classic before blocks:

![themes-handbook-sidebar](https://user-images.githubusercontent.com/1816309/188973807-39dbe6bc-1358-4e44-b810-ad20cf32b52f.png)

## URL of the Page with the Issue

https://developer.wordpress.org/themes/

## Why is this a problem?

Block themes are both the present and future of WordPress.  Information specific to them should come first.

## Suggested Fix

Move "Block Themes" chapter ahead of "Classic Themes" in the sidebar.

---

I'd be happy to self-assign this one and make the changes if others agree.  But, I don't think I have access to edit the sidebar.

**Comment by colorful-tones** [comment]
+1 for me. Thanks for bringing it up.

**Comment by carolinan** [comment]
I have moved the menu items.
