### ISSUE TITLE
Twenty Twenty-Three: User Support Guide

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Documentation-Issue-Tracker#441]
## What is the new page you are requesting?

A user guide for the Twenty Twenty-Three theme and its style variations.

## How will this new page help you?

With a new default theme coming with WordPress 6.1, users will find a getting-started guide helpful. It could include information like:

- How Twenty Twenty-Three works with Full Site Editing, including what templates and patterns are included
- How style variations work and what the included style variations look like
- How to make common customizations
- An overview of some of the features in TT3 that take advantage of WP 6.1 improvements, such as fluid typography

In terms of the format, we can draw inspiration from this existing guide for TT2:

https://wordpress.org/support/article/twenty-twenty-two/

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date, if any
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.

**Comment by kathrynwp** [comment]
Here is the draft article:

https://wordpress.org/support/wp-admin/post.php?post=16093494&action=edit

@femkreations Let me know what you think so far, this is my first time writing a support article.

Thanks to TT3 development lead Sarah Norris (@mikachan) for feedback on the first draft, and @annezazu for inspiration taken from her Twenty Twenty-Two support article!

**Comment by femkreations** [comment]
@kathrynwp This looks great. Thanks for your work. 

- Pls also add that this is the first default block theme marked as accessibility-ready as noted by Ann in [this article](https://make.wordpress.org/core/2022/10/11/wordpress-6-1-accessibility-improvements/) -under Themes. 
- Remove the reference to Twenty Twenty-Two in the first line.

Other than that, great job with the article. Please add screenshots for the Patterns and links and we are good to go.

**Comment by kathrynwp** [comment]
@femkreations Thanks for having a look so quickly!

> Remove the reference to Twenty Twenty-Two in the first line.

Oops, good catch, fixed.

> Pls also add that this is the first default block theme marked as accessibility-ready as noted by Ann in [this article](https://make.wordpress.org/core/2022/10/11/wordpress-6-1-accessibility-improvements/) -under Themes.

Looks like TT2 was also accessibility-ready, so what do you think about this revision to the first line: 

> Twenty Twenty-Three is the new, accessibility-ready, default theme for WordPress Version 6.1

Will add more screenshots and let you know when they're there.

> I have also added a checklist that we normally follow when writing articles 

Great, I'll be sure to double-check that all those are adhered to. Thanks!

**Comment by annezazu** [comment]
>Twenty Twenty-Three is the new, accessibility-ready, default theme for WordPress Version 6.1

This sounds great to me for what it's worth.

>Twenty Twenty-Three is the first default theme to incorporate a collection of style variations [submitted by community members](https://make.wordpress.org/design/2022/09/07/tt3-default-theme-announcing-style-variation-selections/)

Of note, Twenty Twenty-Two has bundled style variations in place as of WordPress 6.0! However, this is the first community submitted style variations so this statement is both true in a sense but a bit confusing. I might simplify it to: "Twenty Twenty-Three is the first default theme to incorporate a collection of community submitted style variations" or "Twenty Twenty-Three incorporates a collection of ten community submitted style variations".

**Comment by femkreations** [comment]
> Twenty Twenty-Three incorporates a collection of ten community submitted style variations".

Thanks for clarifying Ann. I'd go with this version just for simplicity.
"Twenty Twenty-Three includes a collection of ten community-submitted style variations."

**Comment by kathrynwp** [comment]
Thank you, @femkreations and @annezazu! I've made that wording update.

**Comment by kathrynwp** [comment]
@annezazu also mentioned that there is a new TT3 video coming out soon, so we may want to embed that in the doc as well.

**Comment by kathrynwp** [comment]
@mikachan Thanks for the quick reply, and I'm sorry about the lack of access, totally overlooked that! Here's a screenshot you can peek at, let me know if this works well enough:

![whole-page-screenshot](https://user-images.githubusercontent.com/7662449/197787174-c71f88d9-2f7c-4281-a378-201f185dbcf0.png)

**Comment by mikachan** [comment]
No worries, thanks for adding the screenshot! 

> in the gallery of style images, double-check that the most up-to-date style variation name is assigned to each variation screenshot

Yes, all these names look correct to me 👍 I think "Default" works well here too.

> confirm whether all screenshots match the final state of the theme closely enough

The styles in the screenshots look up to date (colours, fonts), however, some of the screenshots include the "Latest Posts" and "View more" headings above the query loop, which have since been removed. The text is extremely tiny, so possibly difficult to notice, but it is different compared to the current layout. It looks like these are included on Default, Canary, Electric, Marigold, Grapes, Aubergine, Whisper and Sherbet.

<img width="1163" alt="Screenshot 2022-10-26 at 10 12 22" src="https://user-images.githubusercontent.com/1645628/197986192-958cc10c-462a-4bda-8b98-9931c84245fd.png">

**Comment by kathrynwp** [comment]
@mikachan Thank you for all the feedback!

- I've kept "Default"
- I've added creator names to the captions for the 10 style variations. Here's a screenshot of what that now looks like:

<img width="751" alt="Twenty_Twenty-Three_–_WordPress_org_Forums" src="https://user-images.githubusercontent.com/7662449/198095028-a914cfba-d9de-483b-b882-fe5eaa240b1b.png">

- I'm looking into the issue with the "Latest Posts" and "View more" headings

**Comment by mikachan** [comment]
Thank you, this looks good to me!

> I'm looking into the issue with the "Latest Posts" and "View more" headings

I don't feel strongly about this, it's a very minor detail.

**Comment by femkreations** [comment]
@kathrynwp Thanks so much for working on this page and doing a fabulous job. We use sentence cases on headings as a guide. So Color Palette is Color palette, Full Site Editing support etc. Hope that clarifies. Its a minor change.

**Comment by kathrynwp** [comment]
@femkreations Thanks for confirming, I've made the update!

**Comment by kathrynwp** [comment]
The new page is now live!

https://wordpress.org/support/article/twenty-twenty-three/

I'll be dropping in the new TT3 video as soon as it's ready, but I'll go ahead and close this out for now.
