### ISSUE TITLE
[HelpHub] Content review - Introduction to Blogging

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#443]
## Issue Description

Outdated screenshots and content. Article is too long

## URL of the Page with the Issue

[Introduction to Blogging](https://wordpress.org/support/article/introduction-to-blogging/)

## Section of Page with the issue

Full article

## Why is this a problem?

Outdated content and too long to read on mobile

## Suggested Fix

Section [Things Bloggers need to know](https://wordpress.org/support/article/introduction-to-blogging/#things-bloggers-need-to-know) could be moved to a second article with a different title.

**Comment by hannaw93** [comment]
I will pick this up :)

**Comment by pls78** [comment]
I'm picking this up :)

**Comment by pls78** [comment]
I reviewed the article as far as the 'Trackbacks' sub-section included; I found the following problem:
* The 'Feeds' link should be updated from https://codex.wordpress.org/Introduction_to_Blogging#Feeds to https://wordpress.org/support/article/introduction-to-blogging/#feeds
* The 'stand-alone “weblog client” software' link should be updated from https://codex.wordpress.org/Weblog_Client to https://wordpress.org/support/article/weblog-client/ (even though it seems to not be relevant anymore)
* The 'Getting Started with WordPress' and the 'WordPress' links (last one in 'Things Bloggers Need to Know' section) point to the same non-existent page: https://codex.wordpress.org/Getting_Started_with_WordPress (I couldn't find a candidate for replacement)
* The 'a comprehensive summary' link is dead (http://www.mezzoblue.com/archives/2004/05/19/what_is_rssx/)
* In the 'Trackbacks' sub-section, the links 'SixApart' and 'MovableType' both point to them same URL https://movabletype.org/: is this intended?

In general, both the terminology used and the linked resources are very outdated (e.g., the introductory video about what blogging is is from 2008).

**Comment by nouman17610** [comment]
Hello @zzap, 
Please assign this task to me and plz guide me on when should I start. Thank you.

**Comment by femkreations** [comment]
@nouman17610 this has been assigned to you. Thank you. If you don't have permission to edit the article, you can rewrite it in the comments or in a google doc and link here.

**Comment by nouman17610** [comment]
@femkreations thank you.
Starting work on it.

**Comment by nouman17610** [comment]
@femkreations 
I have reviewed the article; there were errors related to grammar, sentence structure, punctuation, deprecated links, and outdated data.
I have resolved all the above issues and divided this article into two.

Here are the Google Docs links to the articles
Introduction to Blogging (This is an updated version of the existing article.
https://docs.google.com/document/d/187D_NJM9927oFllQJ4wdwmNeHwmikpVoPISamXq_r6k/edit?usp=sharing

Please create a new post titled "Things Bloggers Need to Know."
https://docs.google.com/document/d/1UD4LmVOEpP727VbJnOr8-iNlsPxLWLdvEFpOQwnGifo/edit?usp=sharing

Things that I have done
1. Rewritten the weak parts of the articles
2. Corrected grammatical mistakes
3. Maintained the continuity in the article
4. Separated the irrelevant portion from the main article and created a new one
5. Updated deprecated links and added valid links to the text.

**Comment by estelaris** [comment]
@nouman17610 the second article that you are suggesting already exists in several articles https://wordpress.org/support/article/trackbacks-and-pingbacks/
https://wordpress.org/support/article/wordpress-feeds/
https://wordpress.org/documentation-test/article/introduction-to-plugins/

Perhaps you would like to write this as an FAQ?

**Comment by nouman17610** [comment]
@estelaris Thank you for the feedback. 
We should finalize the first article, "Introduction to Blogging," with the updated content.

You are right second article's data is already available in the articles you mentioned. It is better to write as an FAQ.
Thank you

**Comment by hannaw93** [comment]
@zzap I updated the article content with the [new version](https://docs.google.com/document/d/187D_NJM9927oFllQJ4wdwmNeHwmikpVoPISamXq_r6k/edit?usp=sharing) added by @nouman17610 . I removed the the information that is covered in mentioned other articles (the potential future FAQ) and put it here: https://docs.google.com/document/d/1b1oIAkMkuYIydVh3OqlP3BjtxG1VjqsQNE0xj1akuS8/edit?usp=sharing

**Comment by hannaw93** [comment]
Updated (the relevant) outdated links mentioned by @pls78 . This can now go to a review :)

**Comment by emmasophieyoung** [comment]
Fixed formatting, grammar, titles
