### ISSUE TITLE
paginate_links() parameters type are incorrect

### ISSUE THREAD

**Issue by xtrembaker** [WordPress/Documentation-Issue-Tracker#444]
## Issue Description
`prev_text` and `next_text` parameters type for the `paginate_links()` function are wrong in the documentation

## URL of the Page with the Issue
[Function paginate_links](https://developer.wordpress.org/reference/functions/paginate_links/)

## Section of Page with the issue
- `prev_text` type
- `next_text` type

## Why is this a problem?
It’s written that `prev_text` and `next_text` are `bool` with a default value as `string` . 

## Suggested Fix
`prev_text` and `next_text` parameters type should be `string` instead of `bool`

**Comment by stevenlinx** [comment]
Thank you for reporting.

However, the Issue in question is the domain of the Make Core team.

The Parameters section of the page comes from in-line doc of the source code.

In this case, it is these two lines.
https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/general-template.php#L4200-L4201

So you'll need to file a ticket over at Core trac.
https://core.trac.wordpress.org

**Comment by stevenlinx** [comment]
> There is already a trac ticket for updating the docblock: https://core.trac.wordpress.org/changeset/54286

Then, the change is already being requested and committed.

> This issue here is for updating the page: https://developer.wordpress.org/reference/functions/paginate_links/

I assume you're new here.

On DevHub, the Description/Parameters/Return/Hooks sections on a Code Reference page are dynamically generated from the source code. Once the source code is changed and committed, the page content on DevHub will get reflected in the next release.
https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-includes/general-template.php#L4212-L4392

This is not the domain of the Docs team. The Docs team has no mechanism to change those content.

**Comment by nikkifurls** [comment]
Oh, perfect! That makes sense. Thank you for explaining that :)

Sounds like this one can be closed!
