### ISSUE TITLE
Typo error for Speed

### ISSUE THREAD

**Issue by kshirodpatel** [WordPress/Documentation-Issue-Tracker#445]
## Issue Description
Type error for speed. It has been mentioned as sped.

## URL of the Page with the Issue
https://developer.wordpress.org/apis/handbook/transients/#overview

## Section of Page with the issue

In this url, the paragraph has sped word, but it should be speed.

## Why is this a problem?
The sped word doesn't make any sense here.

## Suggested Fix
It should be speed not sped.

**Comment by nikkifurls** [comment]
This issue is N/A – this verbiage is correct:
`Also of note is that Transients are inherently sped up by caching plugins`

**Comment by theMikeD** [comment]
Agreed. Is correct as is.
