### ISSUE TITLE
Docs for block-based template parts in classic themes

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#446]
## Issue Description

WordPress 6.1 is introducing [block-based template part support](https://github.com/WordPress/gutenberg/pull/42729) for classic themes.  This is an important step for gradual adoption of FSE.  We need to update the "Gradual adoption" section of the "Converting a classic theme" page with info on how to make use of the feature.

## URL of the Page with the Issue

https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/

## Section of Page with the issue

https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#gradually-adopting-the-full-site-editing

**Comment by carolinan** [comment]
When this page is created, this section in the block editor handbook should be updated so that the content is not duplicated in two different handbooks:
https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#block-based-template-parts

**Comment by justintadlock** [comment]
**Requesting review and feedback for proposed section:**

---

### Adding block-based template parts in classic themes

Since WordPress 6.1, classic themes can add block-based template parts. The feature allows end-users to customize their output via Appearance > Template Parts in the WordPress admin.  Theme authors must register support to enable the feature:

```php
add_theme_support( 'block-template-parts' );
```

From that point, developers can add template parts to their theme's `parts` folder.  For details on creating parts, see the [template parts for block themes](https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/#block-c5fa39a2-a27d-4bd2-98d0-dc6249a0801a) handbook page.

In general, a PHP-based template part that is included via `get_template_part( $name )` can be replaced with a call to `block_template_part( $name )`.  It only needs a corresponding `parts/{$name}.html` file and block markup.  Headers, footers, and even sidebars can be turned into a block-ready area for users.

**Important!**  Classic themes must add opening and closing `<html>` and `<body>` tags along with the appropriate `wp_head()`, `wp_body_open()`, and `wp_footer()` as usual.  These are easy to overlook when replacing header and footer template parts.

**Comment by carolinan** [comment]
This text looks good to me.

**Comment by carolinan** [comment]
Should this concept be introduced on https://developer.wordpress.org/themes/basics/template-files/ or would that become overwhelming?

**Comment by justintadlock** [comment]
[Added the block template parts section](https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes).  Closing this ticket as complete since we reached that goal.
