### ISSUE TITLE
Block theme setup file structure should be simpler

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#447]
## Issue Description

The [file structure](https://developer.wordpress.org/themes/block-themes/block-theme-setup/#file-structure) for the block theme setup page in the handbook could be simplified.  In its current form:

```
assets (dir)
      - css (dir)
            - blocks (dir)
      - images (dir)
      - js (dir)
inc (dir)
patterns (dir)
parts (dir)
      - footer.html
      - header.html
templates(dir)
      - 404.html
      - archive.html
      - index.html
      - page.html
      - single.html
      - search.html
functions.php
index.php
README.txt
rtl.css
screenshot.png
style.css
editor-style.css
theme.json
```

I'd like to see that simplified down to a smaller selection since this is more of an introductory section to block theming:

```
/patterns
	/example.php
/parts 
	/footer.html 
	/header.html
/templates 
	/archive.html 
	/index.html (required)
	/single.html
/functions.php
/index.php (required)
/readme.txt 
/screenshot.png 
/style.css (required)
/theme.json
```

I couldn't remember if `index.php` was still required.  If not, we can ditch it.

The goal here should be to not overwhelm new block theme authors with too much information during setup.  Just get them started with the base files and folders for block themes.

## URL and Section of the Page with the Issue

https://developer.wordpress.org/themes/block-themes/block-theme-setup/#file-structure

**Comment by carolinan** [comment]
I have created a draft update which is scheduled to be published on September 30:
https://developer.wordpress.org/wp-admin/post.php?post=142950&action=edit

One of the code blocks had also broken, and I updated it.

**Comment by kafleg** [comment]
I'm on it.

**Comment by kafleg** [comment]
Block themes require a `style.css` file and an `index.html` template file that you place inside a folder called templates.

Is this the correct statement?
can we break it down and make it more simple? It sounds like those two files should be inside the `templates` folder.

**Comment by justintadlock** [comment]
Thanks for this, @carolinan.  It looks really good.

> Block themes require a `style.css` file and an `index.html` template file that you place inside a folder called templates.
> 
> Is this the correct statement? can we break it down and make it more simple? It sounds like those two files should be inside the `templates` folder.

Personally, I'd opt for simplifying it down to the following because we already further explain it in the text that comes after:

> Block themes require a `style.css` file and a `templates/index.html` file.

**Comment by carolinan** [comment]
I have made the suggested change.

**Comment by justintadlock** [comment]
Closing since this has now gone live.
