### ISSUE TITLE
Internationalization and theme.json

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#448]
## Issue Description

The [internationalization page](https://developer.wordpress.org/themes/block-themes/internationalization/) in the block themes section of the theme handbook does not touch on text in `theme.json` and `/styles/*.json` files.  While there is nothing specific that developers need to do in this instance, we should add a section that explains how this works so that there is no confusion.

## URL of the Page with the Issue

https://developer.wordpress.org/themes/block-themes/internationalization/

## Why is this a problem?

As a theme author, one of the first questions I'd ask is how would I internationalize text in a `theme.json` file, such as "Black" in the following:

```json
{
    "version": 2,
    "settings": {
        "color": {
            "palette": [
                {
                    "name": "Black",
                    "slug": "black",
                    "color": "#000000"
                }
            ]
        }
    }
}
```

## Suggested Fix

Add a new section on the internationalization page that explains how this works for `*.json` files.  Just need a short description.

**Comment by TeBenachi** [comment]
Thanks for bringing it up. I would be happy to address this.

**Comment by carolinan** [comment]
I have added the information about theme.json and scheduled the update for **November 7**.
The entry in the changelog needs to be updated before publishing.

**Comment by carolinan** [comment]
Has this page update been reviewed? Or shall I postpone the publishing further?

**Comment by kafleg** [comment]
I just checked the content of the page and it looks fine to me. I think it can be published.

**Comment by justintadlock** [comment]
This all looks good to me.  I'll go ahead and close this out since it addressed the problem I described.
