### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ramonanextend** [WordPress/Documentation-Issue-Tracker#45]
## Issue Description
I found broken links at two articles.

## URL of the Page with the Issue
1. https://make.wordpress.org/support/handbook/giving-good-support/examples-of-good-vs-bad-support/
2. https://make.wordpress.org/support/handbook/giving-good-support/understanding-users-reading-beyond-the-question-and-probing/

## Section of Page with the issue
1. Broken link is at: "As covered in Approach to providing good support and"
2. Broken link is at: "It’s easy to leave a bad reply," 

## Why is this a problem?
The links go to a non-existing page which prevents people from learning, an it's also confusing.

**Comment by Kenshino** [comment]
@Clorith ^

**Comment by Clorith** [comment]
Thanks, these two pages have been updated.

There may be some other older references, as the support team removed a lot of "dead", which were duplicates of handbook pages from a decade back before the handbook system was in place.
