### ISSUE TITLE
Theme handbook page for custom block styles

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#450]
## What is the new page you are requesting?

A page under the "Advanced" section of the theme handbook (or an alternative place if preferred) for using the [Block Styles API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/).

## How will this new page help you?

While there is an existing [Block Styles API](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/) page, it lives within the Block Editor handbook.  It is also merely an API reference.  While that page can continue being the source of truth for the API, we should have a "how-to" page that describes building custom block styles within themes.  Perhaps cover any best practices or any nuances related to block styles in themes.

As a theme author, the first place I would look for using this API would be in the Theme handbook.

**Comment by carolinan** [comment]
Draft: https://developer.wordpress.org/wp-admin/post.php?post=143053&action=edit

**Comment by kafleg** [comment]
I found a small issue in the text, 
![image](https://user-images.githubusercontent.com/13062231/200275476-45f19a92-def8-4292-b79f-6ed06dffe4b4.png)
![image](https://user-images.githubusercontent.com/13062231/200275596-095c5102-988d-4a60-a446-436866f213b5.png)

Rest of the content is fine to me. 

Thank you

**Comment by carolinan** [comment]
Fixed, thank you

**Comment by justintadlock** [comment]
Overall, this looks really great.  I did have a couple of notes:

1) For registering via PHP, d you think we want to show the example in a callback attached to `init`, e.g.:

```php
add_action( 'init', 'some_callback' );

function some_callback() {
	register_block_style();
}
```

2) Do we need to show how to do a back-compat check for pre-5.3?  Given that we're at 6.1 now, I don't think it's really necessary.  No strong feelings either way.

**Comment by carolinan** [comment]
I completely forgot this page.
I have updated the page according to the suggestions, updated the code block settings to include the language, and published the page.

**Comment by DaisyOlsen** [comment]
Hi @carolinan, I had this flagged to look at, but I see you've already added the content is there any more to be done here that I can help with, or is the issue ready to close since the content is live?

**Comment by carolinan** [comment]
It can be closed. I believe there is a post on the developer blog that would be a good resource to link to but I can add it tomorrow.
