### ISSUE TITLE
Code blocks in the Theme Developer Handbook are missing line breaks

### ISSUE THREAD

**Issue by bacoords** [WordPress/Documentation-Issue-Tracker#453]
## Issue Description
The Theme developer handbook has code blocks with PHP code examples, but the line breaks are missing. This causes the code to just stack up and is pretty un-readable. I've tested this logged in as well and on various browsers to make sure it wasn't just a cache issue.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/template-files-section/page-template-files/

## Section of Page with the issue
Most sections but starts here: [Creating Custom Page Templates for Global Use](https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-custom-page-templates-for-global-use)
As you get further into [bigger chunks of code](https://developer.wordpress.org/themes/template-files-section/page-template-files/#using-conditional-tags-in-page-templates) it gets worse.

## Why is this a problem?
It's extremely hard to read the code blocks- especially longer ones further down the page.

## Suggested Fix
Add the line breaks. Maybe it's a parsing issue with the newer code block UI?

**Comment by adamwoodnz** [comment]
This page is still using a classic editor block, any reason it can't be converted to blocks like [more recent pages](https://developer.wordpress.org/themes/patterns/patterns-and-block-locking/) which don't have the issue?

**Comment by bacoords** [comment]
I'll tag @justintadlock who has also done a lot of work on the handbooks.

**Comment by justintadlock** [comment]
This page is slated for a full update as part of the overhaul: https://github.com/WordPress/Documentation-Issue-Tracker/issues/816

But I went ahead and converted it to blocks and switched out the old shortcodes for code and notices/tips/alerts for the Code and Notice blocks.

---

@adamwoodnz - It was still using the old `[php]` shortcode, so I'm guessing there are other pages in various Dev Resources handbooks that might use that. I'm not sure where that shortcode comes from (some plugin, I guess).
