### ISSUE TITLE
[6.1 release docs] Accessibility improvements DevNote

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#454]
All 6.1 closed tickets with accessibility focus: https://core.trac.wordpress.org/query?status=closed&focuses=~accessibility&milestone=6.1&group=component&col=id&col=summary&col=status&col=focuses&col=type&col=keywords&order=priority

**Comment by zzap** [comment]
Anne will do this

**Comment by sabernhardt** [comment]
(The current [draft is in Google Docs](https://docs.google.com/document/d/1ULUTXv_KM8qGzhIMW9SMyxEEDTDKFpvmISnsGdQHACI/edit).)
