### ISSUE TITLE
[HelpHub] Content review: Preferences Overview

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#455]
## Issue Description

Non-working videos and broken images

## URL of the Page with the Issue

[Preferences Overview](https://wordpress.org/support/article/preferences-overview/)

## Section of Page with the issue

[General](https://wordpress.org/support/article/preferences-overview/#general)

## Why is this a problem?

Cause it is confusing

## Suggested Fix

Reload videos and images. Probably needs new screenshots

**Comment by ivahyael** [comment]
Hi, I hope I still contribute. May I work on this issue? 👋

**Comment by femkreations** [comment]
This page has been reworked for 6.1. Refer to https://github.com/WordPress/Documentation-Issue-Tracker/issues/310

**Comment by zzap** [comment]
Closing in favor of #310
