### ISSUE TITLE
[HelpHub] Categories block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#461]
Article: https://wordpress.org/support/article/categories-block/

## Updating for 6.1
- [x] Add spacing support. [43647](https://github.com/WordPress/gutenberg/pull/43647)
- [x] Add typography support. [43254](https://github.com/WordPress/gutenberg/pull/43254)
- [ ] Hide prefix and suffix placeholders in post terms. [42418](https://github.com/WordPress/gutenberg/pull/42418)
- [x] Add new option to show or hide empty categories. [39426](https://github.com/WordPress/gutenberg/pull/39426)
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Thelmachido** [comment]
Hi @femkreations can you please assign this one to me?

**Comment by femkreations** [comment]
Done @Thelmachido

**Comment by femkreations** [comment]
I went ahead and updated the page:
Added typography, dimension settings info
Added option to show empty categories
Changed name to Categories List block and updated the screenshots
Added ALT tags.

**Comment by Thelmachido** [comment]
Hi @femkreations thank you for working on that, I lost track of this one.
