### ISSUE TITLE
[HelpHub] Separator block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#462]
Article:  https://wordpress.org/support/article/separator-block/

## Updating for 6.1
- [ ] Add top & bottom margin support. [40551](https://github.com/WordPress/gutenberg/pull/40551)

## Updating for 6.0
- [ ] Block Styles: Show style preview when hovered or focused. [34522](https://github.com/WordPress/gutenberg/pull/34522)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by colorful-tones** [comment]
Grabbing this for Friday.

**Comment by maitreyie-chavan** [comment]
@femkreations Please assign this to me

**Comment by maitreyie-chavan** [comment]
@femkreations Here's a suggestion to update the existing article's Style section to include the update made in 6.0 [#34522](https://github.com/WordPress/gutenberg/pull/34522)

---
### Styles

You can modify the Separator block's look by choosing one of the styles available in the block's settings on right-hand side under `Styles`. 

<img width="221" alt="Screenshot 2023-02-17 at 10 58 24 AM" src="https://user-images.githubusercontent.com/20221326/219545947-6fae5fd8-b85c-426d-a21b-ab6e56b07304.png">


Default, Wide Line and Dots are the 3 options to choose from, and you can either hover or focus click on each of the style option to get a preview of their appearance


#### Default style

The line separator will appear centrally aligned with a short length

<img width="487" alt="Screenshot 2023-02-17 at 10 52 29 AM" src="https://user-images.githubusercontent.com/20221326/219546499-b33c16d0-e815-4ac2-ad8e-d2442010ad0f.png">


#### Wide Line style

This style will spread the line separator across the content width having a longer length

<img width="487" alt="Screenshot 2023-02-17 at 10 53 03 AM" src="https://user-images.githubusercontent.com/20221326/219546743-190a7df8-1962-444e-a7c6-509bd2f9203b.png">


#### Dots style

The short solid line seen in the Default style is replaced with a centred dotted line

<img width="487" alt="Screenshot 2023-02-17 at 10 53 23 AM" src="https://user-images.githubusercontent.com/20221326/219547323-28adc2c5-c376-491f-b54e-dcb92c70a81f.png">


> **Note**
> The above style options may vary based on the active theme

**Comment by maitreyie-chavan** [comment]
@femkreations Here's a suggestion to update the existing article and add a `Dimensions` section to include the update made in 6.1 [#40551](https://github.com/WordPress/gutenberg/pull/40551)

---

## Dimensions

The separator block provides the ability to add padding and margin values via the `Dimensions` settings option, giving you more control over creating the content separation

<img width="222" alt="Screenshot 2023-02-17 at 11 27 16 AM" src="https://user-images.githubusercontent.com/20221326/219549381-77382744-a69d-4a0e-bcec-98a8a5fba95e.png">


> For more details, refer to this support article: [Dimension settings overview](https://wordpress.org/documentation/article/dimension-controls-overview/)

**Comment by atachibana** [comment]
Tahir Shahzad will review this issue. I'll assign this issue to him after I got his GitHub account.

**Comment by tahir-shahzad4** [comment]
Reviewed the article and modifications suggested by  @maitreyie-chavan 
- Suggestions for style update are fine 
- Suggestions for dimensions update are fine
Further item that needs to be done
- Video needs to be updated
- Current article have alt attribute with images. For new changes, maybe we can write alt description below image to review. 
- Headings are not in sentence case
- Change log needs to be udpated

**Comment by femkreations** [comment]
Moving this to the 6.2 project board

**Comment by jomarieminney** [comment]
@femkreations this can be closed now :)
