### ISSUE TITLE
WordPress Features

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#47]
## Issue Description
Information is outdated

## URL of the Page with the Issue
https://wordpress.org/support/article/wordpress-features/

## Section of Page with the issue
https://wordpress.org/support/article/wordpress-features/#at-a-glance
https://wordpress.org/support/article/wordpress-features/#broadcast-your-ideas

## Why is this a problem?
The information and links are outdated

## Suggested Fix
from @estelaris "change ""more than a quarter"" for ""almost half"".
"" WordPress isn’t even used as a blog"" links to an article written in 2011
Feeds section's links are very old, is there any updated information regarding feeds?"

from @atachibana "[About feed] WordPress used to create the closed network with feed or comment, but SNS changed it, and now WordPress is a kind of conent repository accessed by REST. We can remove the external links to feed.
[Additional editorial] We should remove this sentence because we have to maintain this page every year -- ""With more than 50 million sites globally and 13 years of proven history, you know you’re getting the best software for the job."""

**Comment by estelaris** [comment]
I am tempted to keep the 2011 link to the sentence "[WordPress isn't even used as a blog](https://max.limpag.com/article/wordpress-open-source-cms-2011/)" for historic purposes. It has absolutely no bad/wrong/negative effect on the content. Will appreciate a discussion from the team.

Follow instructions in the comment from @atachibana `"[About feed] WordPress used to create the closed network with feed or comment, but SNS changed it, and now WordPress is a kind of conent repository accessed by REST. We can remove the external links to feed.`

There is another problematic paragraph: **Backed by community support**. Make the following changes:

- WordPress is supported by a `vibrant community of users ` change that link to https://make.wordpress.org/
- `WordPress Version 4.9 has been downloaded more than 160 million times since it was released a few months ago. ` Change the sentece to say: `The latest version is downloaded as soon as it is published and the numbers keep increasing`. Add the link to `downloaded` https://wordpress.org/download/counter/

**Comment by MuhammadFaizanHaidar** [comment]
@estelaris I have updated the article according to the instructions. Please have a review, find link below!
https://wordpress.org/support/article/wordpress-features/

**Comment by estelaris** [comment]
@atachibana I am not sure what you want us to change on the [feed](https://wordpress.org/support/article/wordpress-features/#broadcast-your-ideas)] section from this article. Should we remove the entire section and add the explanation you mentioned above? or only remove the links to RSS1.0, RSS2.0 and Atom?

**Comment by atachibana** [comment]
@estelaris 
I said that, but RSS is still in use, so let's keep it. You don't need to change anything. Thanks.

**Comment by estelaris** [comment]
This article will be removed as the [Features](https://wordpress.org/about/features/) page under About is kept up-to-date
