### ISSUE TITLE
[HelpHub] Content review: WordPress Feeds

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#471]
## Issue Description

Outdated external links

## URL of the Page with the Issue

[WordPress feeds](https://wordpress.org/support/article/wordpress-feeds/)

## Section of Page with the issue

[More information and resources](https://wordpress.org/support/article/wordpress-feeds/) and throughout the full article

## Why is this a problem?

Outdated information in external links

## Suggested Fix

Review content and find more relevant external links or remove them entirely

**Comment by ivahyael** [comment]
Hi @zzap 👋 I would like to contribute and work on this.

**Comment by ivahyael** [comment]
**Ready for review**
