### ISSUE TITLE
[HelpHub] Content review: WordPress Privacy

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#472]
## Issue Description

There are no individual props in HelpHub articles

## URL of the Page with the Issue

[WordPress Privacy](https://wordpress.org/support/article/wordpress-privacy/)

## Section of Page with the issue

Under [Consent of data collected](https://wordpress.org/support/article/wordpress-privacy/#consent-of-data-collected)

## Why is this a problem?

Plenty of times have article authors consulted with developers on the topic they are writing about but has been a consensus so far in the docs team that there is no personal acknowledgement written.  

## Suggested Fix

Remove the props under the Consent of data collected section. If authors want to give props to anyone who helped them, do so in the Slack #props channel

**Comment by tahmid-ul** [comment]
I would like to work on this issue.
