### ISSUE TITLE
[HelpHub] Border Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#480]
## New page
- [x] Create a new article for the Border Settings under the block settings 
- [x] Make sure the URL slug under Permalink is: border-settings-overview
- [x] Make sure the content in the article matches the 6.1 UI.
- [x] Add the list of blocks that support the Border settings. [Refer to this article](https://make.wordpress.org/core/2022/09/26/core-editor-improvement-catalyst-for-creativity/)

## Updating for 6.1
- [x] Update control labels to the new uppercase styles[42789](https://github.com/WordPress/gutenberg/pull/42789)
- [x] Add tooltips to split border radius controls [40983](https://github.com/WordPress/gutenberg/pull/40983)
- [x]  Make reset to default button only display when required [40917](https://github.com/WordPress/gutenberg/pull/40917)
- [x] Use new border control components in block support [37770](https://github.com/WordPress/gutenberg/pull/37770)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by femkreations** [comment]
@kathrynwp pls refer to this issue related to the task - updating the end-user documentation for design consistency across all the blocks. Once you comment here, I can assign the task to you. Thanks.

**Comment by kathrynwp** [comment]
Thanks, @femkreations ! Feel free to assign the task to @Thelmachido

**Comment by femkreations** [comment]
@Thelmachido Pls comment here, only then I can assign the task to you.

**Comment by Thelmachido** [comment]
Hi, thank you for the pind

**Comment by femkreations** [comment]
Adding this article for reference https://make.wordpress.org/core/2022/09/26/core-editor-improvement-catalyst-for-creativity/
