### ISSUE TITLE
[HelpHub] Revamp block settings section in the Text Block articles

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#482]
Review the existing Text block articles and replace the current content under Block settings with links to the newly created pages for 

1. [ ] Typography, 
2. [ ] Color, 
3. [ ] Dimensions,
4. [ ] Layout, 
5. [ ] Border settings. 

Refer to [#476](https://github.com/WordPress/Documentation-Issue-Tracker/issues/476), [#477](https://github.com/WordPress/Documentation-Issue-Tracker/issues/477), [#478](https://github.com/WordPress/Documentation-Issue-Tracker/issues/478), [#479](https://github.com/WordPress/Documentation-Issue-Tracker/issues/479) and [#480](https://github.com/WordPress/Documentation-Issue-Tracker/issues/480) for link to the individual block settings page. 

Here are the list of Text block articles to be revamped.
- [x] [Paragraph](https://wordpress.org/support/article/paragraph-block/)
- [x] [Heading](https://wordpress.org/support/article/heading-block/)
- [x] [List](https://wordpress.org/support/article/list-block/)
- [x] [Quote](https://wordpress.org/support/article/quote-block/)
- [x] [Classic](https://wordpress.org/support/article/classic-block/)
- [x] [Code](https://wordpress.org/support/article/code-block/)
- [x] [Preformatted](https://wordpress.org/support/article/preformatted-block/)
- [x] [Pullquote](https://wordpress.org/support/article/pullquote-block/)
- [x] [Table](https://wordpress.org/support/article/table-block/)
- [x] [Verse](https://wordpress.org/support/article/verse-block/)

## General
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Hi @Thelmachido Pls comment on this issue, so I can assign the task to you. Thanks for your help!

**Comment by Thelmachido** [comment]
Thanks for the ping @femkreations

**Comment by femkreations** [comment]
@Thelmachido PLs let me know if you are still working on this. Thank you!

**Comment by femkreations** [comment]
I reviewed all the pages and looks like they have all been updated. Thank you for your work @Thelmachido

**Comment by Thelmachido** [comment]
Thank you @femkreations
