### ISSUE TITLE
[HelpHub] Revamp block settings section in the Design Blocks articles

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#484]
Review the existing Design block articles and replace the current content under Block settings with links to the newly created pages for 

1. [ ] Typography, 
2. [ ] Color, 
3. [ ] Dimensions,
4. [ ] Layout, 
5. [ ] Border settings. 

Refer to [#476](https://github.com/WordPress/Documentation-Issue-Tracker/issues/476), [#477](https://github.com/WordPress/Documentation-Issue-Tracker/issues/477), [#478](https://github.com/WordPress/Documentation-Issue-Tracker/issues/478), [#479](https://github.com/WordPress/Documentation-Issue-Tracker/issues/479) and [#480](https://github.com/WordPress/Documentation-Issue-Tracker/issues/480) for link to the individual block settings page. 

Here are the list of Design block articles to be revamped.
- [ ]  [Buttons](https://wordpress.org/support/article/buttons-block/) 
- [ ] [Columns](https://wordpress.org/support/article/columns-block/)
- [ ] [Group](https://wordpress.org/support/article/group-block/)
- [ ] [More](https://wordpress.org/support/article/more-block/)
- [ ] [Page Break](https://wordpress.org/support/article/page-break-block/)
- [ ] [Separator](https://wordpress.org/support/article/separator-block/)
- [ ] [Spacer](https://wordpress.org/support/article/spacer-block/)

## General
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Hi @Thelmachido Pls comment on this issue, so I can assign the task to you. Thanks for your help! @kathrynwp

**Comment by Thelmachido** [comment]
I have managed to go through the articles mentioned on this issue and more. Please feel free to review @femkreations

**Comment by femkreations** [comment]
@Thelmachido Thanks for working on this. Could you pls add links to the overview pages for Typography, Color,  Dimensions, Layout, and Border settings on these pages depending on which of them are available in the block?

I have created a reusable block that can be used for this. Here is what you can do:

- Search for /layout settings overview /dimension settings overview /color settings overview /border settings overview and /typography settings overview to find these reusable blocks
- Depending on which ones are needed on each of the pages add them to the page
- Convert the to regular blocks
- Update the block name in the content of the reusable block.

I have done this for the [archives](https://wordpress.org/support/article/archives-block/#block-settings) page as a sample. Can you pls work on the remaining pages?

Thanks

**Comment by Thelmachido** [comment]
For the above pages, I have added the settings where needed.

Additionally, I went over the Text, Media, Design, Theme & Widget Blocks listed on [the Blocks ](https://wordpress.org/support/article/blocks/)page to see if any articles needed an update. The articles that I updated are listed below: 

- [Paragraph Block](https://wordpress.org/support/article/paragraph-block/ ) Dimension settings 
- [Code Block](https://wordpress.org/support/article/code-block/)  dimension + border settings
- [PullQoute block](https://wordpress.org/support/article/pullquote-block/ ) border + typography settings
- [Table Block](https://wordpress.org/support/article/table-block/)  border + dimensions + typography + color settings
- [Site Logo](https://wordpress.org/support/article/site-logo-block/) added dimension settings
- [Post categories block](https://wordpress.org/support/article/post-categories-block/)  dimension settings
- [Post Date Block](https://wordpress.org/support/article/post-date-block/ )  dimension settings 
- [Post Content block](https://wordpress.org/support/article/post-content-block/)  dimension + typography settings
- [Post featured image block](https://wordpress.org/support/article/post-featured-image-block/)  color settings 
- [Post template](https://wordpress.org/support/article/post-template-block/ ) color settings
- [Comments Block](https://wordpress.org/support/article/comments-block/)  dimension settings
- [Comments template block](https://wordpress.org/support/article/comment-template-block/)  dimension settings
- [Comment Date Block](https://wordpress.org/support/article/comment-date-block/ ) dimension settings
- [Comment edit link](https://wordpress.org/support/article/comment-edit-link-block/)  dimension settings 
- [Post Comments Form Block](https://wordpress.org/support/article/post-comments-form-block/ ) dimension settings 
- [Term Description Block](https://wordpress.org/support/article/term-description-block/)  dimension settings 

Let me know if there is anything else.

**Comment by femkreations** [comment]
Thanks @Thelmachido This looks great.
