### ISSUE TITLE
[HelpHub] Revamp block settings section in the Widgets Blocks articles

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#485]
Review the existing Widget block articles and replace the current content under Block settings with links to the newly created pages for 

1. [ ] Typography, 
2. [ ] Color, 
3. [ ] Dimensions,
4. [ ] Layout, 
5. [ ] Border settings. 

Refer to [#476](https://github.com/WordPress/Documentation-Issue-Tracker/issues/476), [#477](https://github.com/WordPress/Documentation-Issue-Tracker/issues/477), [#478](https://github.com/WordPress/Documentation-Issue-Tracker/issues/478), [#479](https://github.com/WordPress/Documentation-Issue-Tracker/issues/479) and [#480](https://github.com/WordPress/Documentation-Issue-Tracker/issues/480) for link to the individual block settings page. 

Here are the list of Widget block articles to be revamped.
- [ ]  [Archives](https://wordpress.org/support/article/archives-block/)
- [ ] [Calendar](https://wordpress.org/support/article/calendar-block/) 
- [ ] [Categories](https://wordpress.org/support/article/categories-block/)
- [ ] [Custom HTML](https://wordpress.org/support/article/custom-html/)
- [ ] [Latest Comments](https://wordpress.org/support/article/latest-comments-block/)
- [ ] [Latest Posts](https://wordpress.org/support/article/latest-posts-block/)
- [ ] [RSS](https://wordpress.org/support/article/rss-block) 
- [ ] [Search](https://wordpress.org/support/article/search-block/) 
- [ ] [Shortcode](https://wordpress.org/support/article/shortcode-block/)
- [ ] [Social Icons](https://wordpress.org/support/article/social-icons/) 
- [ ] [Tag Cloud](https://wordpress.org/support/article/tag-cloud-block/) 

## General
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Hi @Thelmachido Pls comment on this issue, so I can assign the task to you. Thanks for your help! @kathrynwp

**Comment by Thelmachido** [comment]
Thanks for the ping @femkreations

**Comment by Thelmachido** [comment]
I have managed to go through the articles mentioned on this issue and more. Please feel free to review @femkreations

**Comment by femkreations** [comment]
@Thelmachido Thanks for working on this. Could you pls add links to the overview pages for Typography, Color,  Dimensions, Layout, and Border settings on these pages depending on which of them are available in the block?

I have created a reusable block that can be used for this. Here is what you can do:

- Search for /layout settings overview /dimension settings overview /color settings overview /border settings overview and /typography settings overview to find these reusable blocks
- Depending on which ones are needed on each of the pages add them to the page
- Convert the to regular blocks
- Update the block name in the content of the reusable block.

I have done this for the [archives](https://wordpress.org/support/article/archives-block/#block-settings) page as a sample. Can you pls work on the remaining pages?

Thanks

**Comment by Thelmachido** [comment]
Hi @femkreations

For the above pages I have added the settings where needed as you suggested.

I left aligned the content in the blue block and changed the changelog heading to H2.

Let me know if there something else I should do.

**Comment by femkreations** [comment]
Thank you @Thelmachido . All looks great. Closing this task.
