### ISSUE TITLE
[HelpHub] Revamp block settings section in the Embed Block articles

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#486]
Review the existing Embed block articles and replace the current content under Block settings with links to the newly created pages for 

1. [ ] Typography, 
2. [ ] Color, 
3. [ ] Dimensions,
4. [ ] Layout, 
5. [ ] Border settings. 

Refer to [#476](https://github.com/WordPress/Documentation-Issue-Tracker/issues/476), [#477](https://github.com/WordPress/Documentation-Issue-Tracker/issues/477), [#478](https://github.com/WordPress/Documentation-Issue-Tracker/issues/478), [#479](https://github.com/WordPress/Documentation-Issue-Tracker/issues/479) and [#480](https://github.com/WordPress/Documentation-Issue-Tracker/issues/480) for link to the individual block settings page. 

Here are the list of Embed block articles to be revamped.

- [ ] [Embed](https://wordpress.org/support/article/embed-block/)
- [ ] [Twitter](https://wordpress.org/support/article/twitter-embed/)
- [ ] [YouTube](https://wordpress.org/support/article/youtube-embed/)
- [ ] [WordPress](https://wordpress.org/support/article/wordpress-embed/)
- [ ] [SoundCloud](https://wordpress.org/support/article/soundcloud-embed/)
- [ ] [Spotify](https://wordpress.org/support/article/spotify-embed/)
- [ ] [Flickr](https://wordpress.org/support/article/flickr-embed/)
- [ ] [Vimeo](https://wordpress.org/support/article/vimeo-embed/)
- [ ] [Animoto](https://wordpress.org/support/article/animoto-embed/)
- [ ] [CloudUp](https://wordpress.org/support/article/cloudup-embed/)
- [ ] [Crowdsignal](https://wordpress.org/support/article/crowdsignal-embed/)
- [ ] [Dailymotion](https://wordpress.org/support/article/dailymotion-embed/)
- [ ] [Imgur](https://wordpress.org/support/article/imgur-embed/)
- [ ] [Issuu](https://wordpress.org/support/article/issuu-embed/)
- [ ] [Kickstarter](https://wordpress.org/support/article/kickstarter-embed/)
- [ ] [Mixcloud](https://wordpress.org/support/article/mixcloud-embed/)
- [ ] [Reddit](https://wordpress.org/support/article/reddit-embed/)
- [ ] [ReverbNation](https://wordpress.org/support/article/reverbnation-embed/)
- [ ] [Screencast](https://wordpress.org/support/article/screencast-block/)
- [ ] [Scribd](https://wordpress.org/support/article/scribd-embed/)
- [ ] [Slideshare](https://wordpress.org/support/article/slideshare-embed/)
- [ ] [SmugMug](https://wordpress.org/support/article/smugmug-embed/)
- [ ] [Speaker Deck](https://wordpress.org/support/article/speaker-deck-embed/)
- [ ] [TikTok](https://wordpress.org/support/article/tiktok-embed/) 
- [ ] [TED](https://wordpress.org/support/article/ted-embed/)
- [ ] [Tumblr](https://wordpress.org/support/article/tumblr-embed/)
- [ ] [VideoPress](https://wordpress.org/support/article/videopress-embed/)
- [ ] [WordPress.tv](https://wordpress.org/support/article/wordpress-tv-embed-block/)
- [ ] [Wolfram](https://wordpress.org/support/article/wolfram-embed/)
- [ ] [Facebook](https://wordpress.org/support/article/facebook-embed/)
- [ ] [Instagram](https://wordpress.org/support/article/instagram-embed/)

## General
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Hi @Thelmachido Pls comment on this issue, so I can assign the task to you. Thanks for your help! @kathrynwp

**Comment by Thelmachido** [comment]
@femkreations with the embeds blocks I couldn't find any new settings that were added recently, however, I removed replaced content, added alt text where necessary, and removed re-usable blocks. 

Can you please review and let me know if I have recovered everything for this one?

**Comment by femkreations** [comment]
@Thelmachido Looks great. Thanks for working on these! I updated the changelog heading level to H2 (and made it M size)  so it looks good in the TOC (with no bullets).  Also for accessibility, it is advised to keep the text inside the blue message box left aligned. I did make that update on the pages.
Closing this issue.

**Comment by Thelmachido** [comment]
Thank you very much Femy :)
