### ISSUE TITLE
[HelpHub] Revamp block settings section in the Theme Block articles

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#487]
Review the existing Theme block articles and replace the current content under Block settings with links to the newly created pages for 

1. [ ] Typography, 
2. [ ] Color, 
3. [ ] Dimensions,
4. [ ] Layout, 
5. [ ] Border settings. 

Refer to [#476](https://github.com/WordPress/Documentation-Issue-Tracker/issues/476), [#477](https://github.com/WordPress/Documentation-Issue-Tracker/issues/477), [#478](https://github.com/WordPress/Documentation-Issue-Tracker/issues/478), [#479](https://github.com/WordPress/Documentation-Issue-Tracker/issues/479) and [#480](https://github.com/WordPress/Documentation-Issue-Tracker/issues/480) for link to the individual block settings page. 

Here are the list of Theme block articles to be revamped.
- [x]  [Navigation](https://wordpress.org/support/article/navigation-block/) 
- [x] [Site Logo](https://wordpress.org/support/article/site-logo-block/) 
- [x] [Site Title](https://wordpress.org/support/article/site-title-block/) 
- [x] [Site Tagline](https://wordpress.org/support/article/site-tagline-block/) 
- [x] [Query Loop](https://wordpress.org/support/article/query-loop-block/) 
- [x] [Post Title ](https://wordpress.org/support/article/post-title-block/)
- [x] [Post Excerpt](https://wordpress.org/support/article/post-excerpt-block/) 
- [x] [Post Featured Image](https://wordpress.org/support/article/post-featured-image-block/) 
- [x] [Post Content ](https://wordpress.org/support/article/post-content-block/)
- [x] [Post Date ](https://wordpress.org/support/article/post-date-block/)
- [x] [Post Categories](https://wordpress.org/support/article/post-categories-block/) 
- [x] [Post Tags](https://wordpress.org/support/article/post-tags-block/) 
- [x] [Read More](https://wordpress.org/support/article/read-more-block/)
- [x] [Comment Template](https://wordpress.org/support/article/comment-template-block/)
- [x] [Comment Author Name](https://wordpress.org/support/article/comment-author-name-block/)
- [x] [Comment Date](https://wordpress.org/support/article/comment-date-block/)
- [x] [Comment Content](https://wordpress.org/support/article/comment-content-block/)
- [x] [Comment Reply Link](https://wordpress.org/support/article/comment-reply-link-block/)
- [x] [Comment Edit Link](https://wordpress.org/support/article/comment-edit-link-block/)
- [x] [Comment Pagination](https://wordpress.org/support/article/comment-pagination-block/)
- [x] [Term Description](https://wordpress.org/support/article/term-description-block/)
- [x] [Archive Title](https://wordpress.org/support/article/archive-title-block/) 
- [x] [Template Part](https://wordpress.org/support/article/template-part-block/) 

## General
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Thelmachido** [comment]
Thanks for the ping @femkreations

**Comment by Thelmachido** [comment]
Hi @femkreations

For the above pages, I have added the settings where needed as you suggested.

I left align the content in the blue block and changed the changelog heading to H2. Added the new design tools were necessary.

Let me know if there is something else I should do.

**Comment by femkreations** [comment]
Reviewed all the pages. Looks good.
