### ISSUE TITLE
Minor mistakes in Shortcode-ception section

### ISSUE THREAD

**Issue by jamieburchell** [WordPress/Documentation-Issue-Tracker#488]
## Issue Description

Shortcode is displayed with double square brackets "[[shortcode]]" and function declaration starts with a number "5"

## URL of the Page with the Issue

[Shortcode-ception](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/#shortcode-ception)

## Section of Page with the issue

Shortcode-ception

## Why is this a problem?

Too many square brackets / invalid PHP

## Suggested Fix

Change [[shortcode]] to [shortcode]
Remove the number "5" from `5function wporg_shortcode( $atts = array(), $content = null ) {`

**Comment by nikkifurls** [comment]
Hello! I'd like to work on this. This will be my first contribution :) thank you!

**Comment by nikkifurls** [comment]
1. Fix double square brackets

Change
`This means that if the $content parameter of a shortcode handler contains another shortcode, it won’t be parsed. In this example, [[shortcode]] will not be processed:`
to
`This means that if the $content parameter of a shortcode handler contains another shortcode, it won’t be parsed. In this example, [shortcode] will not be processed:`

2. Fix function declaration

Change
```
5function wporg_shortcode( $atts = array(), $content = null ) {
	// do something to $content

	// run shortcode parser recursively
	$content = do_shortcode( $content );

	// always return
	return $content;
}
add_shortcode( 'wporg', 'wporg_shortcode' );
```
to
```
function wporg_shortcode( $atts = array(), $content = null ) {
	// do something to $content

	// run shortcode parser recursively
	$content = do_shortcode( $content );

	// always return
	return $content;
}
add_shortcode( 'wporg', 'wporg_shortcode' );
```

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision.
