### ISSUE TITLE
update_post_meta function incorrectly cited as having a unique parameter flag

### ISSUE THREAD

**Issue by jamieburchell** [WordPress/Documentation-Issue-Tracker#489]
## Issue Description
The documentation incorrectly states that the `update_post_meta` function has a `unique` flag as its last parameter

## URL of the Page with the Issue

https://developer.wordpress.org/plugins/metadata/managing-post-metadata/#updating-metadata

## Section of Page with the issue

> Similar to [add_post_meta()](https://developer.wordpress.org/reference/functions/add_post_meta/) , the function accepts a post_id, a meta_key, a meta_value, and a **unique** flag.

## Why is this a problem?

The function signature is actually `int $post_id, string $meta_key, mixed $meta_value, mixed $prev_value = ''`

## Suggested Fix

Correct the list of parameters mentioned

**Comment by nikkifurls** [comment]
Hello! I'd like to work on this :)

**Comment by nikkifurls** [comment]
Change
```
Similar to <a href="https://developer.wordpress.org/reference/functions/add_post_meta/" rel="function">add_post_meta()</a> , the function accepts a <code>post_id</code>, a <code>meta_key</code>, a <code>meta_value</code>, and a <code>unique</code> flag.
```
to
```
Similar to <a href="https://developer.wordpress.org/reference/functions/add_post_meta/" rel="function">add_post_meta()</a> , the function accepts a <code>post_id</code>, a <code>meta_key</code>, and a <code>meta_value</code>. It also accepts an optional <code>prev_value</code> – which, if specified, will cause the function to only update existing metadata entries with this value. If it isn't provided, the function defaults to updating all entries.
```

**Comment by stevenlinx** [comment]
I've made the revision.
