### ISSUE TITLE
Link updates on article WordPress features

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#49]
## Issue Description
Update links. Links are to ther WP documentation articles.

## URL of the Page with the Issue
https://wordpress.org/support/article/wordpress-features

## Section of Page with the issue
Several, in the list below, 
example
- [ ] the section is listed first | `then the sentence with the wrong link` and lastly, **the correct link**

## Why is this a problem?
Links still linking to Codex and some are outdated.

## Suggested Fix

- [ ] Built for publishing: `subscribe to specific content sub-feeds` link to https://wordpress.org/support/article/wordpress-feeds/
- [ ] Backed by community support | `vibrant community of users `link to https://wordpress.org/support/article/contributing-to-wordpress/
- [ ] Backed by community support | `Version 4.9 `change to `the latest version` and link to https://wordpress.org/download/counter/
- [ ] Beyond black and white | `media browser to help you store, organize and find the files` link to https://wordpress.org/support/article/media-add-new-screen/
- [ ] Never lose a word | `automatically saves your work` link to https://wordpress.org/support/article/revisions/#autosaves and `WordPress creates a snapshot` link to https://wordpress.org/support/article/revisions
- [ ] Typography nerds rejoice | `WordPress silently typesets each and every letter for seamless web production` link to https://wordpress.org/support/article/how-wordpress-processes-post-content/
- [ ] Drag and drop administration | `dynamic functionality on each page` link to https://wordpress.org/support/article/appearance-widgets-screen/
- [ ] Multiple personalities | `define different roles for different users` link to https://wordpress.org/support/article/roles-and-capabilities/
- [ ] Template driven design | `Template tags` link to https://developer.wordpress.org/themes/basics/template-tags
- [ ] Your site is your castle | `sanitizes all user input` link to https://developer.wordpress.org/plugins/security/data-validation/
- [ ] Maintenace so simple... | `one click updates` link to https://wordpress.org/support/article/dashboard-updates-screen/

**Comment by hasanuzzamanbe** [comment]
Hi,
I want to contribute, How can I start with it?
thanks

**Comment by stevenlin-x** [comment]
I've updated the links.
