### ISSUE TITLE
[HelpHub] Adding a new block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#490]
Article: https://wordpress.org/documentation/article/adding-a-new-block/

## Update for 6.2
- [ ] Update the synced block hover styles in Inserter [46442](https://github.com/WordPress/gutenberg/pull/46442)
- [ ] Move document information and outline to list view panel [44788](https://github.com/WordPress/gutenberg/pull/44788)
- [ ] Don't show empty reusable tab if not allowed to insert reusable blocks [46922](https://github.com/WordPress/gutenberg/pull/46922)
- [ ] Openverse integration [46251](https://github.com/WordPress/gutenberg/pull/46251)
- [ ] Replace text in Reusable tab with an icon [45851](https://github.com/WordPress/gutenberg/pull/45851)
- [ ] Restore the empty paragraph inserter [45542](https://github.com/WordPress/gutenberg/pull/45542)
- [ ] Add media tab [44918](https://github.com/WordPress/gutenberg/pull/44918)
- [ ] add a more pronounced hover effect [44711](https://github.com/WordPress/gutenberg/pull/44711)
- [ ] Redesign the main pattern inserter [44028](https://github.com/WordPress/gutenberg/pull/44028)
- [ ] Move wordcount to the top of the outline [46648](https://github.com/WordPress/gutenberg/pull/46648)

## Update for 6.1
- [ ] Adds CTA and external link to block inserter flow [41112](https://github.com/WordPress/gutenberg/pull/41112)
- [ ] Simplify the inserter styles and scrollable [44088](https://github.com/WordPress/gutenberg/pull/44088)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. Pls make 6.2 updates first and then move to 6.1.
2. Some of the PRs have great videos that can be added to the article

**Comment by Thelmachido** [comment]
I am working on this one, feel free to assign this to me @femkreations

**Comment by Thelmachido** [comment]
This is ready for review, I made updates for 6.2

**Comment by jennimckinnon** [comment]
I edited some single quotation marks that needed to be double quotation marks.

I also noticed there were two images that needed ALT text, but there was an error when I tried to update it.

1. For the third image on the page under the text "Select a block from the list or click on the "Browse all" button to get a list of all the [blocks](https://wordpress.org/documentation/article/blocks/) available in the [WordPress block editor](https://wordpress.org/documentation/article/wordpress-editor/)."

Here's the ALT text: The block inserter modal window

2. For the fourth image on the page under the text "When you pick the option to browse all, a larger window of the blocks available will opened."

Here's the ALT text: The top-toolbar inserter open on the page

Other than that, this one's ready for a second review.

**Comment by sagargurnani99** [comment]
Thanks @jennimckinnon for the work.

I am done with the 2nd review and everything looks good. I have updated the ALT text to the two images which you were not able to do it at that time and also updated the change log.

So, I am closing this issue now.
