### ISSUE TITLE
[HelpHub] Comment Pagination block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#491]
Article : https://wordpress.org/documentation/article/comment-pagination-block/

## Update for 6.2
- [x] Comment pagination numbers: add background color. [43902](https://github.com/WordPress/gutenberg/pull/43902)

## Update for 6.1
- [x]  Update the Comment Pagination Block page to include the information for Previous, Next, and Page Numbers blocks. (Similar to https://wordpress.org/documentation/article/pagination-block/#pagination-inner-blocks )
- [x]  Add a note for this feature
Fix comments query loop pagination not respecting Discussion Settings [40284](https://github.com/WordPress/gutenberg/pull/40284)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by femkreations** [comment]
Refer https://github.com/WordPress/Documentation-Issue-Tracker/issues/323 https://github.com/WordPress/Documentation-Issue-Tracker/issues/324 and https://github.com/WordPress/Documentation-Issue-Tracker/issues/325

**Comment by carolinan** [comment]
Information about the new background color support has already been added to this article.

**Comment by yogskr** [comment]
Hey, @Leonardus-Nugraha. I'd like to work on this issue next!

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1sJDRM3VNApeXOZfY3J3gujiM7ptF-Uk9yEQCSWMZKh4/edit#heading=h.488fdx1ij12g

1st review is done

**Comment by Leonardus-Nugraha** [comment]
article is updated, only information about the inner blocks left

**Comment by Leonardus-Nugraha** [comment]
Checked for the latest version, and added a new section for the inner blocks
