### ISSUE TITLE
[HelpHub] Pocket Casts Embed bock

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#494]
## What is the new page you are requesting?

New article is required for the Pocket Casts Embed block

## New page
- [ ] Create a new article for the Pocket Casts Embed block
- [ ] Make sure the URL slug under Permalink is: pocket-casts-embed-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Updating for 6.1
- [ ] Add Pocket Casts embed block variation [41006](https://github.com/WordPress/gutenberg/pull/41006)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by yogakrisanta** [comment]
Yooo @Leonardus-Nugraha! I'll work on this.

**Comment by Leonardus-Nugraha** [comment]
ready for 2nd review: https://docs.google.com/document/d/1KeAJjAZrnWtq-gwMegw7wbMVStZ_mn8rsvs05XBvK2w/edit?usp=sharing

screencasts:

https://user-images.githubusercontent.com/65521329/203470468-eb275d0b-4c44-4016-9da7-f642136d138a.mp4


https://user-images.githubusercontent.com/65521329/203470471-fd7cf367-7a35-40e4-8f7a-f559d87dfc78.mp4

**Comment by Leonardus-Nugraha** [comment]
Thanks @yogakrisanta & @emmasophieyoung for the article & screencasts!
@femkreations, I've reviewed and published the article: https://wordpress.org/support/article/pocket-casts-embed-block/
Link added to the https://wordpress.org/support/article/blocks/
