### ISSUE TITLE
[HelpHub] Table block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#496]
Article: https://wordpress.org/documentation/article/table-block/

## Updating for 6.2
- [x] Display fixed width table cells option by default [47536](https://github.com/WordPress/gutenberg/pull/47536)

## Updating for 6.1
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## Updating for 6.0
- [x] Block Styles: Show style preview when hovered or focused. [34522](https://github.com/WordPress/gutenberg/pull/34522)
- [x] At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles

**Comment by Ignasrimkunas** [comment]
Hey, @Leonardus-Nugraha assign me

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1eF7yV9Xc7ILCQp3I1cZSq3pylD5Ab6Y8I2S80RhrfV0/edit?usp=sharing

first review is done!

**Comment by femkreations** [comment]
@Ignasrimkunas I have added one task related to 6.2. PLs included this on the page. Thanks

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas & @emmasophieyoung 
@femkreations I've added the update for 6.2 and updated the article: https://wordpress.org/documentation/article/table-block/
