### ISSUE TITLE
[HelpHub] Buttons block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#497]
Article: https://wordpress.org/documentation/article/buttons-block/

## Updating for 6.2
- [x] Fix/flex controls bugs [47533](https://github.com/WordPress/gutenberg/pull/47533)

## Updating for 6.0
- [x] Block Styles: Show style preview when hovered or focused. [34522](https://github.com/WordPress/gutenberg/pull/34522)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by Ignasrimkunas** [comment]
Hey, @Leonardus-Nugraha assign me

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1BnYoGLSB78KtCR2Dn2ybNLNkKEgj7osBFJi-LS-HweA/edit#

1st review done 
@Leonardus-Nugraha

**Comment by femkreations** [comment]
@emmasophieyoung I have added a new task related to 6.2. Can you pls make sure this is included as well. Thanks

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas @emmasophieyoung!
@femkreations added the update for 6.2 and updated the article: https://wordpress.org/documentation/article/buttons-block/
