### ISSUE TITLE
[HelpHub] Video block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#501]
Article: https://wordpress.org/support/article/video-block/

## Updating for 6.1
- [ ] Display upload error notices using snackbars. [43892](https://github.com/WordPress/gutenberg/pull/43892)
- [ ] Mark which attributes of the video should be considered content. [44038](https://github.com/WordPress/gutenberg/pull/44038)
- [ ] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
Hey, @Leonardus-Nugraha assign me

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1NE9OpuQBaPJ6c4nqvmin2omfE1l2AdmmC0wwQVIxmZM/edit#heading=h.agzou5iryxk7

@Leonardus-Nugraha this has it's first review finished, ready for you

**Comment by emmasophieyoung** [comment]
reviewed and published
URL: https://wordpress.org/documentation/article/video-block/
