### ISSUE TITLE
[HelpHub] Archives block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#502]
Article: https://wordpress.org/support/article/archives-block/

## Updating for 6.1
- [ ] Add a control to make block's dropdown label invisible. [43025](https://github.com/WordPress/gutenberg/pull/43025)
- [ ] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha heya assign me

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1zNSbFlOOL9kPEaUXVVLAyPurwjH4K71BYJtPhyXoU7w/edit#

@Leonardus-Nugraha 1st review done

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas & @emmasophieyoung ! Reviewed and updated the article!
https://wordpress.org/documentation/article/archives-block/
