### ISSUE TITLE
[HelpHub] Site Logo block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#504]
Article:  https://wordpress.org/documentation/article/site-logo-block/

## Updating for 6.2
- [x] Update placeholder style [44190](https://github.com/WordPress/gutenberg/pull/44190)
- [x] Apply width to logo container in editor [45821](https://github.com/WordPress/gutenberg/pull/45821)

## Updating for 6.1
- [x] Polish placeholder radius and enable duotone on image setup state. [43425](https://github.com/WordPress/gutenberg/pull/43425)
- [x] Add blurred background to work in nested cases. [43379](https://github.com/WordPress/gutenberg/pull/43379)
- [x] Refactor and simplify dashed placeholders used for Featured Image & Site Logo[43228](https://github.com/WordPress/gutenberg/pull/43228)
- [x] Update/site logo constrain image. [41298](https://github.com/WordPress/gutenberg/pull/41298)
- [x] Add an illustration option to the Placeholder component [41605](https://github.com/WordPress/gutenberg/pull/41605)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by yogskr** [comment]
@Leonardus-Nugraha assign me this issue, thanks!

**Comment by femkreations** [comment]
@yogskr I have added a few tasks related to 6.2. Pls add them to the page. Let me know if you have any questions.

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1B5JWBIO2hNpqTKhOOK5OEKxLZlcYbFUvOHzWLAuxrSw/edit#

first review done

**Comment by Leonardus-Nugraha** [comment]
Article updated! Thanks @yogskr and @emmasophieyoung !
