### ISSUE TITLE
[HelpHub] File block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#505]
Article:  https://wordpress.org/support/article/file-block/

## Updating for 6.1
- [x] Display upload error notices using snackbars. [43893](https://github.com/WordPress/gutenberg/pull/43893)
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by Leonardus-Nugraha** [comment]
I'll work on this one

**Comment by Leonardus-Nugraha** [comment]
@femkreations added the update for 6.1, merge text link settings and download button settings section (based on 6.1), and add some screenshot updates.

https://docs.google.com/document/d/1RW48zg1OUGF-PGpDniNsXLBLWPafMJuhvzDnH_GjUnQ/edit?usp=sharing

**Comment by emmasophieyoung** [comment]
@Leonardus-Nugraha proofed
@femkreations 1st review is good to go

**Comment by femkreations** [comment]
Thaks @Leonardus-Nugraha and @emmasophieyoung I've updated the article. The page looks great. Thanks for your efforts.
