### ISSUE TITLE
[HelpHub] Search block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#506]
Article:  https://wordpress.org/support/article/search-block/

## Updating for 6.1
- [x] Remove margins from the input [42959](https://github.com/WordPress/gutenberg/pull/42959)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha heya assign me

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung !
Moved the content and updated the article: https://wordpress.org/support/article/search-block/
