### ISSUE TITLE
[HelpHub] Archive Title block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#508]
Article:  https://wordpress.org/support/article/archive-title-block/

## Updating for 6.1
- [x] Add a setting to hide the prefix in the archive title. [42594](https://github.com/WordPress/gutenberg/pull/42594)
- [x] Try a single icon for title blocks. [40596](https://github.com/WordPress/gutenberg/pull/40596)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha heya assign me

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1k9Q55lWktbQpFlOKBRkidHs0f6j1RdhPxHsUMJ5-bBc/edit#
@Leonardus-Nugraha 1st review is done, ready for you

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung!
Moved the draft and updated the content: https://wordpress.org/support/article/archive-title-block/
