### ISSUE TITLE
[HelpHub] Search Results Title block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#509]
## New page 
- [x] Create a new article for the Search Results Title block
- [x] Make sure the URL slug under Permalink is: search-results-title-block
- [x] At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## Update for 6.1
- [x] Add a search title variation. [42662](https://github.com/WordPress/gutenberg/pull/42662)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by Leonardus-Nugraha** [comment]
I'll work on this

**Comment by Leonardus-Nugraha** [comment]
Draft ready for editing (cc: @emmasophieyoung)
https://docs.google.com/document/d/1yQWf5iRMyDgeoDD4k_uWAx5RsixsmPg-gGAqqPl7pr8/edit#

**Comment by emmasophieyoung** [comment]
@femkreations reviewed and all ready for you

**Comment by femkreations** [comment]
Thanks @Leonardus-Nugraha and @emmasophieyoung for working on this page content. Here is the article published.

https://wordpress.org/support/article/search-results-title-block/
