### ISSUE TITLE
Content update to New to WordPress - Where to Start

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#51]
## Issue Description
Content update

## URL of the Page with the Issue
https://wordpress.org/support/article/new-to-wordpress-where-to-start/

## Section of Page with the issue
These changes are in section `Step four – Set up WordPress`

## Why is this a problem?
Excesive and unnecesary linking

## Suggested Fix

- [x] Step four | For help on creating ... `Users > Your Profile` pages for guidance. Remove the link to Users.
- [x] Step four | To set the site name and other information ... go to `Administration > Settings > General`. Administration, Settings and General are linked to different pages, and while that is great, neither Administration nor Settings explain how to add/change the name site. Remove both links. Also, add ""in the dashoboard"" at the end of the sentence.
- [x] Step four | After you have published ... quick edit features in the `Administration > Posts > Posts `screen. Administration and posts (the first one) links are not needed.
- [x] Step four | Add your About ... information Pages by going to `Administration > Pages > Add New`. Remove the link to Administration.
- [x] Want to change the ... site? Go to `Administration > Appearance > Themes.` Remove the links to Administration and Appearance.

**Comment by AbeSelig** [comment]
I can help with this - can you assign the issue to me?

**Comment by stevenlin-x** [comment]
The are two problems in your suggested fix:

- 2nd task:
The "in the dashoboard" is a misspelling. It should be "dashboard".

- 5th task:
The "Themes" link still link to Codex:
https://codex.wordpress.org/Appearance_Themes_SubPanel
and should be linked to HelpHub directly:
https://wordpress.org/support/article/appearance-themes-screen/


I've updated the page.
