### ISSUE TITLE
[HelpHub] Comments Title block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#511]
## New page 
- [ ] Create a new article for the Comments Title block
- [ ] Make sure the URL slug under Permalink is: comments-title-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## Update for 6.1
- [ ] Try a single icon for title blocks [40596](https://github.com/WordPress/gutenberg/pull/40596)
- [ ] Create comments title with simple styling [40419](https://github.com/WordPress/gutenberg/pull/40419) 

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by yogskr** [comment]
Heya @Leonardus-Nugraha ! I'd like to work on this issue.

**Comment by Leonardus-Nugraha** [comment]
@femkreations already edited and reviewed by @emmasophieyoung
https://docs.google.com/document/d/1oOo6tMO0msJBLNFU__PaZHXYKzmIlCwyt8oNzo6kSuM/edit?usp=sharing

Screencast: 
https://user-images.githubusercontent.com/65521329/202590642-80e9154d-a034-403b-9d90-1294b5c1cabb.mp4

**Comment by femkreations** [comment]
Thanks @Leonardus-Nugraha and @yogskr for working on this article content. Here is the finished page.
https://wordpress.org/support/article/comments-title-block/
