### ISSUE TITLE
[HelpHub] Table of Contents block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#512]
## New page
- [ ] Create a new article for the Table of Contents block
- [ ]  Make sure the URL slug under Permalink is: table-of-contents-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## Update for 6.1
- [ ] re-enable + use static markup and only support core Heading and Page Break blocks [29739](https://github.com/WordPress/gutenberg/pull/29739)
- [ ] re-enable + use static markup and only support core Heading and Page Break blocks [29739](https://github.com/WordPress/gutenberg/pull/29739)
- [ ] remove editor-only wrapper [40899](https://github.com/WordPress/gutenberg/pull/40899)
- [ ] Fix list block check [41351](https://github.com/WordPress/gutenberg/pull/41351)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by bph** [comment]
Didn't make it into 6.1

**Comment by femkreations** [comment]
Closing this item as it didn't make it to 6.1
