### ISSUE TITLE
[HelpHub] Block Themes

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#515]
Article: https://wordpress.org/support/article/block-themes/

## Update for 6.1
Update screenshot and info for the following:
Add a help tab in the Theme Install screen for the new "Block Themes" search filter. [#56405](https://core.trac.wordpress.org/ticket/56405)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Ignasrimkunas** [comment]
@zzap Will take this

**Comment by zzap** [comment]
All yours @Ignasrimkunas :tada:

**Comment by Ignasrimkunas** [comment]
@zzap All done, https://docs.google.com/document/d/1KTShUupDhxqKv9tXs00VrnqOQP4fQs9u8ovqnqZb3gE/edit?usp=sharing

Updated the screenshot and added mention about it in the text

**Comment by emmasophieyoung** [comment]
@femkreations 1st review finished, ready for you

**Comment by femkreations** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung This looks great. I'm closing this issue.
