### ISSUE TITLE
[HelpHub] Appearance Menus

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#516]
Article: https://wordpress.org/support/article/appearance-menus-screen/

## Update for 6.1
Update screenshots and info for the following
Active buttons Bulk select are confusing while menu is empty[#54799](https://core.trac.wordpress.org/ticket/54799)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by cgarofalo** [comment]
@jennimckinnon I'll do the screenshots for this page too 🙏

**Comment by cgarofalo** [comment]
Screenshots & Video (Version 6.2)

Appearance Menu

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/f1ec1727-26c2-4ea8-9c1e-fd6943ceddb6)

Create Menu

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/14a7a3f6-8f15-470c-8bdf-172a0a413c4a)

Adding Menu Items

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/f4330454-8008-41b0-b0a0-30a6b7272a8e)

Delete Menu Item

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/8280d8bb-e7fb-447c-ac84-c00090fa6332)

Delete Items in bulk

https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/f42e8935-745e-481d-8559-33b0d6df72d0

Multi-Level menus

https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/55434209-44b8-41d5-9da7-701a78c8100a

Add menu to site

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/b880afc8-fccd-4848-9e63-2e6b576fa5e5)

Menu Options

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/2793c263-f702-445e-97c5-cace6d8b8c5c)

**Comment by zzap** [comment]
Is this ready for review @cgarofalo ?

**Comment by cgarofalo** [comment]
@zzap Yes :)

**Comment by Leonardus-Nugraha** [comment]
Screenshots and videos are reviewed, and the article is updated.
Thanks for the contribution @cgarofalo! Great work!
