### ISSUE TITLE
[HelpHub] Permalink settings screen.

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#517]
Article: https://wordpress.org/support/article/settings-permalinks-screen/

## Update for 6.1
Update screenshot and info for the following:
Permalinks screen, add guiding introduction to structure selection.[#55947](https://core.trac.wordpress.org/ticket/55947)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by Leonardus-Nugraha** [comment]
@femkreations updated the screenshot and added alt text

**Comment by femkreations** [comment]
Thanks @Leonardus-Nugraha. This looks great.
