### ISSUE TITLE
Block styles generation (Style Engine)

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Documentation-Issue-Tracker#519]
**2022/10/10 Update from @abhansnuk**

To check:
Categories: General or Core, or both. If it is core as well, we need to update the other ones in review too.

Second review and minor edits done, mostly for non-English speakers.

@bph:
- note in this, have kept 'Style Engine' with capital 'E'. To be checked, to add to capitalization list to use in future.
- in props: should the author of the dev chat be listed in this too?

**Comment by bph** [comment]
Thank you.  published!
