### ISSUE TITLE
Remove Desktopserver references from the docs

### ISSUE THREAD

**Issue by mayankguptadotcom** [WordPress/Documentation-Issue-Tracker#522]
## Issue Description
DesktopServer has shut down and isn't available anymore.

## URL of the Pages with the Issue
- [Installing a local server](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/)
- [Installing DesktopServer](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/desktopserver/)
- [Installing from Zip](https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-zip/)
- [WampServer](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/wampserver/)
- [SVN](https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-svn/)
- [Getting Started](https://make.wordpress.org/core/handbook/tutorials/getting-started/)
- [Contribute](https://make.wordpress.org/core/handbook/contribute/)

## Section of Page with the issue

- [Which local server should I install?](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/#which-local-server-should-i-install)

- Whole Document Page of [Installing DesktopServer](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/desktopserver/)

## Why is this a problem?
[DesktopServer](https://serverpress.com/) has already announced that they're shutting down.

## Suggested Fix
Replace it with Open-source tool, DDEV #521 

EDIT: Added more links that refer to DesktopServer. There may be more, I will continue to search and add more references here.

**Comment by stevenlinx** [comment]
Thank you for filing.

However, the pages in question is from the Core handbook.

So to request the changes, you'll need to:

Drop in on the #Core Slack channel to ask them.
https://wordpress.slack.com/messages/core/

OR

File a ticket over at Core trac.
https://core.trac.wordpress.org

FYI, please see the Coverage section of README.md:
https://github.com/WordPress/Documentation-Issue-Tracker#coverage

"All other Make / WordPress team handbooks are maintained by internally by said respective teams. Please contact them on Make / WordPress Slack to suggest changes."

**Comment by mayankguptadotcom** [comment]
@stevenlinx - have created a core ticket as per your suggestion - https://core.trac.wordpress.org/ticket/56878
@zzap : closing this
