### ISSUE TITLE
Block API changes in WordPress 6.1

### ISSUE THREAD

**Issue by bph** [WordPress/Documentation-Issue-Tracker#523]
https://make.wordpress.org/core/?p=98762&preview=1&_ppp=e0fb8d7e8f
Changed: 

- "traditional WordPress theming" to "traditional WordPress template handling." 
- rephrase: The template path is prefixed with file: and is relative to the location of the block.json file, following the [npm specification](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#local-paths).
- Note:  The entire file is used as a template, so there’s no need to define additional wrapping functions.  (added "additional" as the function 'get_block_wrapper_attributes() is also a wrapper function)

**Comment by abhansnuk** [comment]
Reviewed
