### ISSUE TITLE
Empty "Dashboard Widget Example" section

### ISSUE THREAD

**Issue by smileBeda** [WordPress/Documentation-Issue-Tracker#525]
## Issue Description
The `Example Dashboard widget` section is empty

## URL of the Page with the Issue
https://developer.wordpress.org/apis/handbook/

## Section of Page with the issue
https://developer.wordpress.org/apis/handbook/dashboard-widgets/example-dashboard-widget/

## Why is this a problem?
It is empty, thus useless.

## Suggested Fix
There are plenty of examples on its [parent page](https://developer.wordpress.org/apis/handbook/dashboard-widgets/), or on the [Developer reference](https://developer.wordpress.org/reference/functions/wp_add_dashboard_widget/) or else online.

Depending on how complex we want to make the example I can craft something much cooler of course, this is however a plain simple code sample:

```
/**
 * Function to hook to wp_dashboard_setup action.
 *
 * Calls wp_add_dashboard_widget() to register new widget.
 *
 * @see https://developer.wordpress.org/reference/functions/wp_add_dashboard_widget/
 */
function my_dashboard_widgets() {
	wp_add_dashboard_widget( 'my_dashboard_widget_id', esc_html__( 'The Widget Name', 'text-domain' ), 'my_dashboard_widget' );
}
add_action( 'wp_dashboard_setup', 'my_dashboard_widgets' );

/**
 * Function to echo widget content.
 */
function my_dashboard_widget() {
	esc_html_e( 'This is some text inside the widget area.', 'text-domain' );
}
```

**Comment by stevenlinx** [comment]
I wonder if this sub-page should just be deleted.

As you said, there are already 5 examples on the parent page.

**Comment by stevenlinx** [comment]
Since no one chimed in, so I deleted the empty page.

**Comment by smileBeda** [comment]
Makes sense for me too.

Thanks!

**Comment by stevenlinx** [comment]
> Can be neglected?

I assume yes.

If a web page throws 404 status, SEs will update its index accordingly to reflect the status change (i.e. removing from its index).

**Comment by smileBeda** [comment]
Yeah... that is the ideal world
In reality I have observed how Google keeps showing results that are not just 404 but actual part of totally gone domains. Since 2 years meanwhile I am trying to get those results off the web (inclusive attempting to use Google Console/Search tools to get it removed...)

But I would guess for a site like WP, with thousands of _valid_ results, one 404 won't hurt (To pass link juice _and_ please the relatively dumb SE algorithms, the best I found was to use 301's)
But really, a nuisance.

Closing.
