### ISSUE TITLE
Contributor Day - 25th October, 2022

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#527]
## Welcome to the WordPress Documentation team's Contributor Day 

You can join us via [Zoom](https://us02web.zoom.us/j/88088421252?pwd=cnlRSW84YjlwdjRtYStnVXZnV0Vwdz09) on 25th October, between 10AM UTC and 8PM UTC.

## New contributors

If this is your first time contributing to the Documentation team, please make sure you have following accounts:
- [WordPress.org account](https://login.wordpress.org/register).
- [WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
- [GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).

Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :) 

Following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:
- [General overview](https://wordpress.tv/2022/06/21/milana-cap-overview-onboarding-for-wordpress-documentation-team/)
- [End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
- [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Everyone

When you find issue you'd like to work on, please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue.

**If you attend this Contributor Day, please comment below with your WordPress.org username.** 

---------------------------------------------------------------------------------------------------------------------------------------------------------------

### 1. Updating block editor end user documentation 
- 6.1 - [high priority](https://github.com/orgs/WordPress/projects/45/views/11)
- 6.1 - [normal priority](https://github.com/orgs/WordPress/projects/45/views/2)
- 6.0 - [updating existing docs](https://github.com/orgs/WordPress/projects/28/views/11)
- 6.0 - [creating new docs](https://github.com/orgs/WordPress/projects/28/views/13)

Person to go ask for help: @femkreations, @zzap, @colorful-tones, @samxmunoz, @Leonardus-Nugraha  

### 2. Content review for older documentation 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/388
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/373
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/372
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/475
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/473
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/472
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/471
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/470
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/469
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/458
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/457
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/455
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/452
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/443
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/442
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/438
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/432
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/429
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/428
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/426 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/425
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/424
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/420
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/418
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/371
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/192
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/190

Person to go ask for help: @estelaris, @zzap 

### 3. Rewriting articles that will move to new, Advanced Administration handbook 
- [Advanced administration handbook issues](https://github.com/zzap/WordPress-Advanced-administration-handbook/issues)

Person to go ask for help: @zzap

**Comment by Leonardus-Nugraha** [comment]
I'll join, although won't be for the whole 10 hours
WP: @leonnugraha

**Comment by Leonardus-Nugraha** [comment]
I'll join, although won't be for the whole 10 hours.
WP: leonnugraha

**Comment by ejpadero** [comment]
WordPress.org username: @barn2support
Thank you.

**Comment by nullbytes** [comment]
:wave: w.org: nullbyte

**Comment by ivahyael** [comment]
Joining too! 👋🏼 

wordpress: @ivahyael

**Comment by ivah-y** [comment]
Joining too! 👋 

WordPress: @ivahyael

**Comment by actual-saurabh** [comment]
WP.org username **saurabhshukla**

**Comment by Alireza-Naji** [comment]
.wordpress.org/gwmorteza

**Comment by ravahdati** [comment]
wordpress.org/vadatiertebat

**Comment by tahmid-ul** [comment]
WordPress.org username: tahmidulkarim

**Comment by nielslange** [comment]
Count me in! w.org: nielslange

**Comment by Ignasrimkunas** [comment]
WP.org: wigno

**Comment by ninthcoder** [comment]
wordpress.org username: ninthcoder

**Comment by jhimross** [comment]
WordPress.org 
Username: jhimross

**Comment by jennimckinnon** [comment]
👋 wp.org: @ninianepress

**Comment by kraftner** [comment]
wp.org: [kraftner](https://profile.wordpress.org/kraftner)

**Comment by carolinan** [comment]
wp.org: poena

**Comment by samxmunoz** [comment]
wp.org: [@samanthaxmunoz](https://profiles.wordpress.org/samanthaxmunoz) ❤️
