### ISSUE TITLE
SSL on reverse proxy code example update

### ISSUE THREAD

**Issue by ethanclevenger91** [WordPress/Documentation-Issue-Tracker#528]
## Issue Description
The code example currently on this page will throw PHP notices when running WP-CLI commands, potentially in other situations in which `wp-config.php` is loaded outside the context of a normal web request, or when the request is missing expected headers.

## URL of the Page with the Issue
https://wordpress.org/support/article/administration-over-ssl/

## Section of Page with the issue
The Reverse Proxy example

## Why is this a problem?
PHP notices are noisy.

## Suggested Fix
```
if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)
$_SERVER['HTTPS']='on';
```

Should become...

```
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)
$_SERVER['HTTPS']='on';
```

Personally, I'd also add curly braces, but I would ultimately defer that decision to core's code style guide. Not sure what the policy is without looking.

**Comment by stevenlinx** [comment]
Thank you for filing.

Yes, according to the coding standard, you do need curly braces for control structures.
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#brace-style

I've made the revision.
