### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Organizing Theme Files" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#536]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/basics/organizing-theme-files/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="684" alt="Screenshot 2022-10-25 at 19 52 57" src="https://user-images.githubusercontent.com/3323310/197778017-dacc2777-51f1-47af-8c40-8a6cb3464a2d.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/basics/organizing-theme-files/

## Section of Page with the issue

- [x] [Theme folder and file structure](https://developer.wordpress.org/themes/basics/organizing-theme-files/#theme-folder-and-file-structure)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by carolinan** [comment]
Fixed

**Comment by nielslange** [comment]
Closing this issue as the code snippet had been formatted: https://developer.wordpress.org/themes/basics/organizing-theme-files/
