### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Attachment Template Files" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#541]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/template-files-section/attachment-template-files/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="681" alt="Screenshot 2022-10-25 at 20 10 28" src="https://user-images.githubusercontent.com/3323310/197781827-b2b47a13-6e03-4c07-bc70-df4ab70b8b5c.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/template-files-section/attachment-template-files/

## Section of Page with the issue

- [ ] [Attachment.php](https://developer.wordpress.org/themes/template-files-section/attachment-template-files/#attachment-php)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by carolinan** [comment]
Fixed.

**Comment by nielslange** [comment]
Closing this as the formatting had been corrected: https://developer.wordpress.org/themes/template-files-section/attachment-template-files/
