### ISSUE TITLE
Dashboard versus Administration Panel

### ISSUE THREAD

**Issue by TukuToi** [WordPress/Documentation-Issue-Tracker#56]
## Issue Description
I could not help but notice that often `Dashboard` and `Administration Panel` are used interchangeably.
I _think_ it would be better to stick to one - and I _think_ `Dashboard` is the adequate terms since there is a reference to that in the WP Admin Area, while there is no `Administration Panel`.

## URL of the Page with the Issue
I noticed this here https://wordpress.org/support/article/writing-posts/ but it (most likely) also happens elsewhere.

## Section of Page with the issue
See `Log in to your WordPress Administration Screen (Dashboard).`. Later, only `Administration Panel` is used, however.

## Why is this a problem?
It is not consistent. Specially for a beginner, which is for whom those docs are intended, it is very important to have a reference to things that _exist_ in front of their eyes, so - a `Dashboard` is clear because there is a link/menu item in the WP Admin Area called `Dashboard`. But there is no where an `Administration Panel`.
This could be anything. It could be a single screen, the settings screen, the Dashboard...

## Suggested Fix
Agree on one term and use one term only.

**Comment by atachibana** [comment]
@TukuToi 

Thank you for the comment.
There is some confusion in the definitions associated with "dashboard".

Administration Screen
https://wordpress.org/support/article/administration-screens/

Dashboard Screen
https://wordpress.org/support/article/dashboard-screen/

Dashboard points the top page of Administration Screen(s) in WordPress. So, in this context, Administration Screen is the correct term.
The 'panel' is an archaic name for 'screen'. So, all 'Administration Panel' should be renamed to 'Administration Screen'. I modified every 'panel' with 'screen'.
