### ISSUE TITLE
[HelpHub] How to Use the Preview Function

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#561]
Article: https://wordpress.org/support/article/how-to-use-the-preview-function/

## Update for 6.1

Update this page to show the toolbar with the View button instead of the Preview

**Comment by femkreations** [comment]
Here is the page https://wordpress.org/support/wp-admin/post.php?post=16133271&action=edit
Set for Publish on Nov 1st.
Updated screenshots and content for 6.1.
Added info for Site Editor
Added ALT tags for the images
Added video to show the feature

**Comment by jennimckinnon** [comment]
@femkreations Reviewed this article, and I suggest these edits:

1. Change "It is used to preview what your post/page or the site you are currently working on, looks like with the current changes applied" to "It's used to preview what your post, page, or site looks like with the current changes applied."
<img width="868" alt="image" src="https://user-images.githubusercontent.com/9810898/197864553-5917e87d-7770-437d-b4ae-1020d9292357.png">

2. Some minor edits to the second paragraph
<img width="858" alt="image" src="https://user-images.githubusercontent.com/9810898/197869296-79ffcc84-5123-452c-ba7a-190ff9baf3f8.png">

- "to have a draft of the post/page you are working on" change to "to keep your changes to the draft of the post or page you're working on"
- "post/page" change to "post or page"
- "you are" change to "you're" a couple times
- "your Site Editor" change to "the Site Editor"
- "save your site and the templates you are working on" change to "keep the changes you made to your site and the templates you're working on"

3. Minor sentence edits
<img width="858" alt="image" src="https://user-images.githubusercontent.com/9810898/197867127-cae2fc32-54e1-45e9-aae1-3be8c0a6f170.png">

- "with the various options to view the preview of the page/post or site as shown below" change to "with various options to preview the page, post, or site as shown below"

4. Change "You will see how the page/post or your site will look on the desktop" to "You can preview how your page, post, or site will look on a desktop screen"

<img width="858" alt="image" src="https://user-images.githubusercontent.com/9810898/197867755-b2c5cd9c-0478-47fd-b683-3a3251aba178.png">

**Comment by femkreations** [comment]
All updates made. Thanks @jennimckinnon for catching them.
