### ISSUE TITLE
Commercial Link on Theme Hierarchy page

### ISSUE THREAD

**Issue by bph** [WordPress/Documentation-Issue-Tracker#562]
@AndrewJDFerguson posted this on the Dev Blog theme repo: 
_Not sure if this is the correct place to add this issue, but neither is having a commercial link buried in content on the developer.wordpress.org.

If you view https://developer.wordpress.org/themes/basics/template-hierarchy/#visual-overview you will notice a link "You can also [interact with this diagram](http://wphierarchy.com/)." The link is to wphierarchy.com, and following that link ultimately takes you to https://wpshout.com/wordpress-template-hierarchy/. WPShout appears to be all about getting you to sign up for their paid course, and while there may be some content relevant to the content on the developer.wordpress.org page, it is, in my view, of very little value.

Should this link be there? I think not."_

And shared this screenshot
![193088829-e6faca8f-b080-4651-bff6-92424ba4426e](https://user-images.githubusercontent.com/39980/198060939-b196163b-8f97-4493-85f0-3bd46806a36c.png)

**Comment by carolinan** [comment]
Who created the original diagram? I mean who is it copyrighted to and what is the license?

**Comment by carolinan** [comment]
OK I found the following details in their blog post: "We won’t be including this in Resources, because it was created by the lovely Michelle Schulp, not us:"

@marketimedia Was this resource created for the wordpress.org documentation? Then I think we should remove the link to wpshout as soon as possible.

**Comment by carolinan** [comment]
Let me ping Michelle with the correct username @marktimemedia 😊

**Comment by kafleg** [comment]
Can I remove that link?

**Comment by kafleg** [comment]
Link is now removed.

**Comment by marktimemedia** [comment]
Yeah, I created the static graphic a while ago. There used to be an actual interactive one (that I did not create) at wphierarchy.com, looks like that domain expired and was bought by WPShout.
