### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#565]
In #531, I recently double-checked and corrected all code snippets of the theme handbook. This issue aims to collect all incorrect formatted code snippets that appear within the plugin handbook.

## Incorrect formatted code snippets

An incorrect formatted code snippet is a code snippet that currently has no format, is using a wrong indentation or has some other kind of formatting issue. Here's an example of such a code snippet that does not have formatting and wrong indention:

<img width="665" alt="Screenshot 2022-11-05 at 11 29 12" src="https://user-images.githubusercontent.com/3323310/200100818-316aca0c-6e5e-4bb1-90ed-9be76921a6c4.png">

### Affected pages

- [x] #566
- [x] #567
- [x] #568
- [x] #569
- [x] #570
- [x] #571
- [x] #572
- [x] #573
- [x] #574
- [x] #575
- [x] #576
- [x] #577
- [x] #578
- [x] #579
- [x] #580
- [x] #581
- [x] #582
- [x] #583
- [x] #584
- [x] #585
- [x] #586
- [x] #587
- [x] #588
- [x] #589
- [x] #590
- [x] #591
- [x] #592
- [x] #593
- [x] #594
- [x] #595
- [x] #596
- [x] #597
- [x] #598
- [x] #599
- [x] #600
- [x] #601
- [x] #602
- [x] #603
- [x] #604
- [x] #605
- [x] #606
- [x] #607
- [x] #608
- [x] #609
- [x] #610
- [x] #611

### Potential cause and fix

These code snippets might have been created before the existence of the Code Syntax Block. Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by theMikeD** [comment]
This irritates me because I already did this. Now when I log in I see this:

![Screen Shot 2022-11-05 at 11 49 40 AM](https://user-images.githubusercontent.com/423907/200128461-ce7b041b-797e-4d0d-a777-701e2e080c92.jpg)

Why did this happen? The problem goes away if this block is restored.

**Comment by Kenshino** [comment]
Please don't continue on this ticket - let me speak to the Meta team first to see if we can find an automated way to deal with this

**Comment by Kenshino** [comment]
Likely related change that made this happen -> https://github.com/WordPress/wporg-developer/pull/44

**Comment by dd32** [comment]
I've migrated the blocks over, and gone through all the above issues.

I've closed them as I've verified the page content was correct, and manually converted a few code blocks that were left.

There's 3 issues left that need manual editing of the content, as the issue wasn't the syntaxhighlighter block.

**Comment by theMikeD** [comment]
The last item is now done, so I'm closing this issue.
