### ISSUE TITLE
Plugin Handbook page ordered list is missing a chapter, has wrong numbers, and uses inconsistent terminology

### ISSUE THREAD

**Issue by paulshryock** [WordPress/Documentation-Issue-Tracker#57]
## Issue Description
The [Plugin Handbook page](https://developer.wordpress.org/plugins/) describes the table of contents in an ordered list.

1. It appears that the **Privacy** chapter was added to the table of contents after this page was written. It is missing.
2. Some of the chapter (or "section") numbers mentioned in the list are incorrect.
3. There is inconsistent terminology used: The table of contents list in the left sidebar column is labeled **Chapters**, while the main content's ordered list refers to "sections".

<img width="936" alt="Screenshot of the Plugin Handbook page showing the main ordered list and part of the table of contents" src="https://user-images.githubusercontent.com/7530507/138471382-da40e621-d264-4393-9b75-d2254268c255.png">

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/

## Section of Page with the issue
The main content ordered list

## Why is this a problem?
The **Privacy** chapter is omitted from the list. Readers are given incorrect section numbers compared to what is in the **Chapters** list in the left hand sidebar. They also might not realize that "sections" are the same as chapters.

All of these issues could be confusing, or could make it slightly harder to find information than it needs to be.

## Suggested Fix
After list item number 3, a list item should be added mentioning the **Privacy** chapter. Beginning with ordered list item number 4, all of the "sections" mentioned should be incremented by 1. "Sections" should be referred to as chapters.

The entire ordered list should read like this (changes are in **bold**, notes are _italicized in parenthesis_):

1. If you’re new to plugin development, start by reading the introduction and then move on to the basics.
2. **Chapter** 3 will introduce you to plugin security.
3. Hooks are what make your plugin interact with WordPress. Learn all about them in **chapter** 4.
4. **You can learn about Privacy best practices in chapter 5.** _(This is my own wording, but should be changed to whatever makes sense--this was just an example.)_
5. To find out more about WordPress’ built-in functionality that you can use in your plugin, check out **chapters 6 – 12**: administration menus, shortcodes, settings, metadata, custom post types, taxonomies, and users.
6. Learn about getting data using the HTTP API in **chapter 13**.
7. If you’re using JavaScript, jQuery or Ajax in your plugin, you’ll find the information you need in **chapter 14**.
8. To learn about time-based WordPress tasks using Cron, check out **chapter 15**.
9. **Chapters 16-18** will introduce you to internationalizing your plugin, preparing it for release on WordPress.org, and some developer tools you might find useful.

**Comment by juanmaguitar** [comment]
@theMikeD I would like to understand how these changes are done. 
Could you provide a summary of how these changes have been applied once you do them? 
Thanks in advance!

**Comment by paulshryock** [comment]
Gonna go out on a limb here and guess that site content is managed in WordPress?

**Comment by theMikeD** [comment]
Yes it's managed in WordPress :) Once I get this fixed I'll summarize here.

**Comment by theMikeD** [comment]
This is done, although referring to chapter numbers has been removed since no chapter has numbers in this handbook.
