### ISSUE TITLE
Typo in link destination

### ISSUE THREAD

**Issue by sahilrajthapa** [WordPress/Documentation-Issue-Tracker#59]
## Issue Description
There is a typo in the link destination.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/

## Section of Page with the issue
Introduction to Taxonomies 

## Why is this a problem?
Currently in the introduction to taxonomies section, there is a link to taxonomies page. But the link returns page not found.

## Suggested Fix
https://developer.wordpress.org/plugins/taxonomy/ should be replaced by https://developer.wordpress.org/plugins/taxonomies/

**Comment by stevenlin-x** [comment]
I've fixed it.
