### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Custom Settings Page" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#590]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/settings/custom-settings-page/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="675" alt="Screenshot 2022-11-05 at 13 51 55" src="https://user-images.githubusercontent.com/3323310/200106894-b0b02c4c-7b4d-466e-905a-18b3478ae19b.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/settings/custom-settings-page/

## Section of Page with the issue

- [ ] https://developer.wordpress.org/plugins/settings/custom-settings-page/

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by dd32** [comment]
See https://github.com/WordPress/wporg-developer/pull/152 to auto-expand this code block.

Markup fixed.
