### ISSUE TITLE
Using Caddy to Give WordPress Its Own Directory

### ISSUE THREAD

**Issue by basilhendroff** [WordPress/Documentation-Issue-Tracker#6]
### Source article
[Giving WordPress Its Own Directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)
### The problem I'm having
The article is Apache-centric and doesn't support other webservers. It's an important article as it's referenced from the WP General Settings screen.

![wp11](https://user-images.githubusercontent.com/63370329/129828317-0c997af8-c43c-4a4b-ab3a-43fd1b89de2e.jpg)

### Suggested Improvement

Please include a reference to an equivalent article for the Caddy webserver e.g.

> See Also #
> 1. [Using Caddy to give WordPress its own directory](https://caddy.community/t/using-caddy-to-give-wordpress-its-own-directory/13185)

### References
1. [Giving WordPress Its Own Directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)
2. [Using Caddy to give WordPress its own directory](https://caddy.community/t/using-caddy-to-give-wordpress-its-own-directory/13185)

**Comment by atachibana** [comment]
Though we have another issue #7 for the same page, just adding the 'see also' must be accepted.
I enhanced your suggestion. Thank you.
We may change this section when we receive another web server info.

**Comment by zzap** [comment]
I'm adding `external links` label and reopening issue so that we can discuss relevance for external resource. For reference see https://github.com/WordPress/Documentation-Issue-Tracker/issues/8#issuecomment-915085945

**Comment by atachibana** [comment]
New repository "Advanced Administration" was created, and this page will be moved to there. Continue the discussion at this issue:
https://github.com/WordPress/Advanced-administration-handbook/issues/106
