### ISSUE TITLE
Navigation Block Support Page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#60]
Need a new page for the navigation block and need to [update the overall blocks page here](https://wordpress.org/support/article/blocks/). This doc needs to include the following:

- Responsive hamburger menu that can be turned always on, on for small screen sizes, or off.
- Note about keyboard accessible.
- Ability to add a wide range of blocks including Search, Site Icon, etc.
- Ability to control design aspects from the font size, font family, color, etc.
- Ability to add sub menu items and set the coloring for them separately.
- Ability to add all pages.
- Ability to change vertical or horizontal alignment.

**Comment by annezazu** [comment]
Whew, finally kicked this off with a very rough draft: https://docs.google.com/document/d/1Em-c8TBubfiFc1XDfldtjq_ifXyAt0rIOJjz6pfmLP4/edit?usp=sharing

Hoping to get something firmer in place this week.

**Comment by annezazu** [comment]
Whew -- been hard at work on this. Here's the public preview: 

https://wordpress.org/support/?p=15191692&post_type=helphub_article&preview=1&_ppp=f1d83cdb26

Thanks to anoopd for the various videos! @carolinan in case you can review or @zzap  :) Going to schedule for January 25, 2022 for now as it's full of info and definitely covers the basics.

**Comment by TeBenachi** [comment]
Thank you for putting together the navigation doc. It is very helpful 📚
I thought it might be handy to have additional info on the spacer block and the order of menu links. 

### Spacer block
Under the [additional menu items section](https://wordpress.org/support/?p=15191692&post_type=helphub_article&preview=1&_ppp=f1d83cdb26#add-additional-menu-items), I think it would be useful to have additional info on how to turn the menu items into the spacer block.

To transform a menu item into a spacer block, a menu item need to be converted to a link first, then transform into a spacer block.


https://user-images.githubusercontent.com/30734209/147462484-724ba5e3-1d6e-4355-90d8-565ea090c0bb.mov


### New menu item when using Add all pages option
Under the [Add all pages section](https://wordpress.org/support/?p=15191692&post_type=helphub_article&preview=1&_ppp=f1d83cdb26#add-all-pages), it would be nice to mention that a new menu item will be added automatically when a new page is created. 

### Changing the order of menu links

Under the [Move blocks section](https://wordpress.org/support/?p=15191692&post_type=helphub_article&preview=1&_ppp=f1d83cdb26#move-blocks), I had a little trouble figuring out how to re-arrange the menu items when the “Add All Pages” option and individual “Add Link” option (by adding additional links using “+” button) are together in one navigation. 

In this below screencast, I tried to move the Brisket (created by using an individual “Add Link” option) to between Vegetables and Bakery links (both are created using “Add All Pages” option). It was not possible to move the Brisket  anywhere between the “Add All Pages” group menu items. 

https://user-images.githubusercontent.com/30734209/147462804-f3ff55b9-851b-4a68-acdc-547eeb3f949a.mov

To accomplish this, 

1. First, convert the menu items (group items) to links by selecting Edit
2. Popup appears. Click Convert 
3. Then menu items can be re-arranged in any order


https://user-images.githubusercontent.com/30734209/147462915-6cf4e6ce-0186-4d2b-ac9e-2426782ac88d.mov



Thank you!

**Comment by annezazu** [comment]
Excellent feedback! Thanks so much for reviewing. I just updated the following based on what you shared:
- Added a new section called: "Transform menu items into other blocks"
- Edited the all pages option to include that new pages will automatically be added and instructions to convert to links. 
- Added a note to the Move Block section about needing to convert to links with a link to the above steps. 

Let me know if it looks better now :)

**Comment by TeBenachi** [comment]
Looks great! Thank you so much for updating!!

**Comment by annezazu** [comment]
Closing this out for now since it's scheduled and ready to go.

**Comment by annezazu** [comment]
Going to ship today in [light of this convo in slack](https://wordpress.slack.com/archives/C02RP4WU5/p1641317048292100) where current links in 5.9 RC1 are broken because these are not published.

**Comment by annezazu** [comment]
To loop back on next week... :) Will update the doc accordingly. 

> One thing that stood out to me was lack of info about how to delete the underlying Navigation Menu itself. THat’s achieved via the Advanced Tab. Is that making things too complex for users in this kind of support doc? It just seemed like the kind of info folks might need.

**Comment by annezazu** [comment]
^ looking back over, I had already included a section!  I renamed it for good measure to "manage menus (delete, rename)" to make it easier to find:

https://wordpress.org/support/article/navigation-block/#manage-menus-delete-rename
