### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Localization" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#609]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/internationalization/localization/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="704" alt="Screenshot 2022-11-05 at 14 59 20" src="https://user-images.githubusercontent.com/3323310/200110012-4f2bb99d-2064-47e9-9b51-bd24563c9a0d.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/internationalization/localization/

## Section of Page with the issue

- [ ] [Using Localizations](https://developer.wordpress.org/plugins/internationalization/localization/#using-localizations)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by theMikeD** [comment]
There's no way to insert a code block into an unordered list block, so I move the "code" into an include mono like the rest of the items in this section.
