### ISSUE TITLE
Document new 6.1 spacing presets

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#613]
WordPress 6.1 introduced new spacing sizes and scale supports for theme authors.  We need to document these under the `theme.json` spacing settings section: https://developer.wordpress.org/themes/advanced-topics/theme-json/#spacing

New features include:

- `customSpacingSize`
- `spacingScale`
- `spacingSizes`

Thinking about this on a larger scale, I also wouldn't mind showing the use of these presets within the styles section so that there's a continuation of what a theme author learned earlier.

For example, in the example used down the page:

```json
{ 
	"styles": {
		"margin": {
			"top": "var( --wp--preset--spacing--80 )"
		}
	}
}
```

**Comment by carolinan** [comment]
I am still confused about the spacing presets, and I think the only actual documentation written for them are in the GitHub issues, so adding this is badly needed.

I recently wrote about it here, but I think we can do better, especially the custom spacing scale was difficult to explain:
https://fullsiteediting.com/lessons/theme-json-layout-and-spacing-options/#h-spacing-presets

I am hesitant to include default values for the presets, like this because frankly I do not trust that it will remain these values, because right now there is work to change the font size scale, and I think that the spacing will go through similar changes.

<html>
<body>


–wp–preset–spacing–20 | 0.44rem | 2X-Small
-- | -- | --



</body>
</html>

**Comment by justintadlock** [comment]
> I am still confused about the spacing presets, and I think the only actual documentation written for them are in the GitHub issues, so adding this is badly needed.

Yeah, I had some internal notes on how confusing this was when I first started tinkering with it.  I'm on a couple of other projects, but I definitely want to flesh out some solid docs for this.  So, if no one beats me to this in the next week or two, I can have something ready for review.

> I am hesitant to include default values for the presets, like this table below, because frankly I do not trust that it will remain these values, because right now there is work to change the font size scale, and I think that the spacing will go through similar changes.

Good point.

**Comment by justintadlock** [comment]
Assigning this to myself.  I should have something for review tomorrow.

**Comment by justintadlock** [comment]
Here is the new content to be appended to the `theme.json` page's [spacing section](https://developer.wordpress.org/themes/advanced-topics/theme-json/#spacing).  Some notes:

1. I could really use some technical feedback on the "Custom Spacing Scale" sub-section.  It's tough to concisely explain how `spacingScale` works, and I'd like to keep this as simple as possible.
2. Should we also have a section that explains the default spacing scale that WordPress generates?

---

**Custom Spacing Scale:**

WordPress allows theme authors to create a custom spacing scale by providing a set of configuration instructions for generating it.  When generated, each step in the scale creates a custom CSS property with the slug of `--wp--preset--spacing--{step}` (steps appear in increments of 10, regardless of their value).

The `spacingScale` object has five sub-settings that themes can configure:

- **operator:** The operator used to increment the scale.  The available options are `+` (addition) and `*` (multiplication).  The default value is `*`.
- **increment:** A number in which to increment the scale by when used in conjunction with the `operator` setting.  The default value is `1.5`.
- **steps:** The total number of steps in the scale. The default value is `7`.
- **mediumStep:** The medium value of the scale.  The default value is `1.5`.
- **unit:** A valid CSS spacing unit. The available options are `px`, `em`, `rem`, `vh`, `vw`, and `%`.  The default value is `rem`.

The following example is a custom scale with five steps that increments by `0.25rem`:

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"spacingScale": {
				"operator": "+",
				"increment": 0.25,
				"steps": 5,
				"mediumStep": 0.75,
				"unit": "rem"
			}
		}
	}
}
```

_Note #1:_ The `mediumStep` value is always assigned to the `--wp--preset--spacing--50` preset when WordPress generates the CSS, and the other preset slugs in the scale extend up/down from this middle number in increments of `10`.

_Note #2:_ The spacing scale will never go below `--wp--preset--spacing--10`.  For scales with more than 10 steps, the bottom end of the scale will not generate presets because the `mediumStep` is always set to `--wp--preset--spacing--50`.

**Custom Spacing Sizes:**

For theme authors who want more precise control over the spacing options available to users, they can build out the individual spacing sizes instead of using the WordPress spacing scale system.  This provides control over the option's name, size, and slug.

The `spacingSizes` option allows themes to define an array of size objects.  Each size object accepts three values:

- **name:** The human-readable title for the size, which can be translated.
- **size:** A valid CSS size.  This can be a number and unit, a fluid size using `clamp()`, or a reference to another custom CSS property.
- **slug:** The slug for the size, which will be appended to a generated CSS custom property: `--wp--preset--spacing--{slug}`.

The following example is an example of creating a five-step scale that increments by `0.25rem`.  However, theme authors are not limited in how they set up their sizes.

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"spacingSizes": [
				{
					"name": "Step 1",
					"size": "0.25rem",
					"slug": "10"
				},
				{
					"name": "Step 2",
					"size": "0.5rem",
					"slug": "20"
				},
				{
					"name": "Step 3",
					"size": "0.75rem",
					"slug": "30"
				},
				{
					"name": "Step 4",
					"size": "1rem",
					"slug": "30"
				},
				{
					"name": "Step 5",
					"size": "1.25rem",
					"slug": "50"
				}
			]
		}
	}
}
```

For theme authors who want to implement fluid spacing sizes, they should use the `spacingSizes` setting instead of `spacingScale`.  This allows for the use of custom `clamp()` values.

**Disabling Custom Sizes:**

Theme authors can force users into using the standardized scale set by the theme.  To do this, they must set the `customSpacingSize` setting to `false` (defaults to `true`).  This disables the custom spacing option in the editor UI but leaves the control for the theme's defined sizes available.

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"customSpacingSize": false
		}
	}
}
```

**Comment by carolinan** [comment]
>Should we also have a section that explains the default spacing scale that WordPress generates?
I think there should be an introduction about what the spacing scale is. It can be confusing to jump directly to "custom" spacing scale.
There should also be information about disabling the default spacing scale.

**Comment by carolinan** [comment]
Pinging @glendaviesnz for help with technical review of the theme.json spacing scale documentation.

**Comment by glendaviesnz** [comment]
I added some documentation here https://github.com/WordPress/gutenberg/pull/43349/files - but it is a bit hidden under the [how-to guide](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#presets) - get back to me if you are still unclear about anything after checking through that.

**Comment by justintadlock** [comment]
> I think there should be an introduction about what the spacing scale is. It can be confusing to jump directly to "custom" spacing scale.

Thanks, @poena.  I'll get an intro added in.

**Comment by justintadlock** [comment]
Sorry for getting back to this so late.  I got caught up with other projects.  Anyway, the below is an updated version of this with an included intro of the spacing scale that WordPress has by default.

@carolinan - I borrowed from the table you already put together.

---

**Spacing Scale:**

WordPress generates custom spacing scale by default.  Users can select these options for blocks that support margin, padding, and block gap via the editor UI.  The default scale has seven steps, as shown in the following table:

| CSS Custom Property     | CSS Value | Label    |
| ----------------------- | --------- | -------- |
| `–wp–preset–spacing–20` | `0.44rem` | 2X-Small |
| `–wp–preset–spacing–30` | `0.67rem` | X-Small  |
| `–wp–preset–spacing–40` | `1rem`    | Small    |
| `–wp–preset–spacing–50` | `1.5rem`  | Medium   |
| `–wp–preset–spacing–60` | `2.25rem` | Large    |
| `–wp–preset–spacing–70` | `3.38rem` | X-Large  |
| `–wp–preset–spacing–80` | `5.06rem` | 2X-Large |

Theme authors can use the custom properties to define default margin, padding, or block gap styles via `theme.json`. The following code shows how to set the top and bottom margin for the core Heading block:

```json
{
	"version": 2,
	"styles": {
		"blocks": {
			"core/heading": {
				"spacing": {
					"margin": {
						"top": "var( --wp--preset--spacing--60 )",
						"bottom": "var( --wp--preset--spacing--40 )"
					}
				}
			}
		}
	}
}
```

**Custom Spacing Scale:**

WordPress allows theme authors to create a custom spacing scale by providing a set of configuration instructions for generating it.  When generated, each step in the scale creates a custom CSS property with the slug of `--wp--preset--spacing--{step}` (steps appear in increments of 10, regardless of their value).

The `spacingScale` object has five sub-settings that themes can configure:

- **operator:** The operator used to increment the scale.  The available options are `+` (addition) and `*` (multiplication).  The default value is `*`.
- **increment:** A number in which to increment the scale by when used in conjunction with the `operator` setting.  The default value is `1.5`.
- **steps:** The total number of steps in the scale. The default value is `7`.
- **mediumStep:** The medium value of the scale.  The default value is `1.5`.
- **unit:** A valid CSS spacing unit. The available options are `px`, `em`, `rem`, `vh`, `vw`, and `%`.  The default value is `rem`.

The following example is a custom scale with five steps that increments by `0.25rem`:

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"spacingScale": {
				"operator": "+",
				"increment": 0.25,
				"steps": 5,
				"mediumStep": 0.75,
				"unit": "rem"
			}
		}
	}
}
```

_Note #1:_ The `mediumStep` value is always assigned to the `--wp--preset--spacing--50` preset when WordPress generates the CSS, and the other preset slugs in the scale extend up/down from this middle number in increments of `10`.

_Note #2:_ The spacing scale will never go below `--wp--preset--spacing--10`.  For scales with more than 10 steps, the bottom end of the scale will not generate presets because the `mediumStep` is always set to `--wp--preset--spacing--50`.

**Custom Spacing Sizes:**

For theme authors who want more precise control over the spacing options available to users, they can build out the individual spacing sizes instead of using the WordPress spacing scale system.  This provides control over the option's name, size, and slug.

The `spacingSizes` option allows themes to define an array of size objects.  Each size object accepts three values:

- **name:** The human-readable title for the size, which can be translated.
- **size:** A valid CSS size.  This can be a number and unit, a fluid size using `clamp()`, or a reference to another custom CSS property.
- **slug:** The slug for the size, which will be appended to a generated CSS custom property: `--wp--preset--spacing--{slug}`.

The following example is an example of creating a five-step scale that increments by `0.25rem`.  However, theme authors are not limited in how they set up their sizes.

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"spacingSizes": [
				{
					"name": "Step 1",
					"size": "0.25rem",
					"slug": "10"
				},
				{
					"name": "Step 2",
					"size": "0.5rem",
					"slug": "20"
				},
				{
					"name": "Step 3",
					"size": "0.75rem",
					"slug": "30"
				},
				{
					"name": "Step 4",
					"size": "1rem",
					"slug": "40"
				},
				{
					"name": "Step 5",
					"size": "1.25rem",
					"slug": "50"
				}
			]
		}
	}
}
```

For theme authors who want to implement fluid spacing sizes, they should use the `spacingSizes` setting instead of `spacingScale`.  This allows for the use of custom `clamp()` values.

**Disabling Custom Sizes:**

Theme authors can force users into using the standardized scale set by the theme.  To do this, they must set the `customSpacingSize` setting to `false` (defaults to `true`).  This disables the custom spacing option in the editor UI but leaves the control for the theme's defined sizes available.

```json
{
	"version": 2,
	"settings": {
		"spacing": {
			"customSpacingSize": false
		}
	}
}
```

**Comment by carolinan** [comment]
Looks good to me and I have confirmed that the values in the table are still correct.

**Comment by justintadlock** [comment]
Updated the handbook with the new information.
