### ISSUE TITLE
Theme handbook: Catalog and Update code examples with block markup to use 6.2 markup across the Theme Handbook.

### ISSUE THREAD

**Issue by carolinan** [WordPress/Documentation-Issue-Tracker#617]
## Issue Description

The markup for the group block, column, post content, quote, lists and gallery has changed and where any of these are included in code examples it would be good to update examples.

## Why is this a problem?

Readers may be copying examples that are out of date.

**Comment by DaisyOlsen** [comment]
I'd love to take ownership of this. Let me know if anyone has already put any effort in here cc: @carolinan

**Comment by carolinan** [comment]
I don't think anyone has started.

It would be _nice to have_  a list of documents that has these code examples, for next time they need to be updated.

**Comment by DaisyOlsen** [comment]
That's a great idea @carolinan, thanks for the suggestion, I'll try to make that a part of my process since there will be some digging to find all the examples anyway :-)

**Comment by carolinan** [comment]
We should prepare and update this to use 6.2 markup not 6.1...

**Comment by DaisyOlsen** [comment]
That makes perfect sense!

**Comment by DaisyOlsen** [comment]
THanks so much for doing this @justintadlock If you like, I can take the next action of identifying the 6.2 Markup and putting updated examples in comments here for easy access when we get a bit closer to launch.

**Comment by DaisyOlsen** [comment]
Regarding [How to create template parts with code](https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/#how-to-create-template-parts-with-code)

**Code example for step 1:**

```
<!-- wp:group {"backgroundColor":"vivid-cyan-blue","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-vivid-cyan-blue-background-color has-background"></div>
<!-- /wp:group -->
```

**Step 2**
I don't think this step is needed.

**Code example for step 3**
No Change

**Code example for step 4**
No Change

**Code example for step 5**

```
<!-- wp:group {"style":{"spacing":{"padding":{"top":"2em","right":"2em","bottom":"2em","left":"2em"}}},"backgroundColor":"vivid-cyan-blue","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-vivid-cyan-blue-background-color has-background" style="padding-top:2em;padding-right:2em;padding-bottom:2em;padding-left:2em"></div>
<!-- /wp:group -->
```

**Comment by DaisyOlsen** [comment]
Should the code example in [Step 2: Register the block pattern](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/#step-2-register-the-block-pattern) be updated to reflect current pattern registration with header meta?

**Comment by DaisyOlsen** [comment]
[Landmark](https://developer.wordpress.org/themes/block-themes/accessibility/#landmark)

```
<!-- wp:group {"tagName":"header","layout":{"type":"constrained"}} -->
<header class="wp-block-group"><!-- wp:site-title /--></header>
<!-- /wp:group -->
```

[Skip to content](https://developer.wordpress.org/themes/block-themes/accessibility/#skip-to-content)
```
<!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} -->
<main class="wp-block-group"><!-- wp:heading -->
<h2 id="hello-world">Hello World</h2>
<p>Welcome to WordPress. This is your first post. </p>
<!-- /wp:heading -->
```

**Comment by justintadlock** [comment]
> Should the code example in [Step 2: Register the block pattern](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/#step-2-register-the-block-pattern) be updated to reflect current pattern registration with header meta?

Good question. I'd prefer the `/patterns` folder method as the primary way of showcasing registering patterns. It's easier to understand and less prone to escaping errors.

**Comment by DaisyOlsen** [comment]
I believe I've gotten everything accounted for in the comments above. I would love some eyes on everything to see if I've missed anything obvious.  The markup isn't changing between 6.1 and 6.2, as far as I can see so I don't think we need to wait for 6.2 to push these changes out.

**Comment by justintadlock** [comment]
@DaisyOlsen I've reviewed the code, and everything looks good to me.

**Comment by carolinan** [comment]
Again when I open the edited pages, all paragraphs are broken and have double p tags. Are they not broken when you open the pages?

**Comment by DaisyOlsen** [comment]
I will look to see what might have happened. It was definitely not like that when I closed it but since it's happened more than once there must be some user error involved.

**Comment by carolinan** [comment]
I do not know which WP or Gutenberg version that is being used.

**Comment by DaisyOlsen** [comment]
OK, I did a bit of digging, and it looks like a markup deprecation problem.

All of the affected blocks appear to have an ID in the opening paragraph tag, but it's not reflected as an anchor in the block attributes.

```HTML
<!-- wp:paragraph --> 
<p id="block-9dfbbdba-24d4-42df-b5ca-44105276e4c8">Please read this support article first if you would like an <a href="https://wordpress.org/support/article/site-editor/">introduction to the Site Editor.</a></p> | Added: <p>Please read this support article first if you would like an <a href="https://wordpress.org/support/article/site-editor/">introduction to the Site Editor.</a></p>
 <!-- /wp:paragraph -->
```

The IDs have been there going way back into the revision history but seem to only recently be causing a problem with saving the content. Anywhere the ID is in the paragraph tag, the extra paragraph tags are added when the content is saved, and then a reload of the edit screen shows the broken blocks.

The fastest solution I can see is to convert the block to classic and then back to paragraph for each broken block. The process takes just a few minutes per post and they are easy to spot when scanning the content.

**Comment by DaisyOlsen** [comment]
I've updated the affected scheduled content. cc @carolinan

**Comment by carolinan** [comment]
Thank you, they are all published now (I updated the date in the changelog).
