### ISSUE TITLE
Template Part Focus Mode Support Page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#62]
Needed for 5.9. Can pull information from this: https://make.wordpress.org/core/2021/11/02/core-editor-improvement-introducing-template-part-focus-mode/ Need to explain that seeing this is dependent on theme in use.

**Comment by carolinan** [comment]
I think there is a need for an article about what a template part is, not only the template part focus mode?

**Comment by annezazu** [comment]
Yes! Agreed: https://github.com/WordPress/Documentation-Issue-Tracker/issues/74

**Comment by annezazu** [comment]
Note that we'll need to ensure this is explained: https://github.com/WordPress/gutenberg/issues/30732

**Comment by annezazu** [comment]
Closing this out since I included a section in https://github.com/WordPress/Documentation-Issue-Tracker/issues/74 dedicated to this :)
