### ISSUE TITLE
Data validation and sanitization on several places

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#622]
## Issue Description
Information about data sanitization and validation can be found on 3 different places: Codex, Themes and Plugins handbooks. There is no difference in sanitizing and validating data in plugins and themes. It's how we do things in WordPress generally when dealing with input/output. This kind of functionality is the reason we have Common APIs handbook and that's where all that data should be moved.

## URL of the Page with the Issue

- Codex: https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data
- Codex: https://codex.wordpress.org/Data_Validation
- Themes: https://developer.wordpress.org/themes/theme-security/
- Plugins: https://developer.wordpress.org/plugins/security/

## Why is this a problem?

Because this info should live in one place. It's the same for all WordPress developers.

## Suggested Fix
- [x] Review all the info we currently have, from all 3 places. 
- [x] Keep content that is up to date, remove outdated and add new if applicable. 
- [x] Create meaningful new page or pages in Common APIs for it. 
- [x] Remove duplicates from Theme and Plugins handbooks, keep what's unique for both. Do NOT delete pages.
- [x] Link from Themes and Plugins handbooks to newly created Common APIs page(s).
- [x] Retire Codex page - by removing complete content and adding link to a newly created Common APIs page(s).

**Comment by theMikeD** [comment]
@zzap has created a hope for this in the API handbook. I'll do the consolidation there directly and advise when it's done.

**Comment by theMikeD** [comment]
New structure:

```
Security
	Sanitizing
	Validating
	Escaping
	Nonces
	User Capabilities
	Common vulnerabilities
```

**Comment by theMikeD** [comment]
Plugin pages are copied and slightly tweaked. The "Common Vulnerabilities" from the theme handbook has been copied and blockified.

To do integrate the theme handbook and codex docs into the new structure, while stealing heavily from VIP pages on these topics.

**Comment by theMikeD** [comment]
@zzap is the goal to replace this page too?
https://codex.wordpress.org/Data_Validation

**Comment by zzap** [comment]
> @zzap is the goal to replace this page too? https://codex.wordpress.org/Data_Validation

Yes, that's all common, even though themes don't do much of validating (or at least we advise them not to) but that's still common practice throughout WordPress development.

**Comment by theMikeD** [comment]
[The main Security page](https://developer.wordpress.org/apis/security/) is done, along with [Sanitizing](https://developer.wordpress.org/apis/security/sanitizing/), [Validating](https://developer.wordpress.org/apis/security/data-validation/), and [Escaping](https://developer.wordpress.org/apis/security/escaping/) pages are done. And I will say for the record that the "new" code block looks terrible.

**Comment by theMikeD** [comment]
Nonces is done, and is tracked in [623](https://github.com/WordPress/Documentation-Issue-Tracker/issues/623)

**Comment by theMikeD** [comment]
Source files attached.

[Validating Data.md](https://github.com/WordPress/Documentation-Issue-Tracker/files/10147534/Validating.Data.md)
[Sanitizing Data.md](https://github.com/WordPress/Documentation-Issue-Tracker/files/10147535/Sanitizing.Data.md)
[Escaping Data.md](https://github.com/WordPress/Documentation-Issue-Tracker/files/10147536/Escaping.Data.md)

**Comment by theMikeD** [comment]
The Theme and Plugin handbook pages for validation, sanitization and escaping have been updated with references to teh API handbook.

I can't edit the Codex pages so @zzap can you do those for me please?

**Comment by zzap** [comment]
Thank you @theMikeD for working on it. Closing as fixed.
