### ISSUE TITLE
Nonces on several places

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#623]
## Issue Description
Information about nonces can be found on 3 different places: Codex, Themes and Plugins handbooks. There is no difference in using nonceses in plugins and themes. It's how we do things in WordPress generally. This kind of functionality is the reason we have Common APIs handbook and that's where all that data should be moved.

## URL of the Page with the Issue

- Codex: https://codex.wordpress.org/WordPress_Nonces
- Themes: https://developer.wordpress.org/themes/theme-security/using-nonces/
- Plugins: https://developer.wordpress.org/plugins/security/nonces/

## Why is this a problem?

Because this info should live in one place. It's the same for all WordPress developers.

## Suggested Fix
- [ ] Review all the info we currently have, from all 3 places. 
- [ ] Keep content that is up to date, remove outdated and add new if applicable. 
- [ ] Create meaningful new page or pages in Common APIs for it. 
- [ ] Remove duplicates from Theme and Plugins handbooks, keep what's unique for both. Do NOT delete pages.
- [ ] Link from Themes and Plugins handbooks to newly created Common APIs page(s).
- [ ] Retire Codex page - by removing complete content and adding link to a newly created Common APIs page(s).

**Comment by theMikeD** [comment]
Updated nonces is here https://developer.wordpress.org/apis/security/nonces/

**Comment by theMikeD** [comment]
The Theme and Plugin handbook pages for nonces have been updated with references to the API handbook. 

I can't edit the Codex pages so @zzap can you do those for me please?
