### ISSUE TITLE
Update information on the Pull Quote article 

### ISSUE THREAD

**Issue by Thelmachido** [WordPress/Documentation-Issue-Tracker#630]
## Issue Description
While r[evamping the block settings section in the Widgets Blocks articles](https://github.com/WordPress/Documentation-Issue-Tracker/issues/484) I noticed that we have articles that need to be updated because they don't include some of the new block settings which are color, typography, border **+**  some of the screenshots on the articles need to be updated. 

## Pages that need to be updated
[Pull quote block ](https://wordpress.org/support/article/pullquote-block/) 
[Table Block](https://wordpress.org/support/article/table-block/)

## To Do

- [ ] Update content on the above-listed pages
- [ ] Update screenshots on the listed pages

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by Thelmachido** [comment]
I added the the relevant settings to the above blocks, I will close this issue
