### ISSUE TITLE
Incorrect URL to Gutenberg internationalization info

### ISSUE THREAD

**Issue by cdils** [WordPress/Documentation-Issue-Tracker#631]
## Issue Description
There's an incorrect link in the referenced doc.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

## Section of Page with the issue
[Handling JavaScript files](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#handling-javascript-files)

## Why is this a problem?
The link to 'Gutenburg plugin docs page' is incorrect.

## Suggested Fix
Change existing link:
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/internationalization.md

to:
https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/internationalization.md

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by cdils** [comment]
FYI I'm happy to contribute the fix but am not sure how/where the docs are maintained.

**Comment by theMikeD** [comment]
Done, @cdils can you confirm the fix please?
