### ISSUE TITLE
Template file name update

### ISSUE THREAD

**Issue by praveendias1180** [WordPress/Documentation-Issue-Tracker#634]
### Text correction: 

*Current:* page-{slug}.php (classic theme) or archive-{post-type}.html (block theme)

*Correct:* page-{slug}.php (classic theme) or page-{slug}.html (block theme)

## URL of the Page with the Issue

https://developer.wordpress.org/themes/basics/template-files/

## Section of Page with the issue

[Common WordPress template files](https://developer.wordpress.org/themes/basics/template-files/#common-wordpress-template-files)

## Why is this a problem?

The template name is incorrect (archive-{post-type}.html)

page-{slug}.php (classic theme) or archive-{post-type}.html (block theme)

## Suggested Fix

page-{slug}.php (classic theme) or page-{slug}.html (block theme)

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision:

original:
`page-{slug}.php (classic theme)` or `archive-{post-type}.html (block theme)`

new:
`page-{slug}.php (classic theme)` or `page-{slug}.html (block theme)`
