### ISSUE TITLE
Please, update docs on wp_video_shortcode ... wrong attributes.

### ISSUE THREAD

**Issue by blaasvaer** [WordPress/Documentation-Issue-Tracker#637]
I've spent the better part of two days tracking down why wp_video_shortcode wouldn't accept my 'src' parameter ... it turned out by pure accident, that I had to use 'mp4' instead. Now, that is nowhere in the docs ... someone please update, to save someone else loosing all the budget on tracking down things by googling random stuff when the docs doesn't make any sense.

It also seems some of the parameters are of the wrong type (string/boolean).

Why are developers not supposed to do this when changing stuff? There has to be a one-to-one relation between developing and documentation. Otherwise it gets totally out of control.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
I assume you're referring to this page?
https://developer.wordpress.org/reference/functions/wp_video_shortcode/

1.)
> I've spent the better part of two days tracking down why wp_video_shortcode wouldn't accept my 'src' parameter ... it turned out by pure accident, that I had to use 'mp4' instead. Now, that is nowhere in the docs ...

The description of the page at the top says
"This implements the functionality of the Video Shortcode for displaying WordPress **mp4s** in a post."

Though, I agree, the description of `src` parameter could have mentioned **mp4s**.

2.)
> It also seems some of the parameters are of the wrong type (string/boolean).

I wonder if you can list which parameters are of the wrong type.

**Comment by stevenlinx** [comment]
Since there are no responses to the above questions, I assume this is a false positive.
