### ISSUE TITLE
Support Forum Documentation: Update to reference block editor

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Documentation-Issue-Tracker#641]
## Issue Description

The block editor is in the process of being rolled out across all support forums posts & comments, including the nine main forums, as well as the plugin & themes forums. 

We should update the relevant support docs to explain how to use the block editor in the forums and remove references to the old editor.

Background: https://make.wordpress.org/support/2022/12/introducing-the-block-editor-in-the-support-forums/

There are currently still several forums where the block editor has not yet been rolled out, so perhaps we should wait til that's done before updating the documents.

## URL of the Page with the Issue

https://make.wordpress.org/support/handbook/ - we'll need to go through the support handbook to find all the specific spots that should be updated throughout the handbook

We should also see if there's a logical spot for **user-facing** information on using the block editor in the forum, as opposed to the above handbook, which is geared to volunteers providing help.

## Suggested Fix

- remove references to old editor, including any screenshots
- add references to block editor, including screenshots. Be sure to explain:
  - which blocks can be used in the forums
  - best practices for pasting code (side note: this is the current issue preventing the block editor from being rolled out forum-wide)
  - how to embed screenshots & screencasts
  - where to report bugs with the editor in the forums
- show how to opt out of the block editor in forums in user's forum profile

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by kathrynwp** [comment]
Here's what I've done. On the user-facing side, I:

- Created new page dedicated to using the block editor in the forums
https://wordpress.org/support/forum-user-guide/block-editor/
- Added a link to the new page from the [Forum User Guide](https://wordpress.org/support/forum-user-guide/)
- Added some new items to the [FAQ](https://wordpress.org/support/forum-user-guide/faq/) including: updated revision date at the to, and new items for:
   - [Why is the block editor in the forums different than on my site](https://wordpress.org/support/forum-user-guide/faq/#why-is-the-block-editor-in-the-forums-different-than-the-one-on-my-wordpress-site)
   - [How to report a bug or suggest an enhancement](https://wordpress.org/support/forum-user-guide/faq/#where-can-i-report-a-bug-or-request-an-enhancement-to-the-block-editor-in-the-forums)
   - [How to opt out](https://wordpress.org/support/forum-user-guide/faq/#how-do-i-opt-out-of-using-the-block-editor-in-the-forums)
- [Updated the item about screenshots & embeds](https://wordpress.org/support/forum-user-guide/faq/#can-i-include-screenshots-or-videos)
- [Updated the item about pasting code](https://wordpress.org/support/forum-user-guide/faq/#how-do-i-post-code-examples)

On the volunteer side, I added a new item to the Quick Links section of the support handbook - https://make.wordpress.org/support/handbook/

I'll present these updates at the next Support team meeting on Thurs. Feb. 2. If no further changes are suggested then, this ticket will be able to be closed.

**Comment by kathrynwp** [comment]
I'm going ahead and closing this out.
