### ISSUE TITLE
Core Handbook: Typo and wrong markup on the page "Installing from a Zip File"

### ISSUE THREAD

**Issue by t-hamano** [WordPress/Documentation-Issue-Tracker#642]
## Issue Description
I think there are typo and wrong markup on the page "Installing from a Zip File".

## URL of the Page with the Issue

https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-zip/

## Section of Page with the issue

- `wordpress-svn/wp-config.php` should be `wordpress-trunk/wp-config.php`:

![wp-trunk](https://user-images.githubusercontent.com/54422211/211438661-45b8586a-3d5e-4c33-bec2-455a99a0e32c.png)

- The fifth section is unintentionally enclosed by a pre tag:

![pre](https://user-images.githubusercontent.com/54422211/211438672-886ef833-f115-44b7-8b8a-ba321ebec8cb.png)

**Comment by atachibana** [comment]
@t-hamano 
If you have edit access of that page, you can fix this issue by yourself :-)

**Comment by t-hamano** [comment]
@atachibana
Thanks for the advice!
I was able to fix it from the edit button and would like to close this issue.
