### ISSUE TITLE
Add a list of articles in the HelpHub documentation in the form of the contents of the book

### ISSUE THREAD

**Issue by ilyachalov** [WordPress/Documentation-Issue-Tracker#644]
## What is the new page you are requesting?

I suggest adding a list of articles in the [HelpHub documentation](https://wordpress.org/support/) in the form of the contents of the book. (In addition to the categories, not instead of them.) This list does not necessarily include all the articles available in the HelpHub documentation: for a novice user, a certain group of basic articles is enough, and he will already be able to find the rest himself.

I have prepared three examples of what this list might look like:

1. [category-getting-started.md](https://github.com/ilyachalov/wp-org-docs-contents/blob/main/category-getting-started.md)&nbsp;— list of only articles from the category 'Getting Started'. This is the most problematic category, there are 59 articles in it now. It is not clear to the novice user in what order to read them.

2. [into-categories.md](https://github.com/ilyachalov/wp-org-docs-contents/blob/main/into-categories.md)&nbsp;— list of all articles of HelpHub documentation contained in the categories of HelpHub. HelpHub categories saved. Due to the fact that some articles fall into several categories, there are duplicates in this list. The list from the previous paragraph is part of the list from this paragraph.

3. [without-categories.md](https://github.com/ilyachalov/wp-org-docs-contents/blob/main/without-categories.md)&nbsp;— list of all articles from the categories of the HelpHub documentation, but without breaking down into these categories. I made my division into sections. There are no duplicates in this list.

## How will this new page help you?

Here are the reasons for creating this list:

1. A system for organizing articles using categories (as in HelpHub documentation) works well if there are not very many articles in each category. For example, no more than a dozen. If there are a lot of articles in a category, additional internal organization is required.

2. A novice user (and not just a novice user) often wants to cover everything with one glance. Therefore, it is useful to have links to all articles on one page at hand, and not on multiple pages, as is the case with using categories.

3. It is not clear to a novice user in which order to read articles from categories, since articles are collected in a heap inside categories, and not in a sequential list. The proposed list has a certain recommended sequence of reading articles, so you can immediately start reading articles, and not think which one to read first.

4. The system of organizing articles using categories is designed for a quick selection of articles on a specific topic, but is not designed for sequential reading of all articles. In this regard, it has a drawback: the same article can fall into several categories, and when reading sequentially from the categories, the user constantly stumbles upon duplicates.

## Examples of a similar list in other projects

- handbooks on the website [make.wordpress.org](https://make.wordpress.org/), including [file structure](https://github.com/WordPress/Advanced-administration-handbook#file-structure) of the new 'Advanced Administration Handbook';
- book "Pro Git" on the website [git-scm.com/book](https://git-scm.com/book);
- MySQL 8.0 Reference Manual on [dev.mysql.com/doc/refman/8.0/en/](https://dev.mysql.com/doc/refman/8.0/en/);
- PHP Manual on [www.php.net/manual/en/](https://www.php.net/manual/en/)

and so on (there are many more examples).

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by ilyachalov** [comment]
Due to a big change in the structure of user documentation on the site WordPress.org (changing the addresses of articles, changing the composition of categories: [wordpress.org/support](https://wordpress.org/support/) --> [wordpress.org/documentation](https://wordpress.org/documentation/)) my offer has become irrelevant. So I close this question.
