### ISSUE TITLE
Wrong Currency list for Razorpay Payment Gateway on CampTix Documentation

### ISSUE THREAD

**Issue by GautamMKGarg** [WordPress/Documentation-Issue-Tracker#645]
## Issue Description

Wrong Currency list for Razorpay Payment Gateway on CampTix Documentation

## URL of the Page with the Issue

[Selecting a Payment Gateway](https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/using-camptix-event-ticketing-plugin/#selecting-a-payment-gateway)

## Section of Page with the issue

[Selecting a Payment Gateway](https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/using-camptix-event-ticketing-plugin/#selecting-a-payment-gateway) >> "The gateways/currencies we currently support are:"

## Why is this a problem?

As per [Supported Currencies](https://razorpay.com/docs/payments/payments/international-payments/#supported-currencies) docs, Razorpay supports 92 currencies, but on CampTix docs only 1 currency is mentioned for Razorpay.

## Suggested Fix

Add list of remaining currency also for Razorpay. INR is primary currency for Razorpay but it accept remaining currency also.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by GautamMKGarg** [comment]
@zzap

> Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

What do you mean? Is it internal communication or you need any other information from my end?

**Comment by stevenlinx** [comment]
@GautamMKGarg 

Thank you for filing.

The content of the Make Community handbook is not the responsibility of this repo.

Please see the Coverage of the README.md
https://github.com/WordPress/Documentation-Issue-Tracker#coverage
"All other Make / WordPress team handbooks are maintained by internally by said respective teams. Please contact them on Make / WordPress Slack to suggest changes."

**Comment by GautamMKGarg** [comment]
Could you please suggest me right slack channel/group to report this issue?

**Comment by GautamMKGarg** [comment]
Closed the issue as issue is not relevant for this repo

**Comment by stevenlinx** [comment]
@GautamMKGarg 

FYI,

Make Community Team page on WordPress.org:
https://make.wordpress.org/community/

The slack channel is listed on the top right:
#community-team
