### ISSUE TITLE
[HelpHub] Site Health page

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#651]
## Issue Description

This is a page instead of an article. It contains no developer jargon, so it is ok to keep inside HelpHub.

## URL of the Page with the Issue
 

https://wordpress.org/documentation/site-health/

## Suggested Fix

Migrate full page to /documentation/technicalguides/maintenance

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by estelaris** [comment]
This page should stay as page. I will ask in meta to change the template for the look. Here is the ticket https://meta.trac.wordpress.org/ticket/6740#ticket
