### ISSUE TITLE
[HelpHub] Update PHP page

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#652]
## Issue Description

Another article written as a page instead of an article. This is very simple information that any user must learn.

## URL of the Page with the Issue

https://wordpress.org/documentation/update-php/

## Suggested Fix

Keep in HH and add as an article under /documentation/technicalguides/maintenance

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by estelaris** [comment]
This page should stay as page. I will ask in meta to change the template for the look. Here is the ticket https://meta.trac.wordpress.org/ticket/6740#ticket
