### ISSUE TITLE
Typo in plugin-developer-faq

### ISSUE THREAD

**Issue by mujuonly** [WordPress/Documentation-Issue-Tracker#655]
## Issue Description
As closing a plugin is permanent, we recommend you not push code until you’re **read** to go live.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/

## Section of Page with the issue
https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#when-does-my-plugin-go-live

## Why is this a problem?
Typo in the sentence

## Suggested Fix
read should be ready

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
Thank you for filing.

It's revised.

**Comment by mujuonly** [comment]
@stevenlinx @zzap  Thank you
