### ISSUE TITLE
[Handbook] Create a summary page about External Linking Policy

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#658]
## What is the new page you are requesting?
Due to a number of Issues that has been filed requiring attention to the External Linking Policy, I think there shall be a summary page in the Docs Handbook detailing the policy so far. The current go-to resource is a blog tag page listing multiples blog posts detailing different parts of  the policy, which is not trivial for new comers to decipher.

With a summary page, a fellow community member can be pointed to this page if needed and the Docs team members can update the summary as we go.

I'm willing to write this page if no one wants to.

Summary of the External Linking Policy (as far as I know):

* All links, except those on the whitelist, are prohibited.

* No new links shall be added at this time for all documentation.

* The plug-in handbook is being used as the policy testbed; the rules will eventually apply to all documentation.

* Sites/blogs of any commercial in nature are prohibited.

* No plugins/themes/services/hosting etc will be promoted or recommended. In HelpHub/DevHub, we document only what's in Core or will be in Core.
https://make.wordpress.org/docs/2020/07/06/external-linking-policy-commercial-blogs/
"This is in accordance with HelpHub’s (end user documentation) practice that no plugin, theme, hosting etc will not be promoted or recommended. In HelpHub we are documenting only what’s in core or will be in core."

* No blogs from the sites of plugins/themes/services/hosting etc can be mentioned.

Reference:
https://make.wordpress.org/docs/tag/external-linking-policy/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
@zzap @theMikeD

I've wrote a draft page at the following URL:
https://make.wordpress.org/docs/wp-admin/post.php?post=23834&action=edit

May I request a review or someone else on the team who is willing.

Thank You.

**Comment by zzap** [comment]
>Sites/blogs of any commercial in nature are prohibited. 

That one needs changing. What we want to prohibit are links that are selling products and services on the linked page or hiding content behind a paywall. So, the website can be commercial by its nature but the content of the actual page can not be used for selling/promoting a product or service.

**Comment by stevenlinx** [comment]
Thanks for the reply.

1.)
So I assume the sentence can be revised to the following:

- Sites/blogs can be commercial in nature but the content page linked cannot be used for selling/promoting a product or service.

2.)
Also, if the point above is revised, this seems to conflict with the last point of the summary:
"_No blogs from the sites of plugins/themes/services/hosting etc can be mentioned._"

Because based on the revised point, a blog from sites of plugins/themes/services/hosting etc can be mentioned, just that the content page linked cannot be promotion in nature.

Shall the last point be revised or just be deleted?

Thanks

**Comment by zzap** [comment]
> Also, if the point above is revised, this seems to conflict with the last point of the summary:

Yes, so now you see why this project is dragging so much. It isn't easy to draw a clean line.

I think for now just remove that line, thank you.

**Comment by stevenlinx** [comment]
I've revised and published the post.

https://make.wordpress.org/docs/handbook/documentation-team-handbook/external-linking-policy/

**Comment by theMikeD** [comment]
I would suggest that if you are going to refer the reader to "see point two & three below" that you use a numbered list not a bullet list.

**Comment by stevenlinx** [comment]
@theMikeD 

Done.
