### ISSUE TITLE
Text correction on plugin handbook privacy page

### ISSUE THREAD

**Issue by mujuonly** [WordPress/Documentation-Issue-Tracker#660]
## Issue Description
Text correction on plugin handbook privacy page

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/privacy/

## Section of Page with the issue
 https://developer.wordpress.org/plugins/privacy/#food-for-thought-for-your-plugin

## Why is this a problem?
1. Misspelled - "when an related"
2. Space is missing in between "?" and "Does"

## Suggested Fix
1. "when an related" should be "when a related"
 2. If so, what data?Does the plugin  - Space is needed in between "?" and "Does"

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision.
