### ISSUE TITLE
Outreach to component maintainers 6.2

### ISSUE THREAD

**Issue by bph** [WordPress/Documentation-Issue-Tracker#668]
## Outreach to component maintainers for Field Guide "But Wait, There is More!" section (WordPress 6.1)

**Reference in release documentation**
<details>
[Publishing Field Guide](https://make.wordpress.org/core/handbook/tutorials/publishing-the-field-guide/)
"Each Component team is sent a group direct message in Slack, pulling the list of maintainers from the [individual component pages](https://make.wordpress.org/core/components/)"

Example message: 
_It’s that time again `Component Name` component maintainer(s)… are there any tickets in the 6.0 release that you’d like called out in the Field Guide that aren’t already included in a Dev Note? As a reference, here are the ## tickets currently in the milestone for you: https://core.trac.wordpress.org/query?component=`ComponentName`&-milestone=6.1&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority. Note that we intend to publish the Field Guide next week, so the sooner you can respond the better… thanks!_
</details>

## List of components

- The link goes to the list of tickets for the milestone for the component.  The number of tickets is in parentheses. 
- A blue check mark means maintainers were contacted or no issues. 
-----
- [ ] [Administration ](https://core.trac.wordpress.org/query?component=Administration&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (11)
- [x] [Bootstrap/Load](https://core.trac.wordpress.org/query?component=Bootstrap%2FLoad&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Build/Test Tools](https://core.trac.wordpress.org/query?component=Build%2FTest+Tools&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (33) ✅
- [x] [Bundled Theme](https://core.trac.wordpress.org/query?component=Bundled+Theme&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (58) ✅
- [x] [Cache API](https://core.trac.wordpress.org/query?component=Cache+API&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0) 
- [x] [**Comments**](https://core.trac.wordpress.org/query?component=Comments&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (7) ✅
- [ ] -- [Pings/Trackbacks](https://core.trac.wordpress.org/query?component=Pings%2FTrackbacks&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2)
- [x] [Cron API](https://core.trac.wordpress.org/query?component=Cron+API&milestone=6.1&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Customize](https://core.trac.wordpress.org/query?component=Customize&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5) 🦗
- [x] [Database](https://core.trac.wordpress.org/query?component=Database&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2) ✅
- [x] [Date/Time](https://core.trac.wordpress.org/query?component=Date%2FTime&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(2) 🦗
- [x] [**Editor**](https://core.trac.wordpress.org/query?component=Editor&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(48) _also shared [Gutenberg Dev Note tracking issue] 🦗(https://github.com/WordPress/gutenberg/issues/47771)_
- [x] -- [Autosave](https://core.trac.wordpress.org/query?component=Autosave&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Quick/Bulk Edit](https://core.trac.wordpress.org/query?component=Quick%2FBulk+Edit&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1) 
- [x] -- [TinyMCE](https://core.trac.wordpress.org/query?component=TinyMCE&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Export](https://core.trac.wordpress.org/query?component=Export&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [External Libraries](https://core.trac.wordpress.org/query?component=External+Libraries&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(8) ✅
- [x] [Feeds](https://core.trac.wordpress.org/query?component=Feeds&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1) 🦗
- [x] [Filesytems API](https://core.trac.wordpress.org/query?component=Filesystem+API&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4) ✅
- [x] [**Formatting**](https://core.trac.wordpress.org/query?component=Formatting&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(10) ✅
- [x] -- [Charset ](https://core.trac.wordpress.org/query?component=Charset&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(0)
- [x] -- [Emoji](https://core.trac.wordpress.org/query?component=Emoji&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2) ✅
- [x] -- [Shortcodes ](https://core.trac.wordpress.org/query?component=Shortcodes&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(0)
- [x] [General](https://core.trac.wordpress.org/query?component=General&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(35) ✅
- [x] [Help/About Page](https://core.trac.wordpress.org/query?component=Help%2FAbout&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(8)
- [x] [HTTP API](https://core.trac.wordpress.org/query?component=HTTP+API&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5) 🦗
- [x] [i18n](https://core.trac.wordpress.org/query?component=I18N&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(7) ✅
- [x] [Import](https://core.trac.wordpress.org/query?component=Import&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [ ] [Mail ](https://core.trac.wordpress.org/query?component=Mail&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(3)
- [x] [**Media**](https://core.trac.wordpress.org/query?component=Media&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(28) ✅
- [x] -- [Embeds](https://core.trac.wordpress.org/query?component=Embeds&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3)
- [x] -- [Gallery](https://core.trac.wordpress.org/query?component=Gallery&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Upload](https://core.trac.wordpress.org/query?component=Upload&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Network/Sites](https://core.trac.wordpress.org/query?component=Networks+and+Sites&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(6) ✅🦗
- [x] [Options/Meta APIs](https://core.trac.wordpress.org/query?component=Options%2C+Meta+APIs&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4) ✅
- [x] [**Permalinks**](https://core.trac.wordpress.org/query?component=Permalinks&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(3) 🦗
- [x] -- [Canonical ](https://core.trac.wordpress.org/query?component=Canonical&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1) (sub component) 🦗
- [x] -- [Rewrite Rules](https://core.trac.wordpress.org/query?component=Rewrite+Rules&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0) (sub component)
- [ ] [Plugins ](https://core.trac.wordpress.org/query?component=Plugins&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (5)
- [ ] **[Posts, Post Types](https://core.trac.wordpress.org/query?component=Posts%2C+Post+Types&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)** (11)
- [x] -- [Post Formats](https://core.trac.wordpress.org/query?component=Post+Formats&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Post Thumbnails](https://core.trac.wordpress.org/query?component=Post+Thumbnails&-milestone=6.1&col=id&col=summary&col=milestone=6.2&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] -- [Revisions](https://core.trac.wordpress.org/query?component=Revisions&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4) 🦗
- [x] [Privacy](https://core.trac.wordpress.org/query?component=Privacy&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(1) 🦗
- [x] [Query](https://core.trac.wordpress.org/query?component=Query&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3) 🦗
- [x] [REST API](https://core.trac.wordpress.org/query?component=REST+API&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4) ✅
- [x][Application Passwords](https://core.trac.wordpress.org/query?component=Application+Passwords&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1) ✅
- [x] [Script Loader ](https://core.trac.wordpress.org/query?component=Script+Loader&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(0)
- [ ] [Security](https://core.trac.wordpress.org/query?component=Security&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4)
- [x] [Site Health](https://core.trac.wordpress.org/query?component=Site+Health&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (3) ✅
- [x] [Sitemaps](https://core.trac.wordpress.org/query?component=Sitemaps&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [Taxonomy](https://core.trac.wordpress.org/query?component=Taxonomy&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (7) 🦗
- [x] [**Themes**](https://core.trac.wordpress.org/query?component=Themes&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (19) 🦗
- [x] -- [Menus ](https://core.trac.wordpress.org/query?component=Menus&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(4) ✅
- [x] -- [Widgets](https://core.trac.wordpress.org/query?component=Widgets&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2) ✅
- [x] [Toolbar](https://core.trac.wordpress.org/query?component=Toolbar&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (1)✅
- [x] [Upgrade/Install](https://core.trac.wordpress.org/query?component=Upgrade%2FInstall&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (11) ✅
- [ ] [**Users**](https://core.trac.wordpress.org/query?component=Users&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (7)
- [ ] -- [Login & Registration](https://core.trac.wordpress.org/query?component=Login+and+Registration&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (5)
- [x] -- [Role/Capability](https://core.trac.wordpress.org/query?component=Role%2FCapability&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
- [x] [XML-RPC (1)](https://core.trac.wordpress.org/query?component=XML-RPC&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (0)
---
Note to future self: 
I used [this Google Sheet](https://docs.google.com/spreadsheets/d/12oP6JwQYEseotP4v75G939WwxIG_040_IVtS5kcMSO4/edit#gid=0) to get the message for each component and the link to the tickets, just replace in the message 6.1 with 6.2  in the WP version column.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by bph** [comment]
These 48 tickets for inclusion into the Fieldguide, or Miscellaneous dev note or a single stand-alone dev note post. The tickets are from components without maintainers. 

- [Administration ](https://core.trac.wordpress.org/query?component=Administration&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(11) 
- [Pings/Trackbacks](https://core.trac.wordpress.org/query?component=Pings%2FTrackbacks&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (2)
- [Mail ](https://core.trac.wordpress.org/query?component=Mail&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(3)
- [Plugins ](https://core.trac.wordpress.org/query?component=Plugins&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority)(5)
-  [Posts, Post Types](https://core.trac.wordpress.org/query?component=Posts%2C+Post+Types&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (11)
- [Security](https://core.trac.wordpress.org/query?component=Security&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (4)
- [Users](https://core.trac.wordpress.org/query?component=Users&milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (7)
-  [Login & Registration](https://core.trac.wordpress.org/query?component=Login+and+Registration&-milestone=6.2&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority) (5)

**Comment by carolinan** [comment]
_For review_

Bundled Themes
Twenty Twelve to Twenty Seventeen now includes font files in the theme folder instead of loading fonts from a remote source (Google Fonts). This update ensures that the themes follow current recommendations for fonts from a privacy perspective.

**Comment by bph** [comment]
for External libraries: 
---
The following libraries were updated to the latest versions:

- jQuery ([#57324](https://core.trac.wordpress.org/ticket/57324))
- jQuery Migrate ([#56743](https://core.trac.wordpress.org/ticket/56743))
- PHPMailer ([#57281](https://core.trac.wordpress.org/ticket/57281))
- element-closest ([#52851](https://core.trac.wordpress.org/ticket/52851))
- regenerator runtime ([#57646](https://core.trac.wordpress.org/ticket/57646))
- polyfill-library ([#57646](https://core.trac.wordpress.org/ticket/57646))

**Comment by bph** [comment]
Filesystems API 
Function changes
<code>WP_Filesystem_Direct::move()</code>
In #57375 <code>WP_Filesystem_Direct::move()</code> had directory support added to make it consistent with <code>::move()</code> methods in <code>WP_Filesystem_FTPext</code>, <code>WP_Filesystem_ftpsockets</code> and <code>WP_Filesystem_SSH2</code>.
New functions
<code>wp_opcache_invalidate_directory()</code>
<code>wp_opcache_invalidate()</code> invalidates the OPcache for individual PHP files after overwriting. In #57375 <code>wp_opcache_invalidate_directory()</code> was added to recursively invalidate the OPcache for PHP files after overwriting. The function accepts a single argument, <code>(string) $dir</code>, pointing to the directory containing PHP files for which OPcache is to be invalidated.

**Comment by bph** [comment]
@zzap for three components, we have content for the field guide. see comments above ^^

**Comment by zzap** [comment]
thank you @bph

**Comment by zzap** [comment]
All these are added to the field guide.

**Comment by bph** [comment]
Oops,.should have closed it with the 6.2 release
