### ISSUE TITLE
"Sanitizing Data" page should link to all sanitization functions

### ISSUE THREAD

**Issue by benlk** [WordPress/Documentation-Issue-Tracker#669]
## Issue Description
https://developer.wordpress.org/apis/security/sanitizing/ has a list of sanitization functions, but these do not have descriptions of appropriate usage or links to their documentation/

## URL of the Page with the Issue

https://developer.wordpress.org/apis/security/sanitizing/

## Section of Page with the issue
The list of sanitization functions on https://developer.wordpress.org/apis/security/sanitizing/#sanitization-functions

## Why is this a problem?

The current state increases friction for developers who are trying to choose the correct sanitization function for their purposes.

## Suggested Fix

Link each function in the list to its function reference, such as https://developer.wordpress.org/reference/functions/sanitize_email/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision.

**Comment by benlk** [comment]
Awesome, thank you!
