### ISSUE TITLE
#41474 #57574 Download Media

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#672]
Trac tickets:
- [Feature Request: Download Media button from Attachment Details Page](https://core.trac.wordpress.org/ticket/41474)
- [Add a Download row action to the Media List Table](https://core.trac.wordpress.org/ticket/57574)

Update both screenshots and text on these pages:
- https://wordpress.org/documentation/article/media-library-screen/
- https://wordpress.org/documentation/article/edit-media/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by mujuonly** [comment]
I will take this one

**Comment by mujuonly** [comment]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/459367/230028567-2e7d2cdc-6c4a-4b75-9005-2ca744c6213a.png">
Attachment Details

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/459367/230029485-c99d0647-9514-4b22-a42d-12a67caf3703.png">
Edit Media Page


Changelog
Updated 2023-04-05
Added updated screenshots and content for 6.2.
Added ALT tags for the images

**Comment by yuruaniam** [comment]
I would like to work on this issue

**Comment by mujuonly** [comment]
@zzap Is there something more to do on this one?

**Comment by shabnam611** [comment]
@zzap 
Can I take this one?

**Comment by shabnam611** [comment]
Created draft for Media Library screen to reflect the changes from [here](https://core.trac.wordpress.org/ticket/41474) and [here](https://core.trac.wordpress.org/ticket/57574).

**Comment by shabnam611** [comment]
I have completed checking the documentations:
https://wordpress.org/documentation/article/media-library-screen/
https://wordpress.org/documentation/article/edit-media/

I added the required texts are made sure the images are relevant to 6.2.2 and updated as required.

**Comment by shabnam611** [comment]
@jennimckinnon @zzap @Leonardus-Nugraha 

kindly set this for 2nd review

**Comment by zzap** [comment]
Ready for /review.

**Comment by shabnam611** [comment]
For https://wordpress.org/documentation/article/media-library-screen/
Changelog:
Updated on 2023-06-25

Updated screenshots for media library grid view [because it was showing WordPress 4.0], Attachment details, find posts & pages. 

Updated GIF for Actions

Added alt tag and caption for Media library list view image

Added the paragraph Download file to the edit media page section and made sure the changes from the following issues are being reflected:
https://core.trac.wordpress.org/ticket/41474 and this issue: https://core.trac.wordpress.org/ticket/57574

Updated on 2023-06-27

Changed the photo of media library grid view and the GIF for Actions

**Comment by shabnam611** [comment]
For https://wordpress.org/documentation/article/edit-media/
Changelog:

Updated screenshots for media item edit page, attachment details and made those relevant to 6.2.2

Updated GIF for Restore original image

Made sure there is alt tag and caption for all the images

Added the paragraph Download file for edit media page to reflect the changes mentioned in these issues: https://core.trac.wordpress.org/ticket/41474 

Made sure all the Headings are in sentence case

**Comment by Leonardus-Nugraha** [comment]
Thanks @shabnam611 ! Reviewed and all looks good. I added the changelog to the article
