### ISSUE TITLE
3 link updates for Editing Files > Text Editors

### ISSUE THREAD

**Issue by macmanx2** [WordPress/Documentation-Issue-Tracker#673]
## Issue Description
1 text editor needs to be removed, and 2 need new links.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/editing-files/

## Section of Page with the issue
https://wordpress.org/documentation/article/editing-files/#text-editors

## Why is this a problem?
1 recommended text editor no longer exists, 2 are going to the wrong URL. I'll describe in the fix below. :)

## Suggested Fix
1. Remove Atom since it has been deprecated.
2. Correct Sublime Text link to http://www.sublimetext.com since it is currently linked to a deprecated version.
3. Correct NetBeans link to https://netbeans.apache.org/ since it is currently linked to its documentation.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by estelaris** [comment]
This issue has been moved to DevHub and fosed there. The article under /documentation/ will be deleted and redirected

**Comment by macmanx2** [comment]
Thanks, @estelaris, I'm new to docs operating this way, I'm used to just using my admin powers to edit them directly, so I don't know what your comment means. :)

Would you mind explaining so I know more about the process and where to follow along now?

Thanks!

**Comment by estelaris** [comment]
@macmanx2 developer docs that were removed from HelpHub are being updated in different places, some here in this repository and others are in https://github.com/WordPress/Advanced-administration-handbook. 

Once the new Advance Admin handbook is uploaded to developers.wp.org, it will be redirected to [this link](https://developer.wordpress.org/advanced-administration/wordpress/edit-files/)

**Comment by macmanx2** [comment]
Outstanding, thank you!
