### ISSUE TITLE
[HelpHub] Quote Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#684]
Article: https://wordpress.org/documentation/article/quote-block/

## Updating for 6.2
- [x] unwrap inner block when pressing Backspace at start. [45075](https://github.com/WordPress/gutenberg/pull/45075)
- [x] Merge inner blocks if wrappers are equal [43181](https://github.com/WordPress/gutenberg/pull/43181)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha heya, assign me 🍪

**Comment by Leonardus-Nugraha** [comment]
It's yours, @Ignasrimkunas :D

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1wuABvxwjeGHqfDsFmLJH2Kl8-QEK5owCqd8l1wlsKM0/edit#

First review finished

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung!
Content updated: https://wordpress.org/documentation/article/quote-block/
