### ISSUE TITLE
[HelpHub] Paragraph Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#685]
Article:  https://wordpress.org/documentation/article/paragraph-block/

## Update for 6.2
- [x] Converts paragraphs to headings with keyboard shortcuts. [44681](https://github.com/WordPress/gutenberg/pull/44681)
- [x] Disable drop cap control if text is aligned [42326](https://github.com/WordPress/gutenberg/pull/42326)
- [x] Move Link Control action buttons into lower settings area [47309](https://github.com/WordPress/gutenberg/pull/47309)
- [x] Add clear Apply and Cancel buttons to Link Control [46933](https://github.com/WordPress/gutenberg/pull/46933)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by yogskr** [comment]
@Leonardus-Nugraha  I will work on this one next!

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1ZK5cC9UWARuJzX_tao4JYa0i-Df0JAtFxkPcsZsF0t4/edit#heading=h.mjq0iyj9tts3
First review done!
