### ISSUE TITLE
[HelpHub] Heading Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#686]
Article:  https://wordpress.org/documentation/article/heading-block/

## Update for 6.2
- [ ] Converts paragraphs to headings with keyboard shortcuts. [44681](https://github.com/WordPress/gutenberg/pull/44681)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by ratneshsonar** [comment]
Hi, @femkreations  I will be happy to contribute to this task as well.

**Comment by ratneshsonar** [comment]
I have verified the shortcut key **Ctrl + Cmd + (1-6)** in WIndows OS and **Ctrl + Option + (1-6)** in MacOS transforms the selected paragraph text into a heading block.

However, we need to mention these details in the "Change heading level" section of "Heading Block" page.

**Comment by ratneshsonar** [comment]
Here are a few changes that I would like to propose to the Heading Block doc.

- Alt Tag for “Change text alignment” image is missing

![alt_tag_missing](https://user-images.githubusercontent.com/5754380/230444256-1654892a-7061-4513-9e7b-804bc1606fdc.png)


- The change Align screenshot needs to be updated as there are no size details below the options.
![text_alignment_Screenshot](https://user-images.githubusercontent.com/5754380/230443486-f7dc5de4-9063-401a-ae66-362c1ae90435.png)

- Transform to screenshot needs to be updated as there is a new option for Patterns.
![Trasnforms_to_screenshot](https://user-images.githubusercontent.com/5754380/230443586-516a510c-7d88-428c-8a56-153806ff15ce.png)

**Typography**
- Typography Screenshot needs to be updated, and under Typography, there is a new option Text Decoration. However, the Text Decoration option is Theme specific.
-  
![Typography_screenshot](https://user-images.githubusercontent.com/5754380/230443665-2b897399-d353-4ec4-9adb-8bb9333f6360.png)

**Comment by femkreations** [comment]
Thanks for your work @ratneshsonar  This looks great. can you pls add the alt tag description content as well for all the images

**Comment by zzap** [comment]
Only thing left here are ALT tags for images.

**Comment by nerdontour** [comment]
I checked that all the images have ALT tags. Therefore, we can close this issue.
