### ISSUE TITLE
Dimension Controls Support Page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#69]
[Pulled from this slack convo](https://wordpress.slack.com/archives/C02RP4WU5/p1635880554158000), I plan to approach this by adding an overall dimension controls page that then has link on each respective block page to that page. Pulled from this overview issue https://github.com/WordPress/gutenberg/issues/28356 here are the blocks to update:

- Buttons block: https://github.com/WordPress/gutenberg/pull/34546 
- Spacing block: https://github.com/WordPress/gutenberg/pull/30608 
- Site title block: https://github.com/WordPress/gutenberg/pull/31728 
- Media & text block: https://github.com/WordPress/gutenberg/pull/31002
- Group block: https://wordpress.org/support/article/group-block/
- Cover block: https://github.com/WordPress/gutenberg/pull/34065
- Columns block: https://github.com/WordPress/gutenberg/pull/34630

Need to include padding, margin, min-height, block gap, etc.

**Comment by annezazu** [comment]
Whew have a draft: https://wordpress.org/support/?p=15242206&post_type=helphub_article&preview=1&_ppp=8374967e92

@carolinan or @mkaz would either of you bhance be able to review?

**Comment by carolinan** [comment]
Hi!
The text flows well and is easy to read.

The two first blocks in the image below "How to find dimension controls" have the dimension panel closed, which I found confusing. It felt like the main focus of those images where the typography- and color controls instead.

Types of controls, padding;
>This setting impacts the space behind a block’s content and its border. 

I believe this should be `space between`, not space behind?

Types of controls, margin;
>You can find this in option in blocks like Columns block. 

I think the first `in` needs to be removed.

Block spacing
[This setting can easily be misunderstood](https://github.com/WordPress/gutenberg/issues/37768).
It controls the spacing between blocks that are inside the block that displays the setting (button block inside buttons block).
-I am not sure how to explain that in an easy way.

**Comment by annezazu** [comment]
Thanks so much for reviewing per usual <3. 

> The two first blocks in the image below "How to find dimension controls" have the dimension panel closed, which I found confusing. It felt like the main focus of those images where the typography- and color controls instead.

Great point. For whatever reason, I didn't think to close those tabs out as a way to get a condensed shot. Updated!

>I believe this should be space between, not space behind?

Updated 🤦🏼 

>I think the first in needs to be removed.

Updated 💥 

>Block spacing. This setting can easily be misunderstood. It controls the spacing between blocks that are inside the block that displays the setting (button block inside buttons block). I am not sure how to explain that in an easy way.

I struggled with this too. Thank you for flagging that issue too. Great context on where folks are likely to get confused. To help resolve this, I added in slightly more context to that section and added an additional demo showing the block spacing controls for the parent buttons block and padding controls for the nested blocks. 

At this point, shipping: https://wordpress.org/support/article/dimension-controls-overview/ We can iterate from there.

**Comment by annezazu** [comment]
Added in a link to dimension controls docs to the following docs:
- Buttons block: https://wordpress.org/support/article/buttons-block/
- Group block: https://wordpress.org/support/article/group-block/
- Cover block: https://wordpress.org/support/article/cover-block/

For columns and spacer, these were removed and [will be added back in the future](https://github.com/WordPress/gutenberg/pull/37360#event-5837677333).
