### ISSUE TITLE
[HelpHub] Latest Comments block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#690]
Article:  https://wordpress.org/documentation/article/latest-comments-block/

## Update for 6.2
- [ ] add spacing support. [45110](https://github.com/WordPress/gutenberg/pull/45110)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha I will take this one

**Comment by Leonardus-Nugraha** [comment]
Updates reviewed and published. Thanks @Ignasrimkunas!
