### ISSUE TITLE
Wrong function/action name

### ISSUE THREAD

**Issue by webgodo** [WordPress/Documentation-Issue-Tracker#691]
## Issue Description
There is a code snippet with 4 lines of code:
```php
add_action('init', 'wporg_callback_run_me_late', 11);
add_action('init', 'wporg_callback_run_me_normal');
add_action('init', 'wporg_callback_run_me_early', 9);
add_action('init', 'wporg_callback_run_me_later', 11);
```
In the next paragraph, it's describing the function with priority of 9:

The first function run will be `wporg_call_backrun_me_early()`, because it has a manual priority of 9

The function name is miss-spelled. It should be: `wporg_callback_run_me_early`

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/hooks/actions/#priority

## Section of Page with the issue
Priority

## Why is this a problem?
Function name is different from the one in the snippet.

## Suggested Fix
Change `wporg_call_backrun_me_early` to `wporg_callback_run_me_early`

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
