### ISSUE TITLE
[HelpHub] Post Tags block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#694]
Article:  https://wordpress.org/documentation/article/post-tags-block/

## Update for 6.2
- [x] Add spacing support. [43646](https://github.com/WordPress/gutenberg/pull/43646)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by carolinan** [comment]
@femkreations  This block variation is not displayed as "Post Tags" in the interface, only Tags. I wonder if it needs to be moved to a new slug?  https://wordpress.org/documentation/article/tags-block/ ?

**Comment by carolinan** [comment]
I have scheduled this update as far ahead as May 30, because I would like the support article for the Rich Text options to be published first so that this article can link to it.

_If that is not alright, then all the information about the rich text options can be copied from another block support article and added to this one before publishing._

- Updated screenshots
- Updated one video
- Added information about the prefix and suffix option
- Updated information about the toolbar controls
- Replaced the block name "Post Tags" with "Tags"

**Comment by carolinan** [comment]
Extending the time until publishing to July 30, since the update has not been reviewed.

**Comment by marcdap** [comment]
@zzap I would like to be assigned to this ticket if it is ok.

**Comment by cgarofalo** [comment]
I'd like to be assigned. I have created the new video and screenshots.


Video:

https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/c75f13aa-5ec3-40d0-8813-dec35d719e7a

Screenshots:
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/a11bb6e1-f19b-4674-b432-0c90f96c74da)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/dfe4c0b0-1843-49ad-80b6-a659d9649d67)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/a93d89c8-76c1-4a85-abcc-c8c4915dbe81)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/c0c94fe0-6359-4b2d-b5cb-7f27d6c8382f)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/8e60db39-81e4-41f6-9e59-3f77073c9ad3)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/a2a705ed-1bb0-4592-841b-a68c47ee117d)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/ea76fff3-97c0-4f3b-87cd-04bee9e5714c)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/55f94f7e-8156-4742-ab4f-cf4ba74b2c54)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/6fa4be48-c9d8-4443-a7da-e0a582adc515)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/79d7f83c-40fb-4d16-83e7-793a73acdc44)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/dca281f5-d3e2-49c0-9ad3-6b8b642d2139)

**Comment by marcdap** [comment]
@cgarofalo has done a really good job with the images. I will complement the ones attached to his comment with images related to the mentioned [PR in the description](https://github.com/WordPress/gutenberg/pull/43646).


https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/10672997-e642-438d-b0ec-7728229511a0

#### Dimensions

<img width="281" alt="dimensions" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/7cf0d892-2ae0-4806-aca5-dd961a01051c">

#### Dimensions clickable area

<img width="286" alt="dimensions-click" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/958adcb0-ca99-4909-a425-392bc5128aa3">

#### Dimensions properties

<img width="281" alt="dimensions-properties" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/b4853ef3-0d7c-43cc-b9c1-1674fccbfc8b">

#### Dimensions selected properties

<img width="281" alt="dimensions properties-selected" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/95eee423-b2d5-40a6-a4fb-b9b5dba0f8eb">

#### Dimensions padding visualization

<img width="1020" alt="dimensions-padding-viewer" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/17d7f0ea-79be-40d4-ab2c-cc4bf6c70ff4">

#### Dimensions margin visualization 

<img width="1076" alt="dimensions-margin-viewer" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/6824357/0e4427ed-4b3e-4ecf-b029-7d57b33f0a1a">

**Comment by zzap** [comment]
@Leonardus-Nugraha I have reviewed and published scheduled updates made by @carolinan. You can continue with updates from @marcdap :raised_hands:
