### ISSUE TITLE
[HelpHub] Comments block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#696]
Article:  https://wordpress.org/documentation/article/comments-block/

## Update for 6.2
- [ ] Follow discussion settings in the comments block edit. [44463](https://github.com/WordPress/gutenberg/pull/44463)
- [ ] Add spacing support [45102](https://github.com/WordPress/gutenberg/pull/45102)
- [ ]  Add help text on the HTML element for the Comments and Query Loop blocks [46989](https://github.com/WordPress/gutenberg/pull/46989)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by ratneshsonar** [comment]
Hello @femkreations, please assign this task to me.

**Comment by carolinan** [comment]
The information about the spacing support has already been added to this article.
What remains is:

- Removing the more options
- Adding new screenshot of the tabbed interface for block settings
- If needed, a new video with the new settings icon (the cog icon was replaced).

**Comment by Ignasrimkunas** [comment]
Heya @Leonardus-Nugraha I will fix this one real quick since I can see it's been inactive for a while

**Comment by emmasophieyoung** [comment]
first review done

**Comment by Leonardus-Nugraha** [comment]
Content updated, thanks @carolinan , @Ignasrimkunas , @emmasophieyoung !
