### ISSUE TITLE
[HelpHub] Columns block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#698]
Article:  https://wordpress.org/documentation/article/columns-block/

## Update for 6.2
- [x] Add transform to unwrap the contents. [45666](https://github.com/WordPress/gutenberg/pull/45666)
- [x] Fix missing border regression. [44696](https://github.com/WordPress/gutenberg/pull/44696)
- [x] Move block variation picker styles in the iframe [47109](https://github.com/WordPress/gutenberg/pull/47109)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1Z4LDlDOvElJKYeRoFHudTlab-9hZgPLZsQjIBElHfFE/edit#heading=h.agzou5iryxk7

first review done

**Comment by Leonardus-Nugraha** [comment]
Content updated, thanks @Ignasrimkunas & @emmasophieyoung !
