### ISSUE TITLE
Giving WordPress Its Own Directory

### ISSUE THREAD

**Issue by basilhendroff** [WordPress/Documentation-Issue-Tracker#7]
### Source article
[Giving WordPress Its Own Directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)
### The problem I'm having
There are multiple issues with this article. See https://wordpress.org/support/topic/giving-wordpress-its-own-directory-24/.

### Suggested improvements
1. [Moving a Root install to its own directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#moving-a-root-install-to-its-own-directory)
This section is misleading. What’s impacted is the WordPress Address URL, not the Site Address URL. The site is still accessed at https://example.com. What changes between method I and II is that WordPress is accessed at https://example.com (Method I) or https://example.com/subdir (Method II). Suggested update:

>### Moving a Root install to its own directory [#](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#moving-a-root-install-to-its-own-directory)
>Let’s say you’ve installed WordPress at `example.com`. Now you have two different methods to move WordPress installations into a subdirectory:
>
>1) Without a change in the WordPress URL (remains `example.com`)
>
>2) With a change in the WordPress URL (it will redirect to `example.com/subdirectory`)

2. [Method II (With URL change)](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-ii-with-url-change)
Here’s an instance where Google backfires. A search reveals there are many opinions on what constitutes WP core files. The intent of the article is that core means the whole WP installation. I believe the best way to address this is to remove the word ‘core’ from this section.

3. [.htaccess modification](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#htaccess-modification)
The heading level and the placement of this section suggests that it is related to Method II. In fact, it appears to be more closely aligned to Method I.  Suggested update: Move this section before the main section [Method II (With URL change)](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-ii-with-url-change). This will make it clearer that it's associated with section [Method I (Without URL change)](https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-i-without-url-change)

### References
1. [Giving WordPress Its Own Directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)
2. https://wordpress.org/support/topic/giving-wordpress-its-own-directory-24/

**Comment by atachibana** [comment]
New repository "Advanced Administration" was created, and this page will be moved to there. Continue the discussion at this issue:
https://github.com/WordPress/Advanced-administration-handbook/issues/106
