### ISSUE TITLE
Add XSS warning to page for remove_query_arg

### ISSUE THREAD

**Issue by roytanck** [WordPress/Documentation-Issue-Tracker#703]
## Issue Description
The function `remove_query_arg` uses `add_query_arg`. On the page for the second function, there's a warning about the return value not being escaped. There is no such warning for `remove_query_arg`.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/functions/remove_query_arg/

## Section of Page with the issue
I would add this to the description section.

## Why is this a problem?
Not escaping the return value of `remove_query_arg` can cause severe cross-site scripting vulnerabilities.

## Suggested Fix
I would suggest added a similar warning to the docs for `remove_query_arg`, since it applies there too, and readers may not always follow the link to `add_query_arg`.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by roytanck** [comment]
After reading more about how the developer docs are generated, I created a Trac ticket with a patch: https://core.trac.wordpress.org/ticket/57885 .

**Comment by roytanck** [comment]
My patch was merged for WP 6.2.
