### ISSUE TITLE
[HelpHub] Some asset resource not found on Pagination Block

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#708]
## Issue Description

Missing screenshot, it is in the database but WP is not reading it.

## URL of the Page with the Issue

wordpress.org/documentation/article/pagination-block/

## Section of Page with the issue

https://wordpress.org/documentation/article/pagination-block/#block-settings 

under **Settings**

## Why is this a problem?

missing image

## Suggested Fix

maybe is best to upload again.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by estelaris** [comment]
Issue was open in meta trac [#6827](https://meta.trac.wordpress.org/ticket/6827). Closing that ticket now

**Comment by femkreations** [comment]
Uploaded a new screenshot. Closing this issue
