### ISSUE TITLE
[HelpHub] Dimension Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#710]
Article:  https://wordpress.org/documentation/article/dimension-controls-overview/

## Update for 6.2
- [ ] Layout child fixed size should not be fixed by default and should always have a value set. [46139](https://github.com/WordPress/gutenberg/pull/46139)
- [ ] Add a minHeight block support under dimensions [45300](https://github.com/WordPress/gutenberg/pull/45300)
- [ ] Min Height: Add height control component with slider [45875](https://github.com/WordPress/gutenberg/pull/45875)
- [ ] Adjust the custom range steps to match the units chosen [44959](https://github.com/WordPress/gutenberg/pull/44959)
- [ ] Spacing Sizes Control: Try improving layout spacing [44858](https://github.com/WordPress/gutenberg/pull/44858)
- [ ] Spacing presets: switch to using numbers instead of t-shirt sizes for labels [44247](https://github.com/WordPress/gutenberg/pull/44247)
- [ ] SpacingSizesControl: Increase slider's max value to 300 [44956](https://github.com/WordPress/gutenberg/pull/44956)
- [ ] Modify the styling of the input controls when in unlinked mode [44141](https://github.com/WordPress/gutenberg/pull/44141)
- [ ] ToolsPanel: Add subheadings and reset text to tools panel menu [44260](https://github.com/WordPress/gutenberg/pull/44260)
- [ ] Try: Polish link/unlink buttons  [43802](https://github.com/WordPress/gutenberg/pull/43802)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by annezazu** [comment]
Some notes for future reference as I go through evaluating what needs to be updated. Much of the following are very minor, more technical changes that don't greatly impact the integrity of the documentation from my point of view (new feature, new design, big new ability, etc). Some of these also were a part of 6.1, like this: https://github.com/WordPress/gutenberg/pull/44858 and this: https://github.com/WordPress/gutenberg/pull/44247

As a result, I'm going to focus on updating the following:

- Add a minHeight block support under dimensions https://github.com/WordPress/gutenberg/pull/45300 This was already available with the Cover block but has been expanded.
-  ToolsPanel: Add subheadings and reset text to tools panel menu https://github.com/WordPress/gutenberg/pull/44260
-  SpacingSizesControl: Increase slider's max value to 300 (impacts padding and margin) https://github.com/WordPress/gutenberg/pull/44956

**Comment by annezazu** [comment]
Updated a few screenshots/visuals, including a lower quality GIF with a video as that's more accessibility friendly and easier to see. I included some brief information about the minimum height pulled from the dev note as I think this is a bit confusing to use otherwise: https://make.wordpress.org/core/2023/03/06/minimum-height-dimensions-block-support/

The demonstration video was busted so I replaced it with the video from here: https://make.wordpress.org/core/2022/09/26/core-editor-improvement-catalyst-for-creativity/
