### ISSUE TITLE
[HelpHub] Position Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#712]
## New page for 6.2
- [ ] Create a new article for the Position Settings overview  [Add a Position block support (including sticky), decoupled from layout ](https://github.com/WordPress/gutenberg/pull/46142)
- [ ] Make sure the URL slug under Permalink is: position-settings-overview
- [ ] Link this page to the Group block/ Row and Stack block and any other page that has Position settings in the Block settings sidebar

## Update for 6.2
- [ ] Sticky Position: Hide controls if the block is non-root (has parents) [47334](https://github.com/WordPress/gutenberg/pull/47334)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by annezazu** [comment]
Published: https://wordpress.org/documentation/article/position-settings-overview/ 

Based it off of https://wordpress.org/documentation/article/layout-settings-overview/ to have some overlap in structure.
