### ISSUE TITLE
[HelpHub] Border Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#717]
Article:  https://wordpress.org/documentation/article/border-settings-overview/

## Update for 6.2
- [ ] Try: Polish link/unlink buttons. [43802](https://github.com/WordPress/gutenberg/pull/43802)
- [ ] Border Controls: Update control components to allow 40px height [41860](https://github.com/WordPress/gutenberg/pull/41860)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by carolinan** [comment]
These changes have been published:
Updated screenshots
Updated the list of blocks that has border settings

**Comment by Leonardus-Nugraha** [comment]
Updated block styles to emphasize important links
Ready for 2nd review

**Comment by jomarieminney** [comment]
Reviewed and confirmed:
- [x]  Make sure all screenshots are relevant to the latest version
- [x]  Make sure videos, if any, are up to date
- [x]   Add ALT tags for the images
- [x]  Make sure the headings are in sentence case
- [x]   Convert all reusable blocks to a ‘regular block’.
- [x]  Update the changelog at the end of the article

All content looks good also :)

I think this one can be closed @femkreations
