### ISSUE TITLE
Writing issue in Plugin Handbook

### ISSUE THREAD

**Issue by kojidi** [WordPress/Documentation-Issue-Tracker#721]
## Issue Description

There is a writing issue in plugin handbook documentation

## URL of the Page with the Issue

https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/

## Section of Page with the issue

Third paragraph

## Why is this a problem?

In line two of third paragraph we have two "to" (the "to" has repeated)
the sentence is: When your plugin is uninstalled, you’ll want to clear out any plugin options and/or settings specific to to the plugin, and/or other database entities such as tables.

## Suggested Fix

the correct sentence should be: When your plugin is uninstalled, you’ll want to clear out any plugin options and/or settings specific to the plugin, and/or other database entities such as tables.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision.
