### ISSUE TITLE
[HelpHub] Feedback on WordPress Privacy

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#736]
## Issue Description

Originally reported by https://profiles.wordpress.org/mujuonly/ @mujuonly 

>“https://wordpress.org/plugins/gdpr/ Link two is built by a well-respected development shop and does Explicit Consent the way it should be, but link one is less endorsement-heavy.” – The plugin mentioned in the section above is last updated 3 years ago.This plugin hasn’t been tested with the latest 3 major releases of WordPress.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/wordpress-privacy/

## Section of Page with the issue

[Consent of data collected](https://wordpress.org/documentation/article/wordpress-privacy/#consent-of-data-collected)

**Comment by javiercasares** [comment]
@zzap should we really move Privacy information to the Advanced Handbook?

Privacy, and all the laws related (like GDPR) are a basic concern to all users, and everybody (if you have a blog, it applies) should be concerned about this.

Maybe we can do a big check for all the information there, but I think it is best to leave the page in the HelpHub.

**Comment by javiercasares** [comment]
I've been reading and checking the page, and I think we can delete the part about "Various notes:". Those notes are deprecated and doesn't contribute anything.

Moreover, probably add in some places a link to the Learn WordPress tutorial https://learn.wordpress.org/tutorial/manage-settings-privacy/

In any case, some images of the tools (sections in the WordPress Dashboard) may be great, but everything looks fine to me.

**Comment by zzap** [comment]
Section removed :raised_hands: thanks
