### ISSUE TITLE
[HelpHub] Feedback on Manage Plugins

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#739]
## Issue Description
Originally reported by https://profiles.wordpress.org/yvonnevanleeuwen/

>thanks for this, can you give instruction on manual plugin re-installation, into file manager?

## URL of the Page with the Issue

https://wordpress.org/documentation/article/manage-plugins/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
Please review this.

URL: https://wordpress.org/documentation/article/manage-plugins/

### Manual Plugin Installation

... Here are the detailed instructions to manually install a WordPress plugin by transferring the files onto the webserver.

\<ADD>

1. Download the plugin zip file from the [WordPress Plugin Directory](https://wordpress.org/plugins/) and unzip it locally. For example, in the case of Gutenberg plugin, download as gutenberg.X.Y.Z.zip (X.Y.Z is version)  and unzip it to get the gutenberg/ folder.
2. Transfer the extracted folder to the wp-content/plugins directory of your WordPress site via SFTP or remote file manager.
3. From the Plugins menu in the Administration Screen, click Activate for the transferred plugin.

\</ADD>

## Uninstalling Plugins

\<ADD>
### Manual Uninstallation
In rare cases, you may need to uninstall a plugin by manually deleting the files from the server. This is recommended only when absolutely necessary, for example when your server is not configured to allow automatic uninstallations.

1. From the Plugins menu in the Administratio Screen, click Deactivate for your plugin.
2. Access to your WordPress site via remote file manager.
3. Go to wp-content/plugins directory.
4. Remove your plugin folder.

\</ADD>


\<ADD>
# Reinstalling Plugins

To reinstall the plugin, refer to the documentation above, remove it once, and then install it.

\</ADD>

**Comment by atachibana** [comment]
No one in particular seems to have commented, so I have updated the page.
https://wordpress.org/documentation/article/manage-plugins/
