### ISSUE TITLE
Template Part Support Page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#74]
## What is the new page you are requesting?

An article describing what a template part block is and how best to use it, likely similar to Query Loop or other theme blocks.

## How will this new page help you?

It's part of a feature that will see greater adoption with WordPress 5.9's feature set.

**Comment by carolinan** [comment]
I have started on this, and I found it difficult to describe how:

- The settings are different depending on if it is a full site editing theme or a theme that supports template editing.
- The alignments depend on if the template part block is inside a block with "inherit default layout".
- The Replace option in the toolbar is only available if there is a template part to replace it with (requires theme.json in the theme).

https://wordpress.org/support/?p=15124095&post_type=helphub_article&preview=1&_ppp=d5f684b542

**Comment by annezazu** [comment]
Finally digging in here. Thanks for the patience. For starters, love the simplicity of this line:

>The template part block can be used with a block theme or a theme that has support for template editing.

Stealing it for the navigation block as I had a much clunkier one in place! I'd recommend moving this line after intro-ing, loosely, what it is. 

This is repeated twice:

>Template parts are used to manage blocks that are repeated across the website, for example, the site header and site footer.

I might also update it to say something closer to [what's in the glossary: ](https://developer.wordpress.org/block-editor/explanations/glossary/)

"Building on Block Templates, these parts help set structure for reusable items like a Footer or Header that one typically sees in a WordPress site. They are primarily site structure and are never to be mixed with the post content editor. With Full Site Editing and block based themes, users can create their own arbitrary Template Parts, save those in the database for their site, and re-use them throughout their site. Template parts are equivalent – in blocks – of theme template parts. They are generally defined by a theme first, carry some semantic meaning (could be swapped between themes such as a header), and can only be inserted in the site editor context (within “templates”)."

I'd have "Replacing one template part with another" at the same heading level as "Making changes to a template part".

P.S. For some reason the screenshots you included are a bit blurry for me.

**Comment by annezazu** [comment]
Alright! I dove in and built out this page today with sections similar to other advanced blocks, like the query loop block. As @carolinan noted, this is a tricky block to describe but I think this does it enough justice for now. 

Going to ship today in [light of this convo in slack](https://wordpress.slack.com/archives/C02RP4WU5/p1641317048292100) where current links in 5.9 RC1 are broken because these are not published. 

Going to keep this open for feedback though as I imagine we'll need to iterate cc @zzap @mkaz https://wordpress.org/support/?p=15124095&post_type=helphub_article&preview=1&_ppp=a24fdce4d9

Will loop back with a comment when live (need to finish edits to the Template editor 😅 ).

**Comment by annezazu** [comment]
Noting I had to make some changes since this PR wasn't backported for RC1 (I added way more than I needed to 🤦🏼 ): https://github.com/WordPress/gutenberg/pull/36571

**Comment by annezazu** [comment]
Shipped: https://wordpress.org/support/article/template-part-block/
