### ISSUE TITLE
[HelpHub] Feedback on Post Title Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#744]
## Issue Description

Originally reported by https://profiles.wordpress.org/tech5061/

>This article dos not outline, mention or link to information pertaining to removeing the the title completely.

## URL of the Page with the Issue

https://wordpress.org/documentation/article/post-title-block/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
Please review this. I will also insert missing images from #510 during this modification.

URL https://wordpress.org/documentation/article/post-title-block/

\<ADD> at the bottom section.

## Hiding Post Titles

When you are using a theme that supports the Site Editor, you can hide the post title by removing this Post Title block.

1. Launch Site Editor from Appearance > Editor in Administration Screen and select template that you want to remove the post title.
2. Select Post Title Block
3. Click More options (3 dot icon)  from the Block Toolbar.
4. Click Remove Post Title.
5. Click Save at the top right.

\</ADD>

**Comment by atachibana** [comment]
No one in particular seems to have commented, so I have updated the page.
https://wordpress.org/documentation/article/post-title-block/
