### ISSUE TITLE
[HelpHub] Feedback on File Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#754]
## Issue Description
Originally reported by https://profiles.wordpress.org/jcoonrod/

>Please include details on the three-dot menu. It offers the word “Present” which doesn’t seem to do anything (although I was expecting a full screen display)

## URL of the Page with the Issue

https://wordpress.org/documentation/article/file-block/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
I don't know and could not find the word "Present" in the trhee-dot menu.
However, it is true that there is no detailed description of the 3-dot menu. I would like to replace the current More options section with the following explanation in [Paragraph Block](https://wordpress.org/documentation/article/paragraph-block/).

## More options
The Options menu represented by three vertical dots on the far right of the toolbar gives you more features such as the ability to duplicate or remove the block.

**Comment by atachibana** [comment]
Since there seems to be no particular comment, I have reflected the changes.
