### ISSUE TITLE
[HelpHub] Feedback on CSS

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#761]
## Issue Description
Originally reported by https://profiles.wordpress.org/djcuppat/

>There is no mention of Custom CSS being absent when using the new block-based editor
Also the page begins with templates and template tags when stylesheets are the more relevant. These should appear later to avoid developers having to trawl content that is less relevant

## URL of the Page with the Issue

https://wordpress.org/documentation/article/css/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
The top of the article already describes the location of the new custom CSS.
As for the order of templates and template tags, it is not too much and should be fine as it is now.
