### ISSUE TITLE
[HelpHub] Feedback on Manage WordPress widgets

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#772]
## Issue Description
Originally reported by https://profiles.wordpress.org/abitofmind/

> The introduction section shall give and idea what widgets are and what’s their purpose:
> 
> “Widgets were originally designed to provide a simple and easy-to-use way of giving design and structure control of the WordPress Theme […] Some WordPress Widgets offer customization and options such as forms to fill out, includes or excludes of data and information, optional images, and other customization features.”
> 
> What I miss: General content, that is the same on all pages/posts? Or are there also widgets which are context sensitive, as in specific to the currently opened page/post? E.g. a widget like “Similar articles: …”.
> 
> This characterization is missing. Please amend accordingly. Thanks!

## URL of the Page with the Issue

https://wordpress.org/documentation/article/manage-wordpress-widgets/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
I would like to replace the first line:

> WordPress Widgets add content and features to your Sidebars. Examples are ...

with the following sentence:

WordPress widgets add content and functionality to the widget area. The widget area is a pre-defined area by the theme, typically located in the sidebar or footer, but varies from theme to theme. Examples are ...

**Comment by atachibana** [comment]
The article has been updated.
