### ISSUE TITLE
Delete Optimization page in HelpHub

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#795]
## Issue Description
The "Optimization" page in HelpHub should be deleted since the page has been migrated to Advanced Administration Handbook and made available after the publication of the Handbook.

The content of the page also belong to the Handbook.

## URL of the Page with the Issue
"Optimization" page in HelpHub
https://wordpress.org/documentation/article/optimization/

"Optimization" page in Advanced Administration Handbook
https://developer.wordpress.org/advanced-administration/performance/optimization/

## Why is this a problem?
Duplicate and the content doesn't belong in the right domain.

## Suggested Fix
Delete the page in HelpHub.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by stevenlinx** [comment]
[PR 230 in AAH](https://github.com/WordPress/Advanced-administration-handbook/pull/230) has been approved as outlined above; hence, deleting the corresponding HelpHub version and close this Issue.

**Comment by sabernhardt** [comment]
This page has two links to it from Site Health.
See [Trac 58518](https://core.trac.wordpress.org/ticket/58518).
