### ISSUE TITLE
Code block backticks being converted causing display issues

### ISSUE THREAD

**Issue by kdevnel** [WordPress/Documentation-Issue-Tracker#796]
## Issue Description

When you visit the [wp-env run [container] [command]](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#wp-env-run-container-command) section of the wp-env documentation, there is a callout that with a shell code block.

It looks like the backticks are correct in the repo, but the backticks are being converted on the frontend and causing the formatting to break.

## URL of the Page with the Issue

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/

## Section of Page with the issue

[wp-env run [container] [command]](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#wp-env-run-container-command) section of the wp-env documentation is a callout that with a shell code block.

## Why is this a problem?

The code block isn't displaying correctly

## Suggested Fix

I'm uncertain - I suspect something in the build process or display of the content is leading to the backticks being converted to quotation marks instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
Opened PR in Gutenberg repo https://github.com/WordPress/gutenberg/pull/50090

Thank you for reporting @kdevnel
