### ISSUE TITLE
Contributor Day — 25th April, 2023

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Documentation-Issue-Tracker#799]
## Welcome to the second online WordPress Documentation team's Contributor Day

This is the second online Make WordPress Documentation Team’s independently-led Contributor Day. It’s also the first of the monthly Contributor Days that are held the fourth Tuesday of each month.

You can join us via [Zoom](https://us02web.zoom.us/j/84954615529?pwd=cGxqK2w1SHVWMURhTzNIZVVtM2J3UT09) on 25th April, between 1 PM UTC and 4 PM UTC.

### For those attending this Contributor Day

If you attend this Contributor Day, please comment below with:

1. Your WordPress.org profile username
2. Link(s) to the issue(s) you're working on during the Contributor Day

People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us02web.zoom.us/j/84954615529?pwd=cGxqK2w1SHVWMURhTzNIZVVtM2J3UT09):  @zzap, @estelaris, @Leonardus-Nugraha, @javiercasares, @jennimckinnon

### New contributors

If this is your first time contributing to the Documentation team, please make sure you have the following accounts:

[WordPress.org account](https://login.wordpress.org/register).
[WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
[GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).
Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :)

Following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:

[General overview](https://wordpress.tv/2022/06/21/milana-cap-overview-onboarding-for-wordpress-documentation-team/)
[End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
[Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

For general details on how GitHub works, check out [GitHub’s Getting Started Guide](https://docs.github.com/en/get-started/quickstart/hello-world).

When you find issue you'd like to work on in the [Docs Team Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) here on GitHub:

1.  Please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue, and
2. In that comment, also be sure to tag the [team rep responsible for the handbook](https://make.wordpress.org/docs/handbook/the-team/) that your chosen task is about.

For example, if your task is for the Block Editor End-User documentation, you would tag @femkreations.

Check out the [Team page in the Documentation Team Handbook](https://make.wordpress.org/docs/handbook/the-team/) for a list of team reps.

### General task list

Tasks we plan to work on during the day:

#### 1. Updating block editor end user documentation

6.2 - [medium priority](https://github.com/orgs/WordPress/projects/67/views/10)
6.1 - [normal priority](https://github.com/orgs/WordPress/projects/45/views/2)
6.0 - [updating existing docs](https://github.com/orgs/WordPress/projects/28/views/11)

#### 2. Content review for mobile app end-user articles

[Mobile app content review board](https://github.com/orgs/WordPress/projects/89/views/1)

Person to go ask for help: @estelaris, @zzap

#### 3. Content review for older documentation

 https://github.com/WordPress/Documentation-Issue-Tracker/issues/388
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/373
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/372
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/475
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/473
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/472
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/471
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/470
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/469
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/458
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/457
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/455
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/452
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/443
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/442
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/438
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/432
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/430
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/429
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/428
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/427
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/426
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/425
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/424
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/420
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/418
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/371
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/192
 https://github.com/WordPress/Documentation-Issue-Tracker/issues/190

Person to go ask for help: @estelaris, @zzap

#### 4. Review all articles to confirm images and links are working. Several articles have broken links since the migration. Open individual tickets

Example: 
https://meta.trac.wordpress.org/ticket/6944

People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us02web.zoom.us/j/84954615529?pwd=cGxqK2w1SHVWMURhTzNIZVVtM2J3UT09): @zzap, @estelaris, @Leonardus-Nugraha, @jennimckinnon, @femkreations

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by Leonardus-Nugraha** [comment]
Reviewed and updated #695 and #281

**Comment by zzap** [comment]
- closed [7 issues](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+sort%3Aupdated-desc+updated%3A2023-04-25+assignee%3Azzap)
- opened [6 issues](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+sort%3Aupdated-desc+created%3A2023-04-25+author%3Azzap+)
- opened [3 PRs](https://github.com/WordPress/Advanced-administration-handbook/pulls?q=is%3Apr+is%3Aclosed+author%3Azzap+created%3A2023-04-25) for advanced administration

**Comment by femkreations** [comment]
Reviewed and closed #485

**Comment by jennimckinnon** [comment]
- Updated the Welcome Box on the Make WordPress Docs Team page
- Onboarding
