### ISSUE TITLE
404 — File not found.

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#800]
I have found two issues in the documentation.

The first issue is that the video URL to a "404 - File not found" error. This means that the video cannot be accessed as the file does not exist or has been moved or deleted.

The second issue is that there is an error being displayed on console for both pages stating that "JQuery is not defined".

Attached screenshot for your reference.

Both url here,
https://wordpress.org/documentation/article/page-jumps/
https://wordpress.org/documentation/article/media-text-block/

And also i have create one tickets please check and respond it.
https://meta.trac.wordpress.org/ticket/6948

![filenotfound](https://user-images.githubusercontent.com/45058029/234183892-31619ca1-eba2-4e3d-8d30-986ab5f24023.png)
![mediatext](https://user-images.githubusercontent.com/45058029/234183898-7a5d08d7-8e36-4dd5-997d-155f774713f1.png)
![pagejump](https://user-images.githubusercontent.com/45058029/234183903-914dba15-7461-405d-b8ec-3fb2a2bb42a2.png)
![videonotshowing](https://user-images.githubusercontent.com/45058029/234183910-de470bdb-e17b-4fd8-bf19-5758adbe2c9d.png)
![videourl](https://user-images.githubusercontent.com/45058029/234183912-75ed986e-13b1-4e3b-ac41-6ca4398350ae.png)

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by estelaris** [comment]
@utsavtilava thank you for reporting this. We are looking into all the articles as many lost the linked files during the migration to the new site.

**Comment by zzap** [comment]
This is now fixed. Thank you for reporting @utsavtilava
