### ISSUE TITLE
Incorrect Image src on Verse Block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#801]
## Issue Description
Some Images are not working on the Verse Block theme documentation page. Looks like the incorrect src of image.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/verse-block/

## Section of Page with the issue
Italic

## Why is this a problem?
Incorrect src of image.

## Suggested Fix
Correct URL : https://wordpress.org/documentation/files/2022/02/image-10.png

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
This is fixed now. Thank you for reporting, @utsavtilava
