### ISSUE TITLE
video URL to a "404 - File not found" error.

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#802]
## Issue Description

Video are not working on the Columns Block theme documentation page. Looks like the incorrect URL of video.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/columns-block/

## Section of Page with the issue
Adding and removing columns

## Why is this a problem?
incorrect URL of video.

## Suggested Fix
1) 
https://wordpress.org/documentation/files/2022/12/199975393-3619361f-0045-4a67-97e8-0e738885c4fe-1.mp4

Replace to

https://wordpress.org/documentation/files/2022/12/199975393-3619361f-0045-4a67-97e8-0e738885c4fe.mp4

2)
https://wordpress.org/documentation/files/2022/12/199975406-b6473bd1-9f08-444c-bad2-6dead8b4fd25-1.mp4

Replace to

https://wordpress.org/documentation/files/2022/12/199975406-b6473bd1-9f08-444c-bad2-6dead8b4fd25.mp4

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by sagargurnani99** [comment]
Is this issue already fixed? I had a quick look and couldn't find any "404-File not found" urls. However, I could see only one video on the page which is working fine the other one is a Gif. And, the video has a different URL than the two suggested above in the issue description.
• https://wordpress.org/documentation/files/2023/05/200948093-38384e83-9f5c-4cb3-bc42-75692c1cf125.mp4

**Comment by zzap** [comment]
I'm closing this one ass fixed.
