### ISSUE TITLE
Incorrect Image src on Custom Link Block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#803]
## Issue Description
Images are not working on the Custom Link Block documentation page. Looks like the incorrect src of image.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/custom-link-block/#block-settings

## Section of Page with the issue
Advanced

## Why is this a problem?
Incorrect src of image.

## Suggested Fix
https://wordpress.org/documentation/files/2022/12/image10-1.png

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
