### ISSUE TITLE
Video URL to a "404 - File not found" on Pagination Block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#804]
## Issue Description
Video are not working on the Columns Block theme documentation page. Looks like the incorrect URL of video.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/pagination-block/

## Section of Page with the issue
Advanced

## Why is this a problem?
incorrect URL of video.

## Suggested Fix
https://wordpress.org/documentation/files/2022/12/186367483-ac40069f-850a-4602-a576-e0b4483d5906.mp4

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
Closing this as fixed. Thank you for reporting, @utsavtilava
