### ISSUE TITLE
Incorrect Image src on Post Navigation Link Block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#805]
## Issue Description
Images are not working on the Post Navigation Link Block documentation page. Looks like the incorrect src of image.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/post-navigation-link-block/

## Section of Page with the issue
Move arrows
Change text alignment

## Why is this a problem?
Incorrect src of image.

## Suggested Fix
1) 

https://wordpress.org/documentation/files/2022/12/image9-2-1.png

Replace to

https://wordpress.org/documentation/files/2022/12/image9-2.png

2)
https://wordpress.org/documentation/files/2022/12/image5-3-1.png

Replace to

https://wordpress.org/documentation/files/2022/12/image5-3.png

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
Closing this as fixed. Thank you for reporting, @utsavtilava
