### ISSUE TITLE
Incorrect Image src on Post Title Block

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Documentation-Issue-Tracker#806]
## Issue Description
Images are not working on the Post Title Block documentation page. Looks like the incorrect src of image.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/post-title-block/

## Section of Page with the issue
Change heading level
Change text alignment
More options
Block Settings

## Why is this a problem?
Incorrect src of image.

## Suggested Fix
1)
Change heading level : https://wordpress.org/documentation/files/2022/12/197789888-94cf061b-bd58-4c39-8ec0-831af1487876.png

2)
Change text alignment : https://wordpress.org/documentation/files/2022/12/197790114-2f67aa11-4fe9-4b53-85d9-5159aec73d2d.png

3)
More options : https://wordpress.org/documentation/files/2022/12/197790861-7f625210-750d-4de1-b63e-cfea4a31fa75.png

4)
Block Settings : https://wordpress.org/documentation/files/2022/12/198240157-92e67cde-cf4b-4631-b6d9-cccf0dc8e698-278x1024.png

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
Closing this as fixed. Thank you for reporting, @utsavtilava
