### ISSUE TITLE
Deciding how to call the PHP based themes

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#81]
As theme team is currently updating the [Theme Handbook](https://developer.wordpress.org/themes/), Theme Handbook main page will act as a gateway with two links to each theme.  We will need to decide how to call the PHP based themes. 

Most of us have been calling as Classic Theme.

**Comment by TeBenachi** [comment]
At the theme team meeting, we had a productive discussion and decided Classic Themes is preferable. 

https://wordpress.slack.com/archives/C02RP4Y3K/p1639495209432600

**Comment by kafleg** [comment]
We agreed on:

**Classic Themes
Block Themes**
