### ISSUE TITLE
Wrong url for sanitize_email link under sanitization functions.

### ISSUE THREAD

**Issue by absikandar** [WordPress/Documentation-Issue-Tracker#817]
## Issue Description

On the Sanitizing Data page the link to sanitize_email() is wrong.   

Here is a screenshot of the issue. https://www.screencast.com/t/tLk0kv9Pyn0 

## URL of the Page with the Issue

https://developer.wordpress.org/apis/security/sanitizing/

## Section of Page with the issue

https://developer.wordpress.org/apis/security/sanitizing/#sanitization-functions

## Suggested Fix

The correct link should be https://developer.wordpress.org/reference/functions/sanitize_email/

I hope it helps. 

Thanks

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by sagargurnani99** [comment]
I am interested to work on this. Please let me know me how to proceed further.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've revised the content.
