### ISSUE TITLE
All Settings Screen section of Options does not show how to load it.

### ISSUE THREAD

**Issue by ecotechie** [WordPress/Documentation-Issue-Tracker#818]
## Issue Description
All Settings Screen section of Options does not show how to load it.

## URL of the Page with the Issue
https://developer.wordpress.org/apis/options/#all-settings-screen

## Section of Page with the issue
[All Settings Screen](https://developer.wordpress.org/apis/options/#all-settings-screen)

## Why is this a problem?
This section mentions an option but no way to see it.

## Suggested Fix
Mention /wp-admin/options.php as the location of the page.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by ecotechie** [comment]
Also, the link to 3.0 in that section does not work. I could not find a replacement or where it mentioned this feature being removed in that version.

**Comment by creative-andrew** [comment]
https://developer.wordpress.org/apis/options/#all-settings-screen

- Fixed several typos.
- Added /wp-admin/options.php how access that All Settings Screen

New suggested text:

[WordPress 3.0](https://developer.wordpress.org/support/wordpress-version/version-3-0/) removed Settings > Miscellaneous screen and some of the options cannot be reached (ex. upload_url_path). You may use the All Settings Screen to view and change almost all options listed above. It is accessible by visiting `/wp-admin/options.php`
