### ISSUE TITLE
Meetup Embed Block page still published and showing in search results

### ISSUE THREAD

**Issue by jomarieminney** [WordPress/Documentation-Issue-Tracker#820]
## Issue Description
The meetup embed block was removed from the blocks list, but the URL is still indexed which is confusing for users. There is nothing on the page to show that the block is no longer available.
## URL of the Page with the Issue
https://wordpress.org/documentation/article/meetup-embed/

## Section of Page with the issue
The whole page... as the block is no longer available

## Why is this a problem?
The page still shows in the top few records of the Google search results for terms such as 'Meetup Embed WordPress' even though the block was removed from the [Blocks List](https://wordpress.org/documentation/article/blocks-list/) on 2022-07-18.

## Suggested Fix
A good way to fix this **without deleting the page** might be to:
1. Add a notice at the top of the page that the block is no longer available - suggested text below
2. Add something at the bottom of the page to the changelog.

Alternatively, just unpublish the page entirely so that it no longer shows in search results.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by zzap** [comment]
This issue hanged for too long. I unpublished the post.
