### ISSUE TITLE
[HelpHub] Feedback on Meetup Embed

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#821]
## Issue Description
Originally reported by https://profiles.wordpress.org/jominney/

>I can see that you have removed the Meetup.com Block page however it is still indexed and showing in Google Searches 🙂

## URL of the Page with the Issue

https://wordpress.org/documentation/article/meetup-embed/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by jomarieminney** [comment]
Heads up @zzap i already submitted an issue for this a few days ago

**Comment by zzap** [comment]
Article is unpublished as the block is no longer available.
