### ISSUE TITLE
[HelpHub] Feedback on Categories Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#825]
## Issue Description
Originally reported by https://profiles.wordpress.org/cdillon27/

>It is now called Categories List.

## URL of the Page with the Issue

https://wordpress.org/documentation/article/categories-block/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by jomarieminney** [comment]
The categories block was renamed 'categories list' and the 'post categories' block was renamed to simply be 'categories' as per [#39837](https://github.com/WordPress/gutenberg/pull/39837). Both '[categories](https://wordpress.org/documentation/article/categories-block/)' and '[post categories](https://wordpress.org/documentation/article/post-categories-block/)' block documentation should be updated to reflect the changes in nomenclature. The actual change was done late 2022 when the block(s) were updated to reflect taxonomies on CPTs as well as posts.

This should be an easy fix - just replace any reference to 'Categories Block' to 'Categories List Block' and any reference to 'Post Categories Block' to 'Categories Block'. This also needs to be done on [the Blocks List page](https://wordpress.org/documentation/article/blocks-list/).

**Comment by cgarofalo** [comment]
Hello, I will be grabbing this issue! (WC2023)

**Comment by shabnam611** [comment]
Created draft for the following changes:

Both '[categories](https://wordpress.org/documentation/article/categories-block/)' and '[post categories](https://wordpress.org/documentation/article/post-categories-block/)' block documentation

working on blocks list page.

**Comment by shabnam611** [comment]
Also checked the [Blocks list page](https://wordpress.org/documentation/article/blocks-list/) and made sure both '[categories](https://wordpress.org/documentation/article/categories-block/)' and '[post categories](https://wordpress.org/documentation/article/post-categories-block/)' block documentation has the references modified as required.

**Comment by shabnam611** [comment]
@zzap  @jennimckinnon  @Leonardus-Nugraha
kindly review this one.

**Comment by jomarieminney** [comment]
@estelaris these have been reviewed and the changes from the drafts created by @shabnam611 have been incorporated: 
[Categories List Block](https://wordpress.org/documentation/article/categories-block/)
[Categories Block](https://wordpress.org/documentation/article/post-categories-block/)
The slugs needs to be updated for both to reflect the titles:
/categories-block/ --> /categories-list- block/
/post-categories-block/ --> /categories-block/
Once slugs are updated, this issue can be closed.
