### ISSUE TITLE
Update Theme Handbook main page with links to each theme

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#83]
### Issue:
The block theme info is located in the Block Editor Handbook. When developers look for information on building themes, they most likely go to the Theme Handbook. 

### URL:
Themes section on Block Editor Handbook
https://developer.wordpress.org/block-editor/how-to-guides/themes/

### Suggested Fix:
Add a brief explanation and links to each theme to provide a clear distinction between Classic themes and Block themes on the [Theme Handbook main page.](https://developer.wordpress.org/themes/)

**Comment by TeBenachi** [comment]
Suggested text.  It should go after the 2nd paragraph, and before the step 1 on the [Theme Handbook](https://developer.wordpress.org/themes/). 


_There are two types of themes, the Classic theme, and the Block theme. The Classic theme is the original theme that is built on PHP. On the other hand, the Block theme is the new theme that is built mainly using HTML. The Block theme is composed entirely of blocks allowing users to take full advantage of the full site editor._ 

_Find out how to build the [Classic theme](https://developer.wordpress.org/themes/basics/). Or follow this link to learn how to build the [Block themes](https://developer.wordpress.org/block-editor/how-to-guides/themes/)._  



I'd appreciate any input. Thanks!

**Comment by carolinan** [comment]
>There are two types of themes:

Technically, there are also child themes, and there are hybrids, so I think we should avoid stating this?

**Comment by TeBenachi** [comment]
True. Thank you for your input. 

Revised suggestion:

**In this section, you can learn how to build** the Classic or Block themes. The classic theme is the original theme that primarily uses PHP. The block theme is a newer theme that is built mainly using HTML. The block theme is composed entirely of blocks allowing users to take full advantage of the full site editor.

Head over to the [Block Editor Handbook](https://developer.wordpress.org/block-editor/how-to-guides/themes/) if you are interested in learning about the block theme.

Continue reading if you are interested in building the [classic theme](https://developer.wordpress.org/themes/basics/).

**Comment by TeBenachi** [comment]
Closing this ticket as the Theme Handbook page has been updated.
https://developer.wordpress.org/themes/
