### ISSUE TITLE
sanitize_email() points to docs for sanitize_file_name() in Sanitising Data

### ISSUE THREAD

**Issue by annpocoyo** [WordPress/Documentation-Issue-Tracker#837]
## Issue Description

In the docs for Sanitising Data, the link to the docs for the function `sanitize_email()` points to `sanitize_file_name()`'s docs.

## URL of the Page with the Issue

https://developer.wordpress.org/apis/security/sanitizing/

## Section of Page with the issue

[Sanitization functions](https://developer.wordpress.org/apis/security/sanitizing/#sanitization-functions)

## Why is this a problem?

This may cause confusion for new developers.

## Suggested Fix

By fixing the link and make it point to `sanitize_email()`'s documentation.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by annpocoyo** [comment]
Sorry I accidentally summited an issue before writing it. I am editing it

**Comment by stevenlinx** [comment]
Thank you for filing.

This Issue is being handled over at #817.
