### ISSUE TITLE
[Theme Handbook Overhaul] Getting Started > What is a theme?

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#841]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "What is a theme?" under _Chapter 1: Getting Started_.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/133WkcwtkSoUsPMkHaTDZOIVyg9VKMcGISsV_ol2Z6r0/edit?usp=sharing

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by kafleg** [comment]
> The first draft of this is now finished and is available for review: https://docs.google.com/document/d/133WkcwtkSoUsPMkHaTDZOIVyg9VKMcGISsV_ol2Z6r0/edit?usp=sharing
> 
> **Important notes:**
> 
> * This will need a link review before it can live. The page currently has several links that point to upcoming pages that have not been written yet.

I checked the draft and looks good. I left a comment. You can check it.

**Comment by carolinan** [comment]
Looks good. I left 3 comments. I am mostly wondering if universal themes are still a phrase that is used.

**Comment by justintadlock** [comment]
Agreed that I haven't seen universal used much. I'd like to remove that section. I had to do a lot of digging just to figure out exactly what it was supposed to be.

**Comment by justintadlock** [comment]
Reworked some of the intro text around the different types of themes and removed the Universal section altogether. We might as well not add to the confusion with terminology that was never widely adopted.

**Comment by carolinan** [comment]
The changes look good to me.

**Comment by justintadlock** [comment]
Note that this page will replace the existing What is a theme? page: https://developer.wordpress.org/themes/getting-started/what-is-a-theme/

**Comment by justintadlock** [comment]
This page is now updated.
