### ISSUE TITLE
[Theme Handbook Overhaul] Getting Started > Who is this handbook for?

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#845]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Who is this handbook for?" under Chapter 1: Getting Started.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1pTUDQbuvh89ntRJbbhwudL7umQAJ0XuuHCpjaJYKnuQ/edit?usp=sharing

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by justintadlock** [comment]
The first draft of this documentation page is finished and ready for review: https://docs.google.com/document/d/1pTUDQbuvh89ntRJbbhwudL7umQAJ0XuuHCpjaJYKnuQ/edit?usp=sharing

**Important notes:**

- This will need a link review before it can go live. The page currently has several links that point to upcoming pages that have not been written yet.
- This is a rewrite of an [existing page](https://developer.wordpress.org/themes/getting-started/who-should-read-this-handbook/) in the handbook but is a part of the larger handbook overhaul.

**Comment by kafleg** [comment]
> The first draft of this documentation page is finished and ready for review: https://docs.google.com/document/d/1pTUDQbuvh89ntRJbbhwudL7umQAJ0XuuHCpjaJYKnuQ/edit?usp=sharing
> 
> **Important notes:**
> 
> * This will need a link review before it can go live. The page currently has several links that point to upcoming pages that have not been written yet.
> * This is a rewrite of an [existing page](https://developer.wordpress.org/themes/getting-started/who-should-read-this-handbook/) in the handbook but is a part of the larger handbook overhaul.

Looks good to me.

**Comment by carolinan** [comment]
Perfect, just missing the links, like mentioned above.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149311&action=edit

**Comment by kafleg** [comment]
You can publish this.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/getting-started/who-is-this-handbook-for/
