### ISSUE TITLE
[Theme Handbook Overhaul] Getting Started > Reading this handbook

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#847]
This ticket is a part of #816 and will be used for creating new page titled "Reading this handbook" under Chapter 1: Getting Started.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1XoxapCQ3uCus0tr7V40lgrJ-dMPDIZIY55Fus_ocMKc/edit?usp=sharing

**Some early thoughts:** I'll draft this separately, but it might be worth exploring combining this page and the "Who is this handbook for?" page: https://github.com/WordPress/Documentation-Issue-Tracker/issues/845. This isn't in need of an urgent decision, but I wanted to make a quick note of it for later

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by justintadlock** [comment]
The first draft of this documentation is finished and ready for review: https://docs.google.com/document/d/1XoxapCQ3uCus0tr7V40lgrJ-dMPDIZIY55Fus_ocMKc/edit?usp=sharing

**Important notes:**

- This will need a link review before it can go live. The page currently has several links that point to pages that have not been published yet.
- It is likely that this page will need a few edits as we move along in the handbook overhaul process. It is providing pathways for reading the handbook in the first section, which could potentially change. The current format is based upon the overall outline of the new handbook, but this is something to keep in mind as we get closer to publishing.

**Comment by kafleg** [comment]
> The first draft of this documentation is finished and ready for review: https://docs.google.com/document/d/1XoxapCQ3uCus0tr7V40lgrJ-dMPDIZIY55Fus_ocMKc/edit?usp=sharing
> 
> **Important notes:**
> 
> * This will need a link review before it can go live. The page currently has several links that point to pages that have not been published yet.
> * It is likely that this page will need a few edits as we move along in the handbook overhaul process. It is providing pathways for reading the handbook in the first section, which could potentially change. The current format is based upon the overall outline of the new handbook, but this is something to keep in mind as we get closer to publishing.

Looks good. It is ready to go.

**Comment by carolinan** [comment]
Thank you, I've left some comments. I think the switch from "Your next steps" directly to "What is a namespace" may be a bit steep?

**Comment by justintadlock** [comment]
I reworked that last section to be more focused on "reading code examples."

**Comment by carolinan** [comment]
Looks good to me, thank you.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149314&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/getting-started/reading-this-handbook/
