### ISSUE TITLE
Add a link to the Pocket Casts on the Embeds page

### ISSUE THREAD

**Issue by atachibana** [WordPress/Documentation-Issue-Tracker#849]
## Issue Description

Pocket Casts does not have a link to their top page: https://pocketcasts.com/ .
This issue was reported by Yael at https://wordpress.slack.com/archives/C02RP4WU5/p1685584444616089

## URL of the Page with the Issue

https://wordpress.org/documentation/article/embeds/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
