### ISSUE TITLE
Link the title headings in HelpHub homepage

### ISSUE THREAD

**Issue by stevenlinx** [WordPress/Documentation-Issue-Tracker#851]
## Issue Description
The four headings under [wordpress.org/documentation/](https://wordpress.org/documentation/) shall be linked:

[WordPress overview](https://wordpress.org/documentation/overview/)
[Technical guides](https://wordpress.org/documentation/technical-guides/)
[Support guides](https://wordpress.org/documentation/support-guides/)
[Customization](https://wordpress.org/documentation/customization/)

Linking the headings is beneficial to UX as each link shows a list of all articles under the category.

## URL of the Page with the Issue
[https://wordpress.org/documentation/](https://wordpress.org/documentation/)

## Section of Page with the issue
The center section showing the four titles.

## Why is this a problem?
The are many articles under a category, yet, there is no way to click once from the homepage and see a list of all articles under a particular category.

## Suggested Fix
Link all four titles.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by creative-andrew** [comment]
I will be taking care of this issue if thats okay.

**Comment by stevenlinx** [comment]
I've made the revision.
