### ISSUE TITLE
Font size and link issue in Getting Started at a Contributor Day 

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#853]
## Issue Description
There was an issue with the font size and the link was a 404 page. But, I fixed it already.

## URL of the Page with the Issue
https://make.wordpress.org/themes/handbook/get-involved/getting-started-at-a-contribution-day/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by kafleg** [comment]
Fixed!
