### ISSUE TITLE
Font size and link issue in Running a Theme Review Session page

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#854]
## Issue Description
There was an issue in the font size of the content and 404 pages were found in some internal links. 

## URL of the Page with the Issue
https://make.wordpress.org/themes/handbook/get-involved/running-a-theme-review-contribution-day-session/

**Comment by kafleg** [comment]
Fixed. 

Docs team can verify it.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
