### ISSUE TITLE
Font size issue in Become a Reviewer page

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#855]
## Issue Description
Font size issue in the page. 

## URL of the Page with the Issue
https://make.wordpress.org/themes/handbook/get-involved/become-a-reviewer/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by kafleg** [comment]
Fixed it by resetting the font size to the default.
