### ISSUE TITLE
Font size issue on Onboarding for new reviewers page

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#856]
## Issue Description
Font size issue in the page.

## URL of the Page with the Issue
https://make.wordpress.org/themes/handbook/get-involved/onboarding-for-new-reviewers/

**Comment by kafleg** [comment]
Fixed it by resetting the font size to the default.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
