### ISSUE TITLE
User doc comparing Patterns vs Reusable Blocks vs Template Parts

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#86]
There seems to be widespread confusion around when to use each of these options. Writing a quick doc with an overall explanation comparing/contrasting each with links to respective docs would likely go a long way to help folks make good decisions :) 

Adding the 5.9 label but it's not required for 5.9 IMO.

**Comment by annezazu** [comment]
I have a very rough draft here based on various notes/ideas: https://docs.google.com/document/d/16bT9ME4g8j5Qe_-rOlM0kzk1vuZjPNG5142pK1_Vnmc/edit?usp=sharing

I think a table makes sense to include but, for now, want to get feedback on this first. @carolinan or @zzap would you be so kind? <3

**Comment by annezazu** [comment]
Alrighty. I think I have a fairly stable draft. @carolinan mind taking _one more look_? I'm not as rushed for 5.9 for this but would love to ship it sooner rather than later if possible.

**Comment by carolinan** [comment]
I have read through it and I think it is ready to be published.

**Comment by annezazu** [comment]
Done: https://wordpress.org/support/article/comparing-patterns-template-parts-and-reusable-blocks/
