### ISSUE TITLE
Font size issue on Installing plugins and content page

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#860]
## Issue Description
Fix the font size issue.

## URL of the Page with the Issue
https://make.wordpress.org/themes/handbook/get-involved/onboarding-for-new-reviewers/installing-plugins-and-content/

**Comment by kafleg** [comment]
Fixed it by resetting the font size to the default.

Docs team please check and verify it. Let me know if there is anything that I need to work on.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
