### ISSUE TITLE
Change WordPress Theme Review Team to Themes Team

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#869]
## Issue Description
WordPress Theme Review Team named changed to WordPress Themes Team long back. Need to update this. 

## URL of the Page with the Issue
https://developer.wordpress.org/themes/releasing-your-theme/theme-review-guidelines/

## Section of Page with the issue
Check the entire paragraphs.

**Comment by kafleg** [comment]
Assign this to me. I can fix this.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by jennimckinnon** [comment]
@kafleg Assigned! Thank you, and happy contributing! 🎉 🍪 🙌

**Comment by kafleg** [comment]
Done!
