### ISSUE TITLE
Update theme.json Version

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#87]
Update theme.json version section to include a reference to version 2 associating with WordPress 5.9. 
https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#version

## How will this help theme authors? 
It will help theme authors clarify a few points, including the difference between versions 1 and 2. Also, the Block themes with version 1 continue to work under WordPress 5.9.

**Comment by carolinan** [comment]
@oandregal @mkaz

For this page I would suggest that a table of contents with links to the headings/sections replaces the current toc.

I also think it would be good to try to simplify the language, as a non native English speaker I find that I have to go back and read the text more than once. 
I am assuming that the main reason why a developer visits this page is to learn the implementation details, and secondly as a reference for individual settings. -I can confess that I visit this page sometimes multiple times per day 😄. I do have to scroll a fair bit and struggle to find the correct reference. 

The most common request, in conversation with theme developers, is an example of the theme.json
with *all* available settings for *all blocks*.
I think it is important that the documentation expresses that the settings are, with some exceptions, the same for each block.

When updating the documentation to cover version 2, is there any reason to keep information about version 1?

Perhaps link to the new styles support article would be useful. https://wordpress.org/support/article/styles-overview/

**Comment by carolinan** [comment]
I completely forgot that we also have this page in the theme developer handbook:
https://developer.wordpress.org/themes/advanced-topics/theme-json/

@TeBenachi @kafleg can I go a head and update the examples in this theme handbook page to theme.json version 2?

**Comment by TeBenachi** [comment]
Yes please. Thank you so much!

**Comment by oandregal** [comment]
:wave: There's a couple of documents for `theme.json` in the block editor handbook:

- [theme.json reference](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/): automated doc to refer to each specific property. It's the specification document. In https://github.com/WordPress/gutenberg/pull/37772  I'm proposing to add the version of theme.json in which a given field was introduced.

- [theme.json (global settings & styles)](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/): the original doc that was manually curated. In my view, this one should evolve to be an examples-based doc that theme authors can refer to for inspiration of how something is done.

**Comment by carolinan** [comment]
I think you misunderstood. Theme.json is available for any theme, and can be used without Gutenberg with 5.8 or 5.9. That is the documentation that I am suggesting should be in the theme developer handbook.

And then there are updates and additional **new** features that are being developed tested that were not ready for 5.9.
Since new features can change often, they are not always documented until they are stable.

_Including a theme.json alone does not hide the customizer menu._
