### ISSUE TITLE
URL Redirection 

### ISSUE THREAD

**Issue by kafleg** [WordPress/Documentation-Issue-Tracker#870]
## Issue Description
The link found in this paragraph, `All themes are closely reviewed, and must meet rigorous [theme review guidelines](https://developer.wordpress.org/theme/release/theme-review-guidelines/) to ensure quality and security.` is redirected. Update the page with the proper link. 

## URL of the Page with the Issue
https://developer.wordpress.org/themes/getting-started/what-is-a-theme/

## Section of Page with the issue
Themes in WordPress.org section. https://developer.wordpress.org/themes/getting-started/what-is-a-theme/#themes-on-wordpress-org

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by kafleg** [comment]
Done!
