### ISSUE TITLE
Add Interactive Demo Links to WordPress Block Editor Documentation

### ISSUE THREAD

**Issue by dionysous** [WordPress/Documentation-Issue-Tracker#871]
## Issue Description

The WordPress Block Editor documentation could benefit from integrated interactive demo links ([wordpress.org/gutenberg](https://wordpress.org/gutenberg/)) to provide an enhanced user learning experience.

## URL of the Page with the Issue
[wordpress.org/documentation/article/wordpress-block-editor](https://wordpress.org/documentation/article/wordpress-block-editor/)

## Section of Page with the issue

Several sections: Introduction, Explanation of Blocks, 'Block Editor’s workspace' section, and Conclusion.

## Why is this a problem?

Currently, readers only have text-based instructions and screenshots. Interactive demo links offer an immersive learning experience, allowing users to apply their learning in a practical environment.

## Suggested Fix

Integrate "Try Block Editor Now" links in the following sections (or at least one time):

1. After the introduction of the WordPress Block Editor.
2. Post explanation of what blocks are.
3. In the 'Block Editor’s workspace' section, after explaining how to launch the editor.
4. At the conclusion of the article.

This would provide readers with immediate hands-on experience at each stage of the Block Editor process, thereby enhancing understanding and retention.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by Leonardus-Nugraha** [comment]
I've added links to the Gutenberg demo website in the intro, at the end of the "top toolbar" section, and the end of the article. I spread it that way so they're not too clustered together and repetitive. Plus, I use a highlight box, so they should capture readers attention.
