### ISSUE TITLE
Add Documentation for Block Error: Unexpected or Invalid Content

### ISSUE THREAD

**Issue by Thelmachido** [WordPress/Documentation-Issue-Tracker#877]
## What is the new page you are requesting?

Creating documentation for the most common Block Error `This block contains unexpected or invalid content.` 

<img width="711" alt="Screenshot 2023-06-19 at 15 16 05" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/41231764/4afb6656-5576-4a83-8b09-e931e0650be6">

## How will this new page help you?

There are a number of reasons why users can experience this error in the Gutenberg Editor. This issue was raised in forums: https://wordpress.org/support/topic/still-buggy-and-unintuitive/  
I would like to start an article that covers some of the basics to help out beginners. When the doc is ready we can have a link to the relevant documentation page when someone comes across this sort of error. 

- [ ] The first step will be creating the doc 

-  Basic known issues that lead to this error
- What each of the options on the block will achieve 
- A few basic ways to resolve the issue   

- [ ] Create a Gutenberg GH issue to add an inline support link to the broken block pointing to this newly created documentation article

**Comment by Thelmachido** [comment]
Here is draft for this documentation:

https://wordpress.org/documentation/wp-admin/post.php?post=16357483&action=edit

**Comment by estelaris** [comment]
This has been published.
Next steps

- [ ] Open a ticket in GH/Gutenberg
- [ ] Request the design team to add article link
- [ ] Add it as a feature for 6.4

**Comment by Thelmachido** [comment]
I have created the ticket here: https://github.com/WordPress/gutenberg/issues/51980

**Comment by anandau** [comment]
As the documentation is complete and published, I am marking this as closed.
