### ISSUE TITLE
Invalid haifan( - ) used in wp-env command

### ISSUE THREAD

**Issue by dilipbheda** [WordPress/Documentation-Issue-Tracker#879]
## Issue Description
When any user copy and paste the mentioned command then it will trigger the below error.
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "–-save-dev": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kwt-reflp-hp-54/.npm/_logs/2023-06-20T06_47_02_468Z-debug.log
```

## URL of the Page with the Issue
https://developer.wordpress.org/news/2023/03/quick-and-easy-local-wordpress-development-with-wp-env/

## Section of Page with the issue
Local installation

## Why is this a problem?
https://tinyurl.com/23g8ru2k

## Suggested Fix
It should be `--` instead of `–-`

**Comment by stevenlinx** [comment]
@mburridge
I think this is your post?

**Comment by mburridge** [comment]
@dilipbheda , @stevenlinx thanks for the heads up. I've fixed the error.
