### ISSUE TITLE
Site Logo Block Support Page

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#88]
Need to include information about using it in Site Editor and Template Editor, including the ability to set the Site Icon with it for FSE: https://github.com/WordPress/gutenberg/pull/35892#event-5800922904

**Comment by annezazu** [comment]
Removing for 5.9 as it's not a priority doc and the key part around being able to set a site icon using the site logo block has been appropriately integrated.

**Comment by femkreations** [comment]
Adding to #287 and closing this issue.
