### ISSUE TITLE
Contributor Day — 27 June, 2023

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Documentation-Issue-Tracker#881]
## Welcome to the online WordPress Documentation Team's Contributor Day

This the monthly online Make WordPress Documentation Team’s independently-led Contributor Day. It’s held on the fourth Tuesday of each month.

You can join us via [Zoom](https://us06web.zoom.us/j/85220861178?pwd=SE4vOElLbjlMbE5OdkNWMnR1ZGRMZz09) on 27 June, between 1 PM UTC and 4 PM UTC.

### For those attending this Contributor Day

If you attend this Contributor Day, please comment below with:

- Your WordPress.org profile username
- Link(s) to the issue(s) you're working on during the Contributor Day

People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us06web.zoom.us/j/85220861178?pwd=SE4vOElLbjlMbE5OdkNWMnR1ZGRMZz09): @zzap, @estelaris, @Leonardus-Nugraha, and @jennimckinnon

## New(er) contributors

If this is your first time contributing to the Documentation team, please make sure you have the following accounts:

- [WordPress.org account](https://login.wordpress.org/register).
- [WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
- [GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).
- Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :)

Following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:

- [General overview](https://wordpress.tv/2022/06/21/milana-cap-overview-onboarding-for-wordpress-documentation-team/)
- [End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
- [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

For general details on how GitHub works, check out [GitHub’s Getting Started Guide](https://docs.github.com/en/get-started/quickstart/hello-world).

When you find issue you'd like to work on in the [Docs Team Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) here on GitHub:

1. Please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue, and
2. In that comment, also be sure to tag the [team rep responsible for the handbook](https://make.wordpress.org/docs/handbook/the-team/) that your chosen task is about.

For example, if your task is for the Block Editor End-User documentation, you would tag @femkreations.

Check out the [Team page in the Documentation Team Handbook](https://make.wordpress.org/docs/handbook/the-team/) for a list of team reps.

### Onboarding during Contributor Day
If you have questions or need onboarding, feel free to ask in the [#docs channel on Slack](https://wordpress.slack.com/messages/docs/) or in Zoom. We'll create a breakout room in [Zoom](https://us06web.zoom.us/j/85220861178?pwd=SE4vOElLbjlMbE5OdkNWMnR1ZGRMZz09) to field any questions you may have.

## General task list

Tasks we plan to work on during the day:

1. Updating block editor end user documentation

[6.2 Docs](https://github.com/orgs/WordPress/projects/67/views/2)

3. Content review for mobile app end-user articles

- [Mobile app content review board](https://github.com/orgs/WordPress/projects/89/views/1)
- [Promote Helping to Documentation team with Mobile Apps docs #219](https://github.com/WordPress/Marketing-Team/issues/219)

Person to go ask for help: @estelaris, @jennimckinnon, @zzap

4. Review all articles to confirm images and links are working. Several articles have broken links since the migration. Open individual tickets

Example:
https://meta.trac.wordpress.org/ticket/6944

## Need help?
People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us06web.zoom.us/j/85220861178?pwd=SE4vOElLbjlMbE5OdkNWMnR1ZGRMZz09): @zzap, @estelaris, @Leonardus-Nugraha, and @jennimckinnon

**Comment by jennimckinnon** [comment]
`ninianepress` on WP.org

I had a lot of questions answered today in discussions 🎉 🙌 
- Styling screenshots, file formats
- [Onboarding contributor role](https://make.wordpress.org/docs/handbook/get-involved/team-roles/non-project-roles/#onboarding-coordinator)
- [Mentorship program](https://make.wordpress.org/project/2023/06/23/launch-your-wordpress-contributor-journey-through-the-mentorship-program-pilot/)

**Comment by cgarofalo** [comment]
I attended. (WP: @cold-iron-chef)

**Comment by jomarieminney** [comment]
`jominney` on .org - helped sort out this issue so it can be closed: 
https://github.com/WordPress/Documentation-Issue-Tracker/issues/825
And completed this one which can now be closed:
https://github.com/WordPress/Documentation-Issue-Tracker/issues/462

**Comment by jennimckinnon** [comment]
Closing as the next Contributor Day is in a couple days.
