### ISSUE TITLE
Typo in the database description article.  

### ISSUE THREAD

**Issue by dabowman** [WordPress/Documentation-Issue-Tracker#898]
## Issue Description
In the list of site-specific tables it refers to the term meta table as `wp_term_termmeta`. The actual name of the table is `wp_termmeta` and that's how it is refered to everywhere else on the page. 

## URL of the Page with the Issue
https://codex.wordpress.org/Database_Description

## Section of Page with the issue
Site Specific Tables  
https://codex.wordpress.org/Database_Description#Site_Specific_Tables

## Why is this a problem?
the name is wrong, which is a bit confusing. It made me think that the table names might change in a multi-site context

## Suggested Fix
I think the corrected list of tables should read like this. I re-ordered it to keep things in alphabetical order. 

[wp_2_commentmeta](https://codex.wordpress.org/Database_Description#Table:_wp_commentmeta)
[wp_2_comments](https://codex.wordpress.org/Database_Description#Table:_wp_comments)
[wp_2_links](https://codex.wordpress.org/Database_Description#Table:_wp_links)
[wp_2_options](https://codex.wordpress.org/Database_Description#Table:_wp_options)
[wp_2_postmeta](https://codex.wordpress.org/Database_Description#Table:_wp_postmeta)
[wp_2_posts](https://codex.wordpress.org/Database_Description#Table:_wp_posts)
[wp_2_termmeta](https://codex.wordpress.org/Database_Description#Table:_wp_termmeta)
[wp_2_terms](https://codex.wordpress.org/Database_Description#Table:_wp_terms)
[wp_2_term_relationships](https://codex.wordpress.org/Database_Description#Table:_wp_term_relationships)
[wp_2_term_taxonomy](https://codex.wordpress.org/Database_Description#Table:_wp_term_taxonomy)

**Comment by stevenlinx** [comment]
Thanks for filing.

I've fixed the typo, but the correct order by alphabetical order should be like the following:

[wp_2_term_relationships](https://codex.wordpress.org/Database_Description#Table:_wp_term_relationships)
[wp_2_term_taxonomy](https://codex.wordpress.org/Database_Description#Table:_wp_term_taxonomy)
[wp_2_termmeta](https://codex.wordpress.org/Database_Description#Table:_wp_termmeta)
[wp_2_terms](https://codex.wordpress.org/Database_Description#Table:_wp_terms)
