### ISSUE TITLE
Update authentication metchanisms with application password info

### ISSUE THREAD

**Issue by JanisE** [WordPress/Documentation-Issue-Tracker#9]
On REST API authentication page https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/ :

> While cookie authentication is the only authentication mechanism available natively within WordPress, plugins may be added to support alternative modes of authentication that will work from remote applications. Some example plugins are OAuth 1.0a Server, Application Passwords, and JSON Web Tokens.

1) At this point, also application passwords is available natively, no need for a plugin.

2) "OAuth 1.0a Server" is last updated 5 years ago. Although, it may still be working all right and I don't know if there are better alternatives.

**Comment by zzap** [comment]
Hello @JanisE ,

Thank you very much for reporting this. However, REST API team is in charge for their documentation so it's best to report it in [their repo](https://github.com/WP-API/docs/issues). This is the actual page: https://github.com/WP-API/docs/blob/master/using-the-rest-api/authentication.md

Thanks
