### ISSUE TITLE
Update "Using Themes" with TT2 information

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#90]
Need to update this page https://wordpress.org/support/article/using-themes/ with the following:
- Mention block theme and link to block theme documentation.
- Mention/link to TT2 in default theme section.
- Mention TT2 is a block theme and it won't work with prior versions of WordPress without Gutenberg.

cc @carolinan anything else stand out to you?

**Comment by kafleg** [comment]
CC: @TeBenachi

**Comment by carolinan** [comment]
It's unrelated to TT2, but there are two more updates that can be done to improve the page;
The image in the section "Adding New Themes using the Administration Screens" seems to be broken/missing.

Below the last heading "Creating themes", the name of the team needs to be updated:
`Whichever the case, you are welcome to join Theme Review Team` should be 
`Whichever the case, you are welcome to join Themes Team`

**Comment by annezazu** [comment]
Updated done today and scheduled for January 25, 2022 at the same time as the various other docs. Updates include:
- Fixing the image under "Adding New Themes using the Administration Screens". This was a GIF. As a result, I added a short video instead. 
- Updating the last heading as mentioned above.
- Updated 8,450 themes to "over 9,000" themes based on the current number in the directory (9,143).
- Under "Adding new themes", I added in context around previewing and adding block themes in line with [this dev note](https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/) on the Customizer, preview functionality, etc with block themes.  I titled this section "Adding Block themes" @carolinan curious if this seems okay 😬 felt hacky. 
- Added in 2022 under the default theme section with this statement below "The Twenty Twenty Two theme is the first ever default block theme. It currently only works if you are using WordPress 5.9 and above or if you install the Gutenberg plugin alongside prior WordPress versions."

At this time, since TT2 isn't in the directory, this page will need to be updated again when this link is live  to link to it and update the screenshot showing TT1: https://wordpress.org/themes/twentytwentytwo/

**Comment by carolinan** [comment]
The minimum required version for Twenty Twenty-Two will been increased to 5.9:
https://github.com/WordPress/twentytwentytwo/pull/326

**Comment by annezazu** [comment]
Awesome. Going to loop back on this in early Feb as that's when it seems to be anticipated that TT2 will be live in the directory.

**Comment by annezazu** [comment]
Noting that I updated this page in light of TT2 being live in the directory with a link.
