### ISSUE TITLE
wp-block-heading position is not proper on First Steps with WordPress (Block Editor) Page

### ISSUE THREAD

**Issue by dhrumilkumbhani** [WordPress/Documentation-Issue-Tracker#901]
## Issue Description
First Steps with WordPress (Block Editor) Document page **#start-at-the-top** id heading looks weird.

## URL of the Page with the Issue
https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/#start-at-the-top

## Section of Page with the issue
[Start at the top](https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/#start-at-the-top)

## Why is this a problem?
Incorrect the above image height. 

## Suggested Fix
Set the above image height properly.

![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/57712674/66d890a9-a76a-4da2-8703-7daa6b585941)

Solution 1.
Fix the above image height.

Solution 2.
Add this one css.
h3#start-at-the-top {
    margin-top: var(--wp--preset--spacing--60);
}

After the apply solution 2 it's look like this one.

![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/57712674/6338f496-feff-41b4-ae65-5df83c0172e7)

**Comment by zzap** [comment]
Alignment fixed. Thank you for reporting @dhrumilkumbhani :cookie:
