### ISSUE TITLE
[HelpHub] Slugs to change

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#903]
Some articles need to change the title/slug. Due to the technical process this involves, we are making Trac tickets for the Meta team. We'll track those articles here to prevent issues from hanging open indefinitely.

- [ ] [Categories List Block](https://wordpress.org/documentation/article/categories-block/) - /categories-block/ --> /categories-list- block/ (from #825 )
- [ ] [Categories Block](https://wordpress.org/documentation/article/post-categories-block/) - /post-categories-block/ --> /categories-block/ (from #825 )

**Comment by estelaris** [comment]
The URLs have been changed for both articles and I requested a redirect here[ # 93](https://github.com/WordPress/wporg-documentation-2022/issues/93)

**Comment by estelaris** [comment]
Slugs are working now.
