### ISSUE TITLE
`WP_Query` pagination parameters `posts_per_page` description

### ISSUE THREAD

**Issue by crstauf** [WordPress/Documentation-Issue-Tracker#918]
## Issue Description
> The statement “To reimpose the limit, try using the ‘post_limits’ filter, or filter ‘pre_option_posts_per_rss’ and return -1” is unfortunately not correct. If you return -1 for ‘pre_option_posts_per_rss’, this value will be inserted directly at the LIMIT clause of the SQL query i.e. it will say something like LIMIT 0,-1 in the SQL query.
> This leads to an SQL error so that no result is returned. With this filter it is mandatory that a number > 0 is returned. In case of doubt, you should use the PHP constant PHP_INT_MAX so that on most cases all entries are outputted.
> It is extremely unlikely that there are more than 2147483647 (32-bit OS) or 9223372036854775807 (64-bit OS), but if there are, the return value would have to be increased accordingly.

Reported by `mumbomedia` via User Contributed Notes.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/classes/wp_query/#pagination-parameters

## Section of Page with the issue
Pagination Parameters

## Why is this a problem?
Causes an SQL error.

## Suggested Fix
Remove or rephrase the sentence on how to change the post limit for feeds.

> To reimpose the limit, try using the ‘post_limits’ filter, or filter ‘pre_option_posts_per_rss’ and return [a large number].

**Comment by stevenlinx** [comment]
Thanks for filing.

I've revise the sentence to be:
To reimpose the limit, try using the `post_limits` filter, or filter `pre_option_posts_per_rss` and return a very large number (if you want to return all posts) such as PHP constant `PHP_INT_MAX` so that on most cases all entries are outputted.
