### ISSUE TITLE
Broken link on `WP_SimplePie_Sanitize_KSES`

### ISSUE THREAD

**Issue by crstauf** [WordPress/Documentation-Issue-Tracker#919]
## Issue Description
> The link to the “[SimplePie_Sanitize](https://developer.wordpress.org/reference/classes/simplepie_sanitize)” class in the “[See Also](https://developer.wordpress.org/reference/classes/wp_simplepie_sanitize_kses/#see-also)” section of the “[wp_simplepie_sanitize_kses](https://developer.wordpress.org/reference/classes/wp_simplepie_sanitize_kses/)” documentation is broken.
> 
> The correct URL for the “SimplePie_Sanitize” class is {80% SURE}:
> 
> https://developer.wordpress.org/reference/classes/wp_simplepie_sanitize_kses/sanitize/
> 
> Please fix this broken link.
>
> Thank you.

Reported by `luckybhumkar` via User Contributed Notes.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/classes/wp_simplepie_sanitize_kses/#see-also

## Section of Page with the issue
See Also

## Why is this a problem?
Broken link.

## Suggested Fix
Change URL to https://developer.wordpress.org/reference/classes/wp_simplepie_sanitize_kses/sanitize/ (80% confidence).

**Comment by stevenlinx** [comment]
Thanks for filing.

However, the See Also section belongs to Core Trac
https://github.com/WordPress/wordpress-develop/blob/6.2/src/wp-includes/class-wp-simplepie-sanitize-kses.php#L18

**Comment by crstauf** [comment]
@stevenlinx In what commit was this fixed?

**Comment by stevenlinx** [comment]
@crstauf 
The "See Also section" comes from an inline doc line in the source code.
This is not the domain of DevHub.
So you'll need to file a ticket over at Core Trac to fix this.

**Comment by crstauf** [comment]
Reported in [Trac #59030](https://core.trac.wordpress.org/ticket/59030).
