### ISSUE TITLE
Theme Handbook: Add link to the Block Editor Handbook 

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#92]
### What issue will it solve? 
Currently, the information related to the Block Theme resides within the [Block Editor Handbook](https://developer.wordpress.org/block-editor/how-to-guides/themes/). 
Many theme developers go to the [Theme Handbook](https://developer.wordpress.org/themes/) to look for theme-related info, including the Block Theme. However, the Theme Handbook mainly provides the info related to the Classic theme. 

I think it’s a good idea to add link on the Theme Handbook pages to navigate the theme developers to the Block Theme info. Adding the link can also avoid creating duplicate content between the Block Editor Handbook and the Theme Handbook. 

### Suggestion:
Add visibly stand out, easy to spot link on the top of the pages throughout the Theme Handbook where applicable. For example, [Template Files](https://developer.wordpress.org/themes/basics/template-files/), [Template Tags](https://developer.wordpress.org/themes/basics/template-tags/)

![theme-handbook](https://user-images.githubusercontent.com/30734209/147568128-c8777737-239f-4470-bf89-a70e1ca4ff29.jpg)

Add text links in the content where explains both the Classic and Block Themes. For example, [Getting Started](https://developer.wordpress.org/themes/getting-started/), [Theme Basics](https://developer.wordpress.org/themes/basics/), [Main Stylesheet](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/)

**Comment by kafleg** [comment]
Nice suggestion!

**Comment by carolinan** [comment]
I removed the word "experimental" from the notice on the [first page](https://developer.wordpress.org/themes/).

**Comment by carolinan** [comment]
The template tag page above is not relevant for block themes because they use blocks instead.
Instead of having a notice that links to the block editor handbook, should the page have a notice that says the information is only for classic themes?

**Comment by TeBenachi** [comment]
Yes, there are some pages that share info for both. I was hoping that the link would help new authors finding about the block theme. 

Great point about adding “the information is only for classic themes”. It makes sense and clarify more. 

Suggestion:
**The information is for Classic theme. Want to build a Block theme? See Create a block theme for building a block theme.** 

Agree. I think it's a good idea to check each page to be throughout. 
I can create a list of pages to see where need review and update.

**Comment by TeBenachi** [comment]
Closing this ticket as the Theme Handbook page has been updated. 
https://developer.wordpress.org/themes/

**Comment by TeBenachi** [comment]
Sorry I closed the ticket by mistake.

**Comment by TeBenachi** [comment]
I'm closing this ticket as we are moving forward with moving the Block theme contents to the Theme Handbook.
