### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Theme Structure

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#920]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Theme Structure" under Chapter 2: Core Concepts.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/11MxKcbptVeC1FmtjbwSRaAScY2iL5fhQykNBGC2CA-Y/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this doc is now ready for review: https://docs.google.com/document/d/11MxKcbptVeC1FmtjbwSRaAScY2iL5fhQykNBGC2CA-Y/edit?usp=sharing

One important thing to look out for is making sure I included any and all required files or files/folders that WP recognizes.

**Comment by carolinan** [comment]
As far as I know, theme.json is not actually required.
A theme with an index.html out theme.json will still activate and the site editor is available.
See https://developer.wordpress.org/reference/classes/wp_theme/is_block_theme/
But I tested in 6.3 Rc1 and there are bugs. So this is something that needs to be brought up with the Gutenberg team.

**Comment by justintadlock** [comment]
I moved the `theme.json` down to the Optional files section.  

Yep, if that's buggy, it should be reported upstream.

**Comment by carolinan** [comment]
Update looks mostly good to me, thank you.
In the code example of the advanced theme structure, theme.json is still marked as required.

Maybe the styles folder (for theme style variations) should be mentioned in the advanced theme structure?

**Comment by justintadlock** [comment]
Good call. I don't know how I missed that. It should be mentioned in the "standard" section too.

**Comment by justintadlock** [comment]
This is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149333&action=edit

**Comment by kafleg** [comment]
LGTM

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/core-concepts/theme-structure/
