### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Main Stylesheet

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#921]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Main Stylesheet" under Chapter 2: Core Concepts.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1qhnV03_yt-TAtr2wj2fJOA-MT6IaOVeb2x6k-DtkatU/edit?usp=sharing

**Comment by justintadlock** [comment]
The first draft of this doc is completed and ready for review: https://docs.google.com/document/d/1qhnV03_yt-TAtr2wj2fJOA-MT6IaOVeb2x6k-DtkatU/edit?usp=sharing

**Comment by carolinan** [comment]
I like it, very clear descriptions.
The domain names in the examples need to be replaced.

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
> The domain names in the examples need to be replaced.

I switched over to using `example.com`. Do y'all think that's best?

**Comment by carolinan** [comment]
Yes unless we want to try using something like the playground?. Hmmmm.

**Comment by justintadlock** [comment]
This draft is now in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149336&action=edit

**Comment by kafleg** [comment]
We can change, Tested up to 6.4 and can publish this.

**Comment by justintadlock** [comment]
Updated version number and published here: https://developer.wordpress.org/themes/core-concepts/main-stylesheet/
