### ISSUE TITLE
Word and Sign missing in the doc.

### ISSUE THREAD

**Issue by AsadPolash** [WordPress/Documentation-Issue-Tracker#924]
## Issue Description
Just a simple "fullstop" missing and the word "website" should be added. In the doc, the information is fine, just at the end of the sentence a "FULSTOP" should be added. Also, for better clearance of the sentence the word "Website" should be added.

## URL of the Page with the Issue
https://make.wordpress.org/training/handbook/about/team-profile-badges/

## Section of Page with the issue
Under the "Training Contribution Badge" the section is named "Content Translation"

## Why is this a problem?
It's not a problem, it's just completing properly as other informations in the doc. 

## Suggested Fix
Just adding the '.' (Fullstop) at the end of the sentence will do the solution. Also, for better clarification add the word "website" that makes the sentence complete and portrays a better understanding for the "Learn Website" as mentioned elsewhere within the same doc.

**Comment by bsanevans** [comment]
This was raised in the Training Team, and a fix has been published.

Thanks for noting this, @AsadPolash 🙌

**Comment by AsadPolash** [comment]
@zzap @atachibana @Kenshino
