### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Templates

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#930]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Templates" under Chapter 2: Core Concepts.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1oJzPXap7kVgzYYvMxACaijsBGhlqm_Pv60NW6fy5gwg/edit?usp=sharing

Note that this is a "basics" intro to Templates. There will be a full chapter that covers templating in detail, so this page should introduce the concept to the reader but be a pathway to learning more in the Templates chapter.

**Comment by justintadlock** [comment]
The first draft of this ticket is now finished and ready for review: https://docs.google.com/document/d/1oJzPXap7kVgzYYvMxACaijsBGhlqm_Pv60NW6fy5gwg/edit?usp=sharing

Note that this is just a primer on what templates are. We have a full chapter that will be dedicated to templating.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149340&action=edit

**Comment by kafleg** [comment]
Looks good to me.

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/core-concepts/templates/
