### ISSUE TITLE
Error in the Privacy Policy code example

### ISSUE THREAD

**Issue by authentictech** [WordPress/Documentation-Issue-Tracker#95]
## Issue Description

There is a code error in the Privacy Policy code example
## URL of the Page with the Issue

https://developer.wordpress.org/plugins/privacy/suggesting-text-for-the-site-privacy-policy/
## Section of Page with the issue

The code example section
## Why is this a problem?

The `add_action` statement incorrectly references the function name.
## Suggested Fix

Change `add_action( 'admin_init', 'wporgmy_example_plugin_add_privacy_policy_content' );` to `add_action( 'admin_init', 'wporg_add_privacy_policy_content' );` so that it matches the function name.

Or change both `add_action` statement and function name to use `wporg_my_example_plugin_add_privacy_policy_content` if it is more appropriate.

**Comment by stevenlin-x** [comment]
I've revised the Code Example.
