### ISSUE TITLE
Checking user capabilities example code produces error "Call to undefined function wp_get_current_user()"

### ISSUE THREAD

**Issue by authentictech** [WordPress/Documentation-Issue-Tracker#96]
## Issue Description

The example code provided in the two examples below (which are basically the same code) fails to work because the code produces an error "Call to undefined function wp_get_current_user()".

## URL of the Page with the Issue

1. https://developer.wordpress.org/plugins/security/checking-user-capabilities/#restricted-to-a-specific-capability
2. https://developer.wordpress.org/plugins/security/nonces/#complete-example

## Section of Page with the issue

1. Restricted to a Specific Capability
2. Complete Example

## Why is this a problem?

I am led to believe via https://stackoverflow.com/a/6127607/325067 that the file containing the called function `wp_get_current_user()` (/wp-includes/pluggable.php) doesn't get loaded until _after_ the plugins are loaded; therefore, it can't be used as given in an example plugin.

## Suggested Fix

The call to `current_user_can()` must be wrapped inside another function which is hooked to the `plugins_loaded` action (see Stackoverflow example).

**Comment by stevenlin-x** [comment]
I've revised the Code Examples.
