### ISSUE TITLE
Typo on https://wordpress.org/documentation/article/blocks-list/

### ISSUE THREAD

**Issue by mdrovdahl** [WordPress/Documentation-Issue-Tracker#966]
## Issue Description

"...third part blocks..." should be "...third party blocks..." 

## URL of the Page with the Issue

https://wordpress.org/documentation/article/blocks-list/

## Section of Page with the issue

Second paragraph in the "Blocks list" section.

## Why is this a problem?

Simple typo.

## Suggested Fix

"...third part blocks..." should be "...third party blocks..."

**Comment by annezazu** [comment]
Updated! Thank you for opening this.
