### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Custom Functionality

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#969]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Custom Functionality" under Chapter 2: Core Concepts.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/1OaVZUa22IqIdjReia8mbAkOXxEHBLZM0l5gSVIwtMsA/edit?usp=sharing

**Comment by huzaifaalmesbah** [comment]
Thank you for the kind words! I'm glad you the new page content appealing.

**Comment by justintadlock** [comment]
The doc is ready for review: https://docs.google.com/document/d/1OaVZUa22IqIdjReia8mbAkOXxEHBLZM0l5gSVIwtMsA/edit?usp=sharing

Like most docs in these first two chapters, there are several links to upcoming docs that haven't been written yet.

This doc is also meant to be a "core concepts" / "basics" intro to `functions.php`, so I tried to avoid diving too deeply into the various APIs and features that a theme can use. Those will be in future docs.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149345&action=edit

**Comment by justintadlock** [comment]
Now published here: https://developer.wordpress.org/themes/core-concepts/custom-functionality/
