### ISSUE TITLE
Theme Handbook: Create a new page for Updating Your Theme to explain SVN upload

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/Documentation-Issue-Tracker#97]
Uploading a theme using SVN has been open since October. To encourage theme authors to use SVN, I think it is a good idea to create a new page explaining other ways to update their themes in addition to a zip file. 

My idea is to remove the [Updating your theme section](https://developer.wordpress.org/themes/releasing-your-theme/submitting-your-theme-to-wordpress-org/#updating-your-theme). Then create a new page. 

Draft:
https://gist.github.com/TeBenachi/666ac231b515bf07422b7336ee278c3d

Background stories on SVN: 
- [Allow theme updates via SVN](https://meta.trac.wordpress.org/ticket/5899)
- [Theme upload survey results & next steps](https://make.wordpress.org/themes/2021/09/13/theme-upload-survey-results-next-steps/)

**Comment by joyously** [comment]
Instead of removing a section that could be linked to from other places, could you just add a link to the new page? The new one is mostly about SVN, so the long-standing way to update with a zip file should not be listed **only** there.
And why exactly is there a goal "to encourage theme authors to use SVN"?

**Comment by TeBenachi** [comment]
You have a good point. Thanks for your input. It makes sense not to remove the section if there are cross-links to the section. 

One of the main purposes is to reduce Trac tickets when updating themes. Also, updating can be automated when using SVN.

**Comment by carolinan** [comment]
I agree with Joy.

The text looks correct to me; I think there is a link missing here? "Tips: If you are not sure about the exact name of your theme (e.g. hyphen, underscore), you can find it at this link."

**Comment by kafleg** [comment]
Yes, I recommend adding a new page as well.

**Comment by kafleg** [comment]
(1) Create a copy of the repository on your local machine. Replace /NameOfYourTheme/ with your theme name. svn co https://themes.svn.wordpress.org/NameOfYourTheme/

Is **NameOfYourTheme** or **theme directory name**? Or both works?

**Comment by TeBenachi** [comment]
@kafleg Thanks for checking. NameOfYourTheme is the theme directory name. I added an example to clarify. 

For example, if your theme name is Twenty Twenty-One, use svn co https://themes.svn.wordpress.org/twentytwentyone/

**Comment by TeBenachi** [comment]
Suggestion for the **[uploading your theme section](https://developer.wordpress.org/themes/releasing-your-theme/submitting-your-theme-to-wordpress-org/#uploading-your-theme)** with a link to the new page.

==
When you are ready to submit your theme for review, please upload your theme ZIP at Themes > Upload. **_Future updates are to be uploaded via the same page or SVN. Learn more about [how to update your theme](https://developer.wordpress.org/themes/releasing-your-theme/updating-your-theme/)._**  

More information about the theme review process is available on the [Theme Review Team’s website](https://make.wordpress.org/themes/handbook/review/).

**Comment by kafleg** [comment]
More information about the theme review process is available on the Theme Review Team’s website.

_More information about the theme review process is available on the Themes Team handbook._

**Comment by TeBenachi** [comment]
Thanks for catching that!

**Comment by kafleg** [comment]
Also, we can add a link to the upload page here, _[Themes > Upload](http://wordpress.org/themes/upload)._

**Comment by joyously** [comment]
> For example, if your theme name is Twenty Twenty-One, use svn co https://themes.svn.wordpress.org/twentytwentyone/

I think using a bundled theme name is a bad example since they can be different between the name and the folder. Other themes can't.

**Comment by joyously** [comment]
> More information about the theme review process is available on the Themes Team handbook.

It sounds okay to say "on a website", but sounds funny to say "on a handbook".

**Comment by TeBenachi** [comment]
> > For example, if your theme name is Twenty Twenty-One, use svn co https://themes.svn.wordpress.org/twentytwentyone/
> 
> I think using a bundled theme name is a bad example since they can be different between the name and the folder. Other themes can't.

@joyously Thanks for pointing it out. I changed to hello-world instead. I think it’s neutral enough.

**Comment by TeBenachi** [comment]
Closing this ticket as the page has been updated. 
https://developer.wordpress.org/themes/releasing-your-theme/updating-your-theme/
