### ISSUE TITLE
HTML tag in wp-config.php MySQL Socket example code

### ISSUE THREAD

**Issue by com2** [WordPress/Documentation-Issue-Tracker#979]
## Issue Description

**wp-config.php >> Set database host** code examples with erroneous HTML tags
## URL of the Page with the Issue

https://developer.wordpress.org/apis/wp-config-php/#set-database-host
## Section of Page with the issue

**MySQL Sockets or Pipes** configuration code examples
## Why is this a problem?

Ignorant users not aware of the proper socket path syntax might blindly copy and paste including the HTML tag and it would annoyingly cause the site to fail. I.a.w. the `<strong>`  HTML tags was meant to make the documentation text bold and it was not meant to be part of the example text.  
## Suggested Fix

Remove the `<strong>` tag or alternatively make the documentation text bold in a correct manner, that it remains invisible in the code example.

**Comment by stevenlinx** [comment]
Thank you for filing.

I've removed the html tag <strong> from the code examples.
