### ISSUE TITLE
Contributor Day — 25 July, 2023

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Documentation-Issue-Tracker#982]
## Welcome to the online WordPress Documentation Team's Contributor Day

This the monthly online Make WordPress Documentation Team’s independently-led Contributor Day. It’s held on the fourth Tuesday of each month.

You can join us via [Zoom](https://us06web.zoom.us/j/83644093796?pwd=Zy94clJrK3dmaGJLWGQ1Q08yMGpsUT09) on 25 June, between 1 PM UTC and 4 PM UTC.

### For those attending this Contributor Day

If you attend this Contributor Day, please comment below with:

- Your WordPress.org profile username
- Link(s) to the issue(s) you're working on during the Contributor Day

People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us06web.zoom.us/j/83644093796?pwd=Zy94clJrK3dmaGJLWGQ1Q08yMGpsUT09): @zzap, @estelaris, @Leonardus-Nugraha, and @jennimckinnon

## Environment

For tasks that don't need WordPress 6.3 RC (release candidate), you can set WordPress install in one click by visiting https://playground.wordpress.net/.

For tasks that need WordPress 6.3 RC, you can use this demo tool https://app.instawp.io/launch?t=beta-rc&d=v2.

Any questions you have, aks them in [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel.

## New(er) contributors

If this is your first time contributing to the Documentation team, please make sure you have the following accounts:

- [WordPress.org account](https://login.wordpress.org/register).
- [WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
- [GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile
- (https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).
- Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :)

Following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:

- [General overview](https://wordpress.tv/2022/06/21/milana-cap-overview-onboarding-for-wordpress-documentation-team/)
- [End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
- [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)

For general details on how GitHub works, check out [GitHub’s Getting Started Guide](https://docs.github.com/en/get-started/quickstart/hello-world).

When you find issue you'd like to work on in the [Docs Team Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) here on GitHub:

1. Please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue, and
2. In that comment, also be sure to tag the [team rep responsible for the handbook](https://make.wordpress.org/docs/handbook/the-team/) that your chosen task is about.

For example, if your task is for the Block Editor End-User documentation, you would tag @femkreations.

Check out the [Team page in the Documentation Team Handbook](https://make.wordpress.org/docs/handbook/the-team/) for a list of team reps.

### Onboarding during Contributor Day

If you have questions or need onboarding, feel free to ask in the [#docs channel on Slack](https://wordpress.slack.com/messages/docs/) or in [Zoom](https://us06web.zoom.us/j/85220861178?pwd=SE4vOElLbjlMbE5OdkNWMnR1ZGRMZz09). We'll create a breakout room in Zoom to field any questions you may have.

### Task list for new(er) contributors

For those who wish to contribute who are new(er) to the team, once you have taken a look at the onboarding material above, please feel free to take a look at our project boards that have issues labeled as a "good first issue":

- 6.3 Docs -- [Good first issue](https://github.com/orgs/WordPress/projects/108/views/15) 

Person to go to for help: @femkreations, @estelaris, @Leonardus-Nugraha, @zzap, and @jennimckinnon.

## General task list

Tasks we plan to work on during the day:

1. Updating block editor end user documentation

- 6.3 Docs -- [High priority](https://github.com/orgs/WordPress/projects/108/views/13)
- 6.3 Docs -- [Medium priority](https://github.com/orgs/WordPress/projects/108/views/14)

2. Content review for mobile app end-user articles

- [Mobile app content review board](https://github.com/orgs/WordPress/projects/89/views/1)
- [Promote Helping to Documentation team with Mobile Apps docs #219](https://github.com/WordPress/Marketing-Team/issues/219)

Person to go ask for help: @estelaris, @jennimckinnon, @zzap

3. Review all articles to confirm images and links are working. Several articles have broken links since the migration. Open individual tickets.

Example:
https://meta.trac.wordpress.org/ticket/6944

## Need help?

People to go ask for help on [Slack](https://wordpress.slack.com/messages/docs/) or on [Zoom](https://us06web.zoom.us/j/83644093796?pwd=Zy94clJrK3dmaGJLWGQ1Q08yMGpsUT09): @zzap, @femkreations, @estelaris, @Leonardus-Nugraha, and @jennimckinnon.

**Comment by p14i** [comment]
Attended the contributor day event. WordPress.org profile username: `prikari`.

**Comment by p14i** [comment]
Worked on [Documentation-Issue-Tracker #964](https://github.com/orgs/WordPress/projects/108/views/15?pane=issue&itemId=33125122).

**Comment by femkreations** [comment]
Reviewed #282 and #687 and added my comments

**Comment by jennimckinnon** [comment]
Closing this since I'm posting the next Contributor Day issue now.
