### ISSUE TITLE
[Theme Handbook Overhaul] Core Concepts > Including Assets

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#984]
This ticket is a part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/816 and will be used for creating new page titled "Including Assets" under Chapter 2: Core Concepts.

I will draft the content for the new page in a Google Doc: https://docs.google.com/document/d/14cTrMqTfVEr1DHohHfSm98y9vUJnemHgniBI9eCTVg0/edit?usp=sharing

**Comment by justintadlock** [comment]
This document is now ready for review: https://docs.google.com/document/d/14cTrMqTfVEr1DHohHfSm98y9vUJnemHgniBI9eCTVg0/edit?usp=sharing

Like other docs in Chapters 1 and 2, this one has several invalid links that point to docs that haven't been written yet.

**Comment by 00travelgirl00** [comment]
@justintadlock I have added a few comments. I'm not a php dev, so I can't review, if the content is correct. 

I reviewed from my perspective as a non native (with dyslexia), non dev, that tries to get into theme developing and where examples and clear instrutions are really helpfull.

**Comment by justintadlock** [comment]
This doc is now a draft in the Theme Handbook: https://developer.wordpress.org/wp-admin/post.php?post=149365&action=edit

**Comment by justintadlock** [comment]
Published here: https://developer.wordpress.org/themes/core-concepts/including-assets/
