### ISSUE TITLE
[DevHub] Duplicate `in_array` mention in Common API Handbook > Security

### ISSUE THREAD

**Issue by vHeemstra** [WordPress/Documentation-Issue-Tracker#990]
## Issue Description
Duplicate item about `in_array` under **[Validation Functions](https://developer.wordpress.org/apis/security/data-validation/#validation-functions)** section.

## URL of the Page with the Issue
https://developer.wordpress.org/apis/security/data-validation/#validation-functions

## Section of Page with the issue
Validation Functions

## Why is this a problem?
Evident... ;)

## Suggested Fix
Mention `is_array` instead of `in_array` twice. (Probably the intented content.)

**Comment by stevenlinx** [comment]
Thank you for filing.

I've made the revision.
